### ISSUE TITLE
CKeditor changes character “š” to “&scaron;” in source

### ISSUE THREAD

**Issue by TheSilencer** [ckeditor/ckeditor-dev#1000]
For my site I am using CKeditor to add/edit content and I noticed when I write character š in source code it is changed to &scaron; and this causes problems when I do search on website (because words with š are not fopund in database), so I am wondering how to fix this, so that that character will stay written in the source code the same way (not changed)?

I can fix this by adding this to config:

config.entities = false;

But with this, everything is disabled (even quotes, double quotes,... are now not changed in source), so this is not the best solution, right?

I also tried with those settings, but they don't help:

config.IncludeGreekEntities = false;
config.IncludeLatinEntities = false;

What else can I try? Is there any way to manually set that some characters should not be converted?

**Comment by beatadelura** [comment]
@TheSilencer It seems that `CKEDITOR.config.entities_latin = false;` works fine. Please check 
 [fiddle](https://jsfiddle.net/madvp0bw/1/).

**Comment by f1ames** [comment]
It was also covered on StackOverflow to some extend: https://stackoverflow.com/questions/46373072/ckeditor-changes-character-%C5%A1-to-scaron-in-source/46560357#46560357
