### ISSUE TITLE
Black and White colors don't get highlighted in Color Button panels

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1008]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)
1. Clear editor contents and type dew words. 
2. Select All and set background color to 'Strong Red'.
3. Select a word and set its text color to 'White'.
4. Click inside the word or select part or all of it.
5. Open the 'Font Color' panel button.

### Expected result

White color is highlighted.

### Actual result

Automatic color (which is 'Black') is highlighted.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.7.0+
* Installed CKEditor plugins: N/A

**The same issue can be reproduced with Background Color button and Black color.**

**Comment by beatadelura** [comment]
It is happening with colors: `Light gray`, `White`, `Dark gray`, `Black`.
