### ISSUE TITLE
Default font issue when we remove text from editor

### ISSUE THREAD

**Issue by SuneetBroadway** [ckeditor/ckeditor-dev#1009]
We Are using Document Editor. 

we have set the default font of editor as Arial 9px, but when we remove all the text from editor and font is not selected, then we write some thing, that written text default font becomes Times New Roman 12px automatically instead of default font i.e. Arial 9px.

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by SchmittK** [comment]
@SuneetBroadway, I'm also facing your problem.. Have you created another issue or luckily found a solution ? Thanks in advance.
