### ISSUE TITLE
Ck-Editor pasting text as an image if copied text from OneNote

### ISSUE THREAD

**Issue by asimkhan034** [ckeditor/ckeditor-dev#1016]
## Bug

**Reference Links:**
https://github.com/ckeditor/ckeditor-dev/issues/947
https://github.com/ckeditor/ckeditor-dev/issues/853 (Not directly reference my issue but its related to OneNote as my issue is).

## Provide detailed reproduction steps (if any)

1. Copy some text from OneNote (Desktop Application not Web Application)
2. Paste it in CK-Editor

### Expected result

*I should get only what i have copied from one note as Text*

### Actual result

Pasting will show me the text i have copied , along an image that contains same content.. Means duplicating copied contents..
*- one in text format*
*- other in image format*

## picture is worth a thousand words

![ckeditor onenote](https://user-images.githubusercontent.com/9529534/31276143-d212cf36-aab3-11e7-9a56-a18f88744974.png)

## Other details

* Browser: Chrome
* OS: Win 10
* CKEditor version: version:"4.5.11",revision:"3876e73"
* Installed CKEditor plugins: …

**Comment by beatadelura** [comment]
@asimkhan034 Could you please check, whether this problem occurs with newest CKEditor version 4.7.3?

**Comment by asimkhan034** [comment]
It's resolved in latest version.. Thanks a lot..

**Comment by asimkhan034** [comment]
I got the issue again with the latest version.. 
this issue occurs when i install (pastebase64) this plugin of CK-Editor (for pasting images in base64 format).
kindly check this issue why OneNote text is being affected due to this plugin.

**Comment by mlewand** [comment]
@asimkhan034 this issue should get reported to the original author, as this is not a plugin created by CKEditor developers. I hate to say it, but I guess that the original author removed it from GitHub and does not maintain it anymore, see:

* https://github.com/ahocquet/ckeditor-pastebase64
* https://ckeditor.com/cke4/addon/pastebase64

I think your best shot is to look for another, maintained plugin, that provides the feature you're looking for.
