### ISSUE TITLE
Unwanted styles of table-fake-selection class and attribute

### ISSUE THREAD

**Issue by mr-devboy** [ckeditor/ckeditor-dev#1022]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Create a table and write some text in cell.
2. Select text.
3. Change size or font of selected text.

### Expected result

Size/font of selected text is changed.

### Actual result

One html element has data-attribute **data-cke-table-faked-selection-table**.
Another html element has class **cke_table-faked-selection**.
As result: block with text has unwanted background and font color.
http://joxi.net/Vm69w6acDpp4xr

If repeat change size/font many times - have error in console http://joxi.net/brRQNaecJvv7oA

## Other details

* Browser: Chrome/Firefox/Safari (maybe other)
* OS: MacOS/Windows/Linux
* CKEditor version: 4.7.2

**Comment by beatadelura** [comment]
I'm able to reproduce this issue.

**Comment by Dumluregn** [comment]
Closing issue as it is no longer reproducible in `4.12.1`.
