### ISSUE TITLE
Clicking on Widget drag handle causes the widget to reload the widgets content.

### ISSUE THREAD

**Issue by treyspiva** [ckeditor/ckeditor-dev#1024]
## Are you reporting a feature request or a bug?

type: Question

When a widget drag handle is clicked on the logic treats it as an internal drag and drop operation.  It will then copy the HTML and insert it back again.  Which is fine for widgets whose content is completely contained within the document.  However, for widgets like the embed widget, it means reloading the content again.  

This behavior can be seen by clicking on the drag handle on the embed widget in the demo page.
https://sdk.ckeditor.com/samples/mediaembed.html.

Why is this important because clicking on the embed widget does not seem to set focus to the widget.  So, you are not able to delete it by clicking on the widget and pressing the delete key.  You have to click on the drag handle to make the widget have focus (the blue border shows).  

The question, is there a way to make stop the behavior of redrawing (or refreshing) of the widget content?

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
