### ISSUE TITLE
Bug: cannot add multiple images to table

### ISSUE THREAD

**Issue by keeganstreet** [ckeditor/ckeditor-dev#1027]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps

1. Insert a table
2. Insert an image into a cell of the table
3. Focus on another cell of the same table
4. Press the image button in the toolbar to enter an image into this cell too

### Expected result

Both cells should have an image

### Actual result

Only one image is added to the table

## Screen recording

![image in table](https://user-images.githubusercontent.com/513363/31420680-c37e4ffc-ae8e-11e7-8820-c5de32ba1fd9.gif)

### Other details

Browser: Chrome 61, Safari
CKEditor version: 4.7.3

**Comment by msamsel** [comment]
possible related bug: #522

**Comment by f1ames** [comment]
Updated labels, it happened in all browsers supporting `tableselection` plugin.
