### ISSUE TITLE
New style not applied to entire selection if partially present

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1040]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

This is an issue caused by #584, not yet published.

1. Open a [nightly demo](http://nightly.ckeditor.com/17-10-12-06-05/full/samples/).
1. Select "Hello" word.
1. Apply "Courier New" font.
1. Expand selection to contain whole header.
1. Apply "Courier New" font.

### Expected result

Whole header has "Courier New" font.

### Actual result

Font was not applied to the newly selected part.

## Other details

* Browser: Chrome
* OS: Win10
* CKEditor version: 4.8.0 (nightly, unpublished, 6102c2b)
* Installed CKEditor plugins: Full preset

**Comment by f1ames** [comment]
As this issue occurs only in the current dev version (not published), there is no need for changelog entry IMHO.
