### ISSUE TITLE
Link dialog: id not set after the first time

### ISSUE THREAD

**Issue by TomBosmans** [ckeditor/ckeditor-dev#1046]
## Are you reporting a feature request or a bug?

type: Bug

Referece link: http://nightly.ckeditor.com/17-10-13-06-04/full/samples/

## reproduction steps

1. Create a link with id (in the advance tap)
2. Edit the link (the id is still filled in)
3. Create a second link with id
4. Edit the second link

### Expected result
The id is filled in

### Actual result
The id is empty

## Other details
* Browser: Firefox
* OS: MacOs High Sierra
* CKEditor version: version of the sample, maybe older ones as well?
* Installed CKEditor plugins: Nothing special, same as the sample

**Comment by beatadelura** [comment]
I'm able to reproduce this issue from CKEditor version 4.3.0.
