### ISSUE TITLE
Test 'tests/plugins/tableselection/integrations/clipboard/pasteflow' crashes when browser viewport focused

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1047]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Extracted from #962.
Similar to #945.

## Provide detailed reproduction steps (if any)

The test `tests/plugins/tableselection/integrations/clipboard/pasteflow` started to fail (or rather break bender run in the same manner as mentioned in #945), after changes introduced in #962. However it only fails when browser viewport is focused (focusing browser window or browser URL field makes test run smoothly).

Also when changing tests order, from:

```
'test paste flow (tabular content)': function( editor, bot ) {
	testPasteFlow( bot, 'tabular-paste', '2cells1row' );
},

'test paste flow (non-tabular content)': function( editor, bot ) {
	testPasteFlow( bot, 'nontabular-paste', 'paragraph' );
}
```

to

```
'test paste flow (non-tabular content)': function( editor, bot ) {
	testPasteFlow( bot, 'nontabular-paste', 'paragraph' );
},

'test paste flow (tabular content)': function( editor, bot ) {
	testPasteFlow( bot, 'tabular-paste', '2cells1row' );
}	
```

it works fine despite the browser focus.

## Other details

* Browser: **Edge 16+**
* OS: Windows 10
* CKEditor version: 4.7.3 with #962 
* Installed CKEditor plugins: `clipboard`, `tableselection`, `undo`

**Comment by mlewand** [comment]
Interestingly I can no longer repro it with:

```
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
````

**Comment by f1ames** [comment]
Just wanted to mention that simplest workaround (changing test order) is already present on #1153 (https://github.com/ckeditor/ckeditor-dev/pull/1153/commits/73a07fc0b762b53d1ada469938f662cf7f8f9d9c) and this issue was to analyze the problem in more depth.

I will check if for the former test, the issue is still present on `Edge 16.16299`. If so I suggest to use the already present workaround as @msamsel fix is quite similar. If test will be passing on new Edge version, I will revert those change from #1153.

**Comment by f1ames** [comment]
Confirmed that this issue no longer occurs in `Edge 41.16299`. I reverted the workaround https://github.com/ckeditor/ckeditor-dev/pull/1153/commits/d9e216275f6f2075eb98619a00a1dc44231c943d on `t/468`.
