### ISSUE TITLE
Balloonpanel first appearance arrow rendered in a wrong position

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1054]
## Are you reporting a feature or a bug?

Bug

 ## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/16622

 ## Provide detailed reproduction steps (if any)

1. Use tests/plugins/balloonpanel/manual/balloonpanel manula test.
2. Click on the first red fragment.

 ### Expected result

The arrow is rendered correctly pointing on the red fragment.

 ### Actual result

The arrow is rendered in the center of the balloonpanel.

 ## Other details

Same result on both Chrome and FF. This behavior is only visible on the first balloonpanel appearance. After second click (even on the same fragment) the arrow is rendered correctly.

**Comment by jacekbogdanski** [comment]
It seems like `balloonpanel` works fine, it's just a manual test issue. Balloon arrow is created and repositioned using `balloonpanel.attach` function. However, in the manual test, we firstly attach balloon into the given element and then we modify its content. Changing functions order fixes the issue.
