### ISSUE TITLE
Notification plugin collides and overwrites Web Notifications API

### ISSUE THREAD

**Issue by CExWHamdan** [ckeditor/ckeditor-dev#1057]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Open Developers Tool in your browser 
2. In the Console tab type `Notification`

### Expected result

Web Notifications API should be returned.

### Actual result

CKEditor Notification plugin is returned.

## Other details

* Browser: Chrome Version 61.0.3163.100
* OS: macOs Sierra
* CKEditor version: 4.6.1
* Installed CKEditor plugins: wordcount, notification

**Comment by msamsel** [comment]
I cannot reproduce problem on our sample: https://cdn.ckeditor.com/4.7.3/full-all/samples/.

CKEditor should not leak to global scope except `CKEDITOR` variable. From your description it seems that you have wrong configuration or usage of CKEditor. Alternative there might be situation that third party plugin's author made leak to global scope.

If you are able to reproduce issue without 3rd party plugins, please provide more detailed steps how to repeat such situation.

**Comment by CExWHamdan** [comment]
@msamsel, the issue can only be reproduced with the Notification plugin enabled which seems to be leaking to global scope. Since the Notification plugin is shipped with CKEditor, is it still considered a third party plugin that you don't support?

**Comment by msamsel** [comment]
@CExWHamdan I gave you such information, because I'm not able to reproduce the problem.
I provide you link to our sample, where I repeat your steps and problem with notification does not occur. That's why I suggest possibility of problem with configuration or 3rd party plugins.

Please provide an example (it can be on page like codepen, jsfiddle, etc.) or reproduction steps which will allow on repeating this problem.

**Comment by CExWHamdan** [comment]
Thanks @msamsel for looking into the issue. 

Here's a demo where the issue can be reproduced: https://jsfiddle.net/n0m8pf3a/1/

The demo demonstrates the state of global Notification before and after instantiating a simple CKEditor with the `notification` plugin enabled.

**Comment by msamsel** [comment]
Issue does not occur in actual version of CKEditor.
https://codepen.io/msamsel/pen/RLEQyp?editors=1010

**Comment by mlewand** [comment]
@msamsel This is a still valid issue. If you check the dev version, you're still able to reproduce it there.

## Explaination

The reason why you're unable to reproduce it is that you use 4.7.x version - where `notification` was added as a dependency required by the `clipboard` plugin, which came in standard/full preset. That meant that it was inlined into a minified `ckeditor.js`, which is wrapped with a closure.

The jsfiddle example provided by @CExWHamdan uses 4.6.x where `notification` plugin was not inlined into `ckeditor.js` thus it's loaded at runtime from `plugins/notification/plugin.js`, which is not wrapped with a closure.

We must never leak any global vars other than `CKEDITOR` you have mentioned.
