### ISSUE TITLE
Firefox 56 does not stop loading after showing CKEditor

### ISSUE THREAD

**Issue by sarwarcse** [ckeditor/ckeditor-dev#1060]
## Are you reporting a feature request or a bug?

It's a bug. 

### Actual result

Firefox 56 does not stop loading after showing CKEditor

## Other details

* Browser: Firefox 56
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: colorbutton

**Comment by mlewand** [comment]
Are you sure? I have just checked http://cdn.ckeditor.com/4.7.3/standard/samples/ and it completes the loading correctly.

Tested on FF 56.0.1.

**Comment by aerichmond** [comment]
I can confirm it happens in Firefox 56.0.1.  The issue does not seem to appear on simple examples but does on a lot of the more complex examples like https://sdk.ckeditor.com/samples/autogrow.html .  It may be a Firefox bug and not a CKEditor issue but it might be worth looking into.  Basically the unified reload/stop button in Firefox gets stuck on the stop icon.

**Comment by mlewand** [comment]
Interesting, still I can't repro it on FF 56.0.1 on Win10/Mac even on autogrow link provided by @aerichmond. It might happen that our cdn does load something at your geolocation, can I ask you what is the country you're accessing this website from?

**Comment by mlewand** [comment]
Maybe you're using some blocking extensions for your browsers, which are blocking certain files? Give a try in a browser mode with no extensions added, as we still can not reproduce it.

**Comment by sarwarcse** [comment]
Yea, I have tried after disabling all Firefox extensions but same problem.

**Comment by sarwarcse** [comment]
![screenshot_1](https://user-images.githubusercontent.com/7591427/32055134-b73baca8-ba82-11e7-969b-5dafcf412418.jpg)

Here is the screenshot of Firefox Console.

**Comment by Aulddays** [comment]
Same here.
http://cdn.ckeditor.com/4.7.3/standard/samples/
reproducible on Firefox 56.0.2 Windows 7, even after "Restart firefox with addons disabled".
The page seems to finish loading but the stop/refresh button always remains "stop", just as the screenshot @sarwarcse posted

**Comment by mlewand** [comment]
I still can not reproduce it on:

* http://cdn.ckeditor.com/4.7.3/standard/samples/
* https://sdk.ckeditor.com/samples/autogrow.html

Tested on:

* Win 10 (FF 57.0.4)
* Win 7 (FF 57.0.4)

@Comandeer @f1ames could you guys have a look? If any of you can't reproduce it, then it means we basically can't repro it.

The last thing that comes to my mind is location dependency, maybe CDN is messing things up on our pages. @aerichmond @sarwarcse @Aulddays if you could provide country, from which you're accessing the pages we might try to use proxy to see if that might be the case.

**Comment by f1ames** [comment]
Can't reproduce it either on FF 57 (checked on OS X and Window 10).

**Comment by aerichmond** [comment]
As of Firefox 57 I no longer see the issue.

**Comment by jacekbogdanski** [comment]
As we can't reproduce this issue ( @aerichmond either) I'm closing. We will reopen issue if needed.
