### ISSUE TITLE
Disabling paste dialog broke PasteFromWord plugin

### ISSUE THREAD

**Issue by Ashus** [ckeditor/ckeditor-dev#1067]
Latest behavior change (4.7.x) to not display popup with textarea for certain browsers to enable customized paste broke pasting with formatting.

BUG

### Reproduction steps
1. install ckeditor 4.7.3 with configuration: forcePasteAsPlainText: true
2. use latest Chrome and display the editor
3. try to paste content using the pastefromword button

### Expected result

Paste dialog should come up and bypass the initial forcePasteAsPlainText setting.

### Actual result

"Your browser doesn't allow you to paste this way. Press Ctrl+V to paste." notification pops up.

## Other details

* Browser: Chrome latest stable
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: pastefromword

**Comment by mlewand** [comment]
If you're asking about `forcePasteAsPlainText` support (which got broken in 4.7.x PFW) then it's here: https://github.com/ckeditor/ckeditor-dev/issues/620 just subscribe this issue. You can also add 👍 to bump it up.

If you're used to old paste popup, just download the old version [from 4.6.2 version on our Add-ons repository](https://ckeditor.com/cke4/addon/pastefromword) page.

**Comment by Ashus** [comment]
Just an FYI, using old pastefromword or old pastefromword and pastetext (4.6.2) in new ckeditor (4.7.3) doesn't work either, dialog is not shown and clicking the menu button does nothing.
The referenced bug is something slightly different, but has the same problem cause, broken forcePasteAsPlainText.

**Comment by binodpaikaray** [comment]
Hello,
I'm also facing same issue!
When I paste some content using the toolbar, its shows the below message instead of the previous pop-up

"Your browser doesn't allow you to paste this way. Press ⌘+V to paste."

Please let us know how to fix this?

**Comment by DonWolli** [comment]
Why is this issue CLOSED? I cannot recognize a solution and I need one!!!

**Comment by tcomiotto** [comment]
Paste from Word is still broken in desktop browsers. 

Please bring back the paste dialog in desktop browsers like you did for mobile (https://github.com/ckeditor/ckeditor-dev/issues/595).

**Comment by HosanaUFRRJ2014** [comment]
Please, bring back Paste from Word!!!!!!! I'm using CKEditor 4.10 and it still not working. :'(

**Comment by PatrickNd** [comment]
We got the same problem. My customers would really like to paste from word on chrome!

**Comment by bkosborne** [comment]
I don't think this should have been closed as a duplicate. In FireFox, when using the Paste from Word button, I get message "Press ⌘+V to paste. Your browser doesn‘t support pasting with the toolbar button or context menu option." Well, that's the keyboard command for a standard paste, and that won't behave the same as the "Paste from Word" used to.

I'm not sure what browsers where the button will work on (maybe just IE?), but this button is pretty much useless for other browsers where this message is displayed.
