### ISSUE TITLE
Problem inserting data inside the image format screen

### ISSUE THREAD

**Issue by douglas-caddoweb** [ckeditor/ckeditor-dev#1071]
### Reporting Bug

Good afternoon friends.
I am having trouble inserting an image URL into the image format screen. When I open the screen and try to click on any field, I can not enter any information.
Could someone be helping me in this matter?

* Browser: Chrome, Firefox, Edge
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: imageBrowser

**Comment by msamsel** [comment]
This is a third party plugin not maintained by the CKEditor team.
Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/addons/plugins/all).
