### ISSUE TITLE
uploadimage  refresh  page

### ISSUE THREAD

**Issue by yedajiang44** [ckeditor/ckeditor-dev#1072]
Why after the success of the upload image or cshtml(asp.net razor) can refresh the page, and upload file or html page is not it

the gif

![123](https://user-images.githubusercontent.com/25813145/31849666-7f66f16a-b678-11e7-8c2c-fb258f5990d1.gif)

**Comment by msamsel** [comment]
I'm not able to reproduce the problem on our page: https://ckeditor.com/ckeditor-4/.

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
