### ISSUE TITLE
Using 'Automatic' color on text with already applied color creates 'span.style=color:null'

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1084]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/fullpreset.html.
2. Set content to `foo bar`.
3. Select `bar` and change text color to some predefined/custom one.
4. Select `bar` and change text color to `Automatic`.

### Expected result

Span element with color is removed producing content like `<p>foo bar</p>`.

### Actual result

Span element with color is not removed but modified with a null color producing html like `<p>foo <span style="color:null">bar</span></p>`

## Other details

* Browser: All (checked in Chrome and FF)
* OS: All
* CKEditor version: 4.7.2
* Installed CKEditor plugins: `colorbutton`

**Comment by mlewand** [comment]
Breaking commit: 0db439541897822aadd6970c1454fd9f987facba
