### ISSUE TITLE
Test /tests/core/ckeditor/basepathglobal should work for custom aliases

### ISSUE THREAD

**Issue by beatadelura** [ckeditor/ckeditor-dev#1089]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

If there is no `sub.ckeditor.dev` specified in the local environment `/etc/hosts` test `/tests/core/ckeditor/basepathglobal` fails on Safari.

It could be more flexible and work for custom aliases instead of using fixed `sub.ckeditor.dev`. See [comment](https://github.com/ckeditor/ckeditor-dev/pull/1082#pullrequestreview-71501634).

**Comment by f1ames** [comment]
Closing this one as outdated. It seems there was a problem in the initial issue from which this was extracted - see https://github.com/ckeditor/ckeditor-dev/issues/1061#issuecomment-341457860.
