### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by Tif-P-HK** [ckeditor/ckeditor-dev#1095]
## Are you reporting a feature request or a bug?
Bug/Question

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*
http://nightly.ckeditor.com/17-10-26-06-04/standard/samples/

## Provide detailed reproduction steps (if any)

1. … I noticed that links on the editor on the [sample page](http://nightly.ckeditor.com/17-10-26-06-04/standard/samples/) are actually not clickable. I wonder if this is a bug? 

### Expected result
Link should be clickable 

### Actual result
Mouse cursor doesn't change on hovering, and link is not clickable 

## Other details

* Browser: … Tested Chrome 61.0.3163.100
* OS: … Tested Win
* CKEditor version: … http://nightly.ckeditor.com/17-10-26-06-04/standard/samples/
* Installed CKEditor plugins: … N/A

**Comment by mlewand** [comment]
What do you mean by saying that the links should be clickable? What action should occur?

If you think about opening the link on click, we made an example [openlink](https://github.com/mlewand/ckeditor-plugin-openlink) plugin back in day. Nonetheless it would be nice to add such feature to default CKEditor distribution. It would be a feature request then.

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
