### ISSUE TITLE
changing the label text in menu buttons  and tool tips 

### ISSUE THREAD

**Issue by sekhar0475** [ckeditor/ckeditor-dev#1096]
![label text](https://user-images.githubusercontent.com/20836784/32095613-5b3a92a8-bb21-11e7-8c7c-51ff0436eba0.PNG)
## Are you reporting a feature request or a bug?

 Feature request / Other, please explain.

**Comment by sekhar0475** [comment]
![label text](https://user-images.githubusercontent.com/20836784/32094653-283e973a-bb1e-11e7-85a1-621ae5fa3b01.PNG)

**Comment by sekhar0475** [comment]
![label text](https://user-images.githubusercontent.com/20836784/32095258-30564b64-bb20-11e7-9161-a01f816c8c1f.PNG)

**Comment by msamsel** [comment]
Those labels are taken from our translations. If you wish to modify it, you can change translations and rebuild editor with your changes.
