### ISSUE TITLE
Question : How to have config.pasteFilter more restrictive than config.allowedContent ?

### ISSUE THREAD

**Issue by messenjer** [ckeditor/ckeditor-dev#1099]
Hello,

I want to remove the `text-align:*` styles, when I copy/paste content from word

I have these config : 

```
  config.toolbar_custom =
    [
      ['JustifyLeft', 'JustifyCenter'],
      ['Source'],
      ...
    ]
```

```
config.allowedContent = '* {text-align};a[target,title,href,rel,id];p h2 h3 dt em strong b br i ol ul li div table thead tbody tfoot tr div span blockquote hr;td th[colspan,rowspan];dl[class];'
```

With a `pasteFilter` without `* {text-align};`

```
config.pasteFilter = 'a[target,title,href,rel,id];p h2 h3 dt em strong b br i ol ul li div table thead tbody tfoot tr div span blockquote hr;td th[colspan,rowspan];dl[class];'
```

When I copy/paste the following : https://sdk.ckeditor.com/samples/assets/pfw/CKEditor4.PFW.Sample.Mixed_styles.docx 

I have those style : 

 ```
<p style="text-align:left"><span>This is a sample <strong>.docx</strong> document. Use it to test <em>Paste from Word</em> plugin in CKEditor 4.</span></p>
```

It's possible to have a config.pasteFilter more restrictive than config.allowedContent ?

Or it's possible to remove all `text-align: left, right, justify`, excepted `text-align: center` with ACF

Regards

Mathieu

**Comment by msamsel** [comment]
It depends from where you copy the data:
please take a look into documentation: https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-pasteFilter
If  you wish to modify every pasted data you can change it in paste event processing. Example here: https://codepen.io/msamsel/pen/mqJPde?editors=1011
