### ISSUE TITLE
Register command should extend filter rules with allowedContent

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1103]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open link: https://codepen.io/msamsel/pen/EbaZxK?editors=1010
2. Press <kbd>Ctrl</kbd> + <kbd>H</kbd>
3. Check source twice.

### Expected result
Register a command, should be sufficient for extending filtering rules.

### Actual result
Plugin is not working properly, `itemprop` attribute is removed from the editor.

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.7.3
* Installed CKEditor plugins: full-all

**Comment by mlewand** [comment]
Duplicate of #678.
