### ISSUE TITLE
Execute removeformat command on Paste event

### ISSUE THREAD

**Issue by itshema** [ckeditor/ckeditor-dev#1106]
We are having removeformat as toolbar(Tx Button),this is being clicked once user copy & paste into text area. This involves 3 key strokes & a click(CTRL+C->CTRL+V->Select All->Tx Button click). User wants to minimize it to 2 key strokes(i.e; CTRL+C->CTRL+V).I have found a ticket # 9306 is in confirmed status, Please update on the ticket & version of the ckeditor where it is available. Please let us know how can we invoke it in ckeditor.js

**Comment by msamsel** [comment]
Hi I don't understand what exactly you ask for. :(
Could you adapt your question to our [bug report template](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md) and provide information what exactly you expect from our side?

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
