### ISSUE TITLE
Unable to select complex elements to apply object styles

### ISSUE THREAD

**Issue by msevcenko** [ckeditor/ckeditor-dev#1107]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to CKEditor demo https://ckeditor.com/ckeditor-4/#article
2. Select the whole bulleted list

### Expected result

The Styles Combo in the toolbar should allow to select "Square Bulleted List", as defined in the styles.js.

### Actual result

There is no such option in the Styles Combo.

## Other details

If the style is applied manually: `<ul style="list-style-type: square">` putting cursor inside the list, or selecting the whole list, correctly indicates the selected style (Square Bulleted List), but after unfolding the combo, the style is not shown.

Interesting to note that the style can be canceled using the cancel format button only if the whole list is selected, so the detection that the list is selected somehow works.

Similar problem is e.g. with the table and its cells. Here the Styles Combo works correctly, as long as the table selection plugin is active, the whole cell(s) must be selected to change style thereof, or the style of the table. It is not sufficient to select all the text in the cell or table, as is suggested by the documentation "How Do I Use the Styles on Images, Tables or Other Elements?" - https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_howtos_styles.

This is a regression issue after upgrading from 4.4.5 to 4.7.3, in the 4.4.5 version this functionality worked perfectly.

**Comment by msamsel** [comment]
duplicated: #862
bug is fixed and will be available in 4.8.0.

**Comment by msevcenko** [comment]
Well, thanks. It seems to me that the bug reports something else - that you need to select whole element to be able to change its style. I report that the style cannot be changed at all, even if all its text is selected.

I'll check the update anyway.

**Comment by mlewand** [comment]
I can confirm that this issue was resolved as @msamsel mentioned.

**Comment by msevcenko** [comment]
Yes, look okay in 4.8.0, thanks.
