### ISSUE TITLE
Safari Carriage Returns sometime moving cursor to top of box.

### ISSUE THREAD

**Issue by mhopkins-dynactive** [ckeditor/ckeditor-dev#1110]
This is a bug, but I am not sure it is my fault or ckeditors. 

This bug has already been reported here https://dev.ckeditor.com/ticket/12423 (I am having the same problem as the guy at towards the end of the comments. He says  

> Here is a simple test that fails for me.
> 
> 1) Brand new instance on screen. 
> 2) Click into editor... for me it actually takes two clicks (in Safari). The first click does not "stick". 
> 3) Type a line of text. 
> 4) Press Return (Enter) key. The cursor is moved to the top of the document. 
> 5) Manually position the cursor on the second line, and type some more text. 
> 6) Press Return (Enter) key, and the cursor is once again moved to the top of the document. )
> 

I upgraded to the latest version of CKEditor 4.7.3 hoping that if I upgrade the issue would be resolved.

*What is the actual result of the above steps?*

The problem is better because before on every carriage return it would move the cursor to the top of the page but now it only moves it to the top of the page sometimes. 

But when I go to  the demo on the ckeditor 4 homepage, it does not have this problem. 

What is the best way to go about checking if I have a plugin installed that would mess with the fix. Or is there a patch I can get/look at so that I can fix this problem.

## Other details

* Browser: Safari 11
* OS: Mac
* CKEditor version: 4.7.3
* I have cleared Cache etc.

**Comment by msamsel** [comment]
I have problem with reproduction this issue. I tried to use our main sample for that: https://cdn.ckeditor.com/4.7.3/full-all/samples/.
Can you check if problem is possible to reproduce under above link? If not, then could you prepare some sample were issue will be possible to reproduce?

**Comment by mhopkins-dynactive** [comment]
I finally got a demo up but when I went to test it the problem went away. I think I was having cacheing issues before. I have no idea. 

Thanks,
