### ISSUE TITLE
Can not keep the <font>tag when saving, version 4.6.2

### ISSUE THREAD

**Issue by topliu88** [ckeditor/ckeditor-dev#1115]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)
No

## Provide detailed reproduction steps (if any)

1. Set config to:
```
config.fontSize_sizes = '1/1;2/2;3/3;4/4;5/5;6/6;7/7;';

config.font_style = {
	element: 'font',
	attributes: {'face': '#(family)'},
	overrides: [{
		element: 'font', attributes: {'face': null}
	}]
};
config.fontSize_style = {
	element: 'font',
	attributes: {'size': '#(size)'},
	overrides: [{
		element: 'font', attributes: {'size': null}
	}]
};

config.extraAllowedContent = 'font[*]';
```

2. Set font size to 4 for a string.
3. Saving the form, the CKEditor.getdata() will wrongly convert "font" to "span".

### Expected result

The "font"  tags are kept.

### Actual result

"font" tags were wrongly converted to "span"

## Other details

Till CKEditor 4.5.11 this config works fine.

* Browser: All
* OS: All
* CKEditor version: 4.6.0
* Installed CKEditor plugins: `font`

**Comment by f1ames** [comment]
Can be reproduced here: https://codepen.io/f1ames/pen/goYxgz
