### ISSUE TITLE
How to keep focus on other HTML element

### ISSUE THREAD

**Issue by Ange7** [ckeditor/ckeditor-dev#1120]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

If i'm in ckeditor instance when i click on other input element, i lost the focus

### Expected result

Keep the focus on other input 

### Actual result

Focus is lost, i need to click 2 times 

## Other details

* Browser: all
* OS: All
* CKEditor version: 4

Check this video to see the bug : https://streamable.com/13ipp

**Comment by msamsel** [comment]
Can you prepare code example where problems occur? You can use platform like codepen.io, jsfiddle.net, etc. and link our current version of ckeditor, https://cdn.ckeditor.com/4.7.3/full-all/ckeditor.js
I don't know what kind of configuration and implementation of the editor you have, what disallows for better inspection of this issue.

**Comment by Ange7** [comment]
Problem is fixed when upgraded CKEDITOR to last version 

Thank you
