### ISSUE TITLE
Fake selection is copied with table, what interfere with native selection

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1122]
## Are you reporting a feature request or a bug?

Bug 

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

#1022 - kind of simillar

## Provide detailed reproduction steps (if any)

1. Open editor with `tableselection` plugin.
2. Insert table and type some text in cells.
3. Select entire table and copy it.
4. Paste table somewhere below.
5. Try to select text inside **single** cell.

### Expected result

Selection will be visible

### Actual result

Selection is not visible. Table after copy operation retain `data-cke-table-faked-selection-table` attribute, which block in css displaying native selection.

## Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 4.7.3
* Installed CKEditor plugins: tableselection

**Comment by Dumluregn** [comment]
Closing issue as it is no longer reproducible in `4.12.1`.
