### ISSUE TITLE
Selection gets lost in chrome in inline editor with custom toolbar

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#1127]
## Are you reporting a feature request or a bug?
Feature

## Provide detailed reproduction steps (if any)

1. Select some text in the inline editor.
2. Click on custom toolbar to change a drop down value.
3. The selection gets lost visually as the focus has been moved away from editor.

Note: It works fine on demo page of ckeditor because toolbar is in iframe. I don't want to put the editor or custom toolbar in iframe.

### Expected result

The selection should be greyed out. 

### Actual result

It gets lost visually

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.7.0

**Comment by jswiderski** [comment]
First of all I need to clarify that CKEditor toolbar is not being used inside an iframe. Toolbar for all editors is created on main page. What is inside the iframe are contents of toolbar dropdown to present how given style may look like and to protect the styles from conflicting with others on the same page.

Could you explain what custom toolbar is? Are you using your set of buttons for CKEditor toolbar or you are using your own toolbar custom toolbar and not using CKEditor toolbar at all?

If you mean the second option (your own toolbar creation) then we cannot accept this issue as a valid bug report.

Could you

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
