### ISSUE TITLE
Drag and drop of inline editable widget inside another widget raises an error

### ISSUE THREAD

**Issue by AlfonsoML** [ckeditor/ckeditor-dev#1132]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/query?status=assigned&status=confirmed&status=new&status=pending&status=reopened&status=review&status=review_failed&status=review_passed&summary=~widget&col=id&col=summary&col=status&col=owner&col=type&col=milestone&order=priority

Quite a few bugs about widgets, don't seem to be exactly one of them without reviewing carefully

## Provide detailed reproduction steps (if any)

1. Add the provided sample plugin under a folder "widgettest", it provides two Widgets: WidgetA (block) and WidgetB
[plugin.zip](https://github.com/ckeditor/ckeditor-dev/files/1451657/plugin.zip)
2. Put in the editor the following HTML:
```
<p>Drop of inline editable widgets bug</p>

<p>Put the cursor in the marker and insert WidgetB (inline editable)</p>

<p>&nbsp;<strong><em>insert here --&gt;&nbsp; |&nbsp; &lt;-- inline widget</em></strong></p>

<div class="widgetA">
<div class="widgetA-body">
<p>Block widget, drop the &quot;Text&quot; widget here</p>

<p>end of block widget</p>
</div>
</div>

<p>&nbsp;</p>
```

3. … Using the toolbar, locate the WidgetB (sorry, no icon) and put it in the |, now drop it into the existing block widget below it.

### Expected result

The inline widget is dropped inside the block one

### Actual result

There are errors from that point on and everything fails

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.6
* Installed CKEditor plugins: Sample widgets test

The error is in the setFocusedEditable( widgetsRepo, widget, editableElement, offline ) function.
The widget is WidgetA, and editableElement is label, which belongs to WidgetB, so the 
`editableInstance = widget.editables[ editableName ]` assignment results in undefined.

That happens because when it's called from the selectionChange listener in setupSelectionObserver, it returns the wrong widget for the editable in 
`newWidget = nestedEditable && widgetsRepo.getByElement( nestedEditable )`
At that moment the widget of the editable isn't in the document, so the widgetsRepo.getByElement walks up from the WidgetB until it finds WidgetA, and the rest is all wrong.

**Comment by f1ames** [comment]
Hello @AlfonsoML,
following your scenario and attached plugin I can confirm this issue. However, you have used inline nested editables (applying the workaround from https://dev.ckeditor.com/ticket/10974) which are not fully supported, so I'm afraid it cannot be treated as an actual bug. The issue does not occur if there is no inline editable.

The way I see it, is that you can issue a Feature Request for nested inline editables support and this issue can be covered as a part of it. However, as you can see it was already reported on the previous tracker (https://dev.ckeditor.com/ticket/10974) some time ago and is still not resolved, so it is not a high priority.

Related issues for reference:
https://dev.ckeditor.com/ticket/10974
https://dev.ckeditor.com/ticket/10932
https://dev.ckeditor.com/ticket/10973
