### ISSUE TITLE
ckeditor 4.7.3 Paste from Word not allowing to paste text when track changes on 

### ISSUE THREAD

**Issue by kumasa01** [ckeditor/ckeditor-dev#1133]
## Are you reporting a feature request or a bug?
Bug

We are using  CKEditor version 4.7.3 and tracked changes plugin Version: 1.2.30. When show tracking changes button is on, if we try to paste the text from word document , CKEditor is not allowing to paste the text. This issues only happening when word document has any tables or comments. If we turn off track changes we were able to paste the text into CKEditor.

See attached document we used for testing always failing paste when tracking changes are on.

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …(IE, Firefox, Edge and Chrome
* OS: …Windows 10 
* CKEditor version: …4.7.3
* Installed CKEditor plugins: …LoopIndex Track Changes: Version: 1.2.30 , Paste from Word 
[Paste from Word.docx](https://github.com/ckeditor/ckeditor-dev/files/1452498/Paste.from.Word.docx)

**Comment by msamsel** [comment]
This is a third party plugin not maintained by the CKEditor team.
Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/cke4/addons/plugins/all).
