### ISSUE TITLE
Source button cannot be unselected in Microsoft Edge

### ISSUE THREAD

**Issue by kumasa01** [ckeditor/ckeditor-dev#1138]
Bug

Using Microsoft  Edge browser with CKEditor  version 4.7.3, once you click on "Source" button, it cannot be unselected to revert back to the original state. This issue exists only in MS Edge browser.

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

User should be able to go back to editor view when you click on the button again.

### Actual result

Currently it stays is source view and it is going back to original state when you refresh the browser.

## Other details

* Browser: …Microsoft Edge 40.15063.674.0
* OS: … Windows 10
* CKEditor version: …4.7.3
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
I wasn't able to reproduce the issue. I tested it on our sample: https://cdn.ckeditor.com/4.7.3/full-all/samples/
Can you check if the problem occurs on our sample page?

**Comment by kumasa01** [comment]
We have verified in Demo site and it works. After further testing, we have identified this issue caused by Lite plugin.
