### ISSUE TITLE
On IE11 + CKeditor readonly mode, throw Unspecified error when press Tab button (sometine only select text throw same error)

### ISSUE THREAD

**Issue by binhcx1989** [ckeditor/ckeditor-dev#1140]
## Are you reporting a feature request or a bug?
Bug : on IE11 + CKeditor readonly mode, throw Unspecified error when press Tab button (sometine only select text throw same error)

[ckeditor_unspecified_error.zip](https://github.com/ckeditor/ckeditor-dev/files/1456587/ckeditor_unspecified_error.zip)
![ie11_unspecified_error](https://user-images.githubusercontent.com/2993483/32592324-c7da62c4-c555-11e7-9cdc-c3cc46de8943.png)

## Provide detailed reproduction steps (if any)
Please check my sample source code attach on this ticket. My project using jquery 1.7.1 and Ckeditor 4.7.3 (My customer not allow update jquery to latest version because a lot of functions will active).
I tried to resolve, but not effective.
Step to duplicate this issue :
1. Extract ckeditor_unspecified_error.zip, open with IE11
2. Focus on ckeditor area, then press tab button

### Expected result

Not show any error

### Actual result

Throw javascript error : Unspecified error as capture.

## Other details

* Browser: IE11
* OS: Window 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: No

**Comment by msamsel** [comment]
Hi,
I get jQuery errors from your example. Could you prepare such example in online tools such as codepen.io, jsfiddle.net, etc.? This will provide possibility to check the issue regardless from local settings.
You can link there to CKEditor on CDN: https://cdn.ckeditor.com/4.7.3/full-all/ckeditor.js

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
