### ISSUE TITLE
in CKEditor when we right align HTML lists only the content moves to right, the list type is not moved

### ISSUE THREAD

**Issue by ysrajan** [ckeditor/ckeditor-dev#1144]
## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
This is way how HTML display lists. Take a look here: https://codepen.io/msamsel/pen/ooGqWv

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by mlewand** [comment]
For anyone thinking about tinkering this kind of thing see https://github.com/ckeditor/ckeditor-dev/issues/1578#issuecomment-363252364
