### ISSUE TITLE
Links in Firefox

### ISSUE THREAD

**Issue by valdaiko** [ckeditor/ckeditor-dev#1149]
Bug
### Reproduction steps

1. Insert new link
2. Set cursor at the end of the link
3. Press "space" on keyboard
4. Enter some new text

### Expected result
Link ends and after space goes new simple text

**http://mylink.com** new text

### Actual result

Link doesn't end and next text attaches to previous link

**http://mylink.com[spase]new[spase]text**

## Other details
Bug can be reprodused on the page https://ckeditor.com/ckeditor-4/ like this
http://joxi.ru/nAyqyjOIYLKx9A

* Browser: Firefox 56.0.2
* OS: windows 8.1
* CKEditor version: 4.7.3
* Installed CKEditor plugins: no

**Comment by msamsel** [comment]
It's an upstream issue. It have to be resolved by the browser provider.
https://bugzilla.mozilla.org/show_bug.cgi?id=1357365
