### ISSUE TITLE
Cutting the widget scrolls editor to the end (with t/468)

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1160]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://tests.ckeditor.test:1030/tests/plugins/clipboard/manual/draganddrop
2. Select the widget from the first editor.
3. Press CTRL + X.

### Expected result

Editor scrolls to the end.

### Actual result

Editor does not scroll at all or scroll position is restored.

## Other details

* Browser: Edge 16+
* OS: Windows
* CKEditor version: `major` with #468 
* Installed CKEditor plugins: `clipboard`

**Comment by f1ames** [comment]
Looks like the breaking commit is the first one: https://github.com/ckeditor/ckeditor-dev/pull/1153/commits/55718843c0cb2daefe96310eee9fffb48740aa84. Not sure why ATM.

**Comment by f1ames** [comment]
The exact line is https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/clipboard/plugin.js#L526

while the previous flow doesn't executed this code (due to `CKEDITOR.plugins.clipboard.isCustomCopyCutSupported`) the issue was not visible.

**Comment by f1ames** [comment]
This issue is caused by the fact that when copying/cutting widgets, `pastebin` is still used. Widgets [`copySingleWidget` function](https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/widget/plugin.js#L3083):

https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/widget/plugin.js#L3083-L3169

is called on copy/cut here:
https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/widget/plugin.js#L3503-L3520

or here:
https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/widget/plugin.js#L2690-L2704

Initially I thought scrolling is caused by container holding real selection, but the cause here is `pastebin` container.

The quick workaround for the issue is to fix [`pastebin` container type](https://github.com/ckeditor/ckeditor-dev/blob/2bcbf1ffd39e4bb897c9c1b1930337214da83136/plugins/widget/plugin.js#L3095) from:

`copybinName = ( editor.blockless || CKEDITOR.env.ie ) ? 'span' : 'div'`

to:

`copybinName = ( editor.blockless || ( CKEDITOR.env.ie && CKEDITOR.env.version < 16 ) ) ? 'span' : 'div'`

which brings the same behaviour as on the `major` branch (the editor jumps - scrolling back to where caret is after widget removal).

---

### Is `pastebin` really needed here?

The `clipboard` plugin uses `pastebin` only for browsers not supporting Clipboard API (IE browsers), but for widgets it is used always. I think we should consider restricting its usage only from browsers which really needs it, especially that:

1. `copySingleWidget` is called first and it utilizes `CKEDITOR.editable.getHtmlFromRange` to prepare HTML which is copied by the browser to a clipboard/dataTransfer.
1. `clipboard` plugin listeners are executed, which for browsers supporting Clipboard API, creates `CKEDITOR.plugins.clipboard.dataTransfer`.
1. `CKEDITOR.plugins.clipboard.dataTransfer` object upon creation inserts `text/html` data to clipboard (using `CKEDITOR.editor.getSelectedHtml`) overwriting html which was inserted via `pastebin`.

Also `CKEDITOR.editable.getHtmlFromRange` is the base of the `CKEDITOR.editor.getSelectedHtml` method so the output should is the same.

**Comment by f1ames** [comment]
Extracted #1169.

**Comment by Comandeer** [comment]
Closed in #1170.
