### ISSUE TITLE
Update logo and title in the "About" plugin

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/ckeditor-dev#1165]
## Are you reporting a feature request or a bug?

We need to update the following in the "About CKEditor" plugin

## Provide detailed reproduction steps (if any)

1. Click "About CKEditor" icon

### Expected result

1. Tooltip and window title say "About CKEditor 4"
2. New logo of CKEditor 4

### Actual result

![screen shot 2017-11-14 at 16 12 05](https://user-images.githubusercontent.com/6146254/32787898-0fe59696-c958-11e7-9930-0e3331b17a83.png)

**Comment by msamsel** [comment]
related to #532

**Comment by f1ames** [comment]
Also headers in `*.js` files containing license link should be updated so everything is consistent.

**Comment by mlewand** [comment]
> Delete Check CKEditor User's Guide line and link

This is already tracked in #532.

> Change License link from http://ckeditor.com/about/license to https://ckeditor.com/legal/ckeditor-oss-license/

I have extracted it to #1203 as it will require also changes in source files.

**Comment by f1ames** [comment]
As I was talking with Ryszard about logo, he suggested that we should center dialog text as it looks much better:

<img width="434" alt="screen shot 2017-11-22 at 17 30 52" src="https://user-images.githubusercontent.com/1061942/33138666-5a084e04-cfab-11e7-8110-1c232c8aa340.png">

<img width="435" alt="screen shot 2017-11-22 at 17 30 32" src="https://user-images.githubusercontent.com/1061942/33138678-5da0d6b2-cfab-11e7-8e76-e3c5ba156ff6.png">

WDYT @mlewand @wojtekidd ?
