### ISSUE TITLE
CKEditor not remove special character ' word' when use paste plain text (Ctrl + Shift + V).

### ISSUE THREAD

**Issue by no1412** [ckeditor/ckeditor-dev#1172]
## Are you reporting a feature request or a bug?

Bug 

**Reproduction steps (if any)**
1. Open a CKEditor (4.7.1) page.
2. Cpy the word (** word**) form https://jsfiddle.net/km4gue8u/1/ and used **_Ctrl + Shift + V_** to paste it to editor.
3. Will see the '' still in editor.

### Expected result
*What is the expected result of the above steps?*
The special character will be removed

### Actual result
*What is the actual result of the above steps?*
The special character not be removed

* Browser: chrome & firefox
* OS: MS Windows 7 64 bits
* CKEditor version: 4.7.1

**Comment by msamsel** [comment]
Hi,

plain text is responsible for inserting data without additional html markup, such as Bold, Jusify, etc. It's not responsible for stripping out text and special characters.

**Comment by no1412** [comment]
Thanks @msamsel , If i want to implement this function to remove special character, what should i do?
Added remove logic when CKEditor getData from clipboard?
Or if you have any other valid method?

**Comment by msamsel** [comment]
If you only detect such problem during pasting. I think most optimal would be modifying pasted data to editor.
You can create your own paste listener, which will be executed while data is pasted to editor. Some example how it might look but with adding extra data you can find in below example. In similar way you can process your case. You just need to modify `evt.data.dataValue` according to your needs.
Here you can read more about paste event: https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.editor-event-paste
And example you can find in followed link:
https://codepen.io/msamsel/pen/mqJPde

**Comment by no1412** [comment]
Thanks for your reply, It's useful for me.
