### ISSUE TITLE
Win7/IE11 Backspace/Delete Styling Bug

### ISSUE THREAD

**Issue by InetJustin** [ckeditor/ckeditor-dev#1174]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/accessibility-checker/
2. Set content to 

```
<p><strong>Styled Text</strong></p>

<p>Unstyled Text</p>
```

3. Now place the cursor right before the Unstyled Text line, and press Backspace (or Delete depending where your cursor is) to bring each paragraph into the same paragraph (put both pieces of text on the same line with no space between them).

### Expected result

I expect to see:
`<p><strong>Styled Text</strong>Unstyled Text</p>`

### Actual result

Due to this bug I instead see:
`<p><strong>Styled TextUnstyled Text</strong></p>`

## Other details

* Browser: IE11 11.0.9600.18816 (11.047 [KB4040685](https://support.microsoft.com/en-us/help/4040685/cumulative-security-update-for-internet-explorer))
* OS: Windows 7
* CKEditor version: 4 (latest, whatever is used on ckeditor.com)
* Installed CKEditor plugins: (Basic configuration, nothing special)

Note: I have ONLY been able to reproduce this particular issue on a Windows 7 machine with IE11 that is up-to-date. Versions older than the Oct. 10, 2017 update appear to work as expected, I'm pretty sure this issue is specific to IE11/Win7 and showed up after that particular update. Also, this only appears to show up when using paragraphs instead of divs as the line separator as well.

**Comment by f1ames** [comment]
For now I checked on newer IE11 version on Windows 10 and the issue does not occur there:
![screen shot 2017-12-11 at 13 21 20](https://user-images.githubusercontent.com/1061942/33837025-69114da8-de8b-11e7-9115-cbc9f0889300.png)

I will recheck on mentioned IE11/Win7 version after updating.

**Comment by f1ames** [comment]
I can confirm it happens on mentioned IE11/Win7 version:
![image](https://user-images.githubusercontent.com/1061942/33838095-bb644634-de8e-11e7-9f62-95f4805c077f.png)

both for delete/backspace. The whole content is wrapped into `strong` as mentioned in a description.

**Comment by mlewand** [comment]
@f1ames Can we check if it happens on plain contenteditbale as well? If so we should report it to Microsoft.

If IE11 responds saying that they're no longer support IE11 even though they introduced a regression, it's a strong signal that we kinda should do the same.

**Comment by f1ames** [comment]
@mlewand you are right, it is an IE11 regression (tested here https://codepen.io/f1ames/pen/NXKzob). I will report an upstream issue.

**Comment by f1ames** [comment]
Upstream issue reported: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15053851/. Closing as `resolution:upstream`.
