### ISSUE TITLE
Allow attaching Balloon Panel to a range/selection

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1176]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

It would be great if the Balloon Panel supported attaching to a range object, so that it could be placed literally anywhere in the text and so on.

In result [balloonPanel.attach](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.ui.balloonPanel-method-attach) would support first parameter as a `CKEDITOR.dom.range` too.

Currently the limitation is that the balloon can only be attached to the whole element, so selection like that (in case of balloon toolbar) allows us only to position it relatively to the whole element:

![image](https://user-images.githubusercontent.com/5353898/34043265-916723f0-e1a0-11e7-8efb-4982aac75bb3.png)

Instead we'd like to attach it to the center of a selection.

**Comment by Comandeer** [comment]
Merged into `major`, will be released in CKEditor 4.11.0.
