### ISSUE TITLE
Copy & paste in a table

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [ckeditor/ckeditor-dev#1178]
Hi,

when I write a text into a cell of a table, its not possible to copy this text some times into this same cell. When pressing Ctrl/V, always the whole content of the cell is replaced

Example:
![32840562-4ac7db96-ca18-11e7-907b-8f613bfdd199](https://user-images.githubusercontent.com/1800472/32949473-3fb829f4-cba3-11e7-8209-788fee76cb34.png)

The word "Testtext ->" has to be copied several times, so at the end the table should look like this:
![32840582-5c078f5a-ca18-11e7-8df7-dc881169b56f](https://user-images.githubusercontent.com/1800472/32949505-5961f164-cba3-11e7-9f38-54ddbd9ec8af.png)

But every time I paste the content of the clipboard the content of the cell is completely replaced by the text of the clipboard:
![32840598-69c5bd10-ca18-11e7-9306-840022e7e3d3](https://user-images.githubusercontent.com/1800472/32949518-62bf9306-cba3-11e7-9a60-29eb898a1104.png)

(See also [https://github.com/turnermm/ckgdoku/issues/31](https://github.com/turnermm/ckgdoku/issues/31))

Best regards
Juergen

**Comment by f1ames** [comment]
@Juergen-aus-Koeln could you provide more details on the issue:
* browser used,
* CKEditor version,
* input HTML,
* reproduction steps (which part of HTML should be copied and where to cause the described behaviour).

**Please remember to follow the issue template next time**.

**Comment by Juergen-aus-Koeln** [comment]
Ok, I'll try to give some hints to the users, and I hope that they will remember this

**Comment by jacekbogdanski** [comment]
Hello,
this issue has been solved with `4.7.2` version release. Please, upgrade your CKEDITOR.

**Comment by turnermm** [comment]
See:  turnermm/ckgdoku/issues/31
