### ISSUE TITLE
Elements in elements path are draggable

### ISSUE THREAD

**Issue by wojtekw92** [ckeditor/ckeditor-dev#1191]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/
2. Put cursor somewhere in the text.
3. Try to drag some element from `elementspath`

### Expected result

Elements are not draggable

### Actual result

You can drag element
![draggable](https://user-images.githubusercontent.com/7364832/33071779-2ff19a6a-cebd-11e7-8220-1ffaeeaeae91.gif)

## Other details

* Browser: all
* OS: MacOS 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: elementspath

**Comment by mlewand** [comment]
Fixed with #1191.
