### ISSUE TITLE
Cloud Service plugin supports IE8-IE9

### ISSUE THREAD

**Issue by wojtekw92** [ckeditor/ckeditor-dev#1193]
For now `cloudservice` plugin is not working on IE8/IE9. We should add this support.

**Comment by mlewand** [comment]
What is it, is it feature or a bug? 😄 Use our template for reporting issues.

**Comment by f1ames** [comment]
@wojtekw92 please correct the issue description to use our issue template.

**Comment by msamsel** [comment]
@mlewand do  you know if this issue can be closed?

**Comment by mlewand** [comment]
Let's close it. We'll support only IE11 and modern browsers during the release. If community will require support for old IEs we'll consider it in the future.
