### ISSUE TITLE
Inlinetoolbar 'tests/plugins/inlinetoolbar/manual/inlinetoolbar' throws an exception (t/933)

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1202]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://tests.ckeditor.test:1030/tests/plugins/inlinetoolbar/manual/inlinetoolbar
2. Start clicking on a red elements to make inline toolbar visible.

### Expected result

Toolbar is visible. No errors thrown.

### Actual result

Toolbar is visible. Some errors thrown when toolbar is shown.

![nov-22-2017 13-51-40](https://user-images.githubusercontent.com/1061942/33128327-5818340c-cf8c-11e7-9927-03be1108ee02.gif)

## Other details

* Browser: FF/Edge/IE
* OS: All
* CKEditor version: `t/933`
* Installed CKEditor plugins: `inlinetoolbar`

**Comment by Comandeer** [comment]
Closed by 14051f9.
