### ISSUE TITLE
Race condition while uploading images to CKFinder using uploadimage plugin

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1213]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open a new tab - https://codepen.io/mlewand/pen/RjyoPR.
2. Select all four images rendered in HTML preview.
3. Copy with `ctrl/cmd+c`.
4. Open https://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images.
5. Focus and clear contents of editor under "Uploading Dropped and Pasted Images".
6. Paste using `ctrl/cmd+v`.

 ### Expected result

All four images are upload, each image is different.

 ### Actual result

Randomly some images will duplicate/mangle. If you did not reproduced try again, as it's a basically a race condition.

 ## Other details

* Browser: All
* OS: Windows 10, Mac
* CKEditor version: 4.7.3

**Comment by Comandeer** [comment]
It seems that issue is less likely to happen with open console with "disable cache" option checked.

**Comment by mlewand** [comment]
> It seems that issue is less likely to happen with open console with "disable cache" option checked.

That has to do with a lower performance of HTTP requests. I had significantly "better" results with IE11 too. 🙂
