### ISSUE TITLE
Getting native data from clipboard return empty string with asynchronous requests

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1223]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Open editor
2. Set break point here: https://github.com/ckeditor/ckeditor-dev/blob/5b876ee70ab3e4aefa37c8c9a660a1a48788ce38/plugins/pastefromword/plugin.js#L67-L68
3. Copy some MS Word content to editor
4. Check what is returned with `getData`

### Expected result

full raw text/html clipboard is returned

### Actual result

empty string

## Other details

* Browser: All
* OS: …
* CKEditor version: Major branch
* Installed CKEditor plugins: paste from word, clipboard

**Comment by mlewand** [comment]
This issue was not released yet, so there's no need for adding a changelog entry.
