### ISSUE TITLE
don't want to nest a table in a cell

### ISSUE THREAD

**Issue by mybydhn** [ckeditor/ckeditor-dev#1228]
You don't want to nest a table in a cell. When the cursor is positioned in the cell, the table button is gray. How should I write?

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
