### ISSUE TITLE
Support for WebSpellChecker?

### ISSUE THREAD

**Issue by UserName011** [ckeditor/ckeditor-dev#1230]
CKeditor had builtin support for WebSpellChecker (https://www.webspellchecker.net/    for scayt) :

https://dev.ckeditor.com/query?status=!closed&reporter=SpellChecker.net

https://dev.ckeditor.com/ticket/8172

Why it's no longer exists?

**Comment by f1ames** [comment]
WebSpellChecker is by default added in **Standard** and **Full** build (see https://ckeditor.com/cke4/builder) so nothing has changed in this matter and it can still be used with CKEditor.
