### ISSUE TITLE
Balloon panel is not positioning properly inside divarea editor

### ISSUE THREAD

**Issue by wojtekw92** [ckeditor/ckeditor-dev#1238]
## Are you reporting a feature request or a bug?

Bug 

## Provide detailed reproduction steps (if any)

1. Attach ballon panel to element outside editor view.

### Expected result

Balloon panel should be inside editor view.

### Actual result

Balloon panel is attached outside the view. 

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.8
* Installed CKEditor plugins: balloonpanel, divarea

**Comment by Comandeer** [comment]
Fixed alongside #1048.
