### ISSUE TITLE
Enhanced Image Plugin not working properly

### ISSUE THREAD

**Issue by Jeniczech** [ckeditor/ckeditor-dev#1254]
## Are you reporting a feature request or a bug?

A bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*
https://drive.google.com/open?id=1t7JAPid7fxXjJelgJQW9GL7yGnrjwX3w
## Provide detailed reproduction steps (if any)

1. I customized CKEditor adding Enhanced Image Plugin
2. I downloaded the entire package
3. I installed on the server

### Actual result

When I open the image editor, I cannot choose the aligment, not check the "Captioned Image"

## Other details

* Browser: Chrome
* OS: Mac
* CKEditor version: 4.7.3
* Installed CKEditor plugins: Enhanced Image

**Comment by msamsel** [comment]
Please check your implementation. Here is an example where plugin works correctly:
https://cdn.ckeditor.com/4.7.3/full-all/samples/old/image2/image2.html

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
