### ISSUE TITLE
CKEditor: Button tag is not working.

### ISSUE THREAD

**Issue by pradeepgoud1210** [ckeditor/ckeditor-dev#1259]
Hi,

We have button tags `<button type="button">Edit</button>` almost in all our forms, this tag looks fine when i use CK-Editor version 3, but now we want to upgrade to version 4.7.3. When we use our existing forms with newer version of ck-editor, button tags are displaying as plain text instead of button control. But this is working fine when i use input type button`<input type="button" />`.

Please do the needful.

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
