### ISSUE TITLE
can i use two ckeditor in one page?

### ISSUE THREAD

**Issue by zhuangbb** [ckeditor/ckeditor-dev#1263]
## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
Hi @zhuangbb, GitHub is not a place for such questions. This place is dedicated for reporting bugs or requesting new features in editor.
Another thing is that your question might be checked in less than 5 minutes just implementing it seeing what happen.
Example with multiple inline CKEditors you can find [here](https://cdn.ckeditor.com/4.7.3/full-all/samples/old/inlineall.html).
