### ISSUE TITLE
Edge fires editor#blur event during window resize while editor is focused

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1265]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://codepen.io/mlewand/pen/ZaqVRG
2. Open dev console.
3. Focus the editor.
4. Resize the window.

This looks pretty much like an upstream issue, but we need to confirm that.

### Expected result

No "blur" log is added.

### Actual result

Console log reports "blur" event during resiizng.

## Other details

Chrome, FF, IE11 doesn't have this issue.

* Browser: Microsoft Edge 41.16299.15.0
* OS: Windows 10
* CKEditor version: 4.7.3

**Comment by jswiderski** [comment]
I have just checked problem in Microsoft Edge 40.15063.674.0 - problem can be reproduced in CKE 4.7.3 as well as current major branch.

**Comment by mlewand** [comment]
Actually, before confirming it, I'd ask to check if it isn't upstream issue - because I have a feeling that might be the case.

**Comment by jacekbogdanski** [comment]
It's definitely an upstream issue as it works this way for empty focusable elements (tested on input and editable div). However, I see that the latest Firefox (67.0.4 64-bit) also works the same as Edge, so blur event is fired during window resize on a focused focusable element. You can reproduce the issue for native elements with https://codepen.io/jacekbogdanski/pen/wLxbZV

I'm closing this issue as it seems like it's expected browser behavior (at least for Firefox and Edge) and probably shouldn't cause any important issues with CKEditor itself.
