### ISSUE TITLE
Images pasted from Word should not contain file path as an alternative text

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1267]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open page with CKEditor.
2. Open document in a Word with an image in it.
3. Select all the contents in Word.
4. Paste into the CKEditor.
5. Click "Source" button to see the output.

### Expected result

Image should contain either just the file name (with no directory path), or no alt at all.

### Actual result

Image contains path to an image, like: `X:\Users\foobar\Pictures\picts\1.jpg`.

## Other details

* Browser: Chrome, Firefox, Edge 16
* OS: Any
* CKEditor version: 4.8.0

**Comment by jacekbogdanski** [comment]
I cannot reproduce this issue. Tested on Windows10/Office365 and Windows/Office2013. Everything looks good on paste from Word.

**Comment by msamsel** [comment]
I cannot reproduce it either, without extra actions from my side.
When image is drag&drop to office it gets Description with path to image. But description is not embed in editor, unless image's title is present in Word. In such case both title and description are copied as alt for img tag.
Example;
`<img alt="Tytuł: sth — opis: C:\Users\foobar\Pictures\mini imgs\1.jpg" ...`
![screen shot 2018-01-17 at 14 09 50](https://user-images.githubusercontent.com/9017322/35044301-2543cd4a-fb90-11e7-9661-7c15983e1c10.png)
