### ISSUE TITLE
Unresponsive editor after pasting a big amount of data

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#1271]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Paste some very big amount of data into the editor (could be whole "Pan Tadeusz").
2. Select some text and apply bold to it.

### Expected result

Everything runs smoothly.

### Actual result

Editor becomes nearly unresponsive

## Other details

* Browser: Chrome
* CKEditor version: at least 4.5.0+
* Installed CKEditor plugins: clipboard

it seems that without `clipboard` plugin everything's smooth again.

**Comment by Comandeer** [comment]
Could be connected: https://bugs.chromium.org/p/chromium/issues/detail?id=109587

**Comment by jacekbogdanski** [comment]
The issue https://bugs.chromium.org/p/chromium/issues/detail?id=109587 has been fixed and it seems like everything runs smoothly now. I tested the issue on CKEditor `4.10.1` built version (`full-all`).
![peek 2018-09-13 08-49](https://user-images.githubusercontent.com/10279586/45471617-f1a1e680-b731-11e8-8c2e-98080c993bef.gif)
