### ISSUE TITLE
Unit test 'tests/plugins/balloonpanel/cssloading' fails on IE8/9/10

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1276]
## Are you reporting a feature request or a bug?

Task: Failing test

## Provide detailed reproduction steps (if any)

1. Run `tests/plugins/balloonpanel/cssloading` test.

### Expected result

Test passes.

### Actual result

Test fails.

![screen shot 2017-11-29 at 16 34 13](https://user-images.githubusercontent.com/1061942/33383408-87b2b182-d523-11e7-88d7-757f33f46f03.png)

## Other details

* Browser: IE8/9/10
* OS: Windows
* CKEditor version: 4.8.0 (pre-release `major`)
* Installed CKEditor plugins: `balloonpanel`

**Comment by mlewand** [comment]
I'm pretty sure, the issue will apply to: https://github.com/ckeditor/ckeditor-dev/blob/e6012702ffffc5f896f461f06654a949016d9f93/tests/plugins/balloontoolbar/cssloading.js

So please fix both at the same time.

**Comment by mlewand** [comment]
@f1ames it might be due to the fact that IE doesn't have `document.location.origin`, see https://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/
