### ISSUE TITLE
Failing tableselection/integration/selectall test

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#1277]
## Are you reporting a feature request or a bug?

Failing test

## Provide detailed reproduction steps (if any)

<img width="577" alt="screen shot 2017-11-29 at 16 41 48" src="https://user-images.githubusercontent.com/1078728/33383675-42c4ce60-d524-11e7-8019-de58b812ae51.png">

## Other details

* Browser: Chrome 62.0.3202.94, Safari 11.0.1 (13604.3.5)
* OS: macOS
* CKEditor version: 4.80 (built version with `uploadimage` plugin enabled)

**Comment by Comandeer** [comment]
It seems that integration with `selectall` does not work due to [`selectionChange` listener in `widget` plugin](https://github.com/ckeditor/ckeditor-dev/blob/45cf8e0e8a60ec547f8850d1a91594e6cf9bf98a/plugins/widget/plugin.js#L2732-L2750).

It's not new issue, introduced by changes in 4.8.0, it was just not caught earlier due to the fact that this test does not include `widget` plugin. The easiest way to fix failing test for now is to remove `widget` plugin, but then identical bug as #1278 occurs, which is [being fixed by @f1ames](https://github.com/ckeditor/ckeditor-dev/issues/1278#issuecomment-348136691).

**Comment by f1ames** [comment]
It is basically `widgetselection` plugin which breaks this test. Look slike not a recent regression, it probably just was not tested in such configuration.
