### ISSUE TITLE
Failing core/config/themedui* tests

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#1278]
## Are you reporting a feature request or a bug?

Failing tests

## Provide detailed reproduction steps (if any)

`tests/core/config/themedui` and `tests/core/config/themedui2` throw:

```
Uncaught TypeError: Cannot read property 'registered' of undefined
    at b.toAllowedContentRules (ckeditor.js:1270)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.filter.allow (ckeditor.js:213)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.filter.allow (ckeditor.js:214)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.filter.addFeature (ckeditor.js:218)
    at addFeature (ckeditor.js:265)
    at f (ckeditor.js:649)
    at b (ckeditor.js:648)
    at a (ckeditor.js:650)
    at a.<anonymous> (ckeditor.js:655)
    at a.e (ckeditor.js:10)
```

## Other details

* CKEditor version: 4.80 (built version with `uploadimage` plugin enabled)

**Comment by f1ames** [comment]
Seems like there is some race condition, or `widget` plugin is not loaded for some reason. This error is reproducible on sample (build version) with config (same as in test):
```
config.plugins = 'about,basicstyles,bidi,blockquote,clipboard,colorbutton,colordialog,div,elementspath,enterkey,entities,find,flash,font,format,forms,horizontalrule,image,iframe,indent,justify,link,list,maximize,newpage,pagebreak,pastefromword,pastetext,preview,print,removeformat,resize,toolbar,save,selectall,showblocks,showborders,smiley,sourcearea,specialchar,stylescombo,table,templates,undo,wysiwygarea';

```

**Comment by f1ames** [comment]
Looks like it is caused by `stylescombo` trying to add widget related styles to `ACF`:

![image](https://user-images.githubusercontent.com/1061942/33421762-72bcd5e2-d5b3-11e7-92fa-456eb645bbd8.png)

however, the `widget` plugin is not present. Removing `stylescombo` from config or adding `uploadimage` makes everything is loading fine 🤔

**Comment by f1ames** [comment]
So now, when `uploadimage` is included by default also its dependencies are included in `ckeditor.js` (`widget` plugin).
Even though these two plugins are not used by the editor (considered above config), `widget` plugin by default registers its custom styles handler - https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/widget/plugin.js?utf8=%E2%9C%93#L3591-L3608. And so when the `stylescombo` processes the styles from `style.js`, the custom styles handler for `widget` type exists and gets executed. However, as there is no plugins `widget` initiated it fails.
