### ISSUE TITLE
Deprecated HTML5 video tags

### ISSUE THREAD

**Issue by rhazor** [ckeditor/ckeditor-dev#1309]
Using 4.5.7 library version on Drupal 7 and adding tags like `<video autoplay controls loop></video>` gets replaced to `<video autoplay="" controls="" loop="">` which are depcrecated.

**Comment by Comandeer** [comment]
According to the [HTML specification](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) such syntax of attributes is completely valid:

> If the attribute is present, **its value must either be the empty string** or a value that is an ASCII case-insensitive match for the attribute’s canonical name, with no leading or trailing white space.
