### ISSUE TITLE
CKEditor not working in MS Edge

### ISSUE THREAD

**Issue by fdgsogc91** [ckeditor/ckeditor-dev#1316]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

I am having issues with the installation of CKEditor for MS Edge browsers.  I originally reported this issue in issue #924 but it was closed and not resolved.

Here I explain in more detail my issue...

I really appreciate the assistance with my integration issue of getting CKEditor 4 working on my ColdFusion server in MS Edge in issue #924.

However, no one has yet directly commented on the fact that the documentation (https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_installation) recommends one implementation of CKEditor 4 and your test page which works on Edge uses a different implementation method.  Below I have provided the recommended code which I have used and the code used by the test page (https://cdn.ckeditor.com/4.7.3/full-all/samples/).  I would appreciate some guidance on how to get the recommended implementation done or please point me to the documentation that describes how to implement per the test page.  I'm sorry that the code snippets are not formatting very well. Thank you in advance for your assistance.

**CODE PER DOCUMENTATION**

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A Simple Page with CKEditor</title>
        <!-- Make sure the path to CKEditor is correct. -->
        <script src="../ckeditor.js"></script>
    </head>
    <body>
        <form>
            <textarea name="editor1" id="editor1" rows="10" cols="80">
                This is my textarea to be replaced with CKEditor.
            </textarea>
            <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            </script>
        </form>
    </body>
</html>
```

**CODE PER TEST PAGE**

```html
<div class="adjoined-bottom">
	<div class="grid-container">
		<div class="grid-width-100">
			<div id="editor">
				<h1>Hello world!</h1>
				<p>I'm an instance of <a href="http://ckeditor.com" > CKEditor </a>.</p>
			</div>
		</div>
	</div>
</div>
```

**Comment by mlewand** [comment]
Corrected markdown formatting, and adjusted the issue to our template.

**Comment by mlewand** [comment]
We have changed the code in our main sample some time ago, to simplify the sample and move our "examples" in the [CKEditor SDK](http://sdk.ckeditor.com/).

You can still see "old samples" for instance in http://cdn.ckeditor.com/4.7.3/full-all/samples/old/replacebycode.html - this sample utilizes pretty much the code approach from "code per documentation" block.

This is just a regular HTML/JS so you can get it working despite the backend technology you're using, as long as you're producing a valid HTML and link existing JS code.

You could try even simpler code, like:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A Simple Page with CKEditor</title>
        <!-- Make sure the path to CKEditor is correct. -->
        <script src="https://cdn.ckeditor.com/4.7.3/standard-all/ckeditor.js"></script>
    </head>
    <body>
        <form>
            <textarea name="editor1" id="editor1" rows="10" cols="80">
                This is my textarea to be replaced with CKEditor.
            </textarea>
            <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            </script>
        </form>
    </body>
</html>
```

So you don't have to worry about putting editor in correct place of your webserver, instead you'll hotlink it to our CDN.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
