### ISSUE TITLE
Exception after double-click on the text node

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#1318]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://localhost:1030/tests/plugins/balloontoolbar/manual/balloontoolbar.
2. Double click on "Apollo 11" in the red frame.
3. Double click on "the first" in the red frame.

### Expected result

Text should select without any errors.

### Actual result

There is the error in the console.

## Other details
**GIF**
![bug_cke4](https://user-images.githubusercontent.com/20988892/33549734-d3264450-d8eb-11e7-80e3-aa4556c92f70.gif)

**Notes**
This issue occurs also if you click many times between red frames.

* Browser: All browsers
* OS: Windows 10, MacOS X
* CKEditor version: 4.8.0

**Comment by f1ames** [comment]
Similar to #1202.

**Comment by Comandeer** [comment]
Closed by 14051f9.
