### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by andrew-vogulkin** [ckeditor/ckeditor-dev#1329]
## Provide detailed reproduction steps (if any)
1. click on Table icon on toolbar
2. click on X (not on cancel)
3. click on Table icon on toolbar again
4. click on X (not on cancel) 
5. PROFIT! 
### Expected result
widget close 
### Actual result
tabs is blocked by non breakable loop
## Other details
reason: 
variable *me._.tabBarMode*  not always FALSE.
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/dialog/plugin.js#L453

sorry for eng :) 

* Browser: latest chrome
* OS: ubuntu
* CKEditor version: 4
* Installed CKEditor plugins: tables, images2

**Comment by wojtekw92** [comment]
Hi @andrew-vogulkin I was trying to reproduce this bug on CKEditor 4.7.3 [link](http://cdn.ckeditor.com/4.7.3/standard/samples/) with chrome (`Version 62.0.3202.94`). And this bug doesn't occurs. Can You check if you are able to reproduce this bug with link that I gave you? Can you add versions of CKEditor and chrome to bug description?

**Comment by andrew-vogulkin** [comment]
@wojtekw92 i check link and i cant reproduce, CKEditor 4.7.1, chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by mlewand** [comment]
Great, so I'll close the issue.
