### ISSUE TITLE
Color dialog and other dialog not opening in ckeditor in IE11

### ISSUE THREAD

**Issue by softDevjQueryJS** [ckeditor/ckeditor-dev#1331]
I am using custom CKEditor(version:4.7.3) plugin in modal popup using jQuery. It is working fine in chrome and FF but in IE 10 when I am going to select font color or back color then dialog box get flicker. It doesn't keep open to select color.

This is reported bug which was fixed in version 4 and abovebut still it doesnt seems to be.

Is anyone facing same issue. any solution for this?

**Comment by msamsel** [comment]
Hi,

could you provide example of your implementation in an online service (codepen.io, jsfiddle.net, etc.) Without it, it's hard to guess what might went wrong for you.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
