### ISSUE TITLE
Not installing ckeditor through bower

### ISSUE THREAD

**Issue by zeeshanmulla18** [ckeditor/ckeditor-dev#1332]
## Bug

Hello All,

While installing Ckeditor through bower I am not able to install it and getting the following error log.  Just cannot figure out what the problem could be.  
Error Log : 
bower ckeditor-widget#* EINCOMPLETE Transfer closed with 27497 bytes remaining to read

We got following https related error : CERT_UNTRUSTED

In following way we have applied the dependency in the bower file : 
"ckeditor": "#full/4.4.7",

Can you please let me know what the issue can be.

## Other details

* OS: Ubuntu
* CKEditor version: 4.4.7

Thanks and Regards,
Zeeshan

**Comment by msamsel** [comment]
Some time ago we had small troubles with certficate #1340. I tested bower installation and currently it works fine for me.
If you have different experience please provide more details how to reproduce the error. I close issue for now as it seems to be resolved.
