### ISSUE TITLE
for anchors that wrap text, only the first anchor has an id

### ISSUE THREAD

**Issue by bugreport2017** [ckeditor/ckeditor-dev#1334]
# Are you reporting a feature request or a bug?

Bug

## Check if the issue is already reported

Possibly related to this issue which is instead reproduced using the link dialog:
https://github.com/ckeditor/ckeditor-dev/issues/1046

## Provide detailed reproduction steps (if any)

1. Add some text
2. create an anchor which wraps the added text
3. repeat 1 & 2

### Expected result

Each anchor should have an id.

### Actual result

Only the first anchor has an id.

## Other details

anchors should have an id and name, behaviour is inconsistent without id:
https://dev.ckeditor.com/changeset/7618
https://dev.ckeditor.com/ticket/1961

Reproduced in following sample versions:
https://sdk.ckeditor.com/samples/standardpreset.html
http://nightly.ckeditor.com/17-12-10-07-04/standard/samples/
http://nightly.ckeditor.com/17-12-10-07-04/full/samples/

* Browser: Firefox, Chrome, IE
* OS: windows 7
* CKEditor version: 4.8.0, 4.7.3, 4.7.1 (only tested those)
* Installed CKEditor plugins: see samples

**Comment by nathansamson** [comment]
I believe my fix in https://github.com/ckeditor/ckeditor-dev/pull/1914 will fix this as well

**Comment by mlewand** [comment]
I can confirm that it's going to be fixed by #1046. Please subscribe to mentioned ticket to get further updates.
