### ISSUE TITLE
CKEDITOR.instances.editor.setData excute asynchronously?

### ISSUE THREAD

**Issue by longxingren** [ckeditor/ckeditor-dev#1335]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. I set data of editor via ```window.CKEDITOR.instances.editor.setData``` after page load.
2. And I bind change event to editor via ```window.CKEDITOR.instances.editor.on('change', ()=>{})```.
3. I don't want the change event to trigger when I set data at first.
4. So I try:
```
window.CKEDITOR.instances.editor.setData 
this.bindChangeEvent()
```
and
```
window.CKEDITOR.instances.editor.setData
setTimeout(()=>{this.bindChangeEvent()})
```
### Expected result

```setData``` won't trigger the change event of editor 

### Actual result

Change event always triggered, so is there any function execute asynchronously in ```setData```? 
I found that if I set the time parameter of **setTimeout** to 50 ~100, the change event won't be triggered, the time is **uncertain**.

## Other details

* Browser: chrome 62.0
* OS: windows
* CKEditor version: 4.7.3
* Installed CKEditor plugins: :
a11yhelp
basicstyles
bidi
blockquote
button
clipboard
contextmenu
copyformatting
deselect
dialog
dialogui
elementspath
enterkey
entities
fakeobjects
filebrowser
find
floatingspace
floatpanel
font
format
horizontalrule
htmlwriter
image
image2
indent
indentlist
justify
lineutils
link
list
listblock
magicline
maximize
menu
newpage
notification
panel
pastefromword
pastetext
popup
preview
removeformat
resize
richcombo
selectall
selectallcontextmenu
showborders
sourcearea
specialchar
stylescombo
tab
toolbar
undo
widget
widgetselection
wysiwygarea

**Comment by Comandeer** [comment]
According to [our documentation](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.editor-method-setData), `setData` is always asynchronous. Probably your issue could be fixed by moving your code into `setData` callback:

```javascript
window.CKEDITOR.instances.editor.setData( 'data', function() {
    bindChangeEvent();
} );
```
