### ISSUE TITLE
Keystroke labels should work for function keys (like F7, F8)

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1338]
## Are you reporting a feature request or a bug?

Feature request

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

Extracted from #1154.

## Provide detailed reproduction steps (if any)

Using keystrokes like `editor.setKeystroke( CKEDITOR.CTRL + 117, 'Play' );`, will display **Play (Ctrl+u)** instead of **Play (Ctrl+f7)**.

The cause of this issue is described here: https://github.com/ckeditor/ckeditor-dev/issues/1154#issuecomment-350705733.

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.6.0
* Installed CKEditor plugins: -

**Comment by mlewand** [comment]
Fixed with #1427.
