### ISSUE TITLE
Html issue with editor

### ISSUE THREAD

**Issue by surinderantech** [ckeditor/ckeditor-dev#1343]
I am trying to use ck editor , I add html to editor box it saved to databse successfully. When i reopen my editor page and check source it vanish my all divs and all p tag to all html can you please help me how i can get out from this problem.

**Comment by surinderantech** [comment]
I am trying to use ck editor , I add html to editor box it saved to databse successfully. When i reopen my editor page and check source it vanish my all divs and all p tag to all html can you please help me how i can get out from this problem.

**Comment by surinderantech** [comment]
Please suggest me how to solve this

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
