### ISSUE TITLE
https://ckeditor.com/ckeditor-4 demo run failed

### ISSUE THREAD

**Issue by 1619316848** [ckeditor/ckeditor-dev#1358]
## Are you reporting a feature request or a bug?

bug

## Provide detailed reproduction steps (if any)

1. goto https://ckeditor.com/ckeditor-4/
2. the sample demo, ckeditor init failed, some body can init success and some body can't

### Expected result
Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices

DEMOCKE4 INIT FAIL: TypeError: Cannot read property 'on' of null
at r (main.js:20)
at n (main.js:20)
at Object.init (main.js:20)
at Object.init (main.js:20)
at r (main.js:21)
at HTMLDocument.init (main.js:8)
r @ main.js:21

**Comment by msamsel** [comment]
Hi,
It works fine on my Chrome browser.
Can you describe your environment where you run this page?
What kind of browser, OS do you have?
Do you se some browser extensions?
Does problem appear when you clear out the cache?

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
