### ISSUE TITLE
Make paste notification more straightforward so it does not confuse users

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1363]
## Are you reporting a feature request or a bug?

Task

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

Extracted from #469.

## Provide detailed reproduction steps (if any)

It seems that for some users (see comments in #469), notification which appears after clicking Paste button is quite confusing, indicating that paste does not work.

![image](https://user-images.githubusercontent.com/1061942/34202299-b1360b9e-e577-11e7-8e3a-4687f7a42b3a.png)

We are considering updating it to make it more clear. However, it is already quite short and straightforward, so it is not an easy task. The current message is:

> Your browser doesn't allow you to paste this way. Press ⌘+V to paste.

If you have any propositions, feel free to drop a comment.

## References

* https://disqus.com/home/discussion/ckeditor-com/paste_from_word/#comment-3570081596
  > (...) If you have control over the "Your browser doesn't allow you to paste ..." message, I suggest wording it to indicate that the 'Paste from Word' functionality will be invoked after the Ctrl+V operation.

**Comment by wwalc** [comment]
Let's try proposing maybe several alternatives to see if we will find anything better. Perhaps the message could be less confusing if it explained that the editor cannot access the clipboard...

**Comment by wojtekidd** [comment]
What does exactly _this way_ stand for? When you click right mouse button and try to copy using the browser menu?

**Comment by wwalc** [comment]
Proposal 1: 

Press <kbd>Ctrl</kbd> + <kbd>V</kbd> to paste. Due to technical reasons CKEditor is unable to access clipboard data in your browser.

**Comment by mlewand** [comment]
> CKEditor is unable to access clipboard

I'm afraid people still will read it as our inability / regression as opposed to early CKE4 releases. 😞

**Comment by Comandeer** [comment]
I think that the main issue is with word "allow". Maybe just simply replace "allow" with "support"?

> Your browser doesn't support pasting this way. Press ⌘+V to paste.

In this case it is more clearly that it's browser's fault, not ours.

**Comment by wojtekidd** [comment]
Guys bit the end user must know exactly what stands behind _this way_. Some users might not even be aware that there are various ways of pasting stuff into the editor, because they used one way and it awlays worked.

**Comment by msamsel** [comment]
For me confusing is pronoun, because I’m not sure what is “this way”. I’d rather to see sth like:
“Your browser doesn’t allow on paste with button. Please use keyboard shortcut Ctrl + V to paste.” Or sth similar what clearly define “this way” and inform that I need to use keyboard.

**Comment by AnnaTomanek** [comment]
I'd propose going with (1) solution first (2) explanation second. Something like:

> Press <kbd>Ctrl</kbd> + <kbd>V</kbd> to paste. Your browser doesn't support pasting with the toolbar button or context menu option.

If it is too long, perhaps just changing the order and a small rewording would suffice?

> Press <kbd>Ctrl</kbd> + <kbd>V</kbd> to paste. Your browser doesn't support pasting using other methods.

**Comment by wojtekidd** [comment]
Option 2 seems to be 👌

**Comment by rogerharkavy** [comment]
I think Option 2 is still confusing because of the "your browser" part. To me, that says to the user that they need to use a different browser than the one they are currently using. How about, "The editor doesn't support pasting using other methods."

**Comment by f1ames** [comment]
@rogerharkavy, thanks for sharing, `The browser` versus `The editor` part is a little bit tricky. In this case it is the browser (its API) which doesn't support pasting in such ways (mostly due to security reasons) so the message tries to  describe that (and if you switch to IE browsers it will work without any messages as there are no such limitations). So it is the browser behaviour which is reflected in how editor works (what it can do). I think we should stick with `your browser`.

**Comment by f1ames** [comment]
@mlewand have you considered this issue as candidate for `4.9.0` (as we are already working on improving paste experience)?

**Comment by rogerharkavy** [comment]
@f1ames Thank you for clarifying that, I understand now.

**Comment by mlewand** [comment]
@f1ames thanks for bringing attention to this one. Let's give it a try in this release. Maybe this time the message will be more straightforward.

I'll also vote for first option in https://github.com/ckeditor/ckeditor-dev/issues/1363#issuecomment-353261235.
