### ISSUE TITLE
CKEditor's internal iframe gets hidden depending on page URL... ?

### ISSUE THREAD

**Issue by remi00** [ckeditor/ckeditor-dev#1366]
## Are you reporting a feature request or a bug?

Bug
*...but it definitely requires triage and assessment, as it may be working as designed for some reason, or be a known (config/env?) issue. It sounds too weird not to be related with some configuration, that I'm unaware of...*

## Provide detailed reproduction steps

1. Configure CKEDITOR to replace textarea (any method: `CKEDITOR.replace`, or `jquery.ckeditor()`) with basic config, standard package
2. Now, navigate to the page including CK Editor instance with query string including ampersand character (e.g.: `http://localhost/?id=foo&bar=1`). If the query string won't include ampersand (e.g. `http://localhost/?id=foo`), the issue won't reproduce...

### Expected result

CK Editor instance shall provide editing capabilities and present edited content.

### Actual result

The wysiwyg editor does not show content nor provides any editing capabilities. Interestingly, `iframe` with content gets `hidden` / `display: none`:

```<iframe src="" frameborder="0" class="cke_wysiwyg_frame cke_reset" title="Rich Text Editor, qq" aria-describedby="cke_51" tabindex="0" allowtransparency="true" style="width: 100%; height: 100%; display: none !important;" hidden></iframe>```

## Other details

* Browser: Chrome 63, Firefox 57
* OS: Linux, should not matter
* CKEditor version: latest stable v4.8.0 and nightly from 20-Dec-2017 at 15:09 UTC.
* It does not reproduce on e.g. `nightly.ckeditor.com` online provided samples.

* Installed CKEditor plugins: Standard package.

**Comment by remi00** [comment]
Not an issue, after wasting almost 3hrs I realized it was the ad-blocker plugin causing the issue....

**Comment by koddistortion** [comment]
@remi00 **thank you very much for point that out**. I had the exact same issue yesterday and wasted 4 hours with debugging JS code, DOM inspecting etc. until I found this issue and your "solution".
