### ISSUE TITLE
Dragging files over ckeditor removes css classes from containers

### ISSUE THREAD

**Issue by glillibridge** [ckeditor/ckeditor-dev#1371]
This is a bug
1. Install  ckeditor 4.8 full version, install it, confirm that it is working
2. From outside the browser window click a file and drag it over the ckeditor (without dropping).
3. Some, not all, of the containers (divs or tables) of the ckeditor instance will have their classes removed.
4. Some of ckeditor css is damaged (css removed) as well.
5. Start over, install with custom version ckeditor 4.8 that has only only basic edit/format, image upload, and markdown plugin.  see attached 1 for view
6. Drag file over (do not drop)
7. CSS classes of some (not as many as before) containers is removed and the css of ckeditor is removed in part.  see attached 2 for view

### Expected result
Nothing should happen if I drag an image or file over the ckeditor. Only if I drop on ckeditor should it do any thing. If ckeditor changes css to signify being over something, fine. But change it back after the file has moved off.

### Actual result
see steps 3,4, and 7 above.

## Other details
Note: I have other javascript on the page to catch the dropped file. It works as expected. On the second attachment you can see the image that I dragged over ckeditor in the red bordered box just above ckeditor. 

* Browser: Firefox latest version (57)
* OS: window 7 professional
* CKEditor version: 4.8 downloaded yesterday.
* Installed CKEditor plugins: see above
![ckeditor_drag1](https://user-images.githubusercontent.com/34383420/34267266-15216324-e631-11e7-8ffb-de21f57e7ae9.PNG)
![ckeditor_drag2](https://user-images.githubusercontent.com/34383420/34267268-1539c220-e631-11e7-8860-c88328cbb376.PNG)

**Comment by glillibridge** [comment]
Here attached  is the ckeditor set of  files I used used in the second try. 
[ckeditor_4.8.0_845587f68093-1.zip](https://github.com/ckeditor/ckeditor-dev/files/1580056/ckeditor_4.8.0_845587f68093-1.zip)

**Comment by glillibridge** [comment]
I found the problem. It was in my code

**Comment by mlewand** [comment]
@glillibridge thanks for letting us know 👍
