### ISSUE TITLE
onLoad is not called on dialog radio elements

### ISSUE THREAD

**Issue by anrikun** [ckeditor/ckeditor-dev#1374]
This is a bug.
Everything is in the title:
when defining a *radio* dialog element with an onLoad callback, the callback is not called.
Changing type from radio to select, callback gets called as expected.

**Comment by mlewand** [comment]
@anrikun could you provide a simplified repro setup on CodePen / JSFiddle? What `onLoad` function are you referring to? Is it [`dialogDefinition.onLoad`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.dialog.definition-property-onLoad)?

Adding setup like that would help to verify this issue.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
