### ISSUE TITLE
When I screenshot a image in editor can never have dragable icon rightBottom(upload image have it )

### ISSUE THREAD

**Issue by kongchengqiu** [ckeditor/ckeditor-dev#1376]
Screenshot a image in editor can never have dragable icon rightBottom

**Comment by mlewand** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
