### ISSUE TITLE
When the screenshot or drag to the editor of the picture, why not zoom size (zoom small icons do not have), whether to use the plug-in

### ISSUE THREAD

**Issue by kongchengqiu** [ckeditor/ckeditor-dev#1377]
![123](https://user-images.githubusercontent.com/22467434/34323941-7365aad0-e898-11e7-83ad-2039cebe94b5.gif)

**Comment by mlewand** [comment]
![cannotreproduce](https://user-images.githubusercontent.com/5353898/34409203-92dd383c-ebc8-11e7-9ca8-9e03068fe013.gif)

WFM, looks like you have wrong configuration. For a future, please use our template to report the bugs.
