### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "http://192.168.0.200:90" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by huangche007** [ckeditor/ckeditor-dev#1378]
When I upload image,there is some problem：
Invalid 'X-Frame-Options' header encountered when loading 'http://192.168.0.200:90/v1/article/images/?CKEditor=editor1&CKEditorFuncNum=104&langCode=zh-cn': 'ALLOW-FROM HTTP://192.168.0.103:8080' is not a recognized directive. The header will be ignored.

Uncaught DOMException: Blocked a frame with origin "http://192.168.0.200:90" from accessing a cross-origin frame.

My client ip address:192.168.0.103 The server ip address:http://192.168.0.200

**Comment by jacekbogdanski** [comment]
Hello,

it looks more like not CKEditor issue, but the problem with CORS setup on your server machine. Could you provide more details about your [file manager configuration](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_file_upload) for your server and client?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
