### ISSUE TITLE
Uncaught CKEDITOR.plugins.widget.isDomWidget is not a function exception when moving the cursor over editor

### ISSUE THREAD

**Issue by Yanual** [ckeditor/ckeditor-dev#1386]
## Reproduction steps
1. Installing table plugins, tableresize, tableselection, tabletools, uploadwidget, widget, widgetselection among others.
2. Move the cursor over the CKEditor textarea (no matter the area).
### Actual result
At each movement : **Error** **tableselection/plugin.js** ->
plugin.js:20 Uncaught TypeError: CKEDITOR.plugins.widget.isDomWidget is not a function
    at isWidget (plugin.js:20)
    at CKEDITOR.dom.document.fakeSelectionMouseHandler (plugin.js:279)
    at CKEDITOR.dom.document.listenerFirer (event.js:144)
    at CKEDITOR.dom.document.CKEDITOR.event.fire (event.js:290)
    at HTMLDocument.<anonymous> (domobject.js:46)
isWidget @ plugin.js:20
fakeSelectionMouseHandler @ plugin.js:279
listenerFirer @ event.js:144
CKEDITOR.event.fire @ event.js:290
(anonymous) @ domobject.js:46
### Expected result
No more errors in the browser console each time I move the cursor over the textarea
## Other details
* Browser: Chrome, FireFox
* OS: Win7
* CKEditor version: 4.8
* Installed CKEditor plugins: table, tableresize, tableselection, tabletools, uploadwidget, widget, widgetselection among others …
## Request
I look at the functions available in the plugin widget and I try the isDomWidgetElement function (line 20)and the error does not happen again. I would like to know if my modification is correct and why I have had this problem, am I the only one or if there is another sollution ?
### Modification code on tableselection/plugin.js
Line 20
`
	function isWidget( element ) {
		return CKEDITOR.plugins.widget && CKEDITOR.plugins.widget.isDomWidgetElement( element );
	}
`

**Comment by mlewand** [comment]
You're getting very awkward results - it looks to me that you somehow have **old widget plugin** version while rest of the editor is at 4.8.0, since `isDomWidget` method was introduced in `4.8.0`. This issue can not be reproduced on [CKEditor 4.8.0 build](http://cdn.ckeditor.com/4.8.0/full-all/samples/).

You should update all the editor plugins, otherwise it will often will fail.

Your modification is not doing entirely what the code should do, if you'd inspect the code you'd see that there's one more thing you have to do:

```js
function isWidget( element ) {
	return CKEDITOR.plugins.widget && ( CKEDITOR.plugins.widget.isDomWidgetElement( element ) || CKEDITOR.plugins.widget.isDomWidgetWrapper( element ) );
}
```

But then again, do not use mismatched versions of CKEditor components - because it will break in many, many ways.

**Comment by Yanual** [comment]
Tanks a lot, I'll taken a look on older versions I'll never find this function, isDomWidgetElement and Wrapper seems appear since the 4.5.

**Comment by mlewand** [comment]
Yes it is, but you're  missing [`isDomWidget` functoin which was added in 4.8.0](https://github.com/ckeditor/ckeditor-dev/blob/1f3ce7e8f28013f2eb0e6b801a895b865ba5b8dd/plugins/widget/plugin.js#L1604).

**Comment by Yanual** [comment]
Ok, I'll verify my 4.8.0 build, I don't remember if I downloaded the widget plugin separatly. I'm not at home, I'll do it later. Thanks again.

**Comment by Yanual** [comment]
I checked my build, it dated from October. The method did not exist yet. I just understand now that if you want to integrate an additional plugin you have to re-download the latest build to get the latest corrections and compatibility.
Thank you very much for your help.
Best regards, Yann.

**Comment by markusd1984** [comment]
I'm gettings similar issue with 4.9 using the current builder, so all the plugins that came with it should be for 4.9. I even replaced the widget plugin with 4.9 just in case but didn't help.

> ckeditor.js?p5la2k:1159 Uncaught TypeError: CKEDITOR.plugins.widget.isDomWidget is not a function
>     at B (ckeditor.js?p5la2k:1159)
>     at CKEDITOR.dom.document.v (ckeditor.js?p5la2k:1164)
>     at CKEDITOR.dom.document.m (ckeditor.js?p5la2k:10)
>     at CKEDITOR.dom.document.fire (ckeditor.js?p5la2k:12)
>     at HTMLDocument.<anonymous> (ckeditor.js?p5la2k:65)

ckeditor.js :
`CKEDITOR.tools.buildTableMap=function(q,r,B,v,w){q=q.$.rows;B=B||0;v="number"===typeof v?v:q.length-1;w="number"===typeof w?w:-1;var u=-1,y=[];for(r=r||0;r<=v;r++){u++;!y[u]&&(y[u]=[]);for(var t=-1,z=B;z<=(-1===w?q[r].cells.length-1:w);z++){var p=q[r].cells[z];if(!p)break;for(t++;y[u][t];)t++;for(var A=isNaN(p.colSpan)?1:p.colSpan,p=isNaN(p.rowSpan)?1:p.rowSpan,x=0;x<p&&!(r+x>v);x++){y[u+x]||(y[u+x]=[]);for(var C=0;C<A;C++)y[u+x][t+C]=q[r].cells[z]}t+=A-1;if(-1!==w&&t>=w)break}}return y};(function(){function B(a){return CKEDITOR.plugins.widget&&CKEDITOR.plugins.widget.isDomWidget(a)}function x(a,b){var c=a.getAscendant("table"),d=b.getAscendant("table"),e=CKEDITOR.tools.buildTableMap(c),h=n(a),m=n(b),l=[],k={},f,p;c.contains(d)&&(b=b.getAscendant({td:1,th:1}),m=n(b));h>m&&(c=h,h=m,m=c,c=a,a=b,b=c);for(c=0;c<e[h].length;c++)if(a.$===e[h][c]){f=c;break}for(c=0;c<e[m].length;c++)if(b.$===e[m][c]){p=c;break}f>p&&(c=f,f=p,p=c);for(c=h;c<=m;c++)for(h=f;h<=p;h++)d=new CKEDITOR.dom.element(e[c][h]),
`

**Comment by mlewand** [comment]
Same solution should work for you. Go through the issue once again. However the easiest solution for you would be to rebuild the package using our [package builder](https://ckeditor.com/cke4/builder).
