### ISSUE TITLE
Update year in license headers / docs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1391]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Time to greet year 2018.

Let's update any references in license headers and docs.

**Comment by Comandeer** [comment]
IMO we should prepare some generic script that would do it for us every new year.

**Comment by mlewand** [comment]
@Comandeer That would be lovely, but let's get back to it in... 2019 :D This easy grep seems to be a perfect introduction task for our new devs 🙂

**Comment by Comandeer** [comment]
@mlewand OK, we could get back to it next year, but at least, please, save this grep, because now we have to invent it every single year ;)
