### ISSUE TITLE
Removing headers from table with one row fails

### ISSUE THREAD

**Issue by b2m** [ckeditor/ckeditor-dev#1397]
## Are you reporting a feature request or a bug?

Bug because simple GUI Usage leads to JavaScript Error.

## Provide detailed reproduction steps (if any)

1. Go to https://codepen.io/anon/pen/goxWEe?editors=1010
2. Open the Table Properties (e.g. via the Context Menu)
3. Change Headers to "None"

### Expected result

The Headers of the table are removed.

### Actual result

JavaScript Error: `TypeError: Cannot read property '$' of null`

## Other details

* Browser: Chrome, Firefox, ...
* OS: Linux, Windows, ...
* CKEditor version: 4.8.0 and earlier
* Installed CKEditor plugins: table, tabletools, maybe more

**Comment by msamsel** [comment]
Problem is possible to reproduce on our sample.
Additional option to reproduce:
1. Copy and past to sourcearea:
```
<table border="1" cellspacing="1" cellpadding="1" style="width:500px;"><thead><tr><th scope="row"><br></th><th scope="col"><br></th></tr></thead><tbody></tbody></table>
```
2. Open table properties and change header to `none`.

**Comment by f1ames** [comment]
Closed with https://github.com/ckeditor/ckeditor-dev/commit/2675ac8aa5c167af1d81abaf4652fa01018dd890.
