### ISSUE TITLE
Put the cursor at the end of content when `config.startupFocus = true` is set

### ISSUE THREAD

**Issue by KevinYaoooooo** [ckeditor/ckeditor-dev#1399]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

The [`config.startupFocus`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-startupFocus)`= true;` option does not put the cursor at the end of editor content.

### Expected result

It should be possible to put the cursor at the end of content if `config.startupFocus = true;` was set.

### Actual result

The cursor is always placed at the start of editor content.

## Other details

* Browser: Any
* OS: Any

**Comment by mlewand** [comment]
There are cases when some would like to put the selection the way it is, so at the beginning of the document.

So instead I see it as a feature request, where it could be customized where the selection should appear. By default it will be at the beginning (backward compatibility), but we should also allow explicitly stating where the selection should land. For your case it would be something like:

```js
// Explicitly tell to put the focus at the end of editable.
config.startupFocus = 'end';
```

Also I'm changing browser env, as it works the same in all browsers.

**Comment by KevinYaoooooo** [comment]
Hi @mlewand ,thanks for answering my question, but I've tried, not working for me.

**Comment by mlewand** [comment]
@KevinYaoooooo that's right it won't work yet for you because we have just started developing this feature - so it did not landed in any CKEditor release just yet 🙂

Please keep an eye on this issue, as it gets into the release we'll set the milestone to a release where it lands. From there you will be able to use this feature.

**Comment by KevinYaoooooo** [comment]
@mlewand , thanks for letting me know, looking forward to that feature and bouch of others, cheers~

**Comment by mlewand** [comment]
@KevinYaoooooo This feature has just been positively reviewed and was merged into the `master` branch, which means it's ready for the release.

If you can't wait for the release you can download a 🔥 burning hot nightly release in "CKEditor Nightly Buyild" section on our [Download page](https://ckeditor.com/ckeditor-4/download/). Keep in mind that current nightly has not been verified by our intense integration testing phase, as we do that before the release.

Lastly we just came with a decision to skip minor release and go straight for 4.9.0 release. This means this ticket (and all others) will be incorporated into 4.9.0 release, see [our milestones](https://github.com/ckeditor/ckeditor-dev/milestones) page for a release schedule.

**Comment by KevinYaoooooo** [comment]
Thanks @mlewand, you guys are awesome
