### ISSUE TITLE
Scrollbar in the Styles drop-down list disappears after initial display

### ISSUE THREAD

**Issue by mmojica006** [ckeditor/ckeditor-dev#1405]
when the ESC key is pressed when in inline editing mode. This results in the toolbar being removed. But the cke_focus class is still present on the DIV afterwards as well as the style="position: relative;".

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
