### ISSUE TITLE
ckeditor.insertElement is not working in IE 11

### ISSUE THREAD

**Issue by dilipshelake03** [ckeditor/ckeditor-dev#1418]
## Bug in ckeditor for insertElement function in IE 11?

I am trying to insert new element in ckeditor. I have list of elements in dropdown box. I just want to show the selected value in ckeditor.

I'm using following code for inserting the selected values.

rtEditor = CKEDITOR.instances.xsltRte;
var newElement = CKEDITOR.dom.element.createFromHtml("<span>{{@NT_TOEGANGEN}}
</span>", rtEditor.document );
rtEditor.insertElement( newElement ); 

abov code insert the value in ckeditor as,

 {{@NT_TOEGANGEN}}

but this overrides the existing contents of ckeditor.

i'm getting this issue for IE 11 only. it works fine in other browsers.

Expected Behaviour
- - new element should be inserted at current cursor location.
- - ckeditor existing contents should not get replaced with new element.

* Browser: IE 11
* OS: windows 7
* CKEditor version: 4.8
* Installed CKEditor plugins: ng-ckeditor

**Comment by mlewand** [comment]
`{{@NT_TOEGANGEN}}` is not a valid HTML code. What you're trying to insert is a Text node.

There are few ways to create a node, the simplest would be [`rtEditor.insertText( '{{@NT_TOEGANGEN}}' )`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.editor-method-insertText) and that's it. You could also create your node manually with [`editor.createText()`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.dom.document-method-createText).

And it works perfectly fine on IE11, see https://codepen.io/mlewand/pen/gooevG.

**Comment by dilipshelake03** [comment]
Thanks **mlewand** for quick reply. I was inserting {{@NT_TOEGANGEN}} with span tag as, 

<span>{{@NT_TOEGANGEN}}</span>

**Comment by mlewand** [comment]
The problem is that `{{@NT_TOEGANGEN}}` is not a valid HTML as shown in my CodePen. It could be inserted as a text node tough.

**Comment by dilipshelake03** [comment]
I just tried with insertText() function but still it replacing  existing ckeditor contents.

**Comment by dilipshelake03** [comment]
Hi **mlewand**, I am still facing this issue in IE 11. The existing contents of ckeditor  are getting replace by newly inserted text/element.

please suggest.

**Comment by mlewand** [comment]
I have provided you with a working code https://codepen.io/mlewand/pen/gooevG. Make sure you're doing everything right.

If you're still facing an issue, extract this problem in a way that you can reproduce it on a codepen and send it back to us.
