### ISSUE TITLE
AltGr+A selects editor content with widget at the start or end instead of typing a diacritic "a"

### ISSUE THREAD

**Issue by santaclaus21** [ckeditor/ckeditor-dev#1419]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Set keyboard input language to Polish.
1. Open [CKEditor 4 instance with a Enhanced Image plugin](https://cdn.ckeditor.com/4.8.0/full-all/samples/old/image2/image2.html).
1. Set content using "Source" button to the following HTML:

```html
<figure class="image"><img alt="Saturn V" src="assets/image1.jpg" width="200" />
<figcaption>Roll out of Saturn V on launch pad</figcaption>
</figure>

<p><strong>Apollo 11</strong> was the spaceflight ...</p>
```

1. Put selection in `Apollo 11 ^was the spaceflight ...`
1. Type a `ą` diacritic character by pressing `cmd/ctrl+alt+a`.

### Expected result

"ą" character being typed, nothing else happens.

### Actual result

"ą" character is typed, but whole editor content is being selected.

![Whole content being selected](https://i.imgur.com/5mWzxoU.png)

## Other details

Cannot reproduce the issue on a mac, seems like the only Windows system problem.

* Browser: Chrome
* OS: Windows 10

**Comment by mlewand** [comment]
[config.keystrokes property](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-keystrokes) has an explicit information on how to disable all the keystrokes.

Moreover, Polish letter are not produced by pressing `Alt + <char>` but it's **AltGr** key which is a slightly different key, to keep it short let's say that it acts as ctrl+alt pressed together.

However I can see what is the source of this issue - [our widget selection plugin is attempting to make a selection on `ctrl/cmd + a`](https://github.com/ckeditor/ckeditor-dev/blob/1a9ba27/plugins/widgetselection/plugin.js#L32) without checking `alt` key - this it triggers in `altgr + a` too, which it should not.

I'll just mention that this case will happen only if you have a widget either on a very beginning or end of your content.

I don't see a quick viable workaround for that other than temporarily changing content, which is rather painful.

That being said, I'll put it in the upcoming milestone.

**Comment by santaclaus21** [comment]
@mlewand thank you for explain. Yes, this is case when I have got widget (called "bootstrap grid") at the beginning.

I was trying to temporary fix it by preventDefault, without success on CKEditor..
`$(document).keydown(function(objEvent) {        
				if (objEvent.ctrlKey) {
            if (objEvent.keyCode == 65) {
                objEvent.preventDefault();
								console.log('catch');
            }
        }
});`

**Comment by mlewand** [comment]
I have simplified the issue description. Dropping original content for a reference:

> Bug.
> 
> I have got some problems with widgets and Alt+A keystroke. **Alt+A** (polish "ą") is working for me like **Ctrl+A** (?). I have not found solution to fix it, so I was trying to disable this > keystroke...
> 
> while changing keystroke **is working...**
> `	config.keystrokes = [
>     		[ CKEDITOR.CTRL + 65, 'link' ],
> 		[ CKEDITOR.ALT + 65, 'link' ],
> 		[ CKEDITOR.ALT + CKEDITOR.CTRL + 65, 'link' ]
> 	];`
> 
> I can't disable these keystrokes and **this code is not working** (false, null, emty string):
> `	config.keystrokes = [
> 		[ CKEDITOR.CTRL + 65, false ],
> 		[ CKEDITOR.ALT + 65, false ],		
> 		[ CKEDITOR.ALT + CKEDITOR.CTRL + 65, false ]
> 	];`
> 
> Disable all keystrokes also do nothing:
> `config.keystrokes = [];`

**Comment by mlewand** [comment]
I tried to provide a meaningful summary, but I feel I failed badly (wayyy too long)! 

@AnnaTomanek please, help, help 🙂
