### ISSUE TITLE
ckeditor insertElementIntoRange is not working.

### ISSUE THREAD

**Issue by dilipshelake03** [ckeditor/ckeditor-dev#1430]
## Reports for a bug?

  editor.insertElementIntoRange("<span>New Test</span>", range);
  
I am trying to insert new element at given range. but getting error message as, 

type error Object doesn't support this property or method insertElementIntoRange.

## Other details

* Browser: IE 11
* OS: windows
* CKEditor version: 4.4
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

---

When it comes to [`insertElementIntoRange`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.editable-method-insertElementIntoRange) if you look at the docs, this method should be called on `CKEDITOR.editable` object, not on `CKEDITOR.editor`. So in your case `editor.editable.insertElementIntoRange( ... );`
