### ISSUE TITLE
Add windows env variable

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1433]
## Are you reporting a feature request or a bug?

Feature request.

### Expected result

CKEDITOR.env.win `{Boolean}` property giving information if client OS is Windows.

**Comment by mlewand** [comment]
We generally don't want to do browser sniffing. We discussed the issue that motivated you to create this issue / PR and we should solve it the other way around.

Thus Windows detection is not needed at this point.
