### ISSUE TITLE
Alignment Buttons are disabled when pasting text and enterMode is set to CKEDITOR.ENTER_BR

### ISSUE THREAD

**Issue by renvieir** [ckeditor/ckeditor-dev#1436]
## Are you reporting a feature request or a bug?

Bug

## Check if the issue is already reported

no related bugs 

## Provide detailed reproduction steps (if any)

1. Copy text from anywhere (like a paragraph of [lorem ipsum](https://br.lipsum.com/feed/html))
2. Enter this [Code Pen](https://codepen.io/renvieir/pen/MrVEmj)
3. Paste the text in editor 
4. Click over the text
5. See that alignment buttons are disabled

### Expected result

Alignment Buttons should be enabled

### Actual result

Alignment Buttons are disabled

## Other details

* Browser: Happens in IE11, FireFox and Edge. Don't happen in Chrome.
* CKEditor version: 4.7.3
* Installed CKEditor plugins: all

**Comment by msamsel** [comment]
Your test case works fine for me. I test it on Firefox under MacOS, and IE11 and Firefox under Windows 7, and IE11, Edge, Firefox under Windows 10. In all cases justify button was possible to activate, and after pressing them content was moved properly.

Can you check your case on other computer is it possible for you to reproduce it on different machine? Can you also check if problem exists on our sample pages: https://cdn.ckeditor.com/4.8.0/full-all/samples/ and https://ckeditor.com/ckeditor-4/ ?
Another thing what you could check is disabling all browsers plugins to have clean browser.

**Comment by renvieir** [comment]
I have tested again, in version 4.8 it doesn't really happen, but in 4.7.3 it does.
I couldn't reproduce in sample pages.

**Comment by mlewand** [comment]
In this case please upgrade to the latest version.

**Comment by renvieir** [comment]
Just tested it again and the bug is still there in version 4.8.0.
SO: Windows 10 Pro Version 10.0.16299 Build 16299
Browsers: 
  IE v11.98.16299.0
  Edge 41.16299.15.0
  Firefox 57.0.4
