### ISSUE TITLE
Can't set font/size/color/background with Eclipse Internal Browser on Mac

### ISSUE THREAD

**Issue by csmaclaga** [ckeditor/ckeditor-dev#1446]
## Are you reporting a feature request or a bug?
Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)
none found

## Provide detailed reproduction steps (if any)
On Mac:
1. Start Eclipse (I've used Eclipse 4.5.2 and 4.8.0M2 to reproduce)
2. Click Window / Show View / Other / Internal Web Browser
3. Use https://ckeditor.com/ckeditor-4/#document
4. Select some of the demo text and attempt to apply a new format, font, size, text color or background color to the selected text.

### Expected result
The formatting change is applied to the selected text.

### Actual result
- No formatting change is actually applied.
- The text selection is cleared.
- The cursor position is placed at the beginning of the document
- If you changed the format, the format is applied to the first line (which makes it seem like the problem is that the selection is being cleared and the cursor position reset prior to the formatting change being applied).

## Other details

* Browser: Eclipse internal browser
* OS: Mac OS 10.13.2
* CKEditor version: 4 - whatever is running on the demo page https://ckeditor.com/ckeditor-4/#document
* Installed CKEditor plugins: whatever is running on the demo page

**Comment by mlewand** [comment]
What kind of browser is embedded there? We do not support embedded Eclipse browser.

**Comment by csmaclaga** [comment]
@mlewand - The relevant eclipse FAQ:
https://www.eclipse.org/swt/faq.php#browserplatforms

**Comment by mlewand** [comment]
Thanks, as I can see there are multiple browsers combination used, depending on host OS. We're not supporting using CKE4 in Ecliplse.

I can just suggest using regular browsers instead and everything will work just fine.
