### ISSUE TITLE
After blurring editor it takes 2 clicks to focus a widget

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1458]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open any [CKE4 instance with Enhanced Image plugin](http://cdn.ckeditor.com/4.8.0/full-all/samples/old/image2/image2.html).
1. Focus the image widget by clicking it.
1. Blur the editor, by clicking outside of the editor.
1. Click image once again to focus it.

### Expected result

Image should be focused.

### Actual result

Image is not focused. Only next subsequent click will focus it.

## Other details

This is a regression introduced in 4.7.0 (it might happen it was not present in previous edge releases so we didn't see it).

It's a general widget issue, not limited to the Enhanced Image plugin.

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4.8.0

**Comment by jacekbogdanski** [comment]
In bdbd071 we disabled `editorFocus` on `applyFormatting` event. Without this change Enhanced Image plugin works fine.

**Comment by mlewand** [comment]
Closed with #1466.
