### ISSUE TITLE
CKEditor v4.8.0 encountering javascript errors when loading in Salesforce Lightning.

### ISSUE THREAD

**Issue by chalamalla471** [ckeditor/ckeditor-dev#1459]
## Provide detailed reproduction steps (if any)

1. Downloaded CKEditor v4.8.0 and self hosted on Salesforce Lightning static resources.
2. Loaded ckeditor js file in my component.
3. ckeditor loads on my page with all options "disabled" because there is a js error in ckeditor.js file saying "b.getFirst(...) is null" inside method "CKEDITOR.dom.element.createFromHtml".
4. CKEditor loads perfectly in salesforce classic but not in salesforce lightning.
![error](https://user-images.githubusercontent.com/14814905/34955484-32494e22-f9ea-11e7-83b8-b746f854d7af.PNG)

## Other details

* Browser: All latest browsers
* OS: Windows 8
* CKEditor version: 4.8.0
* Installed CKEditor plugins: Full version

**Comment by msamsel** [comment]
Hi,

Your description is related also to 3rd party software (Salesforce Lightning). I cannot reproduce your error in clear editor. I test it on our main sample here: https://ckeditor.com/ckeditor-4/ and here: https://cdn.ckeditor.com/4.8.0/full-all/samples/

Could you provide an example how to reproduce an error in clear editor (only JS+HTML+CSS)?
You can use codepen.io, jsfiddle.net, etc. to share an example with us.

**Comment by chalamalla471** [comment]
Thank you for responding,

Yes CKEditor4 works perfectly fine on plain HTML. (in JSFiddle also works fine)
Salesforce is CRM Platform and Classic and Lightning are features in it. I am seeing above error when I loaded it in my Lightning component file similar to what is shown in https://cdn.ckeditor.com/ . Only difference is instead of loading script from cdn, I downloaded full version and loading from my server.

I cannot add code, since it runs only on Salesforce Platform, attached screenshots, hopefully that helps.
![capture](https://user-images.githubusercontent.com/14814905/35056281-fcdb0b7a-fb76-11e7-9ac7-31c49044ceb3.PNG)
![capture1](https://user-images.githubusercontent.com/14814905/35056283-fcf32fde-fb76-11e7-8a97-0bc39668e37b.PNG)
![capture2](https://user-images.githubusercontent.com/14814905/35056284-fd043be4-fb76-11e7-967c-2ec53ae4b986.PNG)

**Comment by msamsel** [comment]
Hi @chalamalla471,
thank you for your reply. From your description it seems that the issue is more likely support question not bug or feature request. Please take a look [here](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md) to get more information about support options.

This issue exists only during integration CKEditor with Salesforce. Problem does not appear in clear CKEditor. Salesforce is not platform, which is directly support by CKEditor team. In case that Salesforce is responsible for integrating their platform with CKEditor please contact with their support channel, as there is strictly problem with implementation CKEditor inside their platform. If integration is made by your own, you can try to find some solution on StackOverflow, maybe someone integrate already CKEditor with Salesforce and will be able to help you with this case.

Unfortunately I cannot help if the issue cannot be reproduce directly in CKEditor, or there is no details which points that problem exists directly in CKEditor code.

**Comment by chalamalla471** [comment]
Hi @msamsel,
Thank you for response. I found out way to load CKEditor in Salesforce classic as well as Salesforce Lightning. It is working fine now.

**Comment by sethi000777** [comment]
HI @chalamalla471 ,
Could you please help me in letting me know ,how to load CK Editor in Salesforce lightning . Thank you in Advance.

**Comment by chalamalla471** [comment]
Sure @sethi000777 
Did you get chance to check this [Communicating between Lightning Components and Visualforce Pages](https://developer.salesforce.com/blogs/developer-relations/2017/01/lightning-visualforce-communication.html)?
Where are you having issue?

**Comment by adarshsharma95** [comment]
Hi @chalamalla471 

Could you please add a sample here to load CK Editor in Salesforce lightning . Thanks

**Comment by bhagyashri-sketch** [comment]
Hi @chalamalla471

Could you please confirm whether we can use CK Editor in lightning web component directly without using VF page?
I tried loading CKEditor in lwc, it is going to error part/catch portion but showing error = undefined. I'm not able to understand what is the error exactly.
Please find below my code

testLWC.js 
import { LightningElement } from 'lwc';
import {loadScript } from 'lightning/platformResourceLoader';
import CKEditor from '@salesforce/resourceUrl/CKEditor';


export default class TestLWC extends LightningElement {
renderedCallback() {
        Promise.all([
            loadScript(this, CKEditor + '/ckeditor/ckeditor.js')])
            .then(() => {
                alert('loaded successfully !!');
            })
            .catch(error => {
                alert('not loaded :: --> '+error);
            });
    }

}

It is going to catch portion but shows error = undefined. Also I checked in console this file is getting loaded and I can see response code 200.

![image](https://user-images.githubusercontent.com/93408496/139504583-959ad2e0-9657-47a7-89e1-d3c4682f18d6.png)
