### ISSUE TITLE
Justify Buttons Disabled for styled element in Enter_BR mode

### ISSUE THREAD

**Issue by renvieir** [ckeditor/ckeditor-dev#1479]
## Are you reporting a feature request or a bug?
Bug

## Check if the issue is already reported
This was originally reported in issue [1436](https://github.com/ckeditor/ckeditor-dev/issues/1436). But it was closed after cannot reproduce the bug. Reporting it again since now I can provide more details and evidences.

## Provide detailed reproduction steps (if any)

1. Copy one paragraph of [https://br.lipsum.com/feed/html](https://br.lipsum.com/feed/html)
2. Enter [https://codepen.io/renvieir/pen/MrVEmj](https://codepen.io/renvieir/pen/MrVEmj)
3. Paste the text in editor
4. Click over the text
5. See that alignment buttons are disabled

_Alternative way to reproduce the BUG (Please notice that `Enter_BR` mode is active)_:
1. Open link: https://codepen.io/msamsel/pen/LeabeB
2. Write something
3. Select written text and apply custom font (e.g. Arial)
4. Try to justify text

### Expected result

Alignment Buttons should be enabled

### Actual result

Alignment Buttons are disabled

![ckeditor_entermode](https://user-images.githubusercontent.com/2035797/35160981-f7d81f4a-fd25-11e7-9990-5a6b41887796.gif)

## Other details

* Browsers: 
  * IE version 11.98.16299.0
  * Edge version 41.16299.15.0
  * Firefox version 57.0.4
* OS: Windows 10 Pro Version 10.0.16299 Build 16299
* CKEditor version: 4.8.0
* CKEditor plugins: Justify

**Comment by msamsel** [comment]
Hi,

based on this description currently I can say something more. If you take a closer look into elementspath in editor's footer, you can notice that `<span>` appears in editor's content.
Justification might be only applied to block type elements, so here when we are inside a `<span>`  justification is disabled.

I'll modify your description to get easier way to reproduce the case. What you can do in current case is to not use "Enter BR" bode or paste content as plain text with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>.

**Comment by kehlankrumme** [comment]
Are there any updates on the status of this bug? @msamsel

**Comment by kehlankrumme** [comment]
> Are there any updates on the status of this bug? @msamsel

Bump.

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/ddc76e00039bb39d61b2a0395e71b998391ea5b5.
