### ISSUE TITLE
List item is not movable

### ISSUE THREAD

**Issue by NoTime91** [ckeditor/ckeditor-dev#1481]
## Provide detailed reproduction steps (if any)

1. https://dne4i5cb88590.cloudfront.net/client-area/monthly_2018_01/bug_List.gif.b59783cb7d4f79ba32d003779da166f4.gif

### Expected result

*List Bulleted or Numbered List movable (right or center)

### Actual result

*List Bulleted or Numbered List are not movable

## Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version: ALL
* Installed CKEditor plugins: 
![bug_list](https://user-images.githubusercontent.com/8845515/35188473-07b9850a-fe36-11e7-9909-bfac98f8e2c6.gif)

**Comment by engineering-this** [comment]
Hello,

https://codepen.io/anon/pen/YYgGjY

Here is an example without CKEditor, just on basic html elements. As you can see this behaviour comes from how internet browsers interprets css property `text-aling`. 

If you want other positioning then wrap your list with a `div` element, and then position div with css styling.

Note: Not every browser has same behaviours. Try example from above in Firefox and you will find that list bullets follows its text content.
