### ISSUE TITLE
Request Blocked: Unable to use SharedSpaces via CDN over HTTPS

### ISSUE THREAD

**Issue by devman2k** [ckeditor/ckeditor-dev#1485]
## Bug

 Bug

Mixed Content: The page at 'https://coderightstage.crm.dynamics.com/main.aspx#181642986' was loaded over HTTPS, but requested an insecure script 'http://cdn.ckeditor.com/4.8.0/standard-all/plugins/sharedSpaces/plugin.js/'. This request has been blocked; the content must be served over HTTPS.

1. Reference CDN: <script src="https://cdn.ckeditor.com/4.8.0/standard-all/ckeditor.js" type="text/javascript"></script>
2. Set "CKEDITOR.config.extraPlugins = 'sharedSpaces';"

*What is the expected result of the above steps?*

Should be able to use sharedSpaces (sharing of toolbars for multiple editors on a page)

*What is the actual result of the above steps?*
does not load editor due to content blocked via HTTP script call from within the editor when call should be HTTPS
![untitled](https://user-images.githubusercontent.com/7860424/35247570-f086500c-ff98-11e7-8b70-4941748e95e4.png)

## Other details

* Browser:Chrome
* OS:Win10
* CKEditor version:4.8
* Installed CKEditor plugins: Standard-All

**Comment by msamsel** [comment]
You use wrong name of the plugin. It's `sharedspace` without `s` at the end with small letters.
[`sharedSpaces`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#sharedSpaces) is name of configuration variable to configure this plugin.

Take a look into our sample: https://sdk.ckeditor.com/samples/sharedspace.html at the bottom of page you can find links "Get Sample Source Code", take a look how those editors are configured there.

**Comment by devman2k** [comment]
Yup.. My mistake thanks.

There is another doc in the website that depicts the config as plural which is where I got that config from .

Thanks. please close ticket

Bryan

Bryan Tuttle
President
MCT,MCSD,MCDBA,MCAD

CodeRight Inc.
20 Marion Drive
Tewksbury, MA 01876
Phone: 781-389-9695

**Comment by msamsel** [comment]
@devman2k could you provide a link to doc where you found misleading information? I'd like to update it or elaborate it more to avoid possible future problems.
