### ISSUE TITLE
CTRL V Paste As Plain Text.

### ISSUE THREAD

**Issue by kumasa01** [ckeditor/ckeditor-dev#1488]
## Are you reporting a feature request or a bug?
NO

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

Using 4.7.3, when users copy the text from Word and paste to ckeditor using CTRL V, looking for a option  force as plain text? 

Also is there option disable CTRL V?

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …Widnows
* CKEditor version: …4.7.3
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Hello!

You can use `CTRL+SHIFT+V` to paste as plain text from Word. There is a config option to [force paste as plain text](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#forcePasteAsPlainText) but it's not working with Word in your version of the CKEditor. We will release `4.9.0` soon where we fixed this [issue](https://github.com/ckeditor/ckeditor-dev/issues/1013).
