### ISSUE TITLE
[tableselection] table contents can be removed in readonly mode

### ISSUE THREAD

**Issue by ufdada** [ckeditor/ckeditor-dev#1489]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Insert a table into the editor and enter contents (or just use https://ckeditor.com/ckeditor-4/#document)
2. Set editor in readonly mode
3. Now drag and select the table cells (using the tableselection plugin)
4. Press <kbd>delete</kbd> (actually any key works)

### Expected result

The content shouldn't change at all

### Actual result

Completely removing cells or deleting their content

## Other details

* Browser: chrome, ie11, edge, firefox
* OS: Windows
* CKEditor version: 4.8.0
* Installed CKEditor plugins: tableselection

**Comment by Comandeer** [comment]
Issue is fixed in #1527, fix will be released in 4.10.2.
