### ISSUE TITLE
BUG: CKFinder3

### ISSUE THREAD

**Issue by millzee01** [ckeditor/ckeditor-dev#1502]
## Are you reporting a feature request or a bug?

BUG

1. Launch 1st ckfinder as CKFinder.start( { id: 'A') } with a resource named "files" pointing to a folder called "Images" in browser tab1

2. Create a new folder in "files" called TESTA and open it

3. Launch 2nd ckfinder as CKFinder.start( { id: 'B') } with a resource named "files" pointing to a folder called "Files" in browser tab2 (so both ckfinders are loaded with the same resource names but pointing to different folders)

4. Create a new folder in "Files" called TESTB and open in

5. Now go back to Tab1 and click "files" folder then click "TESTA" folder

6. Now go to Tab2 and click "Files" folder, then open  "TESTB" folder

### Expected result

As we are using different id's we would expect both to operate independently and work between folders without errors

### Actual result

The following CKFinder error appears in 1st CKFinder instance (A) indicating that the instance feature of CKFinder does not work when using multiple CKfinder pages 

error:/Images/TESTB/
Fatal error: Uncaught CKSource\CKFinder\Exception\FolderNotFoundException: Folder not found

However if we open each CKFinder on their own no error is shown and app operates normally.

## Other details

* Any (Google, FireFox, IE and Safari)
* OS: Windows
* CKFinder version: 3
No plugins installed.

**Comment by msamsel** [comment]
This is not a CKFinder repository, please report your issue in proper place.
👉  https://github.com/ckfinder/ckfinder/issues
