### ISSUE TITLE
border is overridden when pasted in with no previously set border

### ISSUE THREAD

**Issue by Justtryingtomakeitwork** [ckeditor/ckeditor-dev#1504]
Bug: the style="border: 0px black;" setting overrides the attribute that is set by the table interface. This occurs if a table is pasted in with no border set. It also makes it impossible to change the border once it is pasted. 

1. create a table in excel with no borders set
2. paste the table into ckeditor with table feature active. 
3. right click table select table properties enter 1 in the Border size.
4. click ok
5. See that there is no border
6. use source to confirm that the border attribute is 1 but the border style is 0px. 

### Expected result
My users will expect that the border setting in the interface would create a border in the table. 
### Actual result
the border setting doesn't add a border. 

* Browser: IE11…
* OS: windows 7
* CKEditor version: 4.8.0 full (but I limit the toolbar)
* Installed CKEditor plugins: tabletools, tableresize, entities

**Comment by msamsel** [comment]
Hi @Justtryingtomakeitwork,

could you confirm that I understand you correctly. The issue here is as follows:
When user paste a table to editor, the table contains border-styles. After that user tries to change border settings with table properties, but even if provide different values, there is nothing happens.  Reason of such situation is fact, that after pasting the table,  it is paste together with styles, which all the time overwrite user settings.
Have I understand you correctly?

**Comment by Justtryingtomakeitwork** [comment]
The excel table has no borders set but it seems to be coming over as
style="border: 0px black;" anyway.  When I try to set a border in the
editor it doesn't work. Looking at the html that is produced, I see the
border="1" property that I set but it is overridden by the style that came
over. I guess your developers need to remove styles that came over when the
editor's border is set, but leave those styles alone if no value is entered
in the editer's border. I haven't tested any of the other settings. Do you
know why you didn't just use the settings for controlling the border in the
editor?

**Comment by msamsel** [comment]
You can configure ACF to prevent of embedding styles for tables.
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_acf.html
https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#disallowedContent
