### ISSUE TITLE
Fake selection allows for removing in a readonly mode

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1516]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Visit https://cdn.ckeditor.com/4.8.0/full-all/samples/old/image2/image2.html
2. Set editor as readonly `CKEDITOR.instances.editor1.setReadOnly( true )`
3. Focus image widget
4. Blur editor
5. Focus image widget once again
6. Press `delete/backspace`

### Expected result

Image widget shouldn't change.

### Actual result

Image widget has been deleted.

## Other details

Needed to fix #1489

* Browser: Any
* OS: Any
* CKEditor version: Any

**Comment by mlewand** [comment]
This is also reproducible with table selection.

**Comment by Comandeer** [comment]
It's also possible to cut widget after blurring and refocusing.
