### ISSUE TITLE
Invalid images selection after paste

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1529]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Visit [Easy Image preview](https://ckeditor4-preview.ckeditor.com/t/932-2961/plugins/easyimage/samples/easyimage.html).
2. Paste random images into editor.
3. Wait for images upload.
4. Press backspace.

### Expected result

The last image is removed.

### Actual result

The last image is not removed.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.9.0
* Installed CKEditor plugins: imagebase

**Comment by mlewand** [comment]
Closed with #1540.
