### ISSUE TITLE
Table selection leaves white space around the image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#1542]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open the sample with Easy Image, table and table selection plugins.
2. Create new table.
3. Paste the image to some cell.
4. Select all table cells.

### Expected result

There is no white space around the image.

### Actual result

Table selection doesn't touch the image.

## Other details

**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/35615532-ab5fe156-0672-11e8-98bf-604a2ccb9425.gif)

* Browser: All browsers
* OS: All platforms

**Comment by Comandeer** [comment]
[Merged](https://github.com/ckeditor/ckeditor-dev/pull/1556#event-1454743344).
