### ISSUE TITLE
High resolution image doesn't resize inside the table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#1545]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open the sample with Easy Image plugin.
2. Insert new table.
3. Upload some high resolution image into the table cell.

### Expected result

The image is scaled.

### Actual result

The image has full size and stretches the editor.

## Other details

**Notes**

It resize properly when you drop the image, i.e. to the paragraph, but if you try to paste it to the table cell, it changes its size.

**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/35618835-5f674f00-067c-11e8-86ef-d884b515720b.gif)

* Browser: Internet Explorer 11
* OS: Windows 10

**Comment by jacekbogdanski** [comment]
I can reproduce this issue on IE. It works fine on other browsers.

**Comment by jacekbogdanski** [comment]
We are not able to fix this issue as it's IE11 bug. It has been fixed for Edge but still exists in IE. You can find out more [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8138939/). For now I'm closing this issue as it's not related to the CKEDITOR 4.
