### ISSUE TITLE
Content jumps after hovering the image with link

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1550]
## Are you reporting a feature request or a bug?

Bug

Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=803045

## Provide detailed reproduction steps (if any)

1. Open dev/t/932-2992/plugins/easyimage/samples/easyimage.html.
2. Focus CKEditor logo image.
3. Apply a link to it.
4. Blur the image.
5. Hover the image.

### Expected result

Image gets highlight, there is no other effect on content.

### Actual result

Vertical scrollbar appears and content 'jumps'.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Closed with #1473.
