### ISSUE TITLE
Linking feature cause failing test

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1552]
## Are you reporting a feature request or a bug?

Bug - failing test

## Provide detailed reproduction steps (if any)

1. [Linking feature](https://github.com/ckeditor/ckeditor-dev/pull/1137) introduced some failing unit tests on IE11.
 
See https://github.com/ckeditor/ckeditor-dev/pull/1137#pullrequestreview-75964661

Note:
Looks like with open browser dev console it works fine :/
Also running single tests make it pass.

**Comment by f1ames** [comment]
Failing tests where ignored in`4.9.0` (see #1585) and should be fixed in `4.9.1`.

**Comment by mlewand** [comment]
Closed in #1699.
