### ISSUE TITLE
Easy image in table might be unreadable

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1553]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Using easyimage inside tables (probably other elements) inside editor, might look strange in case of small container size.
In example below I put `side easyimage` inside table and enlarge left cell.

![screen shot 2018-01-17 at 15 12 22](https://user-images.githubusercontent.com/9017322/35621595-331afc68-0685-11e8-9a3e-6c166a72f7c8.png)

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Closed with #1492.
