### ISSUE TITLE
Inconsistent '@since' tagging

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1557]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

When it comes to docs and `@since` tag, for `major` versions we have it both in `@since 4.X` and `@since 4.X.0` formats used. More in `@since 4.X` format and this is the proper one AFAIR. It will be good to make things consistent in this matter.

**Comment by mlewand** [comment]
Actually we agreed like 2 years ago or sth to go with `4.x.0` format for major. Generally speaking we use full, semver-compatible version in dev resources but we use simplified `4.x` version for any materials aimed at non-tech folks.
