### ISSUE TITLE
Quickstart documentation error - "Adding ckeditor to your page"

### ISSUE THREAD

**Issue by jonathanclark** [ckeditor/ckeditor-dev#1565]
## Are you reporting a feature request or a bug?
Bug

https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html#adding-ckeditor-to-your-page

1. Copy the code in the referenced section of the documentation above
2. Make a sample page from the code
3. Open in a web browser.

Expected result: a web page with a textarea with ckeditor

Actual result: a blank page with an empty body

Cause:
a) the script tag inside the <head> is not properly closed
b) there is an extraneous </textarea> tag before the closing of the script inside the body.

Fix:
a) Close the script tag inside the <head>
b) Remove the extraneous </textarea> tag

i.e. corrected page is 

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A Simple Page with CKEditor</title>
        
	<script src="ckeditor/ckeditor.js"/></script>
    </meta></head>
    <body>
        <form>
            <textarea name="editor1" id="editor1" rows="10" cols="80">
                This is my textarea to be replaced with CKEditor.
            </textarea>
            <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            </script>
        </form>
    </body>
</html>

Now it works

* Browser: Google chrome Version 63.0.3239.132 (Official Build) (64-bit)
* OS:  Linux  4.14.14-1-ARCH
* CKEditor version: 4.8.0
* Installed CKEditor plugins: None

**Comment by mlewand** [comment]
Hi Mohamed,

Thanks for spotting this. [It has already been fixed](https://github.com/ckeditor/ckeditor-docs/commit/02dd55a87a3b417710ac5807d30fffbfbe54d053) in the source, and will be published online soon.

**Comment by mlewand** [comment]
Also this is an issue with docs, so it would be better to report it in https://github.com/ckeditor/ckeditor-docs
