### ISSUE TITLE
Balloon Toolbar not visible after pasting a widget

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1576]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open [SDK sample with Balloon Toolbar and Widget plugin](https://sdk.ckeditor.com/samples/balloontoolbar.html).
2. Select image widget.
3. Cut it.
3. Paste anywhere.

### Expected result

Image is pasted and Balloon Toolbar is shown.

### Actual result

No Balloon Toolbar is visible.

## Other details

* Browser: Chrome, Firefox, Edge (probably cross browser, did not check more)
* OS: Win10
* CKEditor version: 4.8.0

**Comment by jacekbogdanski** [comment]
It looks like the issue has been already solved.
