### ISSUE TITLE
Center justified bullet points

### ISSUE THREAD

**Issue by rjshenk** [ckeditor/ckeditor-dev#1578]
## Are you reporting a feature request or a bug?
Bug

When centering a bullet point I would expect the bullet to follow the text. Instead, the bullet stays left justified and the text goes to the center of the document. 

![centered_bullet_points](https://user-images.githubusercontent.com/13643618/35752978-efad357e-082b-11e8-9a31-242adfb3ecfe.gif)

## Provide detailed reproduction steps (if any)

1. Navigate to https://ckeditor.com/ckeditor-4/#document
2. Create a bullet point with text
3. Try to center that bullet and text

### Expected result

I would expect the bullet point to be in the center of the document with the text.
```
Left justified text
                                    • Centered bullets
                                    • More centered bullets
Left justified text
```

### Actual result
Bullets stay left justified
```
Left justified text
•                                     Centered bullets
•                                     More centered bullets
Left justified text
```

## Other details

* Browser: Chrome version 63.0.3239.132
* OS: macOS High Sierra 10.12.2
* CKEditor version: Ckeditor 4
* Installed CKEditor plugins: What ever plugins you have on your demo site https://ckeditor.com/ckeditor-4/#document

**Comment by msamsel** [comment]
It's a duplicated issue: #1144
Please be aware that inside editor is HTML content.

**Comment by mlewand** [comment]
@msamsel well the issue you have mentioned does not represent the best quality in the world, while this issue has a really valuable description.

To the point: everything what @msamsel wrote in linked issue still holds true, we're working with HTML so we keep default HTML behavior and we havent that much request for this behavior in the past.

That being said if you find it important, there is a simple way to do that with CSS. Just take a look at this demo I have prepared:

https://codepen.io/mlewand/pen/ddXmjQ?q=classic&limit=mine&show_forks=true

The whole trick is to implement a proper CSS. You can find more here: https://stackoverflow.com/questions/7516005/how-to-make-a-bullet-list-align-with-text-in-css

@rjshenk hope you'll find it useful.
