### ISSUE TITLE
Shrinking of text selection

### ISSUE THREAD

**Issue by FastTI** [ckeditor/ckeditor-dev#1586]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

When I select some text and click on toolbar's item (dropdown, image gallery etc) selection start shrinking.

### Normal result

![gi9kwz-nruqrrxd8uveo7g](https://user-images.githubusercontent.com/6927963/35801476-36d06868-0a75-11e8-8396-768ecbf65ba8.png)

### Afterward result

![bdwwt1k6rkovopyxpvypqw](https://user-images.githubusercontent.com/6927963/35801443-18c7d518-0a75-11e8-91ba-8ab6949528d8.png)

**Comment by mlewand** [comment]
What browser is it? Could you reproduce it on our [CKEditor 4 demo page](https://ckeditor.com/ckeditor-4/)?

**Comment by FastTI** [comment]
I have this issue in most browsers
**Chrome** 64.0.3282.140/ **Opera**
**Firefox** 58.0.1

no, I couldn't reproduce it in your demo page

**Comment by mlewand** [comment]
Does it happen with scayt disabled? Also I can see that you have quite a few 3rd party plugins, try to temporarily disable these and see if it still happens with vanilla CKEditor.

It might be also helpful if you provide CKEditor version.

**Comment by FastTI** [comment]
CKEditor4. Yes, I determined, that it's SCAYT plugin do. When it checks words it shrinking selection. I've written SCAYT devs about that. Maybe you have experience on that?

**Comment by mlewand** [comment]
Thanks for checking. Best you can do is report the ticket on [SCAYT issue tracker](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues) which I see you already did in ckeditor-plugin-scayt#154 - so from here you can wait and follow the issue there.

**Comment by FastTI** [comment]
Ok, thanks for your help.
