### ISSUE TITLE
Easy Image caption is not visible after paste

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1592]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open Easy Image sample, e.g. our [nightly preview](https://ckeditor4-preview.ckeditor.com/t/932-2961/plugins/easyimage/samples/easyimage.html).
2. Select the first image.
3. Cut it using `ctrl/cmd+x`.
3. Paste it using `ctrl/cmd+v`.

### Expected result

Pasted image is focused, "Enter image caption" placeholder is visible.

### Actual result

Pasted image is focused but no there's no "Enter image caption" placeholder.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.8.0

**Comment by jacekbogdanski** [comment]
I can reproduce the issue on each used by us browser.
