### ISSUE TITLE
Easyimage link unit tests fails on build version

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1594]
## Are you reporting a feature request or a bug?

Failing tests

## Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/1061942/35864029-d8ef87c4-0b50-11e8-8dad-f634acc05bb0.png)

Probably because link plugin is bundled in build.

**Comment by mlewand** [comment]
Fixed with #1598.
