### ISSUE TITLE
EasyImage plugin shouldn't be enabled in IE 10 or lower

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#1596]
## Are you reporting a feature request or a bug?

Bug
Please **do not report security issues here**, use the contact form at https://ckeditor.com/contact/ instead.

## Provide detailed reproduction steps (if any)

EasyImage plugin shouldn't be enabled in IE 10 or lower.

* Browser: IE < 11

**Comment by mlewand** [comment]
Closed with #1600.
