### ISSUE TITLE
Shared Space toolbar is not show after toolbar destroy and recreate until focus trigger

### ISSUE THREAD

**Issue by cention-sany** [ckeditor/ckeditor-dev#1597]
## Are you reporting a feature request or a bug?
Bug.

## Provide detailed reproduction steps (if any)

1. Have two Ckeditor instances that use sharedspace BUT different toolbar ID. Two different toolbars and not shared.
2. Destroy and recreate the second loaded instance Ckeditor toolbar.
3. The second instance toolbar will not appear until the Ckeditor is focus.

### Expected result

Expected Ckeditor toolbar show after toolbar is recreated.

### Actual result

Second Ckeditor toolbar is not shown.

## Other details

- Shared Space plugin.
- The shared space plugin set a flag on toolbar DOM to make sure only one toolbar appear at one time and switch the toolbar appearance through focus. However, this flag do not get reset when the toolbar is destroy and recreate (the DOM that host the toolbar is not destroy and thus the flag remain). Previously appeared toolbar get destroy and recreate would not be shown because this flag prevent it.
- I has a fix which work for my job but I not confident of it [here](https://github.com/cention-sany/ckeditor-dev/commit/94e82d2d33d08efd33b40df145a0fcddeb53cafd).

**Comment by msamsel** [comment]
It seems like you are using wrongly sharedspace plugin or I misunderstand your description. There should be provided only one ID for toolbar. Take a look at implementation instruction and example: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_sharedspace.html

If you still feel there's a bug, please provide code snippet/sample on page such as codepen.io, jsfiddle.net, what allow on better bug investigation.

**Comment by cention-sany** [comment]
I understand this plugin allow same toolbar to be shared among multiple Ckeditor instances. The plugin also allows us to place the toolbar at any other DOM location instead of stick on top of text box, right? I used it for later case. Even for the former case, the plugin only can only work properly under one single toolbar ID and not more than one even though we can define different IDs.

**Comment by msamsel** [comment]
Hello

Your questions are neither bug report or feature request. It looks like you need support assistance rather than report a bug. Please take a look at support possibilities described here: https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md
Questions like these should be asked on StackOverflow, where more users might benefit from the answer.
