### ISSUE TITLE
How to translate your new paste notification?

### ISSUE THREAD

**Issue by smartcorestudio** [ckeditor/ckeditor-dev#1613]
## Are you reporting a feature request or a bug?
A question

How can I translate new paste notification? Do I need to change it directly in ` ckeditor-dev/plugins/pastetext/lang/ru.js` here on Github?

### Expected result

I've expected to see the new string in Transifex

### Actual result

I can see only the old string in Transifex

**Comment by mlewand** [comment]
In short, all the translations happen though Transifex, see our [contributing docs](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/CONTRIBUTING.md) for more details.

@smartcorestudio Thanks for actively watching our work. I see that you're referring to #1363, it has not been reviewed yet. Once it's positively reviewed and merged to the `major` branch, we'll push new strings to Transifex and from there you'll be able to update it.
