### ISSUE TITLE
Failing test: tests/plugins/button/buttonicon

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1621]
## Are you reporting a feature request or a bug?
Bug: failing test

## Provide detailed reproduction steps (if any)

1. Run test: `tests/plugins/button/buttonicon` - **`test custom button icon with different basepath trailing slash`** on IE10 with build editor.
![screen shot 2018-02-08 at 12 34 06](https://user-images.githubusercontent.com/9017322/35971043-c51feb62-0ccc-11e8-8357-47dad29be700.png)

### Expected result

test pass

### Actual result

test fails

## Other details

* Browser: IE10
* OS: Win7
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

**Comment by mlewand** [comment]
@msamsel I suppose this happens on a build version, is that correct?

**Comment by msamsel** [comment]
@mlewand yes I update the description
