### ISSUE TITLE
Multiple failing tests on Firefox (related to uploading for the most part)

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1631]
## Are you reporting a feature request or a bug?

Failing tests

## Provide detailed reproduction steps (if any)

Multiple tests are failing on dev version:

### http://tests.ckeditor.test:1030/tests/plugins/uploadfile/uploadfile
* http://tests.ckeditor.test:1030/tests/plugins/uploadfile/uploadfile#tests%2Fplugins%2Fuploadfile%2Fuploadfile%20test%20pasting%20images%20in%20the%20editor%20with%20uploadfile%20and%20uploadimage%20plugins
### http://tests.ckeditor.test:1030/tests/plugins/uploadimage/uploadimage
* many tests
### http://tests.ckeditor.test:1030/tests/plugins/uploadwidget/additionalRequestParameters
* main test fails
### http://tests.ckeditor.test:1030/tests/plugins/uploadwidget/uploadwidget
* http://tests.ckeditor.test:1030/tests/plugins/uploadwidget/uploadwidget#tests%2Fplugins%2Fuploadwidget%2Fuploadwidget%20test%20upload%20(integration%20test)

I wasn't able to check whether it's our regression or is it a browser feature introduced with the update.

**Comment by msamsel** [comment]
Regresja:
- http://tests.ckeditor.test:1030/tests/plugins/uploadfile/uploadfile
- http://tests.ckeditor.test:1030/tests/plugins/uploadwidget/additionalRequestParameters
- http://tests.ckeditor.test:1030/tests/plugins/uploadwidget/uploadwidget

**Comment by f1ames** [comment]
@msamsel found breaking commit https://github.com/ckeditor/ckeditor-dev/commit/ef0f318991089f966e754d510b291fd14edc2f96 - the breaking change is altering the test helper (`tests/plugins/clipboard/_helpers/pasting.js`), so in `clipboard` plugin the flow changes and special `if` for image handling is executed (before change in helper it was skipped):

https://github.com/ckeditor/ckeditor-dev/blob/8c431ef1edee07d15df88921e23e717257f969a8/plugins/clipboard/plugin.js#L151-L191
