### ISSUE TITLE
Spell Checker Plugin Issue

### ISSUE THREAD

**Issue by danlipari** [ckeditor/ckeditor-dev#1637]
## Are you reporting a feature request or a bug?

Bug

It appears that the spell checker plugin that ckeditor uses will timeout when the text in the editor is sufficiently large. It does not make a difference whether SCAYT is selected or not. This can be verified by copying the text from the editor in the description and pasting it into ckeditors spell check demo https://sdk.ckeditor.com/samples/spellchecker.html (the second editor on this page is the one with full spell checker). 

If spell checking is required for a large text field the SCAYT spell checker can be used and will not timeout.
Please **do not report security issues here**, use the contact form at https://ckeditor.com/contact/ instead.

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
SCAYT and WSC plugins are third party plugins developed by [WebSpellChecker](https://github.com/webspellchecker) organization. Please report ticket directly in or [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
