### ISSUE TITLE
Failing test mobile Safari tests/plugins/clipboard/forcepasteasplaintext

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1638]
## Are you reporting a feature request or a bug?

Bug: failingtests

## Provide detailed reproduction steps (if any)

1. Test fails on mobile Safari on iOS.
![img_0067](https://user-images.githubusercontent.com/9017322/36031879-8535bece-0dac-11e8-8f6f-8d44d48e094a.jpg)

### Expected result

test pass

### Actual result

test fail

## Other details

* Browser: Safari
* OS: iOS
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

**Comment by jacekbogdanski** [comment]
I can reproduce the issue.
