### ISSUE TITLE
Incorrect selection when focusing editor for the first time

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#1655]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://sdk.ckeditor.com/samples/captionedimage.html
2. Click some text.

### Expected result

Cursor is put at location of click.

### Actual result

Cursor is put at the beginning of the first image widget's editable.

In case, where there is no widget with editable, cursor is put at the beginning of the editor's content.

## Other details

If you can't reproduce issue, try to scroll editor before clicking.
Seems to be reproducible back to 4.5.0, yet not reproducible on raw `[contenteditable]` element.

* Browser: Edge
* CKEditor version: 4.5.0+

**Comment by Comandeer** [comment]
@f1ames not exactly as this issue does not require any scrolling.

**Comment by mlewand** [comment]
@Comandeer @f1ames I believe this actually is a dup of #504. OP of #504 simply added a redundant step. In fact this issue is also reproducible on IEs.
