### ISSUE TITLE
Documentation: Setting SCAYT language

### ISSUE THREAD

**Issue by khawkins98** [ckeditor/ckeditor-dev#1678]
In the docs ([link](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_howtos_scayt.html#how-do-i-change-the-default-language-for-spell-check-as-you-type-scayt)), it would seem that this is enough to set the SCAYT spell checker language:

```
// Sets SCAYT to French.
config.scayt_sLang = 'fr_FR';
```

However, this doesn't do anything.

You must also disable the user's ability to specify a default language in the UI:

```
config.scayt_disableOptionsStorage = 'lang';
config.scayt_sLang = 'fr_FR';
```

And, success.

I know this is technically a SCAYT feature, but it would be good to have fuller guidance in the CKEditor docs.

**Comment by mlewand** [comment]
Thanks @khawkins98 - it makes a perfect sense. I have cross posted this issue directly to our docs repo. You can subscribe it there to keep an eye on that: https://github.com/ckeditor/ckeditor-docs/issues/132

**Comment by markusd1984** [comment]
thanks @khawkins98 this solved it for me too.

Somebody asked about this issue in drupal in 2016 :) https://www.drupal.org/project/ckeditor/issues/2832931#comment-13000856
