### ISSUE TITLE
Hovering dropdown on the end of balloontoolbar changes its size causing flickering

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1682]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Run `tests/plugins/balloontoolbar/manual/balloontoolbar` test.
2. Click on any fragment with red border to open balloon toolbar.
3. Hover Styles dropdown.

### Expected result

Dropdown is hovered, balloon toolbar size does not change.

### Actual result

Dropdown is hovered, balloon toolbar size change and arrow changes its position.

![feb-15-2018 13-54-57](https://user-images.githubusercontent.com/1061942/36258996-0e2c6ad4-125d-11e8-8ef8-97d7328fd5d7.gif)

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.8.0
* Installed CKEditor plugins: `balloontoolbar`

**Comment by mlewand** [comment]
I reproduced the issue on Chrome / FF / Edge (didn't try IE). I can see that the important factor here is high pixel density setting, if you're using `window.devicePixelRatio` >= 2 then the issue occurs.

The bug was not reproducible for me in case of a 1:1 pixel mapping.
