### ISSUE TITLE
Spell check causes deletion of span tag

### ISSUE THREAD

**Issue by cleequantivate** [ckeditor/ckeditor-dev#1684]
## Are you reporting a feature request or a bug?
Bug:
Turning on SCAYT spell check causes span tags next to a span tag within the "Source" view to disappear.

## Provide detailed reproduction steps (if any)
1. Turn on Spell check on

2. Within Source view, place a span tag to another span tag: 
`<span>hello</span><span>world</span>`

3. Save and refresh the page.

4. Go back to Source view and will notice that inner span tags disappear and result to this: `<span>helloworld</span> `

### Expected result
`<span>hello</span><span>world</span>`

### Actual result
`<span>helloworld</span>`

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.3.3
* Installed CKEditor plugins: scayt

**Comment by jacekbogdanski** [comment]
I was not able to reproduce this issue with CKEDITOR 4.8.0, so probably you should upgrade your CKEDITOR instance.  Nevertheless both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization. Please the report ticket directly in or [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
