### ISSUE TITLE
The '/tests/plugins/imagebase/features/link' tests are unstable on Edge

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1686]
## Are you reporting a feature request or a bug?

Other: failing/unstable tests

## Provide detailed reproduction steps (if any)

1. Run `/tests/plugins/imagebase/features/link` test suite.

### Expected result

Whole test suit is passing.

### Actual result

Test suite fails randomly or is run only partially.

---

There are few different behaviours:

1. Tests passing, throwing some errors in the meantime:
![screen shot 2018-02-16 at 15 56 25](https://user-images.githubusercontent.com/1061942/36313843-4138849a-1333-11e8-982d-58ac5e60347d.png)

2. After about 10 - 15 tests are run (all green), browser reloads window, runs tests again, reloads again (probably on the same test) and shows error.

3. Same as before, but there is one failing tests visible.

## Other details

* Browser: Edge (`16.16299`)
* OS: Windows 10
* CKEditor version: `4.9.0`
* Installed CKEditor plugins: `imagebase`

**Comment by engineering-this** [comment]
After some researching the best thing I came up is to isolate tests in Edge. It's not first time Edge works different than other browsers. We can solve it once #1697 is merged to our current working branch.

And about problem with `Unable to get property 'nodeName' of undefined or null reference`

in `plugins/floatpanel/plugin.js:368`
Small changes are needed as following:

```
if ( CKEDITOR.env.ie ) {
	var offsetParent = **element.$.offsetParent &&** new CKEDITOR.dom.element( element.$.offsetParent ),
		scrollParent = offsetParent;

	**if ( scrollParent ) {**
		// Quirks returns <body>, but standards returns <html>.
		if ( scrollParent.getName() == 'html' )
			scrollParent = scrollParent.getDocument().getBody();

		if ( scrollParent.getComputedStyle( 'direction' ) == 'rtl' ) {
			// For IE8, there is not much logic on this, but it works.
			if ( CKEDITOR.env.ie8Compat )
				left -= element.getDocument().getDocumentElement().$.scrollLeft * 2;
			else
				left -= ( offsetParent.$.scrollWidth - offsetParent.$.clientWidth );
		}
	**}**
}
```

**Comment by mlewand** [comment]
@engineering-this issue #1697 has been merged, please revisit this issue once you have some time.
