### ISSUE TITLE
Cannot Declare a Variable Twice iOS Simulator

### ISSUE THREAD

**Issue by mark-bragg** [ckeditor/ckeditor-dev#1688]
## Are you reporting a feature request or a bug?
![screen shot 2018-02-16 at 4 26 28 pm](https://user-images.githubusercontent.com/15349627/36335633-42bff2d2-1336-11e8-9238-7dcbe60ffc61.png)
![screen shot 2018-02-16 at 4 26 49 pm](https://user-images.githubusercontent.com/15349627/36335636-44298750-1336-11e8-8a8a-749baa47abf7.png)

Bug

## Provide detailed reproduction steps (if any)

1. I have CKEditor5 zip downloaded, and the js and js.map files included in the build
2. An HTML doc is opened within a web view and the basic setup is performed to create the classic editors in all the text areas
3. When the app is run on the simulator I get an error in the debugger of the developer portal of Safari

### Expected result

The text areas should become classic editor rich text editors

### Actual result

The text areas stay text areas within the HTML, and an error is indicated in the Safari debugger.

## Other details

* Browser: WKWebView
* OS: iOS
* CKEditor version: 5
* Installed CKEditor plugins: none

**Comment by mlewand** [comment]
@mark-bragg this is a CKEditor 4 issue tracker, your issue is related to CKEditor version 5. Please report the issue https://github.com/ckeditor/ckeditor5
