### ISSUE TITLE
CKEditor not working straight out of the box

### ISSUE THREAD

**Issue by ethman770** [ckeditor/ckeditor-dev#1689]
I have tried both the standard and the full package, and neither worked for me. I did exactly as the instructions said: I unzipped the folder and uploaded it to my website. I when to the /samples/index.html file and it worked, fine, so I went placed the `<script src="ckeditor/ckeditor.js"/>` statement in the head of my web page and 
```
<script>
	CKEDITOR.replace( 'editor1' );
</script>
```
right below my textarea, making sure that the id of the textarea was 'editor1', but my textarea completely disappeared along with all my CSS and was not replaced with ckeditor. I double and triple-checked the file path—it was correct. I tried both with the config.js file intact and after pasting in the changes recommended on the sample/index.html page. 

I went to the [Getting Started](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_installation) link and carefully followed the instructions. I even copied the example that they have there to the samples folder and tried running it from there just like the samples/index.html and I got a completely blank page. I viewed the source and everything looked normal in the code, but nothing displayed normally.

I looked at the source code for the sample/index.html file and saw that there isn't even a textarea in it, just a div?

`<div id="editor"

	<h1>Hello world!</h1>
	<p>I'm an instance of <a href="https://ckeditor.com">CKEditor</a>.</p>

</div`

(I took out the >s above because it was interpreting those. They are in there in the real thing)
What is going on here?

I'm using Google Chrome on Windows 10.
I downloaded CKEditor 4.8.0.
I have the following folders under the plugins folder:
a11yhelp, about, dialog, image, link, magicline, pastefromword, scayt, specialchar, table, tableselection, tabletools, widget, wsc

**Comment by jacekbogdanski** [comment]
Hello,

could you check if there are any console errors in your browser? Looks like CKEDITOR path is invalid. You can always check if you can run CKEDITOR using `<script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>` as your script file.

**Comment by ethman770** [comment]
Thanks for that, it got me on the right track. It turns out that for whatever reason a self-closing tag was not acceptable for a JS reference on my website. I changed reference from what the CKEDITOR had in the documentation, `<script src="ckeditor/ckeditor.js"/>`, to `<script src="ckeditor/ckeditor.js"></script>`, and now it's working.

Thanks again!
