### ISSUE TITLE
Add option to create new editor instance for each test case using bender.tools.createTestsForEditors

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1696]
## Are you reporting a feature request or a bug?

Test feature request

### Expected result

`bender.tools.createTestsForEditors` with additional `isolateTests` flag creates new editor for each test case

### Actual result

`bender.tools.createTestsForEditors` is using the same editor instance for each test case

## Other details

This function already exists inside `plugins/easyimage/_helpers/tools.js` but because I need to use it to test different plugin I thing it's good idea to move it into `bender.tools`.

**Comment by mlewand** [comment]
Fixed in  #1697.
