### ISSUE TITLE
Broken links with anchors from API docs to guides

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-dev#1700]
https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_filter_allowedContentRules.html contains links like https://docs.ckeditor.com/ckeditor4/latest/guide/dev_allowed_content_rules.html#2, but the correct link now is https://docs.ckeditor.com/ckeditor4/latest/guide/dev_allowed_content_rules.html#string-format.

There may be more such links in API docs.

**Comment by mlewand** [comment]
Fixed with #1702.
