### ISSUE TITLE
"Check spelling" feature not working for longer documents

### ISSUE THREAD

**Issue by PetrKaleta** [ckeditor/ckeditor-dev#1701]
Spell checker stopped working for longer documents.

CKEditor: `4.8.0`
Browser: `Google Chrome 64.0.3282.167 (Official Build) (64-bit)`
OS: `macOS High Sierra version 10.13.3`

Steps to reproduce:
1. Open empty CKEditor
2. Paste long text (please use attached text file)
3. Click on `ABC` icon in toolbar and from menu choose `Check Spelling`
4. It will show modal window with loading spinner inside, but no result even after few minutes (no error message in console)

[testing-text.txt](https://github.com/ckeditor/ckeditor-dev/files/1741521/testing-text.txt)

**Comment by Comandeer** [comment]
Both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization.

Please report ticket directly in [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
