### ISSUE TITLE
Mentions plugin

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1703]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

It has been requested for some time to ship a Menitons/Autocomplete feature for CKEditor 4.

The idea is that as you type part of certain text, CKEditor displays a panel suggesting you some suggested values, so that you don't have to write it on your own, but use autocomplete instead.

It should support both synchronous and asynchronous entires lists (feeds).

### Multiple Feeds

The feature should also support **multiple feeds** at the same time.

For instance, you're using `@` to mention users, while `#` to mention ticket numbers.

### Differences from the [Autocomplete plugin](https://github.com/ckeditor/ckeditor-dev/issues/1751)

While Mentions feature is built on top of the Autocomplete feature, it's purpose is to expose as _stupid simple and minimal API_. It should be ready basically by providing list of users (entries) and be ready to use.

Autocomplete in contrast provides much more possibilities to control what's and how being matched, but at a cost of _more complex API_.

## Preview

Users interested in seeing how the feature looks today can preview it on [our Mentions feature branch preview](https://ckeditor4-preview.ckeditor.com/t/1703-b/plugins/mentions/samples/mentions.html).

## Browser Support

Same as for the [Autocomplete plugin](https://github.com/ckeditor/ckeditor-dev/issues/1751).

## Related Issues

* [Autocomplete plugin](https://github.com/ckeditor/ckeditor-dev/issues/1751)

**Comment by mlewand** [comment]
It's important that we keep configuration as simple as possible.

**Comment by mlewand** [comment]
I've been thinking about ways to configure the mentions plugin. As mentioned above, it should be operable by setting config alone, there should be no need to add CKEditor `instanceReady` listeners to execute code, or anything like that.

I have come with few use cases, and a config schemma that fits them all.

## Simple case

Dev simply provides a simple list of user names, mentions plugin will use synchronous data feed.

```js
config.mentions = {
	// User names.
	feed: [ 'andrew', 'bobby', 'james', 'julian', 'kate' ],
	marker: `@`
};

```
## Complex case

Dev uses mentions plugin for three different feeds, two of which use the same marker.

* user names (denoted with `@`)
* group names (denoted with `@`)
* ticket numbers (denoted with `#`)

```js
config.mentions = [ {
	// User names.
	feed: [ 'andrew', 'bobby', 'james', 'julian', 'kate' ],
	marker: `@`
}, {
	// Groups.
	feed: [ 'admins', 'mods', 'users' ],
	marker: '@',
	// Entries have a group HTML class, so that it could feature a customized icon that differs it from users in the dropdown.
	template: '<li data-id="{id}" class="group"><a href="#">{name}</a></li>'
}, {
	// Ticket references.
	feed: [ '1234', '1235', '1236' ],
	marker: '#'
} ];

```

## Asynchronous

In this case dev is requesting backend URL to get the list of users.

Assuming that GET query to `/user-controller/get-list` would return a content like:

```json
[ {
	"id": 1,
	"name": "andrew81",
	"firstName": "Andrew",
	"lastName": "Doe"
}, {
	"id": 2,
	"name": "bob__",
	"firstName": "Bob",
	"lastName": "Doe"
}, {
	"id": 3,
	"name": "jane88",
	"firstName": "Jane",
	"lastName": "Doe"
} ]
```

```js
config.mentions = {
	// User names.
	feed: '/user-controller/get-list',
	template: '<li data-id="{id}" class="group"><a href="#">{firstName} {lastName} ({name})</a></li>'-
};
```

or a more version:

```js
config.mentions = {
	// User names.
	feed: function( query, callback ) {
		callMyBackend( function( results ) {
			callback( results );
		} );
	},
	template: '<li data-id="{id}" class="group"><a href="#">{firstName} {lastName} ({name})</a></li>'-
};
```

**Comment by jacekbogdanski** [comment]
Currently mentions are case sensitive for the feed passed as an array (simple case). 
E.g. with feed `['Anna', 'Thomas', 'John']` typing `@a` will not show autocomplete view.
I think we should change matching feed to case insensitive which is more common and add additional option like `caseSensitive` for case sensitive matching.
