### ISSUE TITLE
Link translation for danish "Display Text" is just english

### ISSUE THREAD

**Issue by brunis** [ckeditor/ckeditor-dev#1705]
## Are you reporting a feature request or a bug?
"Bug" in danish translation

## Provide detailed reproduction steps (if any)
1. Click insert link

### Expected result
"Display Text" should be something similar to "Vis tekst" or "Link tekst" or something similar. Consult your danish translator.

### Actual result
the "Display Text" is an english term

## Other details

* Browser: all
* OS: all
* CKEditor version: latest 4.x release
* Installed CKEditor plugins: link :)

**Comment by mlewand** [comment]
We're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. Please send your contribution there, so that we can pull it into upcoming release.

Thanks!
