### ISSUE TITLE
No 'pluginDefinition.icons' property documentation

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#1709]
## Are you reporting a feature request or a bug?

Task: documentation adjustments 

## Provide detailed reproduction steps (if any)

Looking at [`pluginDefinition`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_pluginDefinition.html) page on SDK, there are docs for `hidpi`, `lang`, `requires` properties. However, there is nothing about `icons` property (which is used in most plugins).

The icons property is removed during build from what I see:
```
icons: 'bold,italic,underline,strike,subscript,superscript', // %REMOVE_LINE_CORE%
```
but still as docs are mainly used during development, the `icons` property should be documented.

**Comment by Dumluregn** [comment]
Issue resolved in #2997.
