### ISSUE TITLE
extraPlugins configuration option should allow whitespaces between values

### ISSUE THREAD

**Issue by arist0tl3** [ckeditor/ckeditor-dev#1712]
## Feature Request

After pulling my hair out trying to debug why I could only add one external plugin at a time, I realized that the config option `extraPlugins` doesn't accept whitespace between values.

Not a huge deal, but *no* other config options seem to have that requirement, and there is no documentation around this required format.

I feel like this is confusing, as `removePlugins` is fine with whitespace, but `extraPlugins` isnt:

![image](https://user-images.githubusercontent.com/9328541/36564245-7923cffc-17d1-11e8-9b2d-bcddf0094e0f.png)

Accepting whitespace would be the better solution, but a note in the docs would be the quicker one, I'm assuming.

Happy to open a PR to trim the whitespace.

**Comment by f1ames** [comment]
Thanks for reporting @arist0tl3! I can confirm it works this way and it will be good to keep `removePlugins` and `extraPlugins` settings consistent (so they both handle whitespaces).

If you feel like creating a PR, it would be great (you may want to check [contributing guide](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_contributing_code.html))!

Btw. the code responsible for this behaviour should be probably somewhere here:
https://github.com/ckeditor/ckeditor-dev/blob/53ac710582ff47dd63ec4368cfd752db5bee6e28/core/editor.js#L499-L505

**Comment by Comandeer** [comment]
There is also third, very similar option to `extraPlugins` and `removePlugins` – `plugins`. The whole handling logic for these three options is in on place, so I'd broaden the scope of issue and fix also whitespaces in `plugins` option.

**Comment by Comandeer** [comment]
Closed in #1762.
