### ISSUE TITLE
Duplicate "Paste" language string in Clipboard plugin

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-dev#1713]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

When adding the Paste dialog back, we created new language strings and duplicated "Paste".

```
paste: 'Paste',
...
title: 'Paste'
```

### Expected result

The existing language string should be reused, with meta language string expanded.

### Actual result

Translation progress is down for all languages and all localizations have an untranslated entry where, in fact, there is often the correct translation already available **in the same file**.

**Comment by mlewand** [comment]
This dialog has been reverted, so we have it as it were in version 4.6.x (including all the original translations). We don't want to add extra noise now to the major branch, so putting this issue to the backlog.
