### ISSUE TITLE
table theme/style

### ISSUE THREAD

**Issue by xsung** [ckeditor/ckeditor-dev#1714]
## Are you reporting a feature request or a bug?

Feature request

### Expected result

I want some fancy style, such as 
![default](https://user-images.githubusercontent.com/31883451/36584659-98a72e20-18b5-11e8-92fc-c2b18513be00.PNG)

### Actual result

only two styles are available: `compact table`, `borderless table`.
![default](https://user-images.githubusercontent.com/31883451/36584581-344226b0-18b5-11e8-8190-38dadf0d62f1.png)

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by xu-song** [comment]
Is there a plugin about `table theme`, like the following example:
https://www.tablesgenerator.com/html_tables

**Comment by msamsel** [comment]
Hi @xsung 

there is already possibility to customise styles available in CKEditor4. Please take a look into this documentation: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_howtos_styles.html

**Comment by xu-song** [comment]
there are only two styles
![s](https://docs.ckeditor.com/ckeditor4/latest/assets/img/styles_03.png)

**Comment by msamsel** [comment]
@xu-song in example there are 2, but you can add your own styles with: https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_stylesSet.html

Please also take a look into last editor on this page and styles available there:
https://sdk.ckeditor.com/samples/styles.html
