### ISSUE TITLE
Simple Ruler

### ISSUE THREAD

**Issue by haoksam** [ckeditor/ckeditor-dev#1721]
## Are you reporting a feature request or a bug?
Bug / Other

## Provide detailed reproduction steps (if any)

1. Get the Full Package of the CKEditor with the **Simple Ruler** plugin included
2. Run CKEditor

### Expected result

Working Editor.

### Actual result

Missing libraries errors .

## Other details
Looks like plugin depends in RequireJS and NoUISlider but just installing them in the project dosen't resolve the problem. 
Is there any way to make Simple Ruler work directly from the box?

* Browser: Any
* OS: Windows 10
* CKEditor version: 4.8.0
* Installed CKEditor plugins: _a11yhelp, about, basicstyles, bidi, blockquote, chart, clipboard, colorbutton, colordialog, contextmenu, dialogadvtab, div, divarea, elementspath, enterkey, entities, filebrowser, find, flash, floatingspace, font, format, forms, horizontalrule, htmlwriter, iframe, image, indentblock, indentlist, justify, language, letterspacing, lineheight, link, list, liststyle, magicline, maximize, newpage, pagebreak, pastefromword, pastetext, preview, print, removeformat, resize, save, scayt, selectall, showblocks, showborders, **simple-ruler**, smiley, sourcearea, specialchar, stylescombo, symbol, tab, table, tableresize, tabletools, templates, toolbar, undo, widget, wsc, wysiwygarea_

**Comment by f1ames** [comment]
This is a third party plugin not maintained by the CKEditor team.

Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/cke4/addon/simple-ruler).
