### ISSUE TITLE
Expose getAbsoluteRect private function

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1724]
## Are you reporting a feature request or a bug?

Feature request

### Expected result

`CKEDITOR.tools.dom.getElementRect` function returns the position of the element on the screen.

### Actual result

`_getAbsoluteRect` function is hidden inside `balloonpanel` plugin.

## Other details

I need to use this function in other place so I think it's good idea to expose it as a public API. This function takes editor and element instances as arguments to calculate element position. It doesn't fit well in `core/element` nor `core/editor` so after some debate with @f1ames we think tools are best place to expose it.

**Comment by mlewand** [comment]
It should be a method in [`element`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dom_element.html) type. While doing that make sure that the method gets a better description, clearly explaining it's purpose and how is it different from https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dom_element.html#method-getClientRect and https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dom_element.html#method-getDocumentPosition

**Comment by Comandeer** [comment]
Closed in #1727.
