### ISSUE TITLE
Add a button for Easy Image plugin

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1730]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

In 4.9.0 we have added a Easy Image plugin.

While simplifying the feature we skipped the image button all along - the problem with this approach is that end user has no clear information whether dropping images (or EI plugin in general) is available at all.

The only way for end user is to drop the file and see if it's being uploaded. In the worst case scenario, page could be replaced with the dropped image.

The solution to that issue will be adding a button that will display a regular `input[file]` allowing for image upload.

## Other details

* CKEditor version: 4.9.0
* Installed CKEditor plugins: easyimage

**Comment by msamsel** [comment]
@mlewand what kind of icon should be used for easy image upload.
CKE5 has regular image icon, but this might be confusing, if editor load image or image2 plugin, which have the same icon.

**Comment by mlewand** [comment]
@msamsel Easy Image won't work correctly side by side with image/image2. Let's use the same button icon as for image/image2 plugin. There's small UX issue with that approach, as one is not able to tell the difference, what exactly plugin is loaded, but we can extract the icon thing into a followup task.

**Comment by msamsel** [comment]
Just to have info how it looks in CKE5, this is the icon used there:
https://github.com/ckeditor/ckeditor5-core/blob/753980680296e3b6de469fe435b959e3716494ec/theme/icons/image.svg

**Comment by msamsel** [comment]
Sample how feature looks in CKE5
![screen shot 2018-03-07 at 10 35 13](https://user-images.githubusercontent.com/9017322/37084676-746b6de0-21f3-11e8-886c-6311fa3a9396.png)
![screen shot 2018-03-07 at 10 35 51 2](https://user-images.githubusercontent.com/9017322/37084675-744d2ca4-21f3-11e8-9c23-1a7e2313b228.png)

**Comment by msamsel** [comment]
Icon case was extracted to: #1758

**Comment by mlewand** [comment]
Since 4.9.0 got postponed and the PR is pretty much R+ I'll still contain it in 4.9.0 release, as we'd really love to ship EI with this button from day 1.
