### ISSUE TITLE
Focus issue with latest iOS after keypad get open in Bootstrap modal !

### ISSUE THREAD

**Issue by avkash4n4u** [ckeditor/ckeditor-dev#1735]
## Are you reporting a feature request or a bug?
BUG - [CKEditor 4.7.0 (revision 320013d)]

## Provide detailed reproduction steps (if any)
1. Bind ck inline within Bootstrap modal.
2. Tap on the editor and try to add/edit content.
3. Cursor focus will get change from the actual position inside modal.

See attached screenshot.
![img_0445](https://user-images.githubusercontent.com/1196597/36958978-78c86a6c-2065-11e8-820b-a2df4487048e.PNG)
![img_4533](https://user-images.githubusercontent.com/1196597/36958979-78f0348e-2065-11e8-9e83-1ed986017262.PNG)

### Expected result
It should remain the cursor position same after open the keypad.

### Actual result
It is not remaining the cursor position same in iOS after keypad popups in modal.

## Other details
* Browser: … iOS safari (iPhoneX and other iPhone devices)
* OS: … iOS
* CKEditor version: … CKEditor 4.7.0 (revision 320013d)
* Installed CKEditor plugins: … Autogrow is enabled no other plugin used!

**Comment by msamsel** [comment]
Issue seems to be the same as this one: #498
