### ISSUE TITLE
Option for Color Dialog add-on to preselect a color in its dialog

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor-dev#1749]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

[Color Dialog](https://ckeditor.com/cke4/addon/colordialog) add-on can be used by many plug-ins to select a color. If a user would like to use this functionality repeatedly with the same color, he must remember each time which color he selected the previous one. I propose an option for `getColorFromDialog()` function in order for the dialog to be launched with an already selected color.

**Comment by jacekbogdanski** [comment]
Hello,

I'm sorry but currently we are not planning to provide this feature. This behaviour could be reproduced using [Copy Formatting](https://sdk.ckeditor.com/samples/copyformatting.html) plugin. But we have already reported feature request to improve selecting custom colours from [Color Dialog](https://ckeditor.com/cke4/addon/colordialog). You can read about it here: #1795. If you like the idea - please give it the thumbs up so we will know that our community is interested in this improvement.

**Comment by Wizard13** [comment]
FWIW, I decided to give it a go and I succeeded using just the `dialogDefinition` event, without changing anything in the original `colordialog` plugin.
