### ISSUE TITLE
Autocomplete plugin

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1751]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

We need a component that provides an ability to display a dropdown with options matched to the currently typed text. This feature is needed for Mentions #1703 and Emoji #1746 features.

This feature should provide a flexible API, it should work both synchronously and asynchronously.

It should allow for customizing the way entries are displayed.

## Preview

Users interested in seeing how the feature looks today can preview it on [our Autocomplete feature branch preview](https://ckeditor4-preview.ckeditor.com/t/1751/plugins/autocomplete/samples/smiley.html).

## Browser Support

Currently we're looking to support the feature in all [supported browsers](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_browsers.html#officially-supported-browsers) except IE8, QM and CM.

**Comment by msamsel** [comment]
@mlewand, @jacekbogdanski it seems that autocomplete do not update itself when selection in editor is changed by mouseclick.

**Comment by jacekbogdanski** [comment]
It's on purpose.  Otherwise, you will get autocomplete view when changing selection like `@Ann^` by mouse click which is pretty annoying.
