### ISSUE TITLE
Copy / Paste In Browser Provides Warning. After Waring and Pasting text do not get Saved to TextArea.

### ISSUE THREAD

**Issue by kaushikmeduri** [ckeditor/ckeditor-dev#1753]
## Are you reporting a feature request or a bug? bug
When attempting to Copy / Paste Browser Provides Warning. After Waring and Pasting text do not get Saved to TextArea.

## Provide detailed reproduction steps (if any)

1. …When attempting to Copy / Paste Browser Provides Warning. After Waring and Pasting text do not get Saved to TextArea.
2. …
3. …

### Expected result
Text Gets Saved in CkEditor
*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*
This is working fine for some browsers. But some people have issues.

## Other details

* Browser: …Chrome/IE
* OS: …Windows
* CKEditor version: … How do we Know it  ? 
* Installed CKEditor plugins: …No

**Comment by kaushikmeduri** [comment]
<img width="541" alt="ckeditor" src="https://user-images.githubusercontent.com/16493566/37035041-3437db6c-2119-11e8-901e-8c3dbc56b35e.png">

**Comment by jacekbogdanski** [comment]
Hello,
you can check a version of a CKEDITOR instance by typing `CKEDITOR.version` in a browser console. 
The dialog on your screen means that you are probably using older version of the CKEDITOR (below 4.7.0). 
I cannot reproduce the issue with 4.8.0 and you should upgrade your CKEDITOR to the latest stable version.
