### ISSUE TITLE
Spans added to FA Icons when switching to Source view

### ISSUE THREAD

**Issue by jslucas** [ckeditor/ckeditor-dev#1754]
## Are you reporting a feature request or a bug? 
Bug

## Provide detailed reproduction steps (if any)

1. Insert a FA icon
2. Switch to Source view
3. The icon has been wrapped in <span aria-label="span widget" contenteditable="false" role="region" tabindex="-1">
4. Switch out of Source view
5. Switch back, there's another <span aria-label="span widget" contenteditable="false" role="region" tabindex="-1"> wrapped around the previous one, and the FA icon.
6. You can do this endlessly, it will keep adding them.

### Expected result

Spans do not get generated by switching to Source view.

### Actual result

A <span aria-label="span widget" contenteditable="false" role="region" tabindex="-1"> is appended each time you switch between Source view.

## Other details

* Browser: Chrome/Firefox, did not test IE or Edge
* OS: Windows10
* CKEditor version: CKEditor 4
* Installed CKEditor plugins: a11yhelp, colordialog, fontawesome, image, pagebreak, smiley, widget, about, dialog, forms, lineutils, pastefromword, specialchar, wsc, bt_table, div, link, preview, table, youtube, btgrid, find, liststyle, scayt, tabletools, clipboard, flash, iframe, magicline, showblocks, templates

**Comment by jacekbogdanski** [comment]
Hello,
this could be related to the #1410. Nevertheless this is a third party plugin not maintained by the CKEditor team.

Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/cke4/addon/fontawesome).
