### ISSUE TITLE
Cloud Services plugin should download token on its own

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-dev#1755]
The names of configuration options for Cloud Services are wrong.

## CKEditor 5

* (cloudServices.)tokenUrl 
* (cloudServices.)uploadUrl

both names are perfect as they precisely describe what kind of data is expected there and what is its purpose: https://docs.ckeditor.com/ckeditor5/latest/api/module_cloudservices_cloudservices-CloudServicesConfig.html 

## CKEditor 4

* cloudServices_token : String
~The token used for CKEditor Cloud Services authentication.~

The explanation is wrong. What the user is supposed to be set there is the token end point URL (URL that will issue tokens for users). Just copy the description from CKEditor 5. 

* cloudServices_url : String
The endpoint URL for CKEditor Cloud Services uploads. Note that this is **the URL only for file uploads**. CS exposes more URLs. That's why it should be named "uploadUrl" not just "url".

So:

* cloudServices_tokenUrl
* cloudServices_uploadUrl 

are the valid names for configuration options.

**Comment by mlewand** [comment]
This will require us to move all the token-related handling to the CS plugin in CKE4. In addition to that we'll have to implement token refreshing.
