### ISSUE TITLE
Attempting to replace an existing Image doesn't update the source.

### ISSUE THREAD

**Issue by rkarina94** [ckeditor/ckeditor-dev#1756]
## Are you reporting a feature request or a bug?
BUG

## Provide detailed reproduction steps (if any)

1. Upload an Image using the Image plugin.
2. Select an image and press ok to display the image in base64 format. 
3. Replace the image with another by right-clicking on the image. 
4. Click the source view and back to the editor view.  

### Expected result
Should display the newly uploaded image.

### Actual result
Displays the original uploaded image.

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.8.0
* Installed CKEditor plugins: {
		'a11yhelp' : 1,
		'autolink' : 1,
		'backgrounds' : 1,
		'base64image' : 1,
		'basicstyles' : 1,
		'bgimage' : 1,
		'blockquote' : 1,
		'chart' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'contextmenu' : 1,
		'docprops' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'image' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imagerotate' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'lineheight' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maxheight' : 1,
		'pagebreak' : 1,
		'panelbutton' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'print' : 1,
		'quicktable' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'scayt' : 1,
		'showblocks' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'textsignature' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'zoom' : 1
}

**Comment by engineering-this** [comment]
It seems like issue is related to third party plugin.
Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/cke4/addon/base64image) or on [addon github repository page](https://github.com/nmmf/base64image)
