### ISSUE TITLE
Detect and link email addresses in autolink plugin

### ISSUE THREAD

**Issue by georgringer** [ckeditor/ckeditor-dev#1761]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

1. Enable the autolink plugin
2. ~Write~ Paste an email address

### Expected result

The email address should be linked with a mailto link

### Actual result

The email address as text only.

**Comment by jacekbogdanski** [comment]
Hello,

I think you misunderstood how `autolink` plugin works. Currently it only turns the pasted URL text into a link. We decided to approve this feature request  and it will be implemented consistent with `autolink` plugin behavior i.e. it will replace email addresses with correct link **only when an email has been pasted**.

Nevertheless you give us a great feature idea to handle typed text with `autolink` plugin. I opened additional feature request for it: #1815. 

If you like the idea please give it thumbs up so we will know that our community is interested in this feature.

**Comment by georgringer** [comment]
Thanks for your response and explanation! I didn't know that it was only about pasting and certainly it is also very important to have those automated created links for typed urls as well. 

We in the TYPO3 community are using ckeditor and those features are missing as it was possible in the previous editor.

**Comment by josefglatz** [comment]
actually TYPO3 has integrated a custom autolinking plugin without mailto-link support https://github.com/TYPO3/TYPO3.CMS/commit/e096754a699db509da5b4307378148886a9aecad
