### ISSUE TITLE
the scroll bar disappears

### ISSUE THREAD

**Issue by camachogfelipe** [ckeditor/ckeditor-dev#1767]
## Provide detailed reproduction steps (if any)

1. one click on the drop-down list items
2. two clicks in the same drop-down list items

### Expected result

the scroll bar don't disappear

### Actual result

the scroll bar disappears

## Other details

* Browser: IE9, EDGE, CHROME, FIREFOX, OPERA
* OS: ALL
* CKEditor version: 4
* Installed CKEditor plugins: NONE

**Comment by jacekbogdanski** [comment]
Hello,
It's a chromium issue and I cannot reproduce it on IE9, Edge and Firefox. 
Duplicate of #774
