### ISSUE TITLE
Easy Image button names are inconsistent with rest of the editor

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1769]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

Every EI button should follow pascal case convention.

So [`EasyimageAlt`](https://github.com/ckeditor/ckeditor-dev/blob/a649b6c3672da62c71df5ba3615baa1c2aabb297/plugins/easyimage/plugin.js#L157) should become `EasyImageAlt` and so on.

**Comment by mlewand** [comment]
If possible, it would be nice to contain it still in 4.9.0 release.

**Comment by msamsel** [comment]
Command names extracted to: #1772
