### ISSUE TITLE
CKEditor is stripping the svg tag

### ISSUE THREAD

**Issue by mgifford** [ckeditor/ckeditor-dev#1774]
This was reported in Drupal 8's issue queue:
  https://www.drupal.org/project/drupal/issues/2897119

How are svg images managed in CKEditor?

In our testing the content in the <title></title> tag was removed.  Unfortunately, that's needed for accessibility:
  https://www.sitepoint.com/tips-accessible-svg/

Would  like to have more direction.

**Comment by jacekbogdanski** [comment]
Hello,

I suppose that @msamsel response worked for you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by mgifford** [comment]
I'm not so much interested in this particular issue for any of my sites as I am about the default behavior.  

It doesn't make any sense to allow an SVG tag, but to strip out a  TITLE tag from within that SVG tag. That default behavior is wrong and breaks accessibility. 

Stripping out the TITLE in other contexts is appropriate as it shouldn't be in the body where CKEditor would be posting it. However, this isn't the case with inline SVG files.

**Comment by szabolcsnagy** [comment]
I run into this issue with CKEditor 4.8.0 in Mura CMS. Inside a widget plugin I render an SVG and the content of the title tag is stripped out when I switch to the source view. 
Interestingly if I add any attribute to the title tag that is preserved. 
For example: `<title aria-label="Hello">Hello<title>` turns into `<title aria-label="hello"></title>`
