### ISSUE TITLE
Provide documentation for linked element in guides

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1781]
## Are you reporting a feature request or a bug?

task - missing documentation

## Provide detailed reproduction steps (if any)

There are used links in our guides to not described API elements, what effects with throwing errors during docs building process. We need to provide documentation for those elements:
* `CKEDITOR.editor#uiSpace` https://github.com/ckeditor/ckeditor-dev/blob/5f41b3fc795ac07493110b94939cc716957c6196/core/creators/themedui.js#L396-L397
* `CKEDITOR.skin.ua_editor`

Links are used here:
* https://docs.ckeditor.com/ckeditor4/latest/guide/dev_api_changes.html
* https://docs.ckeditor.com/ckeditor4/latest/guide/skin_sdk_browser_hacks.html

### Expected result

Provide documentation for those entries

### Actual result

No docs -> Warnings with docs building -> soon it's going to be errors https://github.com/cksource/umberto/issues/507#issuecomment-371538100

**Comment by mlewand** [comment]
Closed in #1787.
