### ISSUE TITLE
Add documentation for CKEDITOR.on

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1788]
## Are you reporting a feature request or a bug?

task - documentation correction.

## Provide detailed reproduction steps (if any)

Issue extracted from this comment: https://github.com/ckeditor/ckeditor-docs/pull/143#discussion_r174059760

CKEDITOR should be mixed by CKEDITOR.event.
https://github.com/ckeditor/ckeditor-dev/blob/c199bf1/core/ckeditor_basic.js#L14

**Comment by Comandeer** [comment]
Fixed in #1789.
