### ISSUE TITLE
Disable image and image2 plugin when Easy Image is present

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#1791]
## Are you reporting a feature request or a bug?

Task

## Description

Currently it's possible to enable Easy Image alongside image and image2 plugins, resulting in strange editor's behaviour. Image plugin has code to prevent loading it when image2 is present. Adding similar code to both image and image2 plugin to prevent loading when EI is present seems like a sensible solution.

**Comment by mlewand** [comment]
Note that it should provide some kind of feedback for the developer. What I'm thinking is to include a log msg.
