### ISSUE TITLE
Default font style is not written into the element style

### ISSUE THREAD

**Issue by 4lch3m1st** [ckeditor/ckeditor-dev#1797]
🐞 Bug report

CKEditor 4.7

📋 Steps to reproduce
1. Do not select the any font style before writing into the ckeditor
2. Write something into the CKEditor -> Font style has been set to default -> OK
3. Check the element style with the dev tools ->Font style is empty
✅ Expected result
Font style should be added as style to the element

❎ Actual result
Font style is empty

📃 Other details that might be useful
Added screenshot from the issue
![element style is empty](https://user-images.githubusercontent.com/15000997/37407681-88cf6e7e-279a-11e8-8462-6eeeccb8df0e.png)

**Comment by jacekbogdanski** [comment]
Hello,

I couldn't reproduce the issue. I reproduced your steps on CKEditor 4.7.0 and 4.8.0 - both works correctly. It didn't matter which paragraph type I used ( you are using `div` type so I checked if its not an issue with this feature) and spellchecker on/off. 

It would be great if you could provide more information about your CKEditor settings like used plugins and how you [configured editor instance](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_configuration.html).

Last but not least: it's good to check if your issue exists on clean CKEditor instance using our [online CKEditor samples](http://cdn.ckeditor.com/4.8.0/full-all/samples/). 

Please give us a response with additional information so we will be able to investigate this issue thoroughly.

**Comment by f1ames** [comment]
I just wanted to mention that there is no configuration option to set default font family. The only setting is [`font_defaultLabel`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-font_defaultLabel) which as described in the docs:
> The text to be displayed in the Font combo is none of the available values matches the current cursor position or text selection.

So it only sets the default font combo label, but does not influence content itself.

---

@4lch3m1st, one workaround for this may be to set this label as you did and then edit `content.css` file (which holds styling for editor content) and set default font-family to the same one used as a label.

You may also look for other ideas on Stackoverflow as there a few suggestions already - https://stackoverflow.com/search?q=ckeditor+default+font.
