### ISSUE TITLE
Paste button no longer reflects clipboard state

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1810]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Make sure your clipboard is empty (you can use shortcut for clearing the clipboard or dedicated tool - https://www.techbout.com/clear-clipboard-in-windows-10-26155/). 
2. Focus the editor

### Expected result

Paste icons should become disabled.

### Actual result

Paste icons stay enabled.
Feature got broken in CKEditor 4.3.0.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.3.0+
* Installed CKEditor plugins: clipboard

**NOTES**: 
1. Currently (CKE 4.9.0) the paste dialog is only available on Mobiles so making the button seems pointless for desktops however despite paste dialog being present or not, this has always been a nice feature (for more advanced users for example) thus we should bring it back.
2. There is a chance that vendors will one day allow JavaScript get to clipboard and allow pasting thus it makes a perfect sense to leave these buttons and make them work as they did before.

**Comment by mlewand** [comment]
Unfortunately that's not possible. In web apps, we can't access the clipboard without user explicit intention - this would be a big security issue. Thus we can't really tell what's in the clipboard. So in the end it's not something we can check before the content is actually pasted.

There is one web app that might allow this kind of things: Google Docs on Google Chrome. Reason for this is that Google ships Chrome out of the box with an extension that sneaks additional API for GDocs only. If you disable the extension, feature will no longer work.

As a side note, on old IEs it's possible to request clipboard access from the API, but even there it results with a security popup asking end user whether the web page should be provided with clipboard data. Imagine how annoying that would be if this dialog would appear on each (sub) page using the CKEditor 😉

**Comment by jswiderski** [comment]
Thx for clarifications @mlewand. I guess I didn't check that properly.
