### ISSUE TITLE
Accessibilty mode Android/iOS: Flyout is not closed properly and focus moves to hidden element

### ISSUE THREAD

**Issue by sumit99531** [ckeditor/ckeditor-dev#1811]
Bug: In accessibility mode using talkback or voiceover, after opening a flyout, it only closes by moving at end or start of flyout elements(it appears to be closed but is not closed properly)

## Provide detailed reproduction steps (if any)

1. Open CKEditor using Talkback(Android) or VoiceOver(iOS)
2. Swipe through toolbar to Styles flyout and click on it
3. Try to close the flyout

### Expected result

Flyout should close using a focus move to some hidded close button and double tapping it.

### Actual result

Flyout closes(appears to be closed) by swiping through end or swiping back from first. If we swipe again to flyout direction, the focus moves to hidden flyout list which is not visible(flyout appears to be closed but is not).

## Other details

* Browser: safari/chrome
* OS: iOS10/ Android 8.0
* CKEditor version: 4.9.0
* Installed CKEditor plugins: standard editor

**Comment by msamsel** [comment]
Hi

CKEditor4 officially supports only JAWS (https://docs.ckeditor.com/ckeditor4/latest/guide/dev_browsers.html#accessibility-support).
That's why I have to resolve this issue with won't fix status.
