### ISSUE TITLE
Autolink plugin typing support

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1815]
## Are you reporting a feature request or a bug?

Feature request

[Autolink plugin](https://ckeditor.com/cke4/addon/autolink) currently only works for pasted content. We could expand the plugin to handle turning URLs and [emails](https://github.com/ckeditor/ckeditor-dev/issues/1761) into links when typing text into editor.

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample with enabled `autolink` plugin.
2. Type `http://example.com`

### Expected result

URL has been replaced with HTML link e.g. `<a href=“http://example.com”>http://example.com</a>`.

### Actual result

URL has been typed as a normal text.

**Comment by hkakumanu-ttc** [comment]
are you guys planning to do this feature?

**Comment by mlewand** [comment]
@hkakumanu-ttc it's not yet in our backlog - however the best way to show that you'd like to see it in the release is to add 👍 reaction in the first post.

**Comment by Comandeer** [comment]
Autolinking was merged to `major` and will appear in CKEditor 4.11.0.

**Comment by mlewand** [comment]
The feature landed on a `major` branch, however `autolink` plugin is not by default included in any of our presets, thus it's not included in any sample.

I created a codepen demo where it could be previewed: https://codepen.io/mlewand/pen/QBGYpL

**Comment by mlewand** [comment]
BTW guys, I'm wondering if there should be added a simplified regexp for string like `www.example.example`, because for URLs currently one must write a fully qualified URL including a protocol, which is a rather rare case. @jacekbogdanski @Comandeer
