### ISSUE TITLE
triple click in Chrome / Safari selects also the next element 

### ISSUE THREAD

**Issue by xpressionlabspeter** [ckeditor/ckeditor-dev#1827]
To reproduce this problem you have to triple click first paragraph when paragraph has at least two words. The fault is on browser side. When triple clicking native method `window.getSelection().getRangesAt(0).endContainer` will be second paragraph while it should be first one.

Original message below:

🐞 Bug report
💻 4.7.3
📋 Steps to reproduce

1.     enter some text on several lines
3.     select with the mouse the first line, by mousedown on first character, drag to last and mousup
4.     select an h1-style: result the first line is now a h1
5.     undo
6.     select the first line by dblclick (three-click) on a word in the first line.
7.     Choose h1-style.
8.     The firstline AND the next paragraph is now h1 

✅ Expected result

only the first line as h1

❎ Actual result
first and second paragraph h1

📃 Other details that might be useful

Only in Chrome and Safari
see attached gif
![film](https://user-images.githubusercontent.com/37589335/37697779-089746e2-2cdf-11e8-878d-751b35dd170f.gif)

**Comment by engineering-this** [comment]
Confirmed on our major dev.

**Comment by mlewand** [comment]
This might be an upstream @engineering-this please check if the same happens on plain `contenteditable` element.

**Comment by engineering-this** [comment]
It is also duplicate of #484
