### ISSUE TITLE
Request for the spanish language

### ISSUE THREAD

**Issue by syedyasser** [ckeditor/ckeditor-dev#1833]
## Are you reporting a feature request or a bug?
Request

## Other details
Please add the spanish as the language as we can check the special character also 
* Browser: … any
* OS: …any
* CKEditor version: …new
* Installed CKEditor plugins: …all

**Comment by msamsel** [comment]
Hi,

spanish translation are available for CKEditor. Here is an example of translation:
https://github.com/ckeditor/ckeditor-dev/blob/major/lang/es.js

If you wish to improve translation, you can commit it to [Transifex](https://www.transifex.com/ckeditor/ckeditor/).
