### ISSUE TITLE
CKEditor documentation search bar

### ISSUE THREAD

**Issue by shirajgill** [ckeditor/ckeditor-dev#1836]
CKeditor Search bar Bug 

Before the revamp of the website for CKEDitor's documentation we were able to use the search bar perfectly fine. But after the revamp we've not been able to use the search bar on the CKEditor documentation page: https://docs.ckeditor.com/ckeditor4/latest/index.html
We are using IE 11 

Thank you.

**Comment by jacekbogdanski** [comment]
Hello,

Thank you for your issue report. As you already know we recently updated our CKEditor's documentation engine. As an result you can experience some issues until we will be able to fix them. 

The issue you submitted is being handled in our documentation engine tracker.

We apologise for any inconvenience that this may have caused you, and we appreciate your understanding as we continue to improve our documentation.
