### ISSUE TITLE
 Style Sheet Parser plugin not functioning in Firefox 

### ISSUE THREAD

**Issue by gtbu** [ckeditor/ckeditor-dev#1837]
## Are you reporting a feature request or a bug?

#8660 closed (Reported by: | raymondp413) but still unsolved  :  
Stylesheetparser-plugin not there (Typesetter CMS 5) or not active - grayed(Cmsimple XH 1.72) in **Firefox** --
but activ in OperaPortable in Cmsimple XH (not in Typesetter with Opera)

*What is the expected result of the above steps?* An idea what is incompatible - 
Please not just a new plugin-version just for ckeditor4.9 - what can i patch ?

## Other details
Browser : Firefox 59.0.1 (in Opera Portable it functions with CMsimple XH 1.72 CMS)
* OS:  Win 10
* CKEditor version: 4.5 and 4.73
* Installed CKEditor plugins: …like Typesetter-CMS : long list

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

Please provide description which allow on bug reproduction on our side. Current description is way too confusing to understand what you have on your mind.
