### ISSUE TITLE
how can i use it as a npm package?

### ISSUE THREAD

**Issue by luoboding** [ckeditor/ckeditor-dev#1849]
how can i use it as a npm package?

**Comment by AnnaTomanek** [comment]
Follow the [Installing CKEditor with Package Managers - npm](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_package_managers.html#npm) guide.

Please note this is a bug tracker. If you are looking for help, check the [CKEditor 4documentation](https://docs.ckeditor.com/ckeditor4/latest/index.html) and use [StackOverflow](https://stackoverflow.com/questions/tagged/ckeditor). Thank you!
