### ISSUE TITLE
Object doesn't support property or method 'createTextRange' IE11, Edge

### ISSUE THREAD

**Issue by robsonkades** [ckeditor/ckeditor-dev#1853]
SCRIPT5007: Unable to get property 'specified' of undefined or null reference
ckeditor.js (95,288)

My imports

`https://cdn.ckeditor.com/4.9.1/full-all/ckeditor.js`
`https://cdnjs.cloudflare.com/ajax/libs/ng-ckeditor/0.2.1/ng-ckeditor.js`

My directive

`function ckEditor($rootScope) {
  return {
      require: 'ngModel',
      link: function (scope, element, attr, ngModel) {
       scope.editorOptions = {
          height : 250,
          toolbar : 'Basic',
          removePlugins : 'save'
      }
    }
  }
}`

Google Chrome ->  OK

* Browser: …
* OS: … Windows 10 Pro
* CKEditor version: … 4.9.1 full
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Hello,
 
`ng-ckeditor` is a third party library not maintained by the CKEditor team.

Please contact with library author to report the problem.
