### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by v2kajay** [ckeditor/ckeditor-dev#1857]
Unable to edit fields when any dialogue box had opened in CKEditor... (image,hyperlink,table) nothing is editable now. Please fix it and let me know

I had tried 
1> config.baseFloatZIndex = 102000;

2> .cke_skin_v2 input.cke_dialog_ui_input_text, .cke_skin_v2 input.cke_dialog_ui_input_password {
            background-color: white;
            border: none;
            padding: 0;
            width: 100%;
            height: 14px;
            /* new lines */
            position: relative;
            z-index: 9999;
      }
3>  orig_allowInteraction = $.ui.dialog.prototype._allowInteraction;
       $.ui.dialog.prototype._allowInteraction = function(event) {
          if ($(event.target).closest('.cke_dialog').length) {
             return true;
          }
       return orig_allowInteraction.apply(this, arguments);
     };

Please let fix it quickly

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
