### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by pgscannell** [ckeditor/ckeditor-dev#1858]
I don't know if anyone else has had this error, but I'm getting a runtime error that is associated with this line in the ckeditor.js file: if(r.init)

The error says:  Line: 24 Unable to get property 'init' of undefined or null reference

(Because the ckeditor.js is compressed, line 24 isn't really line 24.  The variable r is set to: 'var r=k[o]' the uncompressed code where r.init is referenced is if this helps anyone:
var r=k[o];
if ( !n.skin )
   {
   n.skin=r;
   if ( r.init )
      r.init(n);
   }

I'm not sure what could be the problem.  I have all of the copies of the ckeditor javascript files that I copied over from another website that utilizes it with no problems.  Unfortunately I can't run the other website here as it is from an intranet that is only accessible from my home.

I'd like to be able to get by this hurdle if possible.  If anyone knows what I might be missing, please advise me.

One of the problems is that the ckeditor.js file is in compressed format so I can't follow the logic.  Is there a way to get this file uncompressed so I can see what is happening around this line of code?

**Comment by jacekbogdanski** [comment]
Hello,

I really recommend reading our [Quick Start Guide](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html). You will get all required knowledge to install CKEditor on your site. 

If you would like to get uncompressed javascript you could clone current repository i.e. [ckeditor-dev](https://github.com/ckeditor/ckeditor-dev/) and open sample editor. You will find it at `ckeditor-dev/samples/index.html` location. Don't forget you will have to set up some local server to host sample files.

If you will find out that it's not a configuration issue but CKEditor, feel free to create another issue with reproduced steps.
