### ISSUE TITLE
CKEditor 4 logs me out if there's a missing image in the textarea body (the 'source')

### ISSUE THREAD

**Issue by jsfgreen** [ckeditor/ckeditor-dev#1859]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Load CKEditor 4 on a page where the content of CKEditor has a _missing image_

### Expected result

CKEditor should load normally with simply a missing image icon.

### Actual result

CKEditor loads but _clears the session_ and logs me out! (It doesn't redirect, but on next page load or reload the session is cleared so my app redirects me to a login)

## Other details

* Browser: Firefox 59, Safari 11
* OS: MacOS High Sierra
* CKEditor version: 4.5.11
* Installed CKEditor plugins: blockimagepaste,jsplus_bootstrap_include,jsplus_bootstrap_show_blocks,jsplus_bootstrap_block_conf,jsplus_bootstrap_templates,jsplus_bootstrap_table_new,jsplus_bootstrap_button,jsplus_bootstrap_icons,jsplus_bootstrap_gallery,jsplus_bootstrap_badge,jsplus_bootstrap_label,jsplus_bootstrap_breadcrumbs,jsplus_bootstrap_alert

**Comment by engineering-this** [comment]
Hi.

You are using plenty of unofficial plugins. There is possibility that one of them is causing this problem. Could you provide example of CKEditor in which this problem occurs, but without any third party plugins? You can setup CKEditor on page like codepen.io or jsfiddle.net.
