### ISSUE TITLE
Line spacing after hitting the Enter key

### ISSUE THREAD

**Issue by pgscannell** [ckeditor/ckeditor-dev#1860]
The behavior of ckeditor when you hit the enter key is to treat what you have been typing up to that point as a paragraph.  It then places quite a bit of white space.  I had this issue once a long time ago with an earlier download/install of ckeditor.

I just had to to do the download/install again and need to fix that behavior.  In fact, whatever you are 
doing in this textbox that I'm typing into right now is the behavior I want. If I hit the enter key here x
This line is immediately below the one above.

Thanks in advance,
Paul.

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
