### ISSUE TITLE
Cannot select text by double click if parent element for ckeditor is draggable

### ISSUE THREAD

**Issue by r0ss0neri** [ckeditor/ckeditor-dev#1864]
## Are you reporting a feature request or a bug?

Bug

It's not possible to select text by double click if parent element for ckeditor is dragable

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-4/, use Article Editor Tab
2. Find parent element for ckeditor in html tree and make them draggable (add draggable="true")
3. Type any text and try to select by double cklick

### Expected result

Text must be selected

### Actual result

Selection doesn't appear 

## Other details

* Browser: MS EDGE, IE
* CKEditor version: 4.9.1 and earlier 
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Hello,

it's not the CKEditor 4 issue but IE and Edge problem. It has been already reported on [MS Edge Issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10375756/). You will have to follow linked issue for more information about its status.
