### ISSUE TITLE
Set elementspath using plugin lang object

### ISSUE THREAD

**Issue by NathanCH** [ckeditor/ckeditor-dev#1865]
## Details

Hello, I've created a few custom plugins using Widgets for CKEditor. To differentiate our plugins from third-party plugins we decided to namespace each plugin (i.e. company_myPlugin). 

## Problem

Elementspath plugin shows "company_myPlugin" when a Widget is selected. Is there a way to set the elementspath name in my plugin's language object?

I was looking at the ["simplebox"](https://sdk.ckeditor.com/samples/simplebox.html) tutorial example, and I notice the Widget doesn't display in elements path.

I also looked through the source of code of elementspath but sort of lost on how to get this working.

Example:
<img width="758" alt="screen shot 2018-04-05 at 2 45 40 pm" src="https://user-images.githubusercontent.com/1985888/38393599-21f828e2-38e0-11e8-82a4-951781ee9714.png">

## Other details

* Browser: N/A
* OS: N/A
* CKEditor version: 4.6.2
* Installed CKEditor plugins: elementspath, custom

**Comment by mlewand** [comment]
This is exactly what [`widgetDefinition.pathName`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_plugins_widget_definition.html#property-pathName) is used for.
