### ISSUE TITLE
Create an abstract API doc type for DOM rectangle

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#1866]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Some methods in our API are returning objects, similar to DOMRect type.

For instance currently we have [`element.getClientRect()`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dom_element.html#method-getClientRect). Currently we're implementing `range.getClientRects()` (#1499) which will also use it.

The best name for it seems to be `CKEDITOR.dom.rect`. It should be an abstract type.

Based on https://github.com/ckeditor/ckeditor-dev/pull/1627#discussion_r178267720 comment.

**Comment by jacekbogdanski** [comment]
[DOMRect](https://drafts.fxtf.org/geometry-1/#domrect) official docs could be used as an example how to describe this API.

**Comment by mlewand** [comment]
Remember to keep this very, _very_ simple. It's a trivial type, no need to go too crazy about it. 🙂

**Comment by mlewand** [comment]
Closed with #1867.
