### ISSUE TITLE
Issue 1835 doesn't solve issue for CKFinder v2.x

### ISSUE THREAD

**Issue by jonnott** [ckeditor/ckeditor-dev#1869]
## Are you reporting a feature request or a bug?

Bug

Issue 1835 doesn't resolve the issue for CKFinder v2.x, only v3.x .. see comments here:

https://github.com/ckeditor/ckeditor-dev/issues/1835#issuecomment-379395487

**Comment by jswiderski** [comment]
What @jonnott has reported seems to be valid for CKFinder 2.4.2 and below but works fine for CKFinder 2.5 and above including latest CKFinder 2.6.2.

In CKFinder 2.5 the response is JSON however in CKFinder 2.4.2 and below the response is text. Please see attached images. It needs further investigation however it may turn out that JSON requirement will make CKFinder 2.4.2- incompatible with latest CKEditor 4.9.1

![ckf242 headers](https://user-images.githubusercontent.com/5314687/38489257-1afa7afa-3be6-11e8-8019-c0dd049315a3.png)
![ckf242 response](https://user-images.githubusercontent.com/5314687/38489259-1d3a4458-3be6-11e8-9a31-48b47f7efd88.png)


![ckf25 headers](https://user-images.githubusercontent.com/5314687/38489262-20d9d722-3be6-11e8-9b6d-211e7212915c.png)
![ckf25 response](https://user-images.githubusercontent.com/5314687/38489265-22cac8e8-3be6-11e8-9bd5-192e102d11f7.png)

**Comment by mlewand** [comment]
Thanks for the research @jswiderski! Back to the matter: you should upgrade to the latest CKFinder version.

Alternatively if for some reason you really can't upgrade, you can fallback to changing: [`config.filebrowserUploadMethod`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-filebrowserUploadMethod) to `form` value. However you should always work with the latest version of the software.

**Comment by jonnott** [comment]
@mlewand Problem is, with v2.4.2 of CKFinder, the way the license check was done (or the nature of the license itself, I can't remember) changed .. so in order to keep using v2.x, purchasing a new license was needed. This really shouldn't have been the case until v3.x, as it means those with an older license couldn't use > 2.4.0 .. which isn't great.

**Comment by jswiderski** [comment]
@jonnott the configuration option @mlewand has mentioned is for CKEditor and not for CKFinder so using it as shown below:
```
var editor = CKEDITOR.replace( 'editor1', {
	disallowedContent : 'img{width, height}',
	filebrowserUploadMethod : 'form'	
} ); 
CKFinder.setupCKEditor( editor, '../' ) ;
```
should make images work and should not influence license check in any way.

Could you please check if the above is working for you?

**Comment by jonnott** [comment]
Yep, all good now. There should probably be some notes in either one-or-other app's documentation that <code>filebrowserUploadMethod : 'form'</code> is needed for versions of CKFinder prior to 2.5 to work with CKEditor 4.9+..

**Comment by mlewand** [comment]
As mentioned, the workaround has been provided. But remember that CKF 2.4.2 is already 4 years old.

**Comment by jonnott** [comment]
Yes, thanks for the workaround. But the fact there's a workaround possible doesn't mean that the compatibility should not be documented, so that others don't find the same problem..

**Comment by jonnott** [comment]
@mlewand This documentation for CKFinder 2 integration needs updating to specify <code>filebrowserUploadMethod : 'form'</code> is required..

https://docs.ckeditor.com/ckeditor4/latest/guide/dev_ckfinder_integration.html#ckfinder-2
