### ISSUE TITLE
What are the limitations of the demo version?

### ISSUE THREAD

**Issue by it19862** [ckeditor/ckeditor-dev#1871]
CKEditor 4

What are the limitations of the demo version?
I can not understand "ckeditor" paid or free?

**Comment by msamsel** [comment]
Hi @it19862,
please take a look into License FAQ: https://support.ckeditor.com/hc/en-us/sections/115000828829-Licensing-FAQ
In case that you will have additional questions please contact with our support.
GitHub is place for reporting bugs or requesting new features in editor.
