### ISSUE TITLE
Toolbar images are not visible in high contrast mode

### ISSUE THREAD

**Issue by sumit99531** [ckeditor/ckeditor-dev#1874]
Bug: Toolbar images are not visible in high contrast mode

## Provide detailed reproduction steps (if any)

1. Open CKEditor in Edge/IE
2. Switch to high contrast mode (Alt + Shift + Print Scrn in windows) 
3. Observe the CKEditor toolbar

### Expected result

The icons for toolbar buttons(bold, italic, etc) should be properly visible
See the bold icon
![image](https://user-images.githubusercontent.com/11574937/38541257-28867e4a-3cbc-11e8-873b-b0695a21915c.png)

### Actual result

The toolbar icons are not properly visible
![rte_hc](https://user-images.githubusercontent.com/11574937/38541327-60dbf6f8-3cbc-11e8-904e-cfc545ce9cd1.PNG)

## Other details

* Browser: Edge/IE
* OS: Windows 10
* CKEditor version: 4.6.2
* Installed CKEditor plugins: full editor

## Suggestions

Convert all images to svg with fill='currentColor' and use them directly instead of using css to insert them. Even inline svg can work, but never use css to insert images.

**Comment by msamsel** [comment]
Hi @sumit99531,

you need refresh page, because we don't support high contras icon. Those are replaced with labels. Please take a look at below screenshot.
![screen shot 2018-04-10 at 09 38 04](https://user-images.githubusercontent.com/9017322/38542731-ef44bf34-3ca2-11e8-90e9-0bc7e2bb2dc6.png)
