### ISSUE TITLE
Firefox misplaces cursor after certain backspace actions

### ISSUE THREAD

**Issue by Klenkes** [ckeditor/ckeditor-dev#1878]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
1. Type a few words in an empty editor(with Fírefox)
2. SHIFT+ENTER to insert a HTML br and get a new line
3. type a few words in this second line(or add a third line with SHIFT+ENTER)
4. then place the cursor at the start of the second line
5. press backspace!

### Expected result
The two lines should be joined and the cursor should be at the joining position

### Actual result
The two lines are joined BUT the cursor is misplaced further to the begining of the first line. Depends on the amount of words/characters. Doesn't happen in Chrome!

## Other details
* Tested on Firefox Quantum 59.0.2 32Bit and 64Bit on https://ckeditor.com/ckeditor-4/
* OS: at least on Windows7 and 10
* CKEditor version: https://ckeditor.com/ckeditor-4/

**Comment by Comandeer** [comment]
Seems like it's a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1452906
