### ISSUE TITLE
CKEditor Source button - Doesn't load the HTML source or takes indefinite time

### ISSUE THREAD

**Issue by Shashikanth4295** [ckeditor/ckeditor-dev#1879]
## Are you reporting a feature request or a bug?

Functionality issue:

reproduction steps 

1) Go to a page
2) Open CKEditor
3) Click on Source

### Expected result
Should load the HTML code

### Actual result
Doesn't load the HTML source or takes indefinite time

* Browser: Chrome
* OS: Windows 7
* CKEditor version: 4
* Installed CKEditor plugins: unaware

**Comment by jacekbogdanski** [comment]
Hello,

I cannot reproduce your issue. 

If you would like to provide more information about the issue feel free to open a new issue on Github tracker. Doesn't forget to provide sufficient information about an issue so we will able to reproduce it.
