### ISSUE TITLE
is there a way to explicitly set config.allowedContent to automatic mode

### ISSUE THREAD

**Issue by simogeo** [ckeditor/ckeditor-dev#1888]
Im' using Ckeditor 4.7. The question is quite simple 

According to the doc (https://docs.ckeditor.com/ckeditor4/latest/guide/dev_advanced_content_filter.html) automatic mode is set when `config.allowedContent ` is not passed. Id'  like to be able to tell explicitly CKeditor that I want it in automatc mode.

Thanks for your reply,

**Comment by engineering-this** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
Examples:

https://github.com/ckeditor/ckeditor-dev/issues/980
https://github.com/ckeditor/ckeditor-dev/issues/947

**Comment by simogeo** [comment]
Sorry for that, since my issue was not a request nor a bug, I did not filled up anything. I created a new formatted  issue #1891.

Thanks,
