### ISSUE TITLE
is there a way to explicitly set config.allowedContent to automatic mode ?

### ISSUE THREAD

**Issue by simogeo** [ckeditor/ckeditor-dev#1891]
More than a bug or a request, this is a question ...

According to the doc (https://docs.ckeditor.com/ckeditor4/latest/guide/dev_advanced_content_filter.html) automatic mode is set when config.allowedContent is not passed. Id' like to be able to tell explicitly CKeditor that I want it in automatic mode.

## Provide detailed reproduction steps (if any)

1. I'm passing a dynamic value to `config.allowedContent`. 
2.  I'm able to set it to `true` or `false` but ..
3.  ... not able to set it explicitly to "automatic"

### Expected result

Want to be able to set  `config.allowedContent` to automatic Mode **explicitly**.

### Actual result

Testing the syntax : 
 `config.allowedContent = "auto";` does not give any result ....

## Other details

* Browser: any
* OS: ubuntu 16.04
* CKEditor version: 4.73
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
You can force it to be automatic by setting `config.allowedContent = undefined`.

That being said this is a support question, and should be posted on SO. See [SUPPORT.md](https://github.com/ckeditor/ckeditor-dev/blob/master/.github/SUPPORT.md).

**Comment by simogeo** [comment]
thanks
