### ISSUE TITLE
I can't response a window.parent.CKEDITOR.tools.callFunction() vb.net

### ISSUE THREAD

**Issue by SASFMONTOYA** [ckeditor/ckeditor-dev#1894]
## Are you reporting a feature request or a bug?

A bug with the upload images
## Provide detailed reproduction steps (if any)

1. I create a file that contain the code to upload files to the server, I take the example from [here.](https://github.com/AlfonsoML/CKEditorUploader)
2. I change the configuration in the files `config.js`
3. I tried upload a file, in the server all is Okey, the file is charge to my server but when i response to the page, i get this error in the console:

![captura1](https://user-images.githubusercontent.com/22794697/38760231-d8c305aa-3f3f-11e8-90a3-0905bf660df9.JPG)

### Expected result

That the editor take the url that I response and put the image in the editor.

I read [this tutorial](https://www.pluginsforckeditor.com/Tutoriales/86/Subir-ficheros-con-CKEditor/es/n86.aspx)

### Actual result

I get this error:

![captura](https://user-images.githubusercontent.com/22794697/38760364-762de4fe-3f40-11e8-9ab3-0fbe0e02fb83.JPG)

![captura](https://user-images.githubusercontent.com/22794697/38760374-853efe24-3f40-11e8-9085-5b726048df9d.JPG)

![captura1](https://user-images.githubusercontent.com/22794697/38760231-d8c305aa-3f3f-11e8-90a3-0905bf660df9.JPG)

## Other details

* Browser: Chrome 65 & Firefox 59
* OS: Windows 8.1 Pro
* CKEditor version: 4.9.1
* Installed CKEditor plugins: [Enhanced Image](https://ckeditor.com/cke4/addon/image2) and [Office 2013](https://ckeditor.com/cke4/addon/office2013)

* My file `config.js` :
```javascript
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	 config.language = 'es';
	 //config.toolbarCanCollapse = true;
	 config.uiColor = '#FFFFFF';
	 config.height = 500;
	 config.filebrowserUploadUrl = '/Pages/HE/SHE00000/UploadCKEditorFiles.aspx?type=Files';
	 config.filebrowserImageBrowseUrl = '/Pages/HE/SHE00000/UploadCKEditorFiles.aspx?type=Image';
	 config.filebrowserFlashBrowseUrl = '/Pages/HE/SHE00000/UploadCKEditorFiles.aspx?type=Flash';

	 config.toolbarGroups = [
		{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'clipboard', groups: [ 'undo', 'clipboard' ] },
		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ name: 'forms', groups: [ 'forms' ] },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ name: 'links', groups: [ 'links' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		'/',
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'colors', groups: [ 'colors' ] },
		{ name: 'tools', groups: [ 'tools' ] },
		{ name: 'others', groups: [ 'others' ] },
		{ name: 'about', groups: [ 'about' ] }
	];

	config.removeButtons = 'PasteFromWord,Templates,About,Save,Form,Iframe';
};

```

**Comment by wwalc** [comment]
Try changing [config.filebrowserUploadMethod](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-filebrowserUploadMethod) to `form`. 

Starting from CKEditor 4.9.0 all file uploads (including the one initiated by the filebrowser plugin) expect json response similar to this one: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response-file-uploaded-successfully, unless you change the mentioned config option back to `form`.

**Comment by SASFMONTOYA** [comment]
Yes, the solution is that.

I change mi vb.net code for this, in the return.

I create a class:

```vb.net
Public Class responseJSON
        Private _fileName As String
        Private _uploaded As Integer
        Private _url As String

        Public Property fileName() As String
            Get
                Return Me._fileName
            End Get
            Set(ByVal value As String)
                Me._fileName = value
            End Set
        End Property
        Public Property uploaded() As Integer
            Get
                Return Me._uploaded
            End Get
            Set(ByVal value As Integer)
                Me._uploaded = value
            End Set
        End Property
        Public Property url() As String
            Get
                Return Me._url
            End Get
            Set(ByVal value As String)
                Me._url = value
            End Set
        End Property
    End Class
```

```vb.net
 Dim baseUrl As String = "/Images/imagesManual/"
  Dim basePath As String = Server.MapPath("~" & baseUrl)
 ' Done. Now test it!
' No need to modify anything below this line
'----------------------------------------------------
 ' ------------------------
' Input parameters: optional means that you can ignore it, and required means that you
' must use it to provide the data back to CKEditor.
' ------------------------

 ' Optional: instance name (might be used to adjust the server folders for example)
 Dim CKEditor As String = HttpContext.Current.Request("CKEditor")
 ' Required: Function number as indicated by CKEditor.
 Dim funcNum As String = HttpContext.Current.Request("CKEditorFuncNum")
' Optional: To provide localized messages
 Dim langCode As String = HttpContext.Current.Request("langCode")

 ' ------------------------
 ' Data processing
' ------------------------

 Dim total As Integer
     Try
          total = HttpContext.Current.Request.Files.Count
     Catch ex As Exception
           'Return sendError("Error uploading the file")
    End Try

    If (total = 0) Then
        'Return sendError("No file has been sent")
    End If
    If (Not System.IO.Directory.Exists(basePath)) Then
         'Return sendError("basePath folder doesn't exists")
    End If

     'Grab the file name from its fully qualified path at client
    Dim theFile As HttpPostedFile = HttpContext.Current.Request.Files(0)
    Dim strFileName As String = theFile.FileName
       If (strFileName = "") Then
           'Return sendError("File name is empty")
    End If

Dim sFileName As String = System.IO.Path.GetFileName(strFileName)
      If (sFileName.Length > 50) Then
          sFileName = sFileName.Substring(0, 50)
    End If
Dim name As String = System.IO.Path.Combine(basePath, sFileName)
theFile.SaveAs(name)
 Dim url As String = baseUrl + sFileName.Replace("'", "\'")
 ' ------------------------
 ' Write output
' ------------------------
json.fileName = sFileName
 json.uploaded = total
 json.url = url
Response.Write(JsonConvert.SerializeObject(json))
```
I don't know how response error message.

I'll read this page, i hope know how send the message error in the JSON
https://docs.ckeditor.com/ckfinder/ckfinder3-php/commands.html

But the problem with the load images is solved

**Comment by wwalc** [comment]
Here you have the sample json response with an error message:
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response-file-could-not-be-uploaded
and here with files that uploaded correctly:
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response-file-uploaded-successfully

**Comment by SASFMONTOYA** [comment]
@wwalc Thanks, it's all :relaxed:

**Comment by etovar1989** [comment]
Thk, my friend, you saved my ass

**Comment by anhducbkhn** [comment]
> Here you have the sample json response with an error message:
> https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response-file-could-not-be-uploaded
> and here with files that uploaded correctly:
> https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response-file-uploaded-successfully

@wwalc  thanks you!

**Comment by daryoshsetorg** [comment]
in ckeditor file root in config.js file you should have this line in editorConfig like this

CKEDITOR.editorConfig = function( config ) {
	config.filebrowserUploadMethod = 'form';
};
