### ISSUE TITLE
Video added in CKEditor fails to play in fullscreen for Firefox and Edge

### ISSUE THREAD

**Issue by nitish123456** [ckeditor/ckeditor-dev#1900]
## Are you reporting a feature request or a bug?

issue type: Bug 

## Provide detailed reproduction steps (if any)

1.Open CK Editor in Firefox,Edge
2.Add video in the editor,with some overlays on the video
3.Click ion Fullscreen icon.

### Expected result
The video should be played in the fullscreen and the overlays should be visible too.

### Actual result
The video does not play in fullscreen,but overlays on the video get zoomed.

## Other details

* Browser:Edge,Firefox
* OS: Win10
* CKEditor version:4
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
There was no possibility to play video inside editor with default plugins.
