### ISSUE TITLE
Can't open context menu with keyboard shortcut over widget

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1901]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Open editor with some widget
2. Select widget
3. Press <kbd>Shift</kbd>+<kbd>F10</kbd>

### Expected result

Context menu is open as it happen for right mouse button

### Actual result

nothing happen

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.9.2
* Installed CKEditor plugins: full-all

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/92be5c20d911c5126201b0900ddc323310bb0159.
