### ISSUE TITLE
Classic editor does not reposition autocomplete on iOS

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1910]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open [manual test](http://tests.ckeditor.test:1030/tests/plugins/autocomplete/manual/viewposition).
1. Focus the classic editor.
1. Start typing `@` to begin to autocomplete.
1. Scroll the editor editable.

### Expected result

The autocomplete moves along.

### Actual result

Autocomplete remains static.

## Other details

* Browser: iOS
* OS: iOS
* CKEditor version: 4.10.0
* Installed CKEditor plugins: autocomplete

**Comment by jacekbogdanski** [comment]
Above issue have to be fixed by reusing some ugly hack where iframe parent is scrollable, not iframe itself. Please follow https://bugs.webkit.org/show_bug.cgi?id=149264 for more information about issue status.

**Comment by mlewand** [comment]
Closed in #1931.
