### ISSUE TITLE
IE9-11 - setting editor to readOnly mode and pressing Delete throws unspecified error

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1916]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Put attached HTML file on server and run it in a IE9-11 browser. 
**EDIT:** You can also use this [codePen](https://codepen.io/j_swiderski/pen/XqVRxG) if you need online example.
2. Click inside e.g. `Heading 1` and press Delete

[selection_error.zip](https://github.com/ckeditor/ckeditor-dev/files/1938059/selection_error.zip)
### Expected result

Nothing happens

### Actual result

Many [selection-fake-reset](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#selection-fake-reset), [selection-fake-reset](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#selection-fake-reset) and [range-startcontainer](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#range-startcontainer) errors are reported.

Also for IEs: Unspecified error gets thrown in `selection.js` in line `2202`. Code throwing error is `sel.addRange( nativeRange );`

## Other details

According to the reporter:  
> In IE, native selection would throw this error if nativeRange wraps around an invisible node (display: none). 

It might a good tip to investigate.

Please note that problem can be reproduced from CKEditor 4.7.0. so this is rather new issue.

* Browser: IE9-11, Edge
* OS: Windows
* CKEditor version: 4.7.0+
* Installed CKEditor plugins: N/A

**Comment by jswiderski** [comment]
NOTE: In IE9-11 and Edge in CKEditor 4.6.2 and below the backspace button was causing navigation to previous page. This is no longer the case starting from CKEditor 4.7.0. This is something worth taking into account as well.

**Comment by mlewand** [comment]
@ThomasBartelsNOS it took as a little to nail this one 🐛 - but we finally have it.

A fix for this issue is ready and has been merged to our upcoming release. It will be available in 4.10.1.

However you can already see it on [CKEditor preview builds](https://ckeditor4-preview.ckeditor.com/master/samples/).

I have forked the original codepen so that it uses preview CKE4 build here: https://codepen.io/mlewand/pen/rroRGQ

**Comment by ThomasBartelsNOS** [comment]
Great, thanks a lot.
