### ISSUE TITLE
table cursor issue in IE browser

### ISSUE THREAD

**Issue by booracle** [ckeditor/ckeditor-dev#1918]
## Provide detailed reproduction steps (if any)

1. Open up ck-editor sample http://nightly.ckeditor.com/18-04-23-06-04/full/samples/ using IE browser
2. Create a a one row one column table and type in some words under it.
3. Put the cursor inside table.
4. Click on the field under last words

### Expected result
Cursor should be put into last line which contains words like Chrome browser does

### Actual result
Cursor is still in the table and not get out of it.

## Other details

* Browser: IE
* OS:  windows
* CKEditor version: latest version
* Installed CKEditor plugins: no

**Comment by engineering-this** [comment]
Hi
Please provide information on exact version of IE, because we support IE from 8 to 11.

**Comment by booracle** [comment]
I am using 11.0.56, but issue not existed when i upgrade to 11.0.60. Close this issue based on it.
