### ISSUE TITLE
Navigation accessibility issue for VoiceOver rotor users

### ISSUE THREAD

**Issue by adam-bitzesty** [ckeditor/ckeditor-dev#1920]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

Using CKEditor as part of longer form with other simple fields
1. Using VoiceOver, move focus to CKEditor field
2. Attempt to swipe back to previous filed or use form rotor

### Expected result

When focus enters the text field, should be able to swipe backwards or use rotor to return to previous fields or sections

### Actual result

When focus enters the text field, unable to swipe backwards to the previous element or section of the page using swipe gestures or the form rotor

## Other details

* Browser: Safari
* OS: iOS - not sure which version
* CKEditor version: 4.6+
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Sorry but we're not providing [official support for VoiceOver](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_browsers.html#accessibility-support).

Please [contact CKSource](https://ckeditor.com/contact/) to check what possibilities for fixing the issue the extended support can offer.
