### ISSUE TITLE
CKEditor does not work on FireFox

### ISSUE THREAD

**Issue by russia201x** [ckeditor/ckeditor-dev#1921]
## Provide detailed reproduction steps (if any)

1. Just open http://nightly.ckeditor.com/18-04-25-06-04/full/samples/ and check how it works with FireFox (it does not).  

If it makes a difference I am using FF 59.0.2 (64 bit)

### Expected result

CKEditor window.

### Actual result

Nothing.

## Other details

* Browser: FF 59.0.2 (64 bit)
* OS: Win
* CKEditor version: latest night build as well as 4.9.2
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
![image](https://user-images.githubusercontent.com/5353898/39245788-fad7e8b4-4894-11e8-9569-38121ae0918d.png)

WFM

It's very unlikely to CKEditor to ever _not work on Firefox_. Check your proxy, extensions. Might be that some files are blocked by your browser / ISP.
