### ISSUE TITLE
Adding content from source seems to be buggy

### ISSUE THREAD

**Issue by haoyalei** [ckeditor/ckeditor-dev#1928]
The HTML code added from the source code is formatted and the HTML content is modified.

The attribute also has a syntax error, when the foreground style ratio can be controlled.
![39282427-ee3b6430-493b-11e8-8cc9-1363b406f057](https://user-images.githubusercontent.com/15228441/39305840-03447f10-4991-11e8-85a7-fc5dd113f5f5.jpg)

**Comment by haoyalei** [comment]
The HTML code that was written with the markdown was added to the editor source of CKEditor. When the change was made, it was found that the source code was confused and was also formatted.

**Comment by jacekbogdanski** [comment]
I can reproduce the issue. 

## Reproduction steps:

1. Open https://ckeditor.com/latest/samples/
1. Click `Source` button.
1. Paste HTML:
```html
<pre>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</pre>
```
1. Close `Source` mode.
1. Click `Source` mode button again.

## Expected

```HTML
<pre>
&lt;div&gt;1&lt;/div&gt;

&lt;div&gt;2&lt;/div&gt;

&lt;div&gt;3&lt;/div&gt;</pre>
```

## Actual

```HTML
<pre>

&nbsp;</pre>

<div>1</div>

<div>2</div>

<div>3</div>

```

**Comment by jacekbogdanski** [comment]
Afte some digging it looks like `div` element is not allowed as a child of `pre` element.  Content model for `pre` element is `phrasing-content`. In short it allows inline elements, not block like `div`. You can find out more about it by reading W3C specification:

http://w3c.github.io/html/single-page.html#elementdef-pre
http://w3c.github.io/html/single-page.html#phrasing-content-2

You can also validate your HTML using W3C validator to see if it's correct:

https://validator.w3.org/

You can try to setup `CKEDITOR.dtd.pre.div = true` which will force `div` nesting inside `pre` element but it's still a bad idea to create invalid HTML content.
