### ISSUE TITLE
Add caseSensitive option for mentions configuration

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1934]
## Are you reporting a feature request or a bug?

Feature request

Mentions plugin should allow for an additional configuration option i.e. `caseSensitive` to choose between case sensitive/insensitive simple feed matching. You can read more about this issue in `mentions` plugin concept: https://github.com/ckeditor/ckeditor-dev/issues/1703#issuecomment-374188342.

### Expected result

Optional `[caseSensitive=false]` option for `mentions` configuration object.

### Actual result

`mentions` plugin is case sensitive by default. It's not possible to change this behavior except providing different feed.

## Other details

* Browser: any
* OS: any
* CKEditor version: 4.10.0
* Installed CKEditor plugins: mentions

**Comment by mlewand** [comment]
Fixed in #1936.
