### ISSUE TITLE
Align Center Button Removes Previously Prepended Alignment Class

### ISSUE THREAD

**Issue by dorklord23** [ckeditor/ckeditor-dev#1949]
## Are you reporting a feature request or a bug?

A bug

## Provide detailed reproduction steps (if any)
1. I use the following config:

    CKEDITOR.addCss('.align-left{text-align:left}');
    CKEDITOR.addCss('.align-right{text-align:right}');
    CKEDITOR.addCss('.align-center{text-align:center}');
    CKEDITOR.addCss('.align-justify{text-align:justify}');
    CKEDITOR.config.extraPlugins = 'tableresize,colorbutton,colordialog,justify';
    CKEDITOR.config.justifyClasses = ['align-left', 'align-center', 'align-right', 'align-justify'];
    CKEDITOR.replace('editor1');

2. Select a table cell to align

### Expected result

When I click the align center button, `"align-center"` should be prepended to the selected cell's class. 

### Actual result

Clicking the align center button removes the previously prepended alignment class e.g. `class="align-right cke_table-faked-selection"` becomes `class="cke_table-faked-selection"`

## Other details

* Browser: Firefox 59.0.2
* OS: Ubuntu 17.10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Table Resize, Color Button, Color Dialog, Justify
* CKEditor source: https://cdn.ckeditor.com/4.9.2/standard-all/ckeditor.js

**Comment by jacekbogdanski** [comment]
Hello,

I don't have any problems with justify using custom classes. You can see my results on the enclosed gif:

![tablejustify](https://user-images.githubusercontent.com/10279586/39744558-fef7030c-52a4-11e8-9ec8-1ffb035be985.gif)

Also you can use [this codepen](https://codepen.io/jacekbogdanski/pen/bMapVg) to test this case.
