### ISSUE TITLE
Font size plugin applying style despite using classes

### ISSUE THREAD

**Issue by iplukens** [ckeditor/ckeditor-dev#1952]
## Are you reporting a feature request or a bug?
Bug

Despite using classes for font styling, the fontSize plugin will fill in a font-size style.

## Provide detailed reproduction steps (if any)

1. Set up font size to use classes instead of style attribute
```javascript
window.CKEDITOR.config.fontSize_style = {
    element: 'span',
    attributes: {'class': '#(size)'},
    overrides: [{
      element: 'font',
      attributes: {'size': null},
    }],
  };
```
2. Type text in ckeditor
`<p>Hello this is some text</p>`
3. Apply font size to that text
`<p><span class="x-large">Hello this is some text</span></p>`
4. Select the whole text and delete it
5. Start typing new text

### Expected result

*What is the expected result of the above steps?*
The new text will appear in either with no styling or the font-size class `x-large` applied.

### Actual result

*What is the actual result of the above steps?*
The new text appears with a `style: {font-size: ??px}` based on the size attribute.

* Browser: All
* OS: All
* CKEditor version: 4.7.3
* Installed CKEditor plugins: FontSize

**Comment by msamsel** [comment]
Hi @iplukens,
I'm not able to reproduce the issue. Please prepare sample page, where problem will be visible. You can use codepen.io, jsfiddle.net, etc to share such page.

**Comment by iplukens** [comment]
@msamsel Here's a jsfiddle: https://jsfiddle.net/qnLrdoyx/

And gif of the issue: http://recordit.co/Q06wxAQfb9/gif/notify

**Comment by msamsel** [comment]
@iplukens thank you for great example. This help me understand this case.
Unfortunately this behaviour is browser issue not the editor. Where after deleting styled content, webkit browsers replace it with style given by them self. We report this case to browsers' developers around 5 years ago, but still issue is not resolved.
Here you can find reported issue and example with native contenteditable:
* https://bugs.chromium.org/p/chromium/issues/detail?id=226941
* https://bugs.webkit.org/show_bug.cgi?id=114791
* (please look at TC4) https://bug-114791-attachments.webkit.org/attachment.cgi?id=198690
