### ISSUE TITLE
excel copy paste issue

### ISSUE THREAD

**Issue by NetGains8** [ckeditor/ckeditor-dev#1963]
Because of your browser security settings, the editor is not able to access your clipboard data directly. You are required to paste it again in this window.
smartermail version:15.7
* Browser: …chrome(66.),firefox(59),opera(52),uc(7.0)
* OS: …windows 7 64-bit
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
What exactly is your issue? Provide a clear, step by step instruction and expected/actual behavior. This is what the issue template is made for.

**Comment by NetGains8** [comment]
I'm facing issues in copying excel table into ckeditor(SmarterMail).
all borders & formatting are automatically vanished. 
and ehen i use "paste from owrd" add on available there,I'm seeing a dialog box attached here.
![paste from word](https://user-images.githubusercontent.com/39151336/39919836-84ebb252-5532-11e8-896a-ebe9c60c3ec0.PNG)

**Comment by mlewand** [comment]
@NetGains8 does it work for you correctly on this demo: https://sdk.ckeditor.com/samples/pastefromexcel.html?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
