### ISSUE TITLE
After uploading the picture successfully, it did not transform into the real path of the background server. It is still the blob object.Only click the picture to convert it into a real path

### ISSUE THREAD

**Issue by littleQing** [ckeditor/ckeditor-dev#1968]
<textarea name="editor1" style="visibility: hidden; display: none;">
&lt;figure class="easyimage easyimage-full"&gt;&lt;img alt="" src="blob:http://admin.t.youxuan.vding.wang/5341af40-9351-4cb0-a150-e0867856e752" /&gt;&lt;figcaption&gt;&lt;/figcaption&gt;&lt;/figure&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;
</textarea>

<figure class="easyimage cke_widget_element easyimage-full" data-cke-widget-keep-attr="0" data-widget="easyimage" data-cke-widget-data="%7B%22imageClass%22%3A%22easyimage%22%2C%22alt%22%3A%22%22%2C%22src%22%3A%22%22%2C%22caption%22%3A%22%22%2C%22classes%22%3A%7B%22easyimage-full%22%3A1%7D%7D"><img alt="" src="https://file.t.youxuan.vding.wang/source/base/201805/1/6lf64sJ8o6N5U41jPcje3g6akqj1kd-5.jpg" width="1366"><figcaption contenteditable="true" data-cke-widget-editable="caption" data-cke-enter-mode="2" data-cke-filter="480" class="cke_widget_editable" data-cke-caption-hidden="true"><br></figcaption></figure>

****

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by sharifcse57** [comment]
I also having this issue just getting blob image cant get real path.. any idea? i stuck on this because i need actual cloud image path to store in my database.
