### ISSUE TITLE
Image button missing from ckeditor despite being selected in wysiwyg profile.

### ISSUE THREAD

**Issue by purcelltastic** [ckeditor/ckeditor-dev#1974]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. After updating from 4.5.11 to 4.9.2 I don't see the image button on some of my servers when I go to add content (Drupal 7).
2. JS console shows "Error code: cloudservices-no-token-url"

### Expected result

I expect to see the image button included with the other selected ckeditor buttons.

### Actual result

No image button present and JS error. I'm trying to resolve the JS error in the hopes that it is blocking the image button from appearing. I don't wan't to use any cloudservices features, so I'd like to disable cloudserives.

## Other details
I've tried adding "config.removePlugins = 'uploadimage,easyimage,imagebase';" to config.js, but it doesn't seem to change things.

* Browser: chrome, firefox
* OS: Ubuntu, windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
Hi,

Could you give us more detailed information about your CKEditor configuration? It would be even more helpful for us to track and fix the source of bug if you could provide some editor implementation on page like codepen.io or jsfiddle.net in which this problem occurs.

**Comment by purcelltastic** [comment]
Sorry. I had some caching problems that slowed me down in tracking this down. After retesting I found that as long as I replaced the library with one of the packages that didn't include 'Easy Image' I don't get any JS errors and the image button appears.

**Comment by jashalevenson** [comment]
We are also having the issue of the IMCE and image buttons missing from the WYSIWYG, as well as the js errors described above with version 2.9.4. We are not having these issues with 4.4.7
```
                Working           Broken

imce            7.x-1.11          7.x-1.11
imce_wysiwyg    7.x-1.0           7.x-1.0
CKEditor        4.4.7.3a35b3d     4.9.2.95e5d83
wysiwyg         7.x-2.5           7.x-2.5
```

**Comment by engineering-this** [comment]
@jashalevenson To confirm that issue we need to reproduce it on CKEdior configured without third party software. Could you provide sample where issue might be observed? You can use codepen.io or similar page to show the issue.

**Comment by mlewand** [comment]
It sounds like it's an issue in Drupal connector. Please report the issue to Drupal issue tracker as the issue seems not to be related to the CKEditor core itself.
