### ISSUE TITLE
Deleting bullet points with CTRL+A and CTRL+X leaves one bullet point

### ISSUE THREAD

**Issue by WSchulenburg** [ckeditor/ckeditor-dev#1975]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open in Chrome: https://ckeditor.com/ckeditor-4/
2. Enter some text with bullet points: 
![image](https://user-images.githubusercontent.com/37613833/40050390-9e656572-5837-11e8-8da3-239145665887.png)

)
3. Remove the content with CTRL+A and then CTRL+X: 
![image](https://user-images.githubusercontent.com/37613833/40050447-cafef12a-5837-11e8-9132-a2c4e403c452.png)

### Expected result

The whole content is removed

### Actual result

One bullet point is left: 
![image](https://user-images.githubusercontent.com/37613833/40050484-e9f1235a-5837-11e8-94d8-6a56d068c430.png)

## Other details

* Browser: only **Chrome** (now V66) and **Edge**
* OS: Linux / Windows
* CKEditor version: 4.5.9, 4.9.2, **not 5.x (https://ckeditor.com/ckeditor-5-builds/#classic)**
* Installed CKEditor plugins: list-style, page-break

**Comment by jacekbogdanski** [comment]
Hello,

it's not the CKEditor4 issue but an upstream. I already reported the issue on chrome issue tracker. Please, follow up https://bugs.chromium.org/p/chromium/issues/detail?id=844346 issue for information about its status.

**Comment by WSchulenburg** [comment]
Thanks @jacekbogdanski
