### ISSUE TITLE
Script tag gets deleted on backspacing

### ISSUE THREAD

**Issue by dipen10612055** [ckeditor/ckeditor-dev#1979]
## Type of report

Feature request

## Provide detailed reproduction steps (if any)

1. Set the config.allowedContent = true;
2. Type in the content in the source along with the script tag e.g. "Test <script>console.log('sfd');</script><br /> Testing"
3. Navigate to the preview screen and place the cursor next to Test and backspace it to delete the character so that the new word is now "Te".
4. On switching back to the Source, we see that the script tag is deleted.

### Expected result

The script tag should not be deleted on backspacing the content through preview screen.

### Actual result

The script tag gets deleted on backspacing the content through preview screen.

## Other details

* Browser: Chrome, IE, Firefox
* OS: Windows 7 64 bit
* CKEditor version: All the versions
* Installed CKEditor plugins: None

**Comment by engineering-this** [comment]
Hi there,

CKEditor 4 doesn't support script tag at all, so I'm marking this as feature request.

**Comment by mlewand** [comment]
Sorry, but CKEditor is content editor, not a full website creation tool. In that sense we're not looking to support `script` tag.

Any scripting should be done by applying the scripts to the page and not mixing it with the actual contnet.
