### ISSUE TITLE
Lading a large file with lots of math and images

### ISSUE THREAD

**Issue by gopal155** [ckeditor/ckeditor-dev#1980]
## Type of report

Feature request : allow load large file with heavy content(Maths, images and tables)

## Provide description of the new feature
Looking for option to upload large files which is quite heavy. Could it be possible to break files in small chunk and upload subsequently when cursor is moving.

*What is the expected behavior of the proposed feature?*
This will facilitate uploading of large file in web based editor like CKEditor.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
