### ISSUE TITLE
Cut_Copy_Option disabled when selecting text in CK Editor

### ISSUE THREAD

**Issue by Nareshns1987** [ckeditor/ckeditor-dev#1990]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Issue1: . Cut and Copy options are not Available in Chrome browser
![cut_copy_option_disabled_ck_3 6 2editor](https://user-images.githubusercontent.com/39476370/40291257-89d7e928-5ce1-11e8-944a-610a633cdfcf.png)

###Expected result:
The Menu should display properly, with Cut, Copy, Paste and a single instance of Edit Properties

### Actual result:
Cut, Copy options in Menu disabled when selecting any text in side CK editor. 

2. Image properties option is displayed multiple times
![image_properties_repeated](https://user-images.githubusercontent.com/39476370/40291347-11313866-5ce2-11e8-9724-5040872a8680.JPG)

### Actual result:
Image Properties option in menu when selecting any image, displaying multiple times 

###Expected result: Image Properties options should display one time. 

* Browser: … Chrome
* OS: … Windows 8, 10
* CKEditor version: … 3.6.2
* Installed CKEditor plugins: not sure

**Comment by Nareshns1987** [comment]
please provide any solutions to fix other than migrating latest version/release.

**Comment by jacekbogdanski** [comment]
Hello,

It works fine using the latest version of CKEditor4 (4.9.2). We are not providing backward bug fixing so you will have to update CKEditor if you would like to make this feature to work.

**Comment by Nareshns1987** [comment]
Thanks For Response.
