### ISSUE TITLE
Cannot set property 'rawConfig' of undefined

### ISSUE THREAD

**Issue by Marquis-H** [ckeditor/ckeditor-dev#1991]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. open android (UC browser)
2. not show toolbar
3. …

### Expected result

show toolbar

### Actual result

not show toolbar

## Other details

<img width="1915" alt="2018-05-21 6 18 08" src="https://user-images.githubusercontent.com/8198679/40302998-ada517bc-5d23-11e8-9f69-778dd67a9834.png">

* Browser: UC browser
* OS: android
* CKEditor version: 4.0

* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
First of all we do not officially support UC browser, but it looks like configuration issue on your side. Does our sample editor at http://cdn.ckeditor.com/4.9.2/standard/samples/ loads for you correctly?

**Comment by Marquis-H** [comment]
@mlewand thx

**Comment by mlewand** [comment]
I suppose that you were able to confirm that this is some configuration problem. In case you're able to reproduce the issue with our online, unmodified distributions let us know.
