### ISSUE TITLE
Autocomplete plugin requests should be throttled

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1997]
## Type of report

Feature request

## Provide description of the new feature

Throttling feature should be implemented inside `textwatcher` plugin and utilized by `autocomplete` plugin. It should use #1993 function. You can find more details about this issue by reading #1972 ticket and  https://github.com/ckeditor/ckeditor-dev/pull/1983#issuecomment-390646788 comment.

**Comment by mlewand** [comment]
Fixed in #2001.
