### ISSUE TITLE
Names of the CK editor toolbar buttons are missing

### ISSUE THREAD

**Issue by sagar17sep** [ckeditor/ckeditor-dev#1998]
**BUG**

**Provide detailed reproduction steps (if any)**
1. Open CK Editor toolbar using Alt + F10 and navigate to "Insert Toolbar" section.
2. Open Inspect Tool.
3. Navigate to "Image" and "Table" buttons

**Expected result**
The name of the buttons("Image" and "Table") should be present.

**Actual result**
The name of the buttons("Image" and "Table") inside "Insert Toolbar" section are missing. Also, help text (value of title attribute) is inappropriate to describe the context.

**Other details**
Browser: Edge 41.16299.248.0
OS: Windows 10
CKEditor version: 4.6.2
Installed CKEditor plugins:

**Comment by jacekbogdanski** [comment]
Hello,

I'm not sure if I understand you correctly. Are you talking about balloon appearing when you hover button? Or `aria-label` inside button element? In both situations they are present. 

Could you give us more information about your issue?

**Comment by sagar17sep** [comment]
![image](https://user-images.githubusercontent.com/38970470/40957443-e3cd661a-68b2-11e8-88b3-117b05974e48.png)

Could you please look to the above mentioned issue on priority.

**Comment by mlewand** [comment]
@sagar17sep thanks for the report.

After verifying this issue we see that CKEditor already provides sufficient means to hint the button name. This is done by providing `aria-labelledby` and `a[title]` attirbute, so there's more than enough to convey the name. There's no need to add nothing more than that (`a[name]` attribute is deprecated in HTML5).

Below is a summary from Chrome a11y tree:

![inspector accessibility summary, showing proper aria-label for the button](https://user-images.githubusercontent.com/5353898/41295328-970b5dca-6e5a-11e8-88dc-b3d8f711a104.png)

The same in Firefox a11y tree:

![Firefox accessibility tree shows a porper button name](https://user-images.githubusercontent.com/5353898/41296129-8267cc62-6e5c-11e8-93f2-afe527ddfa49.png)

If some tool does not pick it up, it looks like a upstream issue, beyond CKEditor.
