### ISSUE TITLE
Ckeditor adds unnecessary <UL>tags with <li> tags

### ISSUE THREAD

**Issue by sibasishpalo** [ckeditor/ckeditor-dev#2000]
## Type of report

Bug

## Provide detailed reproduction steps 

1. Open [http://nightly.ckeditor.com/18-05-22-06-04/full/samples/](url) in Google chrome and IE both.
2. switch to source mode and paste the content from the attached text file in both the browser. 
3. switch back to edit mode (WYSIWYG mode).
4. in Chrome it renders properly but in IE it adds extra `<ul>` tags to each `<li>` tag (screenshots are attached with the ticket)
5. in Chrome it ends `<li>` properly if it doesn't have an end tag but in IE its adding `<ul>` for each `<li>` tag which is not ended
6. why there is a difference in behavior WRT browsers.
7. how can i mimic the same behavior in IE what we are doing in chrome.

please help on this.

### Expected result

it should render how its rendering the list in chrome

### Actual result

behavior is different

 in IE as compared to chrome

## Other details

* Browser: IE 11
* CKEditor version: provided the link above
* Installed CKEditor plugins: provided the link above

**Text document with the problem content**

[CKEditor_Issue.txt](https://github.com/ckeditor/ckeditor-dev/files/2026877/CKEditor_Issue.txt)

**Below is the screenshot from Chrome**
![image](https://user-images.githubusercontent.com/30113621/40365751-fa704e70-5df2-11e8-9be3-17d9d914c46f.png)

**Below is the screenshot from IE**
![image](https://user-images.githubusercontent.com/30113621/40365817-23afbef6-5df3-11e8-92d9-8bed31a47d95.png)

**Comment by jacekbogdanski** [comment]
Hello,

I don't think it's CKEditor issue. Provided HTML contains invalid elements nesting according to the specification: https://www.w3.org/TR/html52/grouping-content.html#the-ul-element

To be more precise: `ul` elements can contain only `li` elements or script-supporting elements which are `script` and `template`. 

If you delete `span` and `font` tags nested inside `ul` i.e.
```html
<ul>
<!-- remote this lines -->
  <span>
  <font>
<!-- remote this lines -->
 <li>content</li>
</ul>
```
your example HTML will work fine.

**Comment by sibasishpalo** [comment]
Thank you for the reply.

if its not an issue with CKEditor then why there is a difference in behavior in Chrome and IE??

How Chrome is able to handle the same content graciously.

Please help.
