### ISSUE TITLE
Firefox: Right-clicking on multiple selected cells containing empty paragraphs removes the selection

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2003]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. Paste below table with paragraphs in Firefox into https://sdk.ckeditor.com/samples/table.html
`<table style="width:500px"><tbody><tr><td><p>&nbsp;</p></td><td><p>&nbsp;</p></td></tr><tr><td><p>&nbsp;</p></td><td><p>&nbsp;</p></td></tr></tbody></table>`
2. Select all cells
3. Right-click on one of cells, select Cell Properties and apply Blue background.

### Expected result

Selection stays and background gets applied to all cells.

### Actual result

Selection disappears and background gets applied only to right-clicked cell.

## Other details

Problem can only be reproduced in Firefox (both standard and ESR) but only when table contains empty paragraphs and right-click is performed on a cell with the empty paragraph. 

If table doesn't contain empty paragraphs or right-click is performed on a cell with non-empty paragraph everything works as expected. Also by default the table inserted through toolbar button has no paragraphs so the problem doesn't occur there as well. 

* Browser: Firefox 
* OS: Windows
* CKEditor version: 4.9.2
* Installed CKEditor plugins: table, tableselection

**Comment by engineering-this** [comment]
After digging around:

Browsers I tested (including Firefox on MacOS) fire event `contextmenu` right after `mousedown`. However on Windows Firefox fires `contextmenu` after `mouseup`, and it changes selection between `mousedown` and `mouseup`. I'd propose to store selection when `evt.data.$.button == 2` (which should refer to right click). And at this point add listener `once( 'mouseup'...` and restore selection.
