### ISSUE TITLE
Strange behavior when user inputs "<sometexthere>" in ckeditor, data is sent to the server, and rewriten in ckeditor

### ISSUE THREAD

**Issue by NicolasCast** [ckeditor/ckeditor-dev#2005]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

ckeditor handles text between char '<' and '>' (less than / more than signs) strangely.

CASE 1

1. setup ckeditor 5 on a textframe inside a html form
2. in ckeditor, the user write :
> <script>
3. send the data to the server (POST method)
4. print the received POST data in the same textframe (where ckeditor acts), without any modification

CASE 2

1. setup ckeditor 5 on a textframe inside a html form
2. in ckeditor, the user write :
> \<blablahello\>
3. send the data to the server (POST method)
4. print the received POST data in the same textframe (where ckeditor acts), without any modification

### Expected result

CASE 1

ckeditor should display :
> <script>

CASE 2

ckeditor should display :
> \<blablahello\>

### Actual result

CASE 1

ckeditor displays :
> \<\p\>

CASE 2

ckeditor displays nothing (empty)

## Other details

* Browser: Firefox 60.0.1 quantom
* OS: windows
* CKEditor version: CKEditor 5 classic editor build v10.0.0
* Installed CKEditor plugins: none

**Comment by msamsel** [comment]
Hi @NicolasCast,
this repository it's dedicated to CKEditor4. Please report issues related to CKEditor5 here: https://github.com/ckeditor/ckeditor5/issues/new
