### ISSUE TITLE
The selection is lost after copying a text in the read-only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2016]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Connect an external keyboard to iPad.
1. Open the editor in the read-only mode.
1. Tap some word and hold for a while, until text gets selected.
1. Press some key on the keyboard (the copy button should become enabled).
1. Tap the copy button (it should be quick, without holding).

### Expected result

The selection is preserved.

### Actual result

The selection is lost and the browser notification about copying has appeared.

## Other details

If you repeat steps 2, 3 and 4, then do a `force tap` (tap and hold for a while), the selection would be preserved and there would be no notification.

I've checked it with previous versions and this issue exists for a long time. It occurs on `4.3.2` (last version available via CDN).

* Browser: Safari
* OS: iOS 11.3
* CKEditor version: 4.9.2

**Comment by jswiderski** [comment]
Sample file used for testing: [selection_lost.zip](https://github.com/ckeditor/ckeditor-dev/files/2044451/selection_lost.zip)

**Comment by jacekbogdanski** [comment]
The issue is iOS upstream. When using `contenteditable=false` native `document.getSelection()` function doesn't contain information about selected text. 

I already reported the issue on WebKit issue tracker. You can find the current status of the issue visiting: https://bugs.webkit.org/show_bug.cgi?id=186347

**Comment by mlewand** [comment]
Thanks for clarification on that @jacekbogdanski!
