### ISSUE TITLE
Paste From Word only works in Chrome if you click the button

### ISSUE THREAD

**Issue by renatop7** [ckeditor/ckeditor-dev#2025]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Copy word document with stylings
2. Try to paste it into editor using Chrome
3. Text is unformatted
4. Click on the button "Paste from word"
5. Alert "Your browser doesn‘t support pasting with the toolbar button or context menu option." appears.
6. Paste it again, text has stylings.

### Expected result

If you use Firefox you get the full styling by simply pasting the first time, you don't have to click on the button.

### Actual result

Unformatted text on first paste.

## Other details

* Browser: Chrome
* OS: All
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Full - Using Divarea

**Comment by renatop7** [comment]
@engineering-this 
https://codepen.io/renatop7/pen/LrpEbL

And here is an example of the bug (even on Firefox is not working 100%):
![ckeditor](https://user-images.githubusercontent.com/4468986/40864977-7861aa82-65cc-11e8-9824-5573de70c992.gif)

**Comment by engineering-this** [comment]
`Paste From Word` plugin works only for Microsoft Word. You are trying to paste from Google docs on your gif. That is not supported yet by our editor.
