### ISSUE TITLE
Use autocomplete output template in emoji plugin - refactoring

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2032]
## Type of report

Task

## Provide description of the task

* Refactor code inside emoji responsible for output template. https://github.com/ckeditor/ckeditor-dev/pull/2006#discussion_r191233675
https://github.com/ckeditor/ckeditor-dev/blob/294c5d3da4153faedbfc429579d62648f87a9e7d/plugins/emoji/plugin.js#L32-L35

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Closed by #2071.
