### ISSUE TITLE
Pasting hebrew with english incorrectly pastes the content in the editor

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#2033]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Paste this right aligned mixed content(english +hebrew) in the editor. Attaching the screenshot as the content is getting flipped here as well. 
2. The content gets incorrectly pasted and flipped.

### Expected result
The content gets pasted correctly.

### Actual result
The order of content gets disturbed. So the last word now appears first and the first two words appear after the English word.
## Other details

* Browser: All
* OS: All
* CKEditor version: 4.9.2
* Installed CKEditor plugins:default plugins + tableresize, justify, indentblock
![capture](https://user-images.githubusercontent.com/18426614/40677724-4d118faa-6333-11e8-981c-11193f7044a8.PNG)

**Comment by msamsel** [comment]
Changing alignment does not force block to be considered as right to left text.
Do you use configuration option to switch editor to `right to left` mode?
https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsLangDirection
Alternatively you can also change style to `Language: RTL`, so given block will get right to left direction.

If it's not problem of your editor's configuration, then please provide sample where issue might be observed. You can use codepen.io or similar page to show the issue.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
