### ISSUE TITLE
Mentions dropdown doesn't show up after activating styling

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2038]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open the editor with `mentions` plugin.
2. Change the font family/font style/activate bold or italic.
3. Press <kbd>@</kbd> to activate mentions dropdown.

### Expected result

The dropdown appears.

### Actual result

The dropdown doesn't appear. It will show up if you type something, then delete.

## Other details
**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/40712699-9a3f97b0-63fe-11e8-9f48-a6843f859fcc.gif)

* Browser: Chrome, Safari, Opera
* OS: All platforms

**Comment by jacekbogdanski** [comment]
This issue was resolved with #2041 in 4.10.0 release.
