### ISSUE TITLE
Image inserted twice in copy paste from Word, Pages, Paint

### ISSUE THREAD

**Issue by shystruk** [ckeditor/ckeditor-dev#2040]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

In Firefox when you copy and past image, I see two POST requests (filebrowserImageUploadUrl).

### Expected result

*What is the expected result of the above steps?*
One image should be displayed

### Actual result

*What is the actual result of the above steps?*
Two images displayed

## Other details

* Browser: Firefox
* OS: any
* CKEditor version: 4.7.3
* Installed CKEditor plugins: extraPlugins: 'youtube,kalink,c_maximize,sourcedialog,simpleuploads',

**Comment by jacekbogdanski** [comment]
Hello,

I wasn't able to reproduce your issue using [Enhanced Image Plugin](https://sdk.ckeditor.com/samples/image2.html) with CKEditor `4.9.2`. Could you check if your issue exists after CKEditor upgrade?

**Comment by mlewand** [comment]
I recall an issue like that in the past. @shystruk make sure to give a try with the latest release of CKEditor and confirm whether the issue persists.

**Comment by shystruk** [comment]
New version resolved this issue.
Thanks!
