### ISSUE TITLE
Uploads and base64 conversion won't work when only an image is pasted from MS Word

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2044]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create word document with an image and optionally some text
2. Open editor sample in Edge browser 
3. Copy only an image in MS Word document
4. TRy pasting that image into CKEditor with `Ctrl+V`

### Expected result

Image gets pasted and converted into base64 string or uploaded depending on the setup.

### Actual result

Nothing happens in Office 365.
In Office 2010 either nothing happens or local image path is used.

## Other details

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: pastefromword

Screen Cast:
[Edge.zip](https://github.com/ckeditor/ckeditor-dev/files/2061977/Edge.zip)

**Comment by mlewand** [comment]
In that case the proper solution is to add a proper image upload plugin, such as [Easy Image](https://ckeditor.com/cke4/addon/easyimage) or [Image Upload](https://ckeditor.com/cke4/addon/uploadimage) + [Image](https://ckeditor.com/cke4/addon/image) plugin.
