### ISSUE TITLE
Reuse code in tools.throttle and tools.eventsBuffer

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2045]
## Type of report

Task

## Provide description of the task

In #1993 we added throttling function, however it introduced some copy'n'pasted code as mentioned in review comment https://github.com/ckeditor/ckeditor-dev/pull/1996#pullrequestreview-124055850.

The code should be reused.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.10.0

**Comment by jacekbogdanski** [comment]
Closed by #2060.
