### ISSUE TITLE
Bump SCAYT/WSC plugins

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2050]
## Type of report

Feature request

## Provide description of the new feature

WebSpellChecker team released new version of [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/tree/release.5.0.0.4) and [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc/tree/release.5.0.0.4) plugins, both marked as 5.0.0.4 release.

Let's verify that it can be safely included with 4.10.0 release and preset these libraries in the presets.

**Comment by mlewand** [comment]
Plugins were bumped in presets, however we still need changelog entry that gives a summary of changes.

**Comment by mlewand** [comment]
Got yesterday a message from WSC team that `ckeditor-plugin-wsc` @ `5.0.1.1` was just released, which included a fix for issue reported by @msamsel. Let's update presets to include that version instead of `5.0.1`

**Comment by msamsel** [comment]
@mlewand updated branch in presets:
`ckeditor/ckeditor-presets#wsc-test-env-5.0.1`
