### ISSUE TITLE
npm install the full version

### ISSUE THREAD

**Issue by zhupp034** [ckeditor/ckeditor-dev#2053]
I need to npm install the full version of rich text, but you don't provide it now

**Comment by msamsel** [comment]
There is plenty of options to install CKEditor. I assume, you already found those information, but I'd like to mention them in case that someone will found this issue in the future.
- https://docs.ckeditor.com/ckeditor4/latest/guide/dev_best_practices.html#installation
- https://docs.ckeditor.com/ckeditor4/latest/guide/dev_package_managers.html#npm

There exists a little bit tricky way to install full version. If you look closer in npm we're using this repository to publish releases: https://github.com/ckeditor/ckeditor-releases. Inside this repository you can find branches with `full` and `basic` versions of builded CKEditor4. What you can do is to install dependancy of this repository with specific branch like `full/latest` or `full/stable` (e.g: `npm i ckeditor/ckeditor-releases#full/latest --save`)

**Comment by davdenic** [comment]
> That is the command I was looking for!

> In the documentation write it you should! 

Thank you :)
