### ISSUE TITLE
Failing tests in /tests/plugins/easyimage/uploadintegrations

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2057]
## Type of report

Failing test

## Provide description of the task

http://ckeditor.test:1030/tests/plugins/easyimage/uploadintegrations

## Other details

* Browser: Edge 42
* OS: Windows 10

![screen shot 2018-06-06 at 14 13 46](https://user-images.githubusercontent.com/23366849/41037733-6b453708-6994-11e8-8a36-303ee4a136e1.png)

**Comment by jacekbogdanski** [comment]
Tests seem to be failing again for the newer Edge browser.

![image](https://user-images.githubusercontent.com/10279586/59696734-d7c78f80-91ec-11e9-9569-d34ed68651b2.png)

**Comment by f1ames** [comment]
It also fails on `4.11.4` version (build only) which means it may be caused by Edge update (from version `17` to `18`).

**Comment by engineering-this** [comment]
In Edge 18 I have different TC failing.
![Screenshot 2019-07-01 at 11 15 53](https://user-images.githubusercontent.com/23366849/60424899-a3db6980-9bf1-11e9-9183-53a545249af4.png)
