### ISSUE TITLE
Selecting text in Android is impossible

### ISSUE THREAD

**Issue by hughpearse** [ckeditor/ckeditor-dev#2058]
Steps to reproduce:
Use the ckeditor in Android. Select a large block of text using your finger. (Note: If you use a computer mouse with an Android emulator you may not be able to reproduce the defect).

Problem:
The copy/paste popup keeps appearing before more than 1 word can be selected.

Expected result:
Multiple adjacent words can be selected at a time on Android.

https://imgur.com/a/DaQbqpP

**Comment by jacekbogdanski** [comment]
Duplicate of #1743.
