### ISSUE TITLE
CKEditor some characters will get an extra question mark after it

### ISSUE THREAD

**Issue by lavenderchih** [ckeditor/ckeditor-dev#2068]
When use the toolbar functions that comes with CKEditor ,such as Bold, underline, Italic, or press ctrl + enter to shorten the space between lines, then save my html back to Database.

when I reopen the ckeditor again , some characters will some how get an extra question mark after it.

Then i look back to the Data base, i noticed that it get an extra dot for the character. as attachment shown below.

i am using UTF-8 edcoding as well. that is why i am very curious about this issue.

![1528424662279](https://user-images.githubusercontent.com/34846507/41208806-58ec42e0-6d59-11e8-99f9-beba7abef2dc.jpg)
![1528424579423](https://user-images.githubusercontent.com/34846507/41208809-59876694-6d59-11e8-94b9-2981b1aff9b4.jpg)
![1528424750175](https://user-images.githubusercontent.com/34846507/41208808-595bae46-6d59-11e8-8717-b76fceeaee89.jpg)
![1528424726782](https://user-images.githubusercontent.com/34846507/41208807-5914292c-6d59-11e8-8b48-b6a1766a5c34.jpg)

**Comment by jswiderski** [comment]
As we have already explained in private ticket, CKEditor is JavaScript application and it has nothing to do with saving data. Please check the encoding across your application. The UTF-8 should be used everywhere - HTML pages, data bases and server-side code (some streams or readers use encoding so it is important to make sure it is set to UTF-8 as well).
