### ISSUE TITLE
Cell properties dialog has locked height unit type

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2084]
## Type of report

New Feature

## Provide detailed reproduction steps (if any)

1. Open http://cdn.ckeditor.com/4.9.2/full-all/samples/index.html
2. Clear editor contents and create a new table.
3. Open context menu and choose cell properties.

### Expected result

Cell height can be changed from pixels to percentage unit.

### Actual result

Cell height unit is text instead of a select.

## Other details

* CKEditor version: 4.9.2
* Installed CKEditor plugins: tabletools
![screen shot 2018-06-13 at 16 58 05](https://user-images.githubusercontent.com/23366849/41359553-098cd18c-6f2b-11e8-871b-efac82a432f4.png)

**Comment by mlewand** [comment]
Changed type to a feature request.
