### ISSUE TITLE
Failing test on built editor: tests/plugins/autolink/autolink

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2093]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run test on built editor: tests/plugins/autolink/autolink

### Expected result

test pass

### Actual result

test fails
![screen shot 2018-06-15 at 14 24 01](https://user-images.githubusercontent.com/9017322/41467704-c99091f8-70a7-11e8-83d8-a3b7e38cfa12.png)

## Other details

* Browser: Chrome, Firefox
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
IE 10
