### ISSUE TITLE
Autocomplete cannot be initialise before instance ready

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2114]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Try to initialise autocomplete plugin during `loaded` stage of editor.

### Expected result

Possibility to initialise autocomplete regardless o editor status.

### Actual result

Error is thrown, because `editable` doesn't exist yet.
https://github.com/ckeditor/ckeditor-dev/blob/c39b0e2e2bcec87109caa79bcc2ac65bfd9bbfb7/plugins/autocomplete/plugin.js#L248-L249

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: autocomplete

**Comment by mlewand** [comment]
Fixed in #2118.
