### ISSUE TITLE
SCAYT or WSC polluting global page styles

### ISSUE THREAD

**Issue by deant** [ckeditor/ckeditor-dev#2147]
## Type of report

**Bug**:

I am observing that CKeditor is inserting the following line at the bottom of my page's `<head>`:

```
<link rel="stylesheet" type="text/css" href="http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/themes/classic-blue/all.css">
```

This would be bad enough given the potential for style definitions from this file to clash with my own (for example, this file defines rules for `.more-list`, `.button-holder`, `.i-icon`, and other such classnames that are not too unlikely to be used elsewhere), but it also defines the top-level tag rules:

```
textarea,input {
 font-family:inherit;
 font-size:inherit;
 line-height:inherit
}
```

Which are changing the appearance of all the input boxes on my page!
I'm not sure since when this behavior started...

## Provide detailed reproduction steps (if any)

1. Add a CKeditor instance to your page, which includes the WSC and SCAYT plugins.
2. Add a `<textarea>` or `<input>` to the page, unrelated to the CKeditor instance.
3. In my case, I load the page in an `<iframe>` contained in another page (not sure if this is important or not...).
3. Observe that after a brief delay (after CKeditor finishes loading), the `<textarea>` and `<input>` get re-styled. (Specifically, the size of the text changes).

### Expected result

CKeditor should **NOT** be adding stylesheets to the main page `<head>`, or if it does they should only include rules that are scoped using very unique id or classname selectors, unlikely to clash with anything else defined elsewhere.
...More likely, I expect this stylesheet is _supposed_ to be inserted into the CKeditor `<iframe>`, rather than into the containing page?  Note that this needs to work correctly even if the containing page is itself inside an `<iframe>` (as it is in my case).

### Actual result

_Styles are applied to page elements outside of the CKeditor!_

## Other details

* Browser:  **Firefox v60 x64**
* OS:  **Windows 10 x64**
* CKEditor version:  **4.6.2**
* Installed CKEditor plugins:  **a11yhelp, autogrow, basicstyles, blockquote, button, clipboard, colorbutton, colordialog, contextmenu, dialog, dialogui, elementspath, enterkey, entities, fakeobjects, filebrowser, find, floatingspace, floatpanel, font, format, horizontalrule, htmlwriter, image, imagebrowser, indent, indentblock, indentlist, justify, lineheight, link, list, listblock, liststyle, magicline, maximize, menu, menubutton, nbsp, noabp, onchange, panel, panelbutton, pastefromword, pastetext, popup, removeformat, resize, richcombo, scayt, selectall, showblocks, showborders, sourcearea, specialchar, symbol, tab, table, tableresize, tabletools, textselection, toolbar, undo, wsc, wysiwygarea**

**Comment by jacekbogdanski** [comment]
Both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization. Please the report ticket directly in or [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.

**Comment by mlewand** [comment]
This is actually a serious thing. Though it's an upstream we need to keep track of that, as most of our presets do include SCAYT and we want to make sure that it does not cause issues like that.

The class names that the OP referenced are in fact very likely to clash, so they should be reasonably prefixed.

**Comment by deant** [comment]
I've reposted this on the SCAYT repository issue tracker as [bug #159](https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/159).
(I'm assuming it's SCAYT and not WSC just from the URL of the included CSS file, but I could be wrong about that).

**Comment by mlewand** [comment]
@deant it does look that it's a SCAYT part, so you should be correct with that.

**Comment by mlewand** [comment]
SCAYT team closed the issue, and from what I can see the issue has been mitigated by prefixing selectors with `sc-`, so there's `.sc-more-list`, `.sc-button-holder` etc.

The fix was applied to static files served from SCAYT servers, so there's no need to update on CKE side.
