### ISSUE TITLE
Telephone link type support in the Link plugin

### ISSUE THREAD

**Issue by Kwadz** [ckeditor/ckeditor-dev#2154]
## Type of report

Feature request

## Provide description of the new feature

We should be able to select a telephone link type (`<a href="tel:`) in addition to the mail link type with the [Link plugin](https://ckeditor.com/cke4/addon/link).

**Comment by mlewand** [comment]
I'd like to see a semantically correct field being used for that field, so `input[type=tel]` makes the most sense here.

I don't think there should be a validation by default, but it would be nice if we'd expose an optional config option for a valid phone regexp.

The telephone type should be added as an option to the "Link Type" dropdown. There's no need to add it as  an extra protocol in the "URL" type.

**Comment by mlewand** [comment]
Note that the feature has landed on the `major` branch.

If you'd like to see it in action today, you can check [our `major` branch preview sample](https://ckeditor4-preview.ckeditor.com/major/samples/index.html) in a true early adopter fashion 🙂
