### ISSUE TITLE
Text with a '@' becomes a link while using mentions

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2160]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open `tests/plugins/autocomplete/manual/viewstart#child`.
1. Put the caret at the end of the text.
1. Type `@foo` and press <kbd>Spacebar</kbd>.

### Expected result

Autolinking doesn't activate.

### Actual result

Autolinking has been activated.

## Other details
**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/41849159-3c0ea226-7880-11e8-99b1-857d130c695a.gif)

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.10.0

**Comment by jacekbogdanski** [comment]
It looks more like you are using `autolink` with email support. Manual tests for `autocomplete` doesn't have a very advanced `textTestCallback` function implementation. It allows starting `autocomplete` in the middle of the word and it's not an issue (although it could be fixed for manual tests). 

Of course, this behavior is not accepted in `mentions` plugin.

**Comment by Mgsy** [comment]
After a talk with @jacekbogdanski, we agreed that it's not a bug and it works fine with the mentions.
