### ISSUE TITLE
Highlighting Placeholders using latest CKEditor and Placeholders causing chrome to crash

### ISSUE THREAD

**Issue by wesme1337** [ckeditor/ckeditor-dev#2166]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Insert a placeholder into the latest version of ckeditor
2. Verify the placeholder tag has no characters after (markup is ok)
3. Click outside of ckeditor to set the editor to not the active element
4. Click and drag to highlight the placeholder

### Expected result

Browser doesnt crash

### Actual result

Browser crashes with no error details. 

## Other details

Here is a video example of the issue: 
https://drive.google.com/file/d/1LRw_2rUp9aecGRbEOeV8AYRrAHuCV3kL/view?usp=sharing

This bug can be replicated by using the demo:
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_placeholder.html

* Browser: Chrome 67.0.3396.87 and Chrome Canary Build Version 69.0.3472.0
* OS: MacOS 10.12.6
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Placeholder and default plugins

**Comment by mlewand** [comment]
Interesting, I can reproduce the issue with both stable Chrome and Canary on Windows too.

**Comment by engineering-this** [comment]
Hi,

I have reproduced it in plain html and reported to Chrome, hence I'm labelling this as an upstream:

https://bugs.chromium.org/p/chromium/issues/detail?id=859098

Problem occurs with `<span contenteditable="false">` inside editable which is inside iframe.
