### ISSUE TITLE
Emoji matching should be case insensitive

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2167]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Emoji matching should be case insensitive.

ATM there are some emojis like `:OK_hand:`, and since there is no case insenstivity, typing `:ok_` will not match this emoji.

![Matches for `:OK_` phrase](https://i.imgur.com/izHih9d.png)

![No matches for lowercased `:ok_` phrase](https://i.imgur.com/pTutIrY.png)

### Expected result

Matches should be case insensitive.

### Actual result

Letter casing matters.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.10.0
* Installed CKEditor plugins: emoji

**Comment by samwebstudio** [comment]
The same problem occurred with me..

**Comment by samwebstudio** [comment]
I can resolve with the problem just visit [website designing company](

https://www.samwebstudio.com/services/web-designing
--


)
https://www.samwebstudio.com/services/web-designing
--


)
https://www.samwebstudio.com/services/web-designing
--


)

**Comment by samwebstudio** [comment]
I can resolve this problem, I have 4+ year of experience in [website designing & development](https://www.samwebstudio.com)
