### ISSUE TITLE
MS Edge 17 - paste image from another tab causes TypeError for isBlock

### ISSUE THREAD

**Issue by kylane** [ckeditor/ckeditor-dev#2169]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using CKEditor build 4.9.2 in a React project in Microsoft Edge 17
2. Copy an image from another tab within Edge
3. Paste image into the CKEditor

### Expected result

No console error.

### Actual result

Console error: Unable to get property 'isBlock' of undefined or null reference

## Other details

* Browser: Microsoft Edge 17
* OS: Win10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: clipboard, dialog, specialchar

**Comment by jacekbogdanski** [comment]
Hello,

I can reproduce the issue. It seems to work natively so it's not an Edge upstream.

**Comment by kylane** [comment]
Thanks @jacekbogdanski!

More to this issue - after using a clipboard viewer, edge seems to copy a bunch of wacky (word-like) tags - and adding the pasteFilter: 'semantic-content' seemed to filter out most of that junk before being handed to the ACF - which then did its thing correctly. I note that its on by default for CH and FF, but not MS* - but specifically setting it seemed to fix my issue above.
