### ISSUE TITLE
Can't scroll the editor after opening the autocomplete dropdown

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2171]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open the `tests/plugins/autocomplete/manual/viewposition` test.
2. Follow the scenario.

### Expected result

It works as described in `expected` section.

### Actual result

The editor scrolls up after opening the autocomplete dropdown and can't be scrolled down.

## Other details

* Browser: Safari
* OS: iOS 11.4
* CKEditor version: 4.10.0

**Comment by jacekbogdanski** [comment]
Duplicate of #1926
