### ISSUE TITLE
Improve emoji names

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2175]
## Type of report

Task

## Provide description of the task

Improve emoji names, to be lowercase

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Actually it's very similar, but the scope of this issue is to modify `json` file so that it includes only lowercased identifiers. The other issue is more generic and requires full case insensitivity.
