### ISSUE TITLE
Emoji plugin should support keywords

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2181]
## Type of report

Feature request

## Provide description of the new feature

Open sample with Emoji plugin.
Start typing `:smile`

### Expected

`slightly_smiling_face` emoji is being matched too

### Actual

`slightly_smiling_face` emoji is not matched

### Additional Details

[Unicode](https://unicode.org/emoji/charts/emoji-list.html) specifies keywords associated with each smiley, that increases the likelihood of matching given emoji. We should add a support for that too.

**Comment by wwalc** [comment]
Note:  keywords should have higher priority than CLDR. So first display all emojis that match keywords, then look for CLDR matches.

**Comment by mlewand** [comment]
Closed by #2461.
