### ISSUE TITLE
Allow adding custom CSS to editor context menu

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2202]
## Type of report

Feature request

## Provide description of the new feature

Contents of editor menus, including context menu are being displayed inside an iframe. For context menu only `editor.css` file is being attached. 

Two approaches can be used here:
1. Attach` contents.css` to context menu iframe just like it is being done for dropdowns.
2. Add configuration setting for specifying path to custom CSS file for editor context menu.

From what I have checked, the whole logic works in the following way:
1. Everything starts with panel prototype using CSS: 
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/panel/plugin.js#L114-L117

2. That CSS gets inserted into array which later gest inserted into iframe: 
https://github.com/ckeditor/ckeditor-dev/blob/major/core/tools.js#L346-L360
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/panel/plugin.js#L75-L80
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/panel/plugin.js#L114-L117

3. Context menu plugin is based on general Menu plugin which uses panel mentioned in point 1 to specify its own CSS: 
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/menu/plugin.js#L163
for which path is calculated based on getCssPath method:
https://github.com/ckeditor/ckeditor-dev/blob/major/core/skin.js#L137-L163

It seems to me that the best place for inserting new CSS would be here:
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/menu/plugin.js#L163
We could create a new configuration setting which would get read there.

**Comment by jacekbogdanski** [comment]
Actually, this feature request seems much easier to implement than digging so deep into `contextmenu` dependencies. It just requires passing additional parameter into [context menu base constructor call](https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/contextmenu/plugin.js#L31). I will create following PR with an improvement.
