### ISSUE TITLE
ckeditor.js:formatted:830 Uncaught TypeError: Cannot read property '224' of undefined

### ISSUE THREAD

**Issue by hkakumanu-ttc** [ckeditor/ckeditor-dev#2212]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.Updated CKEditor to 4.10 
2. …
3. …

### Expected result

*What is the expected result of the above steps?*
Should load CKEditor normally
### Actual result

*What is the actual result of the above steps?*
I am getting error in console with CKEditor
![screen shot 2018-07-09 at 10 58 14 am](https://user-images.githubusercontent.com/35239157/42467606-352c94b2-8367-11e8-8583-ddeae42f6995.png)

## Other details

* Browser:Chrome
* OS:Mac
* CKEditor version:4.10
* Installed CKEditor plugins:   config.plugins = 'a11yhelp,' +
  'ttc_link,' +
  'basicstyles,' +
  'bidi,' +
  'button,' +
  'clipboard,' +
  'colorbutton,' +
  'colordialog,' +
  'copyformatting,' +
  'contextmenu,' +
  'dialogadvtab,' +
  'elementspath,' +
  'enterkey,' +
  'entities,' +
  'font,' +
  'format,' +
  'horizontalrule,' +
  'indent,' +
  'justify,' +
  'list,' +
  'liststyle,' +
  'maximize,' +
  'pastefromword,' +
  'pastetext,' +
  'popup,' +
  'removeformat,' +
  'resize,' +
  'sourcearea,' +
  'specialchar,' +
  'table,' +
  'tabletools,' +
  'tab,' +
  'toolbar,' +
  'undo,' +
  'wysiwygarea,' +
  'wsc';

**Comment by mlewand** [comment]
I can't reproduce this issue. It doesn't happen on our demos, nor with vanilla clean CKEditor with all the listed plugins **except** `ttc_link`.

Does the error occur if you disable `ttc_link` plugin?

**Comment by hkakumanu-ttc** [comment]
@mlewand Yes I can reproduce it after removing ttc_link

**Comment by mlewand** [comment]
@hkakumanu-ttc and can you tell if you reproduce the issue using the link I have provided in my previous comment? If not it looks to me like you might have a corrupted download, in which case replacing the editor with freshly downloaded copy should do the trick.

**Comment by hkakumanu-ttc** [comment]
This occurred using the source code directly instead of optimized code. Not sure why it happened and couldn't reproduce that in your Codepen. Thanks for following up
