### ISSUE TITLE
'Permission Denied' error in Firefox when using divarea plugin

### ISSUE THREAD

**Issue by rconn3** [ckeditor/ckeditor-dev#2216]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
Fiddle: https://jsfiddle.net/rcconner/yfgLq3e8/
1. Focus into the number input area
2. Notice the error in the javascript console

### Expected result
No Error

### Actual result

Error: Permission denied to access property "nodeType"[Learn More] ckeditor.js:64:260
CKEDITOR.dom.node
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:64:260
CKEDITOR.dom.selection
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:425:36
CKEDITOR.editor.prototype.getSelection
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:422:238
g
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:1148:292
e
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:10:68
CKEDITOR.event.prototype</<.fire</<
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:11:428
a/<
https://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:60:498

## Other details
* Browser: Firefox
* OS: All
* CKEditor version: 4.8
* Installed CKEditor plugins: divarea

**Comment by rconn3** [comment]
Something interesting I found is that if you focus into the ckeditor before focusing into the number input, the error doesn't pop up

**Comment by angelika** [comment]
Anything happening with this issue?

**Comment by m-burger** [comment]
Hello there,

I can confirm this is also happening with the version 4.5.10 in Firefox 64.0.2 (64 bits) on Mac.

+1

**Comment by mlewand** [comment]
Please add "👍" reaction to the first post, that

**Comment by piernik** [comment]
I can confirm a bug. When ckeditor has divarea plugin and You focus on an input field with type number, error occurs. I have windows 10 with FireFox 66

**Comment by jacekbogdanski** [comment]
The issue is caused by Firefox itself. `window.getSelection` results in invalid range containers when used with the active number input element. I already reported the upstream issue on Firefox issue tracker, please subscribe https://bugzilla.mozilla.org/show_bug.cgi?id=1563739 for more details about its state.

From my perspective, the issue is not causing any serious problem except console error, so there is no need for any workaround. However, if you notice some issues with your browser application or CKEditor itself, please, give us know so we can reopen this issue and consider a solution.

**Comment by LiamDawe** [comment]
This does actually cause issues, it prevents you closing some dialogue boxes.

It's happening to me a lot when trying to open HTML video, you get the dialogue, change something, then click OK and nothing happens but it does keep adding errors to the console.

> Error: Permission denied to access property "nodeType" 4 ckeditor.js:78:31
>     node https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:78
>     selection https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:469
>     getSelection https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:466
>     Image https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:1096
>     save https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:1090
>     init https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:1086
>     l https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:10
>     fire https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:12
>     fire https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:13
>     okListener https://www.gamingonlinux.com/includes/ckeditor/plugins/widget/plugin.js?t=J8Q8:1178
>     l https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:10
>     fire https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:12
>     onClick https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:637
>     onClick https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:575
>     l https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:10
>     fire https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:12
>     click https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:574
>     button https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:566
>     l https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:10
>     fire https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:12
>     a https://www.gamingonlinux.com/includes/ckeditor/ckeditor.js?v=4.13:73
