### ISSUE TITLE
CKEDITOR.tools.convertToPx returns last valid value, when called with wrong input

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2223]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open console.
2. Type 'CKEDITOR.tools.convertToPx( '10px' ) // returns 10.
3. Type 'CKEDITOR.tools.convertToPx( 'poop' ) // returns 10.

### Expected result

I'm not sure what it should return, maybe false, but definitely not last output.

### Actual result

Same as above

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
This is actually not our issue, we're going to follow [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) rule here.
