### ISSUE TITLE
CKEDITOR 4.10 doesn't initialize second time inside bootstrap modal

### ISSUE THREAD

**Issue by hkakumanu-ttc** [ckeditor/ckeditor-dev#2231]
## Type of report

I updated to latest CKEDITOR 4.10 and its currently loading editor inside bootstrap modal. It loads the first time and doesn't show up on the second click. I tried destroy() and it still didn't work.All it was showing a blank area.Is anyone facing the same issue?

## Provide detailed reproduction steps (if any)

I
 Expected result
It should initialize normally

### Actual result

Its not initializing 

## Other details

* Browser: Chrome
* OS:Mac
* CKEditor version: 4.10
* Installed CKEditor plugins: …
'a11yhelp' : 1,
		'basicstyles' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'button' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'dialog' : 1,
		'dialogadvtab' : 1,
		'dialogui' : 1,
		'div' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'fakeobjects' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'flash' : 1,
		'floatingspace' : 1,
		'floatpanel' : 1,
		'font' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'image' : 1,
		'imagebrowser' : 1,
		'imgbrowse' : 1,
		'indent' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'link' : 1,
		'list' : 1,
		'listblock' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'menu' : 1,
		'menubutton' : 1,
		'newpage' : 1,
		'pagebreak' : 1,
		'panel' : 1,
		'panelbutton' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'popup' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'richcombo' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'smiley' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tabletools' : 1,
		'templates' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1

**Comment by mlewand** [comment]
Please provide a working demo using codepen.io/jsfiddle that will give us exact steps you're taking to repro the issue.

**Comment by hkakumanu-ttc** [comment]
I fixed this using CKEDITOR.timestamp = new Date(); before creating a new one.
