### ISSUE TITLE
Character count is not correct

### ISSUE THREAD

**Issue by Rajagopalang** [ckeditor/ckeditor-dev#2237]
## Character count is not correct

Bug

## Provide detailed reproduction steps (if any)

1. …In my application i'm using the code to get character count textEditor.getData().length. this is not come correct result.
2. …So next i used wordcount plugin, this also not working.(textEditor.getData().length)
3. …

### Expected result

I want exact result when i use textEditor.getData().length

### Actual result

But i got irrelevant character count.

## Other details

* Browser: …Chrome
* OS: …Windows7
* CKEditor version: …4.7.3
* Installed CKEditor plugins: …Standard

**Comment by jacekbogdanski** [comment]
Hello,

[`editor.getData`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#method-getData) function returns **raw** editors data - which means it will contain the same content as editor in HTML format. If you want to get clean text output, use [`editor.editable().getText`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editable.html#method-getText) function.

Give it a try and let us know if it resolves your problem. If I misunderstood your intention, please provide more information about the issue e.g.

* is it occurs on latest 4.10.0 CKEditor version?
* attach `editor.getData()` output
* attach text/HTML causing the issue

**Comment by Rajagopalang** [comment]
jacekbogdanski,

Thanks for your guidance... I changed in wordcount plugin code. Now coming correct count with HTML as well plain text count. Thanks lot.

Regards,
Rajagopalan.G

**Comment by Rajagopalang** [comment]
After pass in Quality control  , i will close this ticket. Thanks

**Comment by Rajagopalang** [comment]
Thanks for your support...i'm going to close this ticket...
