### ISSUE TITLE
Information on a11ychecker plug-in

### ISSUE THREAD

**Issue by jongund** [ckeditor/ckeditor-dev#2242]
## Type of report

Task

## Provide description of the task

* Need information on where the rules engine for the a11ychecker pulg-in is loaded from, does not appear to be using the local quail.jquery.js or quail,jquery.min.js files to evaluate pages

## Other details

* need to update the rules to comply with WCAG 2.0 requirments and options related to using new accessible authoring plug-ins, see: https://github.com/a11yfirst/plugins-dev/tree/a11yfirst

**Comment by mlewand** [comment]
This is a question related to Accessibility Checker, not the CKEditor itself so I moved it to a proper repostiroy cksource/ckeditor-plugin-a11ychecker#256.
