### ISSUE TITLE
Autolink is not integrated with the undo plugin

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2244]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://codepen.io/mlewand/pen/QBGYpL
2. Focus the editor at the end of editable.
3. Type `foo foo@bar.baz bar`
4. `Ctrl+z` all the way to the first snapshot

### Expected result

Editor goes to the initial state.

### Actual result

Content contains a link that was not there.

## Further Steps

1. Redo `ctrl+y` all the way (till there are no redo steps anymore).

### Expected result

Editor contains: `Type an email or a link: foo foo@bar.baz bar`.

### Actual result

Editor contains: `Type an email or a link: foo foo@bar.bazfoo@bar.baz bar`.

## Other details

My testing shows that Firefox produces a slightly different results.

* Browser: All
* OS: Any
* CKEditor version: 4.11.0 preview

**Comment by Comandeer** [comment]
See #2221.

**Comment by mlewand** [comment]
After a talk with @jacekbogdanski it turned out that this issue is invalid as it did not include the `undo` plugin. Sorry for the confusion 🙂
