### ISSUE TITLE
Misplacement of paste message notification.

### ISSUE THREAD

**Issue by hkakumanu-ttc** [ckeditor/ckeditor-dev#2260]
Type of report
Bug

Provide detailed reproduction steps (if any)
When using the paste button of ckeditor, a notification appears saying
"Press Ctrl+V to paste. Your browser doesn‘t support pasting with the toolbar button or context menu option."
The problem is that it appears in wrong emplacement (far away from the ckeditor bar)
This bug occurs only the first time I click on the paste button. When clicking again, the notification appears in the right place (close to the ckeditor bar)

This happens only in the bootstrap modal and unfortunately couldnt reproduce the same in Codepen.

Expected result
When clicking on the paste button in the first time, the notification appears in the right place

Actual result
When clicking on the paste button in the first time, the notification appears in the wrong place

Other details
Browser: Chrome
OS: Mac
CKEditor version: 4.10
Installed CKEditor plugins: …

**Comment by hkakumanu-ttc** [comment]
Sorry I fixed this by updating my skins. My skins folder is out of date.

**Comment by mlewand** [comment]
Happy it has worked for you, thanks for letting us know.
