### ISSUE TITLE
Widgets based on simple box get cut off after the second instance

### ISSUE THREAD

**Issue by rjsteinert** [ckeditor/ckeditor-dev#2269]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://tangy-form-editor.glitch.me/ in Chrome.
2. Open Chrome Dev tools and set a breakpoint on line 141 in `tangy-form-item-editor.js`. This is the line where `CKEDITOR.inline('editor1')` is called.
2. Click "edit" under "Fruit Survey"
3. The breakpoint hits, not how there are 6 widgets.
4. Press play in the devtools and now note how there are only two widgets in the CKEditor insance.

Before `CKEDITOR.inline()`:
<img width="1280" alt="screen shot 2018-07-27 at 3 25 41 pm" src="https://user-images.githubusercontent.com/156575/43342755-e00787cc-91b1-11e8-9ed9-4a69f706ad12.png">

After `CKEDITOR.inline()`:
<img width="1280" alt="screen shot 2018-07-27 at 3 29 05 pm" src="https://user-images.githubusercontent.com/156575/43342777-eb47db64-91b1-11e8-9aca-0ed9f0c385c8.png">

### Expected result

We expect to have all DOM in the CKEditor instance that we placed in it.

### Actual result

We only have two elements out of 6.

## Other details

* Browser: Chrome
* OS: Mac OS X
* CKEditor version: 4 (built online a couple of days ago)
* Installed CKEditor plugins: Magicline, some other custom plugins based on simple box. The plugin being used in this demo is here https://github.com/Tangerine-Community/tangy-form-editor/blob/master/ckeditor/plugins/tangy-input/plugin.js

**Comment by msamsel** [comment]
Hi @rjsteinert,

it seems that our content filtering mechanism strip out part of those tags. As you are using custom elements, have you register them in [ACF](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_acf.html) and configure [DTD](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dtd.html)?

Please extract your case to clear HTML+JS code, where we could analyse it more precisely. What might help understand better this case.

Alternatively you can also make 6 editors with [inlineAll](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR.html#method-inlineAll) method.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
