### ISSUE TITLE
hyperlink not retaining href value

### ISSUE THREAD

**Issue by ajboord** [ckeditor/ckeditor-dev#2270]
## Are you reporting a feature request or a bug?
BUG

The issue that I am reporting is that since upgrading to 4.9.2 when adding a link, the url is always blank.

thank you!

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
