### ISSUE TITLE
iOS: Dropdown style doesn't get applied and not all vales are being shown in dropdowns afterwards

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2280]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Put attached test page on server and open it in a browser
2. Tap somewhere in the text to set the selection (it can either be collapsed selection or you can select a word) 
3. Open Font-size dropdown and select size 72 (**actually you can select any size from 24 to 72 to see the bug**)
4. (**First issue**) Style doesn't get applied, (**Second issue**) dropdown "reloads" itself and font sizes are now available only to value 11 and not to initial 72.
**NOTE:** Applying any of the remaining values works as expected also applying initially any font-size between 8 and 22 works as expected as well. 

### Expected result

Dropdown should be showing all the values and style application should work the first time.

### Actual result

Dropdown doesn't show all the values and style isn't applied initially. 

## Other details

* Browser: Safari
* OS: iOS 11.3.1, 11.4.1 (tested environments)
* CKEditor version: 4.10.0
* Installed CKEditor plugins: CKEditor full package.

Problem can be reproduced with FontSize and Style dropdowns. It looks like it has something to do with the number of options being used as both shorter dropdowns (Format and FontName) work as expected.

In styles dropdown problem can be reproduced if we select any style below "inserted Text"

We had problems reproducing this issue here: http://cdn.ckeditor.com/4.10.0/full/samples/ thus the attached test page.

[tes-paget.zip](https://github.com/ckeditor/ckeditor-dev/files/2253160/tes-paget.zip)
[screen-cast.zip](https://github.com/ckeditor/ckeditor-dev/files/2253161/screen-cast.zip)

**Comment by jacekbogdanski** [comment]
I can reproduce the issue on iOS `11.4`. However, it looks like an upstream issue thus I'm also able to reproduce it with [this codepen](https://codepen.io/jacekbogdanski/pen/NMbdwz). It looks like contenteditable element is scrolled up with any interaction when the content is long enough. It explains why you weren't able to reproduce the issue with a smaller number of options inside the dropdown.

**Comment by jacekbogdanski** [comment]
There is a link into already reported iOS issue https://bugs.webkit.org/show_bug.cgi?id=139694
