### ISSUE TITLE
Rename phone link option label

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2284]
## Type of report

Task

## Provide description of the task

In #2154 we added a phone link type. That's all good, but it got labelled as "telephone", while more common way to say that is just "phone".

Let's simplify this before we ship this feature.

## Other details

* Browser: Any
* CKEditor version: 4.11.0

**Comment by mlewand** [comment]
Note this change does not require tests.

**Comment by jacekbogdanski** [comment]
Closed via #2286
