### ISSUE TITLE
Refactor tableselection manual tests to reflect correct table structure

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2289]
## Type of report

Task

## Provide description of the task

This is a followup for #996. Some of our manual tests for `tableselection` plugin have invalid table structure e.g. `tfoot` is above `tbody` element. We should refactor manual tests to meet [WHATWG](https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element) standards.

## Other details

* CKEditor version: 4.10.1
* Installed CKEditor plugins: tableselection

**Comment by Comandeer** [comment]
Duplicate of #2165.
