### ISSUE TITLE
Dropping list, starting with a link, on body Margin results with an error

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2292]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open this codepen - https://codepen.io/j_swiderski/pen/wxYvPE
2. Select whole list which has link as first element. 
3. Drop it on the body margin as shown in attached video. 

### Expected result

List gets dropped somewhere in text.

### Actual result

 List disappears and JavaScript error gets thrown e.g. 
**Firefox:**
Message: this.getRanges(...)[0] is undefined
File:  selection.js:
Line: 2412
Code: this.getRanges()[ 0 ].scrollIntoView(); 

**Chrome:**
Message: Cannot read property 'scrollIntoView' of undefined
Rest is the same.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.5.4+
* Installed CKEditor plugins: N/A

**Screen Cast:** [error.zip](https://github.com/ckeditor/ckeditor-dev/files/2266736/error.zip)

**Comment by mlewand** [comment]
It looks like clipboard plugin is causing the issue. Issue was introduced in CKEditor 4.5.0 - before it was impossible to drop in such case.

**Comment by Comandeer** [comment]
Fixed in 4.11.3.
