### ISSUE TITLE
Pasting content from MS Outlook and then bolding it results in JS error

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2294]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://codepen.io/mlewand/pen/gdWWJO.
1. Copy contents from attached MS Outlook message - using `Ctrl+A` `Ctrl+C` shortcuts.
1. Open editor sample in a browser, click inside the editor, press `Ctrl+A` and then Backspace or Delete.
1. Paste Outlook contents using `Ctrl+V`
1. Don't click anywhere (this is especially important when reproducing in Chrome) and just press `Ctrl+A`
1. `Ctrl+A` to select all the content and then click on Bold button in the toolbar.

Screen Cast: [error.zip](https://github.com/ckeditor/ckeditor-dev/files/2269490/error.zip)
Outlook Message: [Sample Mail.zip](https://github.com/ckeditor/ckeditor-dev/files/2269492/Sample.Mail.zip)

### Expected result

Content gets Bold, no error are thrown in the console.

### Actual result

Content gets Bold however js error is thrown:
**Message:** Cannot read property 'getParents' of null
**File:** range.js
**Line:** 278
**Code:** endParents = endNode.getParents(),

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.10.0

**Comment by mlewand** [comment]
The reason why is this happening is that Outlook leaves some comments in the pasted markup, and colorbutton plugin breaks when iterating over comments. This clearly should not break the plugin.

As such it is not colorbutton bug, not related really to the Outlook. I'll update the issue appropriately.

It didn't happen with PFW plugin  as it cleared the HTlML comments.

**Comment by mlewand** [comment]
Reverted original title / description, as I mistakenly have placed updates related to second similar issue (#2296).

**Comment by Comandeer** [comment]
Merged into 4.10.2.

**Comment by mlewand** [comment]
Note that this fix has been merged to 4.10.2 release, as 4.10.1 release is already closed and waiting to be released.

You can already preview it on codpen, using 4.10.2 preview: https://codepen.io/mlewand/pen/OoxgqV
