### ISSUE TITLE
Pasting from Excel

### ISSUE THREAD

**Issue by zhangqhzz** [ckeditor/ckeditor-dev#2295]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. inline…
2. nothing…
3. pasting from Microsoft Excel.…

### Expected result

excel table in the ckeditor

### Actual result

The excel table is together with the ckeditor external HTML string.

If you paste between two characters, there's no problem
## Other details

* Browser:  all…
* OS: win10…
* CKEditor version: 4.7.0-4.10.0…
* Installed CKEditor plugins: tableresize,pastefromword…

**Comment by zhangqhzz** [comment]
<table><tr><td>dfdsf</td><td>dfd</td></tr>
<tr><td><div id=“introduction”>.......</div></td><td>dfdf</td></tr>
</table>

.....

script  ：CKEDITOR.inline( 'introduction' .......................

**Comment by zhangqhzz** [comment]
`<table>
  <tr><td>dsfsdfds</td><td>dfdfdf</td></tr>
  <tr><td>
	<div id="introduction">
		introduction（CKEDITOR）
	</div>
</td><td>dfdfdf</td></tr>
</table>`

div(CKEDITOR)  in the td(table)

**Comment by zhangqhzz** [comment]
Pasting from Excel  at the beginning or end of the ckeditor

**Comment by jacekbogdanski** [comment]
Hello,

pasting tables from MS Excel is not fully supported. We are working on this feature, you can check its status here: #1490. 

If you would like to see this feature in upcoming CKEditor 4 releases, visit mentioned feature request and give it thumbs up :+1: so we will be sure that our community is interested in this changes.
