### ISSUE TITLE
Pasting image from clipboard in Chrome

### ISSUE THREAD

**Issue by lateklmast** [ckeditor/ckeditor-dev#2301]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Draw something in MS Paint.
2. Make selection in MS Paint.
3. Copy selection (Ctrl+C).
4. Paste it to CKEditor (Ctrl+V) – can be reproduced on https://sdk.ckeditor.com/samples/classic.html

### Expected result

Pasted image into the editor in Chrome.

### Actual result

Pasting works in Firefox but does not work in Chrome (nothing happens).

## Other details

* Browser: Chrome 67
* OS: Windows 10
* CKEditor version: 4 like on https://sdk.ckeditor.com/samples/classic.html
* Installed CKEditor plugins: same as on https://sdk.ckeditor.com/samples/classic.html

**Comment by mlewand** [comment]
Reason why you don't see any image pasted is that there is no image upload plugin added in this particular sample.

Instead go to for instance [Easy Image sample](https://sdk.ckeditor.com/samples/easyimage.html) that has the [Easy Image plugin](https://ckeditor.com/cke4/addon/easyimage) integrated and does exactly what you'd like it to do.

However you have noted one thing, that we could enable it by default in all our examples - I'll pass it on, so we could improve it.

**Comment by lateklmast** [comment]
Easy Image plugin is the way, however, why it works in Firefox even without any other dependencies?

**Comment by mlewand** [comment]
Firefox does that natively, and injects your clipboard into the `[contenteditable]` element as base64 encoded image. Other browsers don't have this feature available, thus you don't see it there 🙂

**Comment by slythefox** [comment]
It works in Internet Explorer 11, but not Chrome.

**Comment by mlewand** [comment]
@slythefox there's an issue for that in Chromium, we can't do anything about it. Please provide your feedback there: https://bugs.chromium.org/p/chromium/issues/detail?id=316472

**Comment by maubol** [comment]
> @slythefox there's an issue for that in Chromium, we can't do anything about it. Please provide your feedback there: https://bugs.chromium.org/p/chromium/issues/detail?id=316472

It looks like it's broken for me in IE11 now too. IE used to upload the image using the imageUploadUrl config setting, but now it does not.

**Comment by azhershaikh** [comment]
I am using  image2 which is enhanced image plugin and still in chrome browser it does not allow to paste image in ckeeditor. any pointers will be appreciated

**Comment by f1ames** [comment]
@azhershaikh Could you provide exact steps which doesn't work for you?

**Comment by eyal0** [comment]
Saw a similar bug in Chrome related to ozone.

https://meta.stackoverflow.com/questions/411266/pasting-images-from-the-clipboard-doesnt-seem-to-work-anymore-on-chrome-for-lin/411569#411569

https://bugs.chromium.org/p/chromium/issues/detail?id=1247919#c30
