### ISSUE TITLE
Font plugin should allow to apply style with any tag

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2315]
## Type of report

feature

## Provide description of the new feature

Current implementation of font plugins doesn't allow on using other tags than `font` and `span`. There should be possibility to apply font size with any tag, that user want.
Issue extracted from this comment: https://github.com/ckeditor/ckeditor-dev/pull/1440#discussion_r192588813

**Comment by mlewand** [comment]
TBH I don't know if anyone will face a use case related to that. I'm closing this issue until Community rises this issue, showing that this has really any use.
