### ISSUE TITLE
Adding local plugins to CKEditor4 full version

### ISSUE THREAD

**Issue by moatasem1** [ckeditor/ckeditor-dev#2325]
I'm using CKEditor4 full version using a CDN:
`<script src="//cdn.ckeditor.com/4.10.0/full/ckeditor.js"></script>`
I'm trying to add local plugins that I downloaded:
```
CKEDITOR.plugins.addExternal( 'simplebutton', '//localhost/plugins/simplebutton', 'plugin.js' );
CKEDITOR.replace( 'editor', {
    extraPlugins: 'simplebutton',
    toolbar: [
        { name: 'simplebutton', items: [ 'simplebutton' ] }
    ]
});
```
But I get the following errors:
`Uncaught SyntaxError: Unexpected token <          ?t=I63Cplugin.js:1`
```
ckeditor.js:264 Uncaught TypeError: Cannot read property 'icons' of null
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:264)
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:263)
    at e (ckeditor.js:258)
    at Array.y (ckeditor.js:258)
    at v (ckeditor.js:258)
    at ckeditor.js:259
```

Even if I don't include the toolbar part and just include  `extraPlugins: 'simplebutton'`

I get the same error.

**Comment by mlewand** [comment]
I'm sorry but this is a place for reporting CKEditor bugs and not place for seeking advice or support.

I believe you have already [posted this question on StackOverflow](https://stackoverflow.com/questions/51908490/adding-local-plugins-to-ckeditor/51909850#51909850) - which is the proper place to look for support.
