### ISSUE TITLE
Autolink typing support breaks integration with autoembed plugin

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2340]
## Type of report

Bug

## Provide description of the task

On major branch tests are failing:
`tests/plugins/autoembed`

![screen shot 2018-08-27 at 15 22 55](https://user-images.githubusercontent.com/23366849/44662269-92439700-aa0d-11e8-8f0d-41e8f2000413.png)
![screen shot 2018-08-27 at 15 25 58](https://user-images.githubusercontent.com/23366849/44662270-9374c400-aa0d-11e8-95d9-97c6feabc1dc.png)
![screen shot 2018-08-27 at 15 26 07](https://user-images.githubusercontent.com/23366849/44662272-940d5a80-aa0d-11e8-8006-2c36f7cb1830.png)
![screen shot 2018-08-27 at 15 26 12](https://user-images.githubusercontent.com/23366849/44662274-94a5f100-aa0d-11e8-9fc6-7a3a3d8b2a94.png)

## Other details

* Browser: any
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Looks like a regression since it doesn't fail on `master`.

**Comment by engineering-this** [comment]
Culprit: https://github.com/ckeditor/ckeditor-dev/commit/f9f688acaf5684c750c0eb51fd4d7ea27014f583
Manual test also fails: `tests/plugins/autoembed/manual/autoembed`.

**Comment by jacekbogdanski** [comment]
Improved autolink plugin with typing support breaks integration with autoembed plugin. I will rename ticket title and labels thus it's autolink bug, not issue with autoembed tests.

**Comment by engineering-this** [comment]
@jacekbogdanski Although it's not an issue with test I suggest to keep that label, so other devs can find this ticket, so we don't end up with duplicates.

**Comment by Comandeer** [comment]
Fixed with #2372.
