### ISSUE TITLE
Failing tests tests/plugins/justify/justify

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2349]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

Failing tests on Firefox: `http://localhost:1030/tests/plugins/justify/justify`

![image](https://user-images.githubusercontent.com/10279586/44789694-8d155200-ab9d-11e8-9f75-f4cb29ca20be.png)

**Comment by Comandeer** [comment]
Merged into 4.10.2
