### ISSUE TITLE
Failing test on iOS release

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2350]
## Type of report

Failing test

## Provide description of the task

iOS Safari build release failing tests:

`test/plugins/balloonpanel/positioningonstatic` - test fail when run from dashboard
```
Name: test positioning in nonstatic body (inline)

Triangle tip y position outsid of element
Expected: Greater than 464 and lower than 485. (string)
Actual:   1013.5 (number)
```
`test/plugins/easyimage/balloontoolbar` - test occassionally fail when run from dashboard
```
Name: test balloontoolbar positioning (classic)

Balloon y position
Expected: 203.78125 (number)
Actual:   202.78125 (number)

Name: test balloontoolbar positioning (divarea)

Balloon y position
Expected: 465.59375 (number)
Actual:   464.59375 (number)

Name: test balloontoolbar positioning (inline)

Balloon y position
Expected: 666.59375 (number)
Actual:   665.59375 (number)
```

## Other details

* Browser: Safari
* OS: iOS
* CKEditor version: 4.10.1
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Fixed by #2371.
