### ISSUE TITLE
Emoji dropdown doesn't show up with preceding space

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2352]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Reproduce test steps `/tests/plugins/emoji/manual/spacerequired`.

### Expected result

Works as expected described in a test case.

### Actual result

Typing second `:bu` in the first line doesn't show up dropdown.

![peek 2018-08-30 10-20](https://user-images.githubusercontent.com/10279586/44839093-2eec7b80-ac3e-11e8-994e-4ef5f086679d.gif)

## Other details

* Browser: Firefox, IE10
* CKEditor version: 4.10.1

**Comment by mlewand** [comment]
@jacekbogdanski can you reproduce it in 4.10.0? It might be same issue as referenced to @engineering-this.

**Comment by jacekbogdanski** [comment]
I cannot reproduce it so it looks like a regression.
