### ISSUE TITLE
Ignore tests requiring console on mobiles

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2361]
## Type of report

Task

## Provide description of the task

Following tests require tester to open console:

`tests/plugins/image2/manual/easyimage`
`tests/plugins/image/manual/image2`
`tests/plugins/image/manual/easyimageimage2`
`tests/plugins/image/manual/easyimage`

They should be ignored on mobile devices.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Are you sure the tests should be ignored? You cannot check console output on mobile devices, although you can still check if correct image plugin has been loaded. Not sure if the test requires additional note that you have to skip console check. However the problem popped up, so we may consider adding such information. WDYT @engineering-this?

**Comment by engineering-this** [comment]
It would be ok to keep tests if test steps clearly said what to do on mobiles.
