### ISSUE TITLE
Emoji plugin will not load when using CDN.

### ISSUE THREAD

**Issue by bosonau** [ckeditor/ckeditor-dev#2364]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Fiddle: [https://jsfiddle.net/fcrg5kow/5/](https://jsfiddle.net/fcrg5kow/5/)
in Chrome's console:
`(index):1 Failed to load https://cdn.ckeditor.com/4.10.0/full-all/plugins/emoji/emoji.json?t=I63C: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fiddle.jshell.net' is therefore not allowed access.`

### Expected result

Should be able to load the plugin's json file.

### Actual result

loading it fails and javascript error is thrown.

## Other details

I think it's failing because the file in question is a .json file and not .js.  it seems other plugins work fine (tried mention )

can you add CORS to JSON resources for your CDN?

* Browser: Chrome, Opera
* OS: MacOS Sierra
* CKEditor version: 4.10.0
* Installed CKEditor plugins: emoji

**Comment by mlewand** [comment]
I have confirmed the issue. Our admins added proper headers to .json files as well, so you should be able to fetch JSONs from other domains too.

Thanks for the report!
