### ISSUE TITLE
Styling HTML comments in top level element result with extra paragraphs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2380]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample with source area, e.g. [full preset sample](http://cdn.ckeditor.com/4.10.0/full/samples/).
2. Go to source mode using "Source" button.
3. Replace the source markup with the following:

	```html
	<p>foo</p>
	<!-- com -->
	<p>bar</p>
	```

1. Go back to WYSIWYG mode by clicking "Source" button once again.
1. Focus the editor.
1. Select all the contents (e.g. `CTRL/CMD+A`).
1. Apply bold (e.g. `CTRL/CMD+B`).
1. Click "Source" button once again to inspect the result markup.

### Expected result

HTML markup should look like:

```html
<p><strong>foo</strong></p>
<!-- com -->

<p><strong>bar</strong></p>
```

### Actual result

```html
<p><strong>foo</strong></p>

<p><strong><!-- com --></strong></p>

<p><strong><strong>bar</strong></strong></p>

<p>&nbsp;</p>

```

* There's an unnecessary paragraph created around the comment node.
* There's an extra paragraph at the end.

## Other details

I can reproduce it in 4.4.2, didn't check earlier - so it doesn't look like a regression.

* Browser: Any
* OS: Any

**Comment by Comandeer** [comment]
Merged into 4.10.2.
