### ISSUE TITLE
filterRulesDefinition docs are empty

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2387]
## Type of report

Task

## Provide description of the task

[`filterRulesDefinition`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser_filterRulesDefinition.html) docs are empty. We need to document its members.

**Comment by jacekbogdanski** [comment]
I can confirm the issue.

**Comment by Comandeer** [comment]
Merged into 4.11.3.
