### ISSUE TITLE
Minimal character count for autocomplete is incorrect if preceded with an unfinished autocomplete match

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2394]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any editor with Emoji plugin enabled.
2. Focus the editor.
3. Empty the contents (e.g. `ctrl/cmd+a`, `del`).
1. Type `:smiling_face`.
1. Press `esc` key to **cancel** completion, so it doesn't get replaced by a emoji.
1. Press `space`.
1. Type `:smi`.

### Expected result

Dropdown with emoji appears.

### Actual result

No dropdown appears.

## Other details

Interestingly if you continue the typing till you have `:smiling_face_` (so that it is longer than the first token) the autocomplete appears.

This issue is very, very awkward. At first I thought that matching doesn't work at all, but then it seemed to me that it works, but minimal charcount is considered based on preceding match.

I presume that the issues is in autocomplete plugin rather than emoji. 

Looks like it's a regression in **4.10.1** as I can't reproduce it with 4.10.0. I guess that it got introduced with #2195.

* Browser: Any
* OS: Any
* CKEditor version: 4.10.1

**Comment by engineering-this** [comment]
I can reproduce it.

**Comment by engineering-this** [comment]
Looks like it is related to #2352.

**Comment by jacekbogdanski** [comment]
I closed the mentioned issue (#2352) as a duplicate thus it's the same one. However, I believe that this issue is more related to the emoji plugin than autocomplete itself thus mentions works as expected with the same use case.

**Comment by jacekbogdanski** [comment]
The issue has been introduce by https://github.com/ckeditor/ckeditor-dev/commit/b2641241a7248cd1b9ea7825a083afec629135bb

**Comment by mlewand** [comment]
Fixed with #2452.
