### ISSUE TITLE
Ckeditor Popup trigger unable to edit content in middle

### ISSUE THREAD

**Issue by Amrudha-sns** [ckeditor/ckeditor-dev#2400]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …Added the destroy instance code to destroy the previous instance and then created the new inline instance
2. …When click on the editable div the inline editor popup triggers and the cursor moves end of the editable div ,unable to edit content in the middle.
3. …try {
				CKEDITOR.instances[currentid].destroy();
				var editor = CKEDITOR.inline( currentid, {  //Editable area div id
					enterMode : CKEDITOR.ENTER_BR, //Lines are broken with <br> elements
					allowedContent : true,
				});
			}
			catch(err){
				var editor = CKEDITOR.inline( currentid, {  //Editable area div id
					enterMode : CKEDITOR.ENTER_BR, //Lines are broken with <br> elements
					allowedContent : true,
				});
			}

### Expected result

*What is the expected result of the above steps?*Need to edit content at random position even the destroy instance method is added.

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …Chrome Version 69.0.3497.81
* OS: …Windows 7
* CKEditor version: … 4.9.2
* Installed CKEditor plugins: …strinsert,tokens,sharedspace,backgrounds,checkbox,textsignature

**Comment by jacekbogdanski** [comment]
Hello,

Destroying classic editor and replacing it with inline editor works fine for me using our latest sample. Make sure that editor target element has `contenteditable=true` attribute. E.g.

```javascript
CKEDITOR.instances[ editorId ].destroy();
document.getElementById( editorId ).setAttribute( 'contenteditable', true );
CKEDITOR.inline( editorId );
```
