### ISSUE TITLE
npm image unavailable

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2405]
## Type of report

Task

## Provide detailed reproduction steps (if any)

There's a problem with invalid link to the image produced by npm.

Reason for this is that npm hotlinks directly to GH (master branch), which have this image in the `.npm` directory.

**Comment by mlewand** [comment]
I added a workaround for that in e811f32 till a proper fix is rolled out.

**Comment by mlewand** [comment]
We had a quick chat and came that the best idea will be simply to use permalinks to an image, like `https://raw.githubusercontent.com/ckeditor/ckeditor-dev/a7c641362080b3b4f88abb1d5552e6097a8795fd/assets/ckeditor4.png`.

**Comment by Comandeer** [comment]
We decided to link to particular commit, not branch, to be able to modify images in the future, leaving older versions untouched, with images showing editor at that time.

**Comment by Comandeer** [comment]
Closed in #2456.
