### ISSUE TITLE
CKEditor dev npm package is missing keywords

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2406]
## Type of report

Task

## Provide description of the task

Dev version has no npm keywords in [`package.json`](https://github.com/ckeditor/ckeditor-dev/blob/master/package.json).

**Comment by mlewand** [comment]
I guess we can just copy the keywords from the [release version](https://github.com/ckeditor/ckeditor-releases/blob/279d9437b88c2812e4ea3dc701427018f26ce55e/package.json#L10-L19), shouldn't we @AnnaTomanek?

**Comment by AnnaTomanek** [comment]
Yep, go ahead, thanks! 👍
