### ISSUE TITLE
Polish Translation for Id and Style in english

### ISSUE THREAD

**Issue by mjkmike** [ckeditor/ckeditor-dev#2409]
Other, Is the polish translation supposed to be in English for both ID and Style strings?  Our test team flagged this as an issue.

### Expected result

Polish Translations for both strings

### Actual result

Id and Style are displayed in ID and style.

## Other details
Looked at the polish file in the master branch.  This may be a misunderstanding, but we would expect that to be translated.

**Comment by mlewand** [comment]
Nothing like that is happening in the latest CKEditor, see screen below, both english are properly in English:

![image](https://user-images.githubusercontent.com/5353898/45449982-1157f100-b6d7-11e8-949e-a3fee6b15791.png)

See http://cdn.ckeditor.com/4.10.1/full/samples/ for unmodified CKEditor sample.

**Comment by mjkmike** [comment]
Hi, sorry.  When the CKEDITOR language is set to Polish those two strings are still in English.  Is that how its supposed to be or are those strings supposed to be translated to Polish like the rest of the strings.
