### ISSUE TITLE
Major: Type error in 'tests/plugins/undo/change'

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2425]
## Type of report

Task

## Provide detailed reproduction steps (if any)

Open test on current major branch:

`tests/plugins/undo/change#tests%2Fplugins%2Fundo%2Fchange%20test%20no%20change%20event%20on%20create%20and%20destroy`

Throws type error although it passes.

**Comment by mlewand** [comment]
Looks like it was introduced in 4.9.0.

**Comment by engineering-this** [comment]
This has been fixed on master, so once branches are merged this is solved also on major.
