### ISSUE TITLE
Edge Permission Denied thrown when right-clicking into editor

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2426]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open demo page - https://ckeditor.com/ckeditor-4/
2. Right-click in the editor. This can be the initial click but you can also focus the editor first and then right-click it. 

![edge](https://user-images.githubusercontent.com/5314687/45744078-e0f3e380-bbfd-11e8-8112-d5fee91c2229.png)

### Expected result

Menu shows up.

### Actual result

Menu shows up and Permission Denied error gets thrown.

## Other details

* Browser: Edge
* OS: Win10
* CKEditor version: 4.5.4+
* Installed CKEditor plugins: N/A

In CKEditor 4.5.2 you needed to left-click and the right-click to get Permission denied.
In CKEditor 4.5.3 problem doesn't exist
Starting from CKEditor 4.5.4 Permission denied is being thrown on first right-click in the editor.

**Comment by mlewand** [comment]
Can you check it on the master branch? We fixed a similar issue for the upcoming 4.10.2 release.

**Comment by jswiderski** [comment]
i have checked latest master changes and in deed problem is gone.
