### ISSUE TITLE
Remove Format changes selection when applied to unsupported element

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2451]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open nightly sample - http://nightly.ckeditor.com/18-10-02-06-04/full/samples/.
2. Clear editor contents and type any text.
3. Select the text and set Formatting to "Heading1" and then apply the Numbered list.
4. Click on Remove Format button (Notice that Format dropdown no longer shows "Heading 1" at this point)
5. Change the formatting in the Format dropdown to "Heading2"

### Expected result

Format dropdown should display "Heading 2".

### Actual result

Format dropdown displays "Format".
Please note however that new Format gets applied properly. Only the selection is being moved from `H1` element to its parent `ol`. If you change the selection and click inside the `H1`, the Format dropdown will show it correctly again.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: Format Dropdown.

When Remove Format is applied, it looks like selection is being moved from the actual element to its parent. This behavior is in my opinion correct for inline elements because when format is removed, the inline element (like span or strong) is being removed as well. When it comes to block-level elements, things get more complicated. By default [removeFormatTags](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removeFormatTags) is only be applied to inline elements and documentation say that only inline elements can be used on that list. There is however nothing stopping from setting this configuration option to `config.removeFormatTags = 'h1,div,blockquote'`. What is more, such setup will work properly (provided that start of element is selected) when removing formatting form H1 for example (tag will get removed). Since the plugin works ok for both types of tags and the only thing which says otherwise is one sentence in documentation, what should we do?
1. Apply Remove Format to tag only if it is on the list? That way we could avoid selection changes for not supported tags and leave current behavior untouched. Best solution IMHO.
2. Block the block-level tags permanently? Disallow them on the list and ignore them when Remove Format is applied?
3. Ignore it and leave it as it is? Kind of makes sense because this plugin should not be used for not supported tag in the first place but on the other hand how could the user know that.

Screen cast: [remove format.zip](https://github.com/ckeditor/ckeditor-dev/files/2441540/remove.format.zip)

**Comment by Comandeer** [comment]
The fix was merged into 4.11.2.
