### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by preethagg** [ckeditor/ckeditor-dev#2458]
## Type of report

Bug

After upgrading to CKEditor4, the CKEditor is not appearing in IE 11 and throws the following error:

SCRIPT438: Object doesn't support property or method 'assign'
ckeditor.js (1302,392)

## Other details

* Browser: IE11
* OS: Windows
* CKEditor version: CKEditor4
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
I tested each editor build on IE11 and everything works.

Can you reproduce your issue with the latest CKeditor 4.10.1? If yes then please provide example on page like codepen.io or jsfiddle.net so we can use it to find out what is wrong.

**Comment by preethagg** [comment]
Upgraded from CKeditor 4.10 to CKeditor 4.10.1, which fixed the issue. Thanks.

**Comment by engineering-this** [comment]
Thanks for information.
