### ISSUE TITLE
Widget nested editable triggers blur event on focus in Firefox

### ISSUE THREAD

**Issue by mflorea** [ckeditor/ckeditor-dev#2470]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/7t4wvg06/6/ using **Firefox**
2. Open the JavaScript console (Developer Tools)
3. Click over "foo" to focus the widget (inside the CKEditor's editing area)
4. Type something in the widget
5. Click below "foo" to blur the widget (i.e. outside of the widget)

### Expected result

Step 3 should log

    editable focus

and step 5 should log

    editable blur

### Actual result

Step 3 logs

    editable focus
    editable blur

and step 5 doesn't log anything.

## Other details

* Browser: Firefox 61.0.1
* OS: Ubuntu 17.10
* CKEditor version: both 4.10.1 and 4.10.0
* Installed CKEditor plugins: **copyformatting**

It doesn't reproduce on Chrome or if you remove the ``copyformatting`` plugin.

My investigation shows that this is a regression caused by 3a9f058fb5a6dee84444254199fe70252182e90b which was committed in CKEditor 4.10.0 . The change for Firefox is that

    editorFocus: false,

has become

    editorFocus: true,

so the ``applyFormatting`` command requires the editor to be focused but in my case I don't call this command explicitly so I don't understand how it affects the widget.

**Comment by engineering-this** [comment]
@mflorea thank you for your report. I can confirm this bug.

**Comment by Comandeer** [comment]
The issue was fixed by #2792. The fix will be released in 4.11.3.
