### ISSUE TITLE
image paste not working

### ISSUE THREAD

**Issue by ananthbtechit** [ckeditor/ckeditor-dev#2471]
## Provide detailed reproduction steps (if any)
I am using responsive file manager for uploading the file.In this how to upload the pasted image in the specified path.
Below code used for uploding:
config.filebrowserBrowseUrl = 'responsive_filemanager/filemanager/dialog.php?type=2&editor=ckeditor&fldr=',
    config.filebrowserUploadUrl = 'responsive_filemanager/filemanager/dialog.php?type=2&editor=ckeditor&fldr=',
    config.filebrowserImageBrowseUrl = 'responsive_filemanager/filemanager/dialog.php?type=1&editor=ckeditor&fldr=',

I can able to upload the file in the specified path but pasted image not uploaded in the specified path

### Expected result

Pasted image to be copied in the specified path .

### Actual result
image not uploaded the specified path

## Other details
* Browser: … Version 69.0.3497.100 (Official Build) (64-bit)
* OS: … RHEL 7.5
* CKEditor version: … 4.10
* Installed CKEditor plugins: … tableresize

**Comment by mlewand** [comment]
This is a support question related to your uploading library vendor. In that case you have to contact directly the author of uploading lib. You can always use CKFinder - with you get profressional support.
