### ISSUE TITLE
Add Ctrl+K keystroke for link command

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#2478]
## Type of report

Feature request

## Provide description of the task

Currently link command is hidden under <kbd>Ctrl</kbd>+<kbd>L</kbd> keystroke, however [the industry standard is <kbd>Ctrl</kbd>+K</kbd>](https://github.com/ckeditor/editor-recommendations/issues/10#issuecomment-193686789). Probably it'd be better to add the new keystroke for our link plugin to align our behaviour with the rest of the world.

**Comment by wimleers** [comment]
I'm glad CKEditor is doing this now, back in 2013 we had to add an override for this: https://www.drupal.org/project/drupal/issues/1879120#comment-7556673 :)
