### ISSUE TITLE
React Integration

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2480]
## Type of report

Feature request

## Provide description of the new feature

It would be nice to have an actively maintained React integration for CKE4.

Naturally it will land in a separate repository, I'm just adding the issue here so we can track it here.

**Comment by engineering-this** [comment]
Closing. The integration is published.

* CKEditor4 React integration repository - [ckeditor/ckeditor4-react](https://github.com/ckeditor/ckeditor4-react)
* CKEditor4 React integration on npm - [npmjs.com/package/ckeditor4-react](https://www.npmjs.com/package/ckeditor4-react)
* How to use - [ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html)
* Example usage/integrations - [ckeditor.com/docs/ckeditor4/latest/examples/react.html](https://ckeditor.com/docs/ckeditor4/latest/examples/react.html)
