### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2481]
## Type of report

Feature request

## Provide description of the new feature

It would be nice to have an actively maintained Angular integration for CKE4.

Naturally it will land in a separate repository, I'm just adding the issue here so we can track it here.

**Comment by nasiruddin-saiyed** [comment]
+1 & Can please add a new branch for `Angular`, so we can make pull request or post issues targeting specific branch.

**Comment by tobang** [comment]
Hi. What is the status of this issue? Need Angular support of version 4. Thank you

**Comment by mlewand** [comment]
Hi, the code of the integration itself has been just reviewed - but we still need docs before releasing it. That will take some time.

I can't provide you with any precise ETA, but it should take no longer than couple of weeks. The best way to get informed is to subscribe to this issue. We'll have a beta period so that way you'll be informed as soon as the beta is available.

**Comment by nasiruddin-saiyed** [comment]
@mlewand  is there any way to get hands on alpha release ? So we can create tests on our basis.

**Comment by mlewand** [comment]
I'll try to push this matter a little bit next week to see if we can publish preview. Keep in mind that next week we'll be doing a code freeze and extensive testing the upcoming 4.11.3 release, so that might be a busy period for us, but we'll try.

**Comment by mlewand** [comment]
@nasiruddin-saiyed @tobang The integration preview is out, you can find it at https://www.npmjs.com/package/ckeditor4-angular! You can find the guide here: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html - give it a try!

Sorry for longer wait but we had a lot of work around CKEditor 4 and CKEditor 5 these days.

**Comment by nasiruddin-saiyed** [comment]
@mlewand That's good enough! I'm exited to replace my manually created components. I was thinking to help you out, let us have your road map and we'll able to contribute :+1: 

Happy Coding!
Nasiruddin

**Comment by engineering-this** [comment]
Package is public, docs are complete. I guess we can close this? CC @f1ames

**Comment by f1ames** [comment]
Closing 👍

* CKEditor4 Angular integration repository - https://github.com/ckeditor/ckeditor4-angular
* CKEditor4 Angular integration on npm - https://www.npmjs.com/package/ckeditor4-angular
* How to use - https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html
* Example usage/integrations - https://ckeditor.com/docs/ckeditor4/latest/examples/angular.html
