### ISSUE TITLE
Improve UI panel arrow design

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2483]
## Type of report
Feature request

## Provide description of the new feature
Extracted from https://github.com/ckeditor/ckeditor-dev/issues/2062#issuecomment-429842350

Arrow next to UI panel button seems to be a little to close to icon. In case of emoji dropdown (maybe also in background) it's clearly visible. We should be able to somehow control position of this arrow or just improve its position to be better in such scenarios.
<img width="46" alt="screen shot 2018-10-15 at 15 16 12" src="https://user-images.githubusercontent.com/9017322/46953152-4d42f500-d08d-11e8-9d29-f55423ff0200.png">
<img width="43" alt="screen shot 2018-10-15 at 15 16 19" src="https://user-images.githubusercontent.com/9017322/46953153-4d42f500-d08d-11e8-9a27-67e9bffab8d0.png">

**Comment by jacekbogdanski** [comment]
Arrow has already attached CSS class and so emoji button. I wonder if we really need special treatment for the case which could by already easily styled by CSS?

```css
.cke_button__emojipanel .cke_button_arrow {
  margin-left: 5px;
}
```

WDYT @mlewand, @msamsel ?

**Comment by mlewand** [comment]
I think the change should be applied to all icons that have this kind of arrow. Language/SCAYT dropdown also look kinda weird with the arrow so close to it.

However simply increasing causes our toolbar to go into 4 lines for the full preset, which is not an option. So we need to adjust that, maybe shaving some padding somewhere else?

**Comment by jacekbogdanski** [comment]
I changed left margin from 1 to 2px. Unfortunately, the bigger margin will require cutting some other buttons to avoid line wrapping which don't seem good also. Take a look on screenshot please, especially @dkonopka :

![image](https://user-images.githubusercontent.com/10279586/47353469-ab3e9080-d6bc-11e8-9bf9-4ab53fd9220f.png)

**Comment by dkonopka** [comment]
☝️ Still, 2px looks too small spacing IMHO. How does it look with for example 4 pixels?

**Comment by jacekbogdanski** [comment]
4 pixels look definitely better, although they wrap the first line of the toolbar which as @mlewand mentioned creates 4 lines for full CKEditor. I was wondering about changing the padding size of buttons but they are just perfect sized in my eye. Do you see some place where we can cut some pixels to fit full editor in 3 lines?

4px margin:
![image](https://user-images.githubusercontent.com/10279586/47358225-7553d900-d6c9-11e8-91ca-551b0d275e06.png)

**Comment by jacekbogdanski** [comment]
It seems like line wrapping is caused by container outside of the editor. It makes me wonder if we can change anything without sacrificing some space of existing toolbar elements. Any change resulting in bigger/smaller toolbar may break some users interfaces - even as small as 1px margin.

I think we may update a little our button element with class giving us information if the button is expandable and if so - shrink its left and right paddings to build a place for arrow margin. It's already possible with `aria-haspopup="true"` but I prefer to not relay CSS styles on aria labels. I will try this approach to see if it's working correctly.
