### ISSUE TITLE
Empty span tag removed automatically

### ISSUE THREAD

**Issue by kite57** [ckeditor/ckeditor-dev#2484]
This is the bug. I am facing strange Issue in ckeditor, following is the scenario

1. I have added table with content
2. Following is the html of Table

```
<tr>
   <td colspan="2">
	   <span style="font-size:12px;"><b>Final Diagnose :</b></span>
    </td>
    <td colspan="2">
 		<span style="font-size:12px;"><b>[Final_Diagnose]</b></span>
    </td>
</tr>
<tr>
     <td colspan="4"><span style="font-size:12px;"></span></td>
</tr>

```
3.When I am saving this html, blank span tag removed and only `<td>` tag remains, so that when i am setting font size to whole html(using select all and assign font-size), and if i add anything in span tag then font size will be applied but if i did not add any text content than span tag with font size attribute removed.

After Saving Html Code

```
<tr>
   <td colspan="2">
	   <span style="font-size:12px;"><b>Final Diagnose :</b></span>
    </td>
    <td colspan="2">
 		<span style="font-size:12px;"><b>[Final_Diagnose]</b></span>
    </td>
</tr>
<tr>
     <td colspan="4"></td>
</tr>

```

### Expected result

Empty Span Tag with attributes should not be  removed,So when i add any content in that span, it will take saved font size

### Actual result

Empty Span Tag with attributes removed, so when i add some content, default font size applied, it is not taking saved font size

## Other details

* Browser:Chrome(Latest Version)
* OS:(Windows7)
* CKEditor version:3.6

**Comment by msamsel** [comment]
This behaviour is working as designed. Empty spans are considered as invisible and are removed from content to not pollute outputted HTML. You should add `&nbsp;` inside  such span to preserve it.
To modify this behaviour you might want to look closer to [CKEDITOR.dtd](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html#property-S-removeEmpty) class.
