### ISSUE TITLE
 The value does not disappear when pasting the table of Excel

### ISSUE THREAD

**Issue by masato-higa** [ckeditor/ckeditor-dev#2486]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use IE11. Change document mode to IE10
2. Paste the table created with Excel
3. Select multiple cells and press the delete key
4. The value of the selected cell does not disappear

![djw6c-mv2a7](https://user-images.githubusercontent.com/8719634/47009372-4c868d80-d177-11e8-8192-136ef9d35003.gif)

### Expected result

The value of the selected cell disappears

### Actual result

The value of the selected cell does not disappear

## Other details

* Browser: IE11 ( document mode : IE10 )
* OS: Win10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
Hi,

The [Table Selection Plugin](https://ckeditor.com/cke4/addon/tableselection) is responsible for handling selection in tables (these nice blue background on selected cell), but it supports IE10 only IE11 and newer browsers. Without this plugin editor can use only browsers native selection, which doesn't work well with tables.
