### ISSUE TITLE
Mentions are not matching unicode/diacritic characters

### ISSUE THREAD

**Issue by Adrienb91** [ckeditor/ckeditor-dev#2491]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use CKEDITOR 4.10 with mentions plugin
2. Include mentions data with accents like 'Céline TEST'
3. Try to use mentions with data typing '@Cé'

### Expected result

Mentions propose entry 'Céline TEST'

### Actual result

No results

## Other details

It seems due to emphasis/accents 
I've tried with direct data in array or with function feed.

I think we would have same results trying with accents or not (@Cel or @Cél must return same results).
It can be solved with a new regexp parameter to apply to request and data ?

Thanks per advance !

* Browser: Any
* CKEditor version: 4.10
* Installed CKEditor plugins: Mentions

**Comment by Adrienb91** [comment]
Capture
![ckeditor_mentions_accent_pb](https://user-images.githubusercontent.com/44245255/47116006-ab740180-d260-11e8-9721-9ffb8cd810f0.png)

**Comment by mlewand** [comment]
I can confirm the issue. Looks like it happens with pretty much any unicode characters, I was able to reproduce the problem with some Polish characters too.

**Comment by mlewand** [comment]
@Adrienb91 I had a quick look at this and I was able to come with a workaround to this problem, you can temporarily apply it yourself before we come with a upstream fix, it's enough to adjust [`CKEDITOR.plugins.mentions.configDefinition.pattern`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions_configDefinition.html#property-pattern) property, like so:

```js
mentions: [ {
	feed: ['Anna', 'Anęmość', 'Thomas', 'John'],
	minChars: 0,
	pattern: /\@[a-zA-Z0-9_À-ž]*$/
} ]
```

That should cover you with diacritics you're looking for. Here's an example (it uses Polish diacritics but feel free to adjust the config to include any other entries): https://codepen.io/mlewand/pen/PyRQOE

**Comment by Adrienb91** [comment]
@mlewand : Thanks a lot, it works like a charm !

I've added spaces and & character : `pattern: /\@[a-zA-Z0-9_\s&À-ž]*$/`
