### ISSUE TITLE
Changing text color on iOS with divarea plugin doesn't work

### ISSUE THREAD

**Issue by mark-wade** [ckeditor/ckeditor-dev#2492]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to an CKEditor 4 instance with both the **divarea** and **colorbutton** plugins **using an iOS device**.
2. Highlight some text and try to use the color button on the toolbox to change the font color of the highlighted text.

### Expected result

The highlighted text changes to the selected color.

### Actual result

Nothing - the text color does not change.

## Other details

* Browser: Safari
* OS: iOS
* CKEditor version: 4.10.1
* Installed CKEditor plugins: Basic preset + divarea + colorbutton

**Comment by jacekbogdanski** [comment]
Hello,

actually, it seems like the issue is caused by `inline` editor, not `divarea` plugin. It's already reported at #948.
