### ISSUE TITLE
Add a way to fetch multiple keystrokes for a single command

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#2493]
## Type of report

Feature request

## Provide description of the new feature

Some commands might have multiple hotkeys, we need to API that returns all the hotkeys.

There's already a [`editor.getCommandKeystroke`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-getCommandKeystroke) but it supports only one returned keystroke.

An example case is link command. In 4.11.0 we added <kbd>ctrl+k</kbd> keystroke in addition to already existing <kbd>ctrl+l</kbd>.

What are the options?

* Introduce `asArray` (or `returnMultiple` or something like that) parameter that tells that the function should return an array. (We can't change currently returned value for backward compatibility)
* Introduce complimentary `editor.getCommandKeystrokes` (note plural form).

Looking at above I'm more keen towards additional argument. Adding an extra function will further bloat our docs.

**Comment by Comandeer** [comment]
I'd also go with parameter, `returnMultiple`. Having two functions with nearly identical names and different options could be very confusing.
