### ISSUE TITLE
No access to CKEditor ("This site can't be reached")

### ISSUE THREAD

**Issue by lwcorp** [ckeditor/ckeditor-dev#2495]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. My site's editor uses https://cdn.ckeditor.com
2. I enter through my browser to any page or subdomain of https://ckeditor.com

### Expected result

1. My editor should be loaded
2. The site should be seen by my browser

I'd like to mention that other people in country and even ISP are able to enter the website.
If you for any reason blacklisted my specific IP address (or range), please write a relevant message and tell me how to whitelist it.

### Actual result

1. My editor just remains blank and it renders my website obsolete for new content
2. My browser displays "This site can't be reached"
![no host](https://user-images.githubusercontent.com/1773306/47207649-6f41bd80-d394-11e8-82e0-1f4ddd80e1b1.png)
![site can t be reached](https://user-images.githubusercontent.com/1773306/47207650-6f41bd80-d394-11e8-98bf-2997a53cae6f.png)

## Other details

* Browser: Chrome 70, Firefox 62, Edge 42, Internet Explorer 11
* OS: Windows 10 64-bit
* CKEditor version: Not relevant as I'm also talking about the whole website
* Installed CKEditor plugins: Not relevant as I'm also talking about the whole website

**Comment by mlewand** [comment]
hi @lwcorp, thanks for the report. I can assure you that we're not deliberately blocking you or anyone from our CDN.

We had a DNS issue couple days ago I got an information that it has been fixed and it should be propagated by now.

Do you have a possibility to check whether https://cdn.ckeditor.com or https://ckeditor.com could be resolved from a different device (phone, another computer, smart fride 😉) from the same network? You could also try to [run a following command line: `ipconfig /flushdns`](https://www.noip.com/support/knowledgebase/how-do-i-flush-my-windows-dns-cache/) and see if that helps.

As a quick _workaround_ I know that when the DNS issue hit us few days back a workaround was to set DNS server to Google's DNS (8.8.8.8 and 8.8.4.4) - but I can see how one would not like to switch DNS to the one served by Google.

**Comment by lwcorp** [comment]
Thanks for the quick reply!
ipconfig /flushdns didn't make any difference. I still have no access.
It happens in multiple devices. The only way I got in was by disconnecting my phone from my WiFi and using cellular connection instead, which means a different IP address.

What do you think?

**Comment by vokiel** [comment]
Hi @lwcorp, could you please check OpenDNS (`208.67.222.222`) because it seems that there is an outdated version at Google's DNS (at least for your region).

**Comment by lwcorp** [comment]
Switching DNS will break everything I do online. What can you do make just make it work with my normal ISP DNS? Again, it does work for other users in my ISP.

**Comment by vokiel** [comment]
@lwcorp seems that DNS cache is refreshed now, please check if it's working for you.

**Comment by lwcorp** [comment]
It works, thanks! How come it didn't affect other people from my ISP and geo?

In any case future, can you find a way in the future to produce a related message when trying to access your website? Keep in mind it didn't prevent acess from just the CDN, but from your website in general.

**Comment by clarkks** [comment]
My website is still unable to load cdn.ckeditor.com. We had to temporarily switch to a local copy on our live site. Our dev site cannot connect to cdn.ckeditor.com. Any ideas?

**Comment by mlewand** [comment]
I don't think we're able to change messages provided by the browser in this case. Best what we can do is to react on signals from the community in case if such situation happens 🙂 Thanks for the report.

**Comment by keenminded** [comment]
Hello,
I am having the same exact issue when accessing ckeditor.com or the cdn. I have tried flushing the dns, but to no avail. Everything works when I connect through a different IP address. This is the only website what is inaccessible to us. Please advise, or can you flush the dns on your end as before? Thank you in advance.

**Comment by cha0s** [comment]
This seems to be cropping up again, FYI.

**Comment by cha0s** [comment]
Sorry, it is a DNSSEC issue as the other issue explains. Disabling that in my local bind config:

```
        dnssec-validation no;
```

fixes it. Though, I hate that I have to do so to access this one site ...

**Comment by phanvdam** [comment]
Hi, unfortunately I'm still can't getting connect to cdn.ckeditor.com on Windows, please help!

**Comment by TarunG96** [comment]
HI @lwcorp I'm experiencing this issue again. Can not access https://cdn.ckeditor.com/ , saying this site can not be reached.
![Uploading Screenshot from 2022-01-17 18-28-24.png…]()

**Comment by lwcorp** [comment]
> HI @lwcorp I'm experiencing this issue again. Can not access https://cdn.ckeditor.com/ , saying this site can not be reached.

Appreciated, but I'm not the one who fixed this. I never happened to experience it again after [the fix](https://github.com/ckeditor/ckeditor4/issues/2495#issuecomment-431393078), and right now the link you provided does work for me.

**Comment by TarunG96** [comment]
@lwcorp  or anyone - this link is not opening on a particular ISP only.. any suggestions ?
