### ISSUE TITLE
Copy-Pasting from MS Word on NT10 broken with Firefox

### ISSUE THREAD

**Issue by ccwienk** [ckeditor/ckeditor-dev#2498]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

This problem seems to be very specific to the execution environment. Namely:

- NT 10 (a.k.a. Windows 10)
- Firefox (tested on latest stable)
- Microsoft Word from MS Office 365

If any one of the above-named runtime environments is changed, the bug is not reproducible.

1. Create a document or open an existing Document using MS Word (from MS Office 365)
2. If not present, enter some arbitrary text. Select some text and copy it into the clipboard (CTRL-C or right-click: copy)
3. Open a website embedding CKEditor 4
4. Paste the copied contents

### Expected result

The contents should be pasted with the formatting from the word document (or at least without any formatting as plain-text).

### Actual result

Each line of inserted text is prefixed with some HTML-ish fragments. E.g.:

```
style='font-size: 12.0pt;mso-bidi-font-size: 11.0pt;line-height:107%'>Then the copied text
```

## Other details

* Browser: Firefox (latest as of creation date of this ticket)
* OS: NT 10 (Windows 10) x64 - and ONLY this OS
* CKEditor version: tested with 4.7 and 4.10 (latest available as of creation date of this ticket)
* Installed CKEditor plugins: n/a

As already mentioned above: The bug is only reproducible if copy-pasting from MS Word (Office 365) to Firefox on NT 10.

Any other combination worked without problems.

**Comment by msamsel** [comment]
Hi,

basic editor's config contains [paste from word](https://ckeditor.com/cke4/addon/pastefromword) plugin which converts styles form Word to HTML styles. So it's seems to work as it should. You get styled content to look similar to this in MSWord. If you change font color, size or make some hyperlinks, then all those thins should be properly copied to editor. More information about this plugin you can find [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_pastefromword.html)

You can always paste things as plain text with <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>C</kbd> or force editor to always [paste as plain text](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-forcePasteAsPlainText).

If I understand your case wrongly, then feel free to provide more details in comment to reopen it. :)

**Comment by msamsel** [comment]
Hi,

basic editor's config contains [paste from word](https://ckeditor.com/cke4/addon/pastefromword) plugin which converts styles form Word to HTML styles. So it's seems to work as it should. You get styled content to look similar to this in MSWord. If you change font color, size or make some hyperlinks, then all those thins should be properly copied to editor. More information about this plugin you can find [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_pastefromword.html)

You can always paste things as plain text with <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>C</kbd> or force editor to always [paste as plain text](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-forcePasteAsPlainText).

If I understand your case wrongly, then feel free to provide more details in comment to reopen it. :)

**Comment by ccwienk** [comment]
Hi @msamsel 

I thinks this is a mis-understanding. As I tried to elaborate in my bug report, copy-pasting from MS Word works fine except for the special case of copy-pasting from MS-Word on NT10 with the CKEditor being rendered in a Firefox web-browser.

So in other words:
If copy-pasting on the very same machine (still NT10) from MS-Word, but running Google-Chrome instead of Firefox, pasting works.

It is the very special case of NT10 + Firefox + MS-Word that shows this behaviour.
