### ISSUE TITLE
Editor appends <div id="level-access-access-assistant-highlight-container"></div> to text fields in wordpress when modifying in wp-admin

### ISSUE THREAD

**Issue by rileyjsumner** [ckeditor/ckeditor-dev#2503]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create/open a wordpress instance in chrome, install the Advanced Custom Fields Plugin to the site
2. Create/edit a post with a text field, shows up in either the main text box or ACF text editor
3. Update the page. `<div id="level-access-access-assistant-highlight-container"></div>` will be appended to the end of the textbox
4. Sometimes deleting the `<div/>` from a ACF textbox and updating will cause the `<div/>` to be appended to the main post box at the top.

### Expected result

*WP should save my html as is*

### Actual result

`<div id="level-access-access-assistant-highlight-container"></div>` *is appended to the end of text boxes*

## Other details

* Browser: Chrome
* OS: Windows
* CKE Instance: Wordpress

**Comment by msamsel** [comment]
Hi, Thank you for leaving your bug report.
However, as far as I know the editor used in Wordpress application is not CKEditor. As much as I would like to help, I cannot advise on a product which has not been developed by CKSource.
