### ISSUE TITLE
Unneccessary tags shown on ckeditor bottom bar on click div tag on IE11 browser

### ISSUE THREAD

**Issue by rajnitt** [ckeditor/ckeditor-dev#2509]
## Type of report

Bug

##Issue on Internet Explorer 11. Its not produced on Chrome.

1. click on editor text area, <div> and <p> tags will display on bottom bar of editor.
2. click on <div> tag, unnecessary tags will be display on bar which are not required.

### Expected result
Unnecessary tags must not be display on bar while clicking div tag. expected as chrome.

### Actual result
Unnecessary tags displayed on clicking div tag.

## Other details

* Browser: Internet Explorer 11
* OS: Windows 10
* CKEditor version: 4.9.2

**Comment by msamsel** [comment]
Hi,

I compared IE11 and Chrome, and I see that `elementspath` in both cases looks the same. Please check if mentioned issue might be reproduced here:
http://cdn.ckeditor.com/4.10.1/full-all/samples/ and if so, then please provide some screenshots or details about the issue.

**Comment by rajnitt** [comment]
Here is screenshot on IE11

![issue](https://user-images.githubusercontent.com/11902273/47414853-a565af80-d78f-11e8-8c8e-71f46816fcb5.png)

**Comment by msamsel** [comment]
Thank you for your screenshot.
Tags which appears suggest that you might used 3rd party plugins not supported by CKSource.

Does this issue occurs for you on: http://cdn.ckeditor.com/4.10.1/full-all/samples/ or https://ckeditor.com/ckeditor-4/?

**Comment by rajnitt** [comment]
ok thanks,
Yes its not occur on provided link.

**Comment by msamsel** [comment]
Most probably one of extra added plugins breaks your editor. I advice to take standard or full preset of CKEditor and gradually add 3rd party plugins to your setup. And when you find broken plugin then contact with its author. :)
