### ISSUE TITLE
bbcode is not work in Plugins['font']

### ISSUE THREAD

**Issue by cocody** [ckeditor/ckeditor-dev#2512]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … select any size in Plugins['font']
2. … html change \<span style="72px"\>1234\</span\> in this time
3. … click `view source` become `=72px1234`

### Expected result
[size=72]1234[/size]
*What is the expected result of the above steps?*

### Actual result
`=72px1234`
*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: … 4.10.1
* Installed CKEditor plugins: … BBCode Output Format

## How to fix this?

// bbcode - plugin.js
```javascript
// 141
// before
if (part == 'size') 
    optionPart += '%';

// after
if (part == 'size') {
    if (optionPart.match(/(\d+)%$/)) {
        optionPart += '%';
    } else {
        optionPart += 'px';
    }
}

// 669
// before
var percentValue = value.match(/(\d+)%$/);
if (percentValue) {
    value = percentValue[1];
    tagName = 'size';
}

// after
var percentValue = value.match(/(\d+)%$/);
var pxValue = value.match(/(\d+)px$/);
if (percentValue) {
    value = percentValue[1];
} else if (pxValue) {
    value = pxValue[1];
}
tagName = 'size';
```

**Comment by jacekbogdanski** [comment]
Hello,

As BBCode format has several flavors, the current implementation of this plugin is based on the following specification:

https://www.phpbb.com/community/faq.php?mode=bbcode

which means that the recommended way to style font size is by using percentage values. You change font size format using [`fontSize_sizes`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-fontSize_sizes) configuration option. E.g. 
```javascript
config.fontSize_sizes = '30/30%;50/50%;100/100%;120/120%;150/150%;200/200%;300/3'
```
