### ISSUE TITLE
Pasting over a selection that includes a table working incorrectly

### ISSUE THREAD

**Issue by lkues** [ckeditor/ckeditor-dev#2513]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Copy a line of text.
2. Select text that includes a table.  See attachment.
3. Paste the line of text from Step 1.

### Expected result

Selected text gets replaced with copied text.

### Actual result

Selected text does not get replaced.  Table in the selection is cleared and copied text gets put in the fist cell of the table.  See attachment.
## Other details

* Browser: All
* CKEditor version: 4.7.2
* Installed CKEditor plugins: tableselection

![select-txt](https://user-images.githubusercontent.com/34172584/47431445-d337fd80-d769-11e8-9753-a83644ca6df8.png)

![after-paste](https://user-images.githubusercontent.com/34172584/47431470-e0ed8300-d769-11e8-87de-48a4363a4bd7.png)

**Comment by jacekbogdanski** [comment]
Hello,

I can reproduce the issue by using our latest CKEditor version. This issue may be related to https://github.com/ckeditor/ckeditor-dev/issues/875

The editor is performing paste inside a table. Works fine without `tableselection` plugin

**Comment by f1ames** [comment]
Can confirm with `4.11.3` version:

![table issue1](https://user-images.githubusercontent.com/1061942/53172935-d7283f00-35e6-11e9-930a-4637dda84e84.gif)

**Comment by f1ames** [comment]
Dup of #875.
