### ISSUE TITLE
AutoComplete can not get Chinese characters，不能识别汉字，

### ISSUE THREAD

**Issue by yyz841875845** [ckeditor/ckeditor-dev#2525]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

**Comment by jacekbogdanski** [comment]
Hello,

Autocomplete plugin allows you to create your [custom matching function](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_autocomplete.html#text-test-callback). You may want to use regex matching Chinese characters, e.g.

`
/@[\u4E00-\u9FCC\u3400-\u4DB5\uFA0E\uFA0F\uFA11\uFA13\uFA14\uFA1F\uFA21\uFA23\uFA24\uFA27-\uFA29]|[\ud840-\ud868][\udc00-\udfff]|\ud869[\udc00-\uded6\udf00-\udfff]|[\ud86a-\ud86c][\udc00-\udfff]|\ud86d[\udc00-\udf34\udf40-\udfff]|\ud86e[\udc00-\udc1d]/g
`

if you are refering to [Mentions](https://ckeditor.com/cke4/addon/mentions) plugin, you can also use [custom matching regex](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions_configDefinition.html#property-pattern) which should resolve your issue.

```javascript
config.mentions = [
  {
     feed: [ '不能识别汉字' ],
     pattern: /^[\u4E00-\u9FCC\u3400-\u4DB5\uFA0E\uFA0F\uFA11\uFA13\uFA14\uFA1F\uFA21\uFA23\uFA24\uFA27-\uFA29]|[\ud840-\ud868][\udc00-\udfff]|\ud869[\udc00-\uded6\udf00-\udfff]|[\ud86a-\ud86c][\udc00-\udfff]|\ud86d[\udc00-\udf34\udf40-\udfff]|\ud86e[\udc00-\udc1d]$/
  }
]
```

**Comment by yyz841875845** [comment]
thanks very much
