### ISSUE TITLE
Test typos

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2531]
## Type of report

Task

## Provide description of the task

There is wrongly closed div tag in test:
https://github.com/ckeditor/ckeditor-dev/blob/major/tests/core/editor/manual/commandkeystrokeall.html#L3

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
There are also other typos:

* `tests/plugins/emoji/manual/twoeditors` – step 4. should refer to the second editor, not the first one
* `tests/core/selection/manual/focusnestededitable` – "text text"
