### ISSUE TITLE
Exception on init in /tests/plugins/contextmenu/manual/contentscss

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2533]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open `tests/plugins/contextmenu/manual/contentscss` in Edge.

### Expected result
The test initializes properly.

### Actual result
The test doesn't initialize and there is the error in the console:

```
SCRIPT5007: SCRIPT5007: Unable to get property 'split' of undefined or null reference
```

## Other details

* Browser: Edge 17
* OS: Windows 10
* CKEditor version: 4.11.0

**Comment by msamsel** [comment]
I can reproduce it on IE10

**Comment by engineering-this** [comment]
Occurs in Safari.
