### ISSUE TITLE
Separator in toolbar moves when buttons are hoverd with keyboard

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2546]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open full-all sample
2. Press <kbd>Alt</kbd>+<kbd>F10</kbd>
3. Start to move focus in toolbar with keyboard

![oct-31-2018 09-40-39](https://user-images.githubusercontent.com/9017322/47776049-b95e6380-dcf1-11e8-8cc0-850f91cfc967.gif)

### Expected result

Separators are not moving

### Actual result

Last separator change its position.

## Other details

* Browser: Chrome, IE10
* OS: MacOS, Win7
* CKEditor version: 4.11
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
As @jacekbogdanski notes it's not a recent regression, it was introduced in 4.6.0. I'm surprised we did not noticed it so far.

**Comment by Comandeer** [comment]
Merged into 4.11.2.
