### ISSUE TITLE
Emoji panel styling issues

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2547]
## Type of report

Bug

Emoji panel styles on Firefox require some improvements:

1. Focused input causes outline which increases input size excluding search icon - it doesn't look good because it looks like and input and search icon doesn't create whole component.
1. Emoji symbol preview is cut off from the bottom. It's visible mostly on FF, but Chrome may also look better with some additional padding.

![image](https://user-images.githubusercontent.com/10279586/47776000-9af86800-dcf1-11e8-822f-93d2ba241a4b.png)

**Comment by jacekbogdanski** [comment]
@engineering-this already proposed some improvements for the first point which IMO looks pretty neat: 
![oct-30-2018 17-02-03](https://user-images.githubusercontent.com/10279586/47776496-d5163980-dcf2-11e8-8430-8787f74c6a1d.gif)

**Comment by jacekbogdanski** [comment]
There is a slight jumping when focusing the last category (between heart and flag).
![emojipanel](https://user-images.githubusercontent.com/10279586/47777210-879acc00-dcf4-11e8-8611-2337657f304d.gif)

**Comment by mlewand** [comment]
@jacekbogdanski issue with jumping focus indication will not be solved as a part of this issue, please extract it.
