### ISSUE TITLE
Context menu incorrectly positioned on Firefox

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2548]
## Type of report

Failing test

## Provide description

1. Open `/tests/plugins/contextmenu/manual/keystroke` manual test.
1. Reproduce test steps.

## Expected

Test passes.

## Unexpected

A context menu is incorrectly positioned.

## Other details

It may be a bug, not failing test.

* Browser: Firefox
* CKEditor version: 4.11.0

**Comment by mlewand** [comment]
I see that this is a bug, and the dropdown is not visible at all.
