### ISSUE TITLE
Visible focus jumping when focusing emoji panel category

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2560]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample with emoji panel.
2. Click emoji button.
3. Click the last category.

### Expected result

Emoji panel changes categories smoothly.

### Actual result

There is a slight jumping when focusing the last category (between heart and flag).
![emojipanel](https://user-images.githubusercontent.com/10279586/47777210-879acc00-dcf4-11e8-8611-2337657f304d.gif)

## Other details

* Browser: Firefox
* CKEditor version: 4.11.0
* Installed CKEditor plugins: emoji

**Comment by jacekbogdanski** [comment]
The issue is caused by a doubled focus on the item https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/emoji/plugin.js#L530 

`markItem` calls focus synchronously. It also causes `input` filed outline blinking when opening emoji panel.

**Comment by jacekbogdanski** [comment]
It looks like the issue is already fixed by changes made to emoji panel recently. @engineering-this could you also confirm it, so we can close this ticket and #2580 PR as no longer needed?

**Comment by engineering-this** [comment]
I can't reproduce it any more.
