### ISSUE TITLE
Buttons are activated by clicking them with right button

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#2565]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://sdk.ckeditor.com/samples/classic.html
2. Right click any button inside the toolbar.

### Expected result

Nothing happens.

### Actual result

* Button is activated.
* Additionally native context menu could open.

## Other details

* Browser: IE, Edge
* CKEditor version: 4.5.0+

Seems like it's connected with the fact that clicks are handled by `mouseup` event in IEs: https://github.com/ckeditor/ckeditor-dev/blob/0806fb6c214d78caeda6f5b2ef3f729669b4a009/plugins/button/plugin.js#L32

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/f5699ec9d6ffb82d2a834fdceeaad00d4a363fd4.
