### ISSUE TITLE
Failing tests /tests/core/tools/absoluterectposition

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2566]
## Type of report

Failing tests

## Provide description of the task

Both tests from `/tests/core/tools/absoluterectposition` fails on iOS when run from dashboard. Works fine when tests are executed directly.

## Other details

* Browser: iOS
* CKEditor version: 4.11.0

**Comment by mlewand** [comment]
Closed with #2658.
