### ISSUE TITLE
Emoji dropdown categories buttons scroll whole page

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2571]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open test `/tests/plugins/emoji/manual/dropdown/dropdownfiltering`.
2. Resize browser window to point where scrollbars appear.;
3. Open emoji dropdown.
4. Press category button.

### Expected result

Emoji list is scrolled, but page scroll remains the same.

### Actual result

Whole page is scrolled.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Fixed with #2587.

**Comment by engineering-this** [comment]
As #2587 is merged I'm closing this issue.
