### ISSUE TITLE
Safari: can't focus nested editable

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2574]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample/test with widget that has a nested editable.
`/tests/plugins/widget/manual/nestedautoparagraphing`
`/tests/plugins/widget/manual/block`
2. Focus editor.
3. Focus nested editable.

### Expected result

Nested editable should be focused.

### Actual result

Nested editable is not focused.

![nov-05-2018 16-13-59](https://user-images.githubusercontent.com/23366849/48006594-0db07b80-e116-11e8-87f5-024c19e919ca.gif)

## Other details

Clicking multiple times will eventually focus nested editable.

* Browser: Safari 12.0
* OS: macOS 10.14
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
@engineering-this I cannot reproduce this issue
My environment:
Safari: Version 12.0 (13606.2.11)
MacOS HighSierra: 10.13.6 (17G65)
Tested with current master (7aee701b5), and 4.11.2

Please check if issue is possible to reproduce on your side and if not then please close the ticket.

**Comment by engineering-this** [comment]
I can't reproduce it anymore.
