### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by s458f** [ckeditor/ckeditor-dev#2590]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
local file ckeditor.js could not be imported successfully,but the remote file (https://cdn.ckeditor.com/4.11.0/standard/ckeditor.js) works well.

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
