### ISSUE TITLE
Page break support for pastefromword

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2598]
## Type of report

Feature request

## Provide description of the new feature

MS Word allows users to insert [page break](https://support.office.com/en-us/article/insert-a-page-break-7613ff46-96e5-4e46-9491-40d7d410a043). It's possible to find out if document have page break by `<br clear=all style='mso-special-character:line-break;
page-break-before:always'>` element available from clipboard. It may allow us to preserve page breaks inside editor by extending `pastefromword` with correct filter.

The feature should produce the same HTML output for page breaks like [Page Break](https://ckeditor.com/cke4/addon/pagebreak) plugin.

You can use [pagebreak_sample.zip](https://github.com/ckeditor/ckeditor-dev/files/2566626/pagebreak_sample.zip) for tests.

## Preview / Demo

Users interested in seeing how the feature looks today can preview it [here](https://ckeditor4-preview.ckeditor.com/t/2598/samples/index.html).

**Comment by mlewand** [comment]
Note there's already a solution proposed for that. The enhancement can be previewed at https://ckeditor4-preview.ckeditor.com/t/2598/samples/index.html
