### ISSUE TITLE
Typing after selecting a complete list disables the input

### ISSUE THREAD

**Issue by lucash** [ckeditor/ckeditor-dev#2599]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open ckeditor sample page of the current version, e.g. http://cdn.ckeditor.com/4.11.1/full-all/samples/index.html
2. Add a bullet list.
3. Add at least two items to the bullet list, e.g. "a" and "b".
4. Select the complete list (from the start of the first item until the end of the last item), either using the mouse or using the keyboard.
5. Type anything, e.g. "x".

### Expected result

All bullet points except one disappear and what you are typing is added as content to the remaining bullet point.

### Actual result

All bullet points disappear and what is typed does not appear. However a caret is blinking at the position where I would expect it (indented as if there was a bullet point).

## Other details

* Browser: Firefox version 62.0.2 and 63.0.1
* OS: macOS 10.13.6
* CKEditor version: 4.11.1, also happens with 4.9.2 and 4.10.1
* Installed CKEditor plugins: As configured in the sample page.

![ckeditor_list_bug](https://user-images.githubusercontent.com/68697/48338342-afc7ea80-e665-11e8-93c8-7fa021b4c4b7.gif)

**Comment by jacekbogdanski** [comment]
Hello,

As I can see the issue is not related to CKEditor but Firefox upstream. You can verify it by reproducing your steps using https://codepen.io/anon/pen/bQBVzM

I already reported this upstream on Firefox issue tracker, please follow updates on it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1506536
