### ISSUE TITLE
ckeditor5 pre code or highlight.js | prism.js

### ISSUE THREAD

**Issue by woisk** [ckeditor/ckeditor-dev#2601]
How to integrate code to highlight? Pre code

HTML, c++, C, PHP
![image](https://user-images.githubusercontent.com/18644664/48395078-ef1f3580-e750-11e8-9ae0-c4c1f52de832.png)

**Comment by Comandeer** [comment]
This repository is dedicated for issues in CKEditor 4. If you want to post an issue or feature request for CKEditor 5, please do it in [appropriate repository](https://github.com/ckeditor/ckeditor5).
