### ISSUE TITLE
Mentions plugin doesn't work with non-latin characters

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor-dev#2605]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I use greek words for mentions plugin, together with minChars: 0. If I type '@', every word is displayed, including the greek ones. Then, I type a single greek character.

### Expected result

Matching greek words should be displayed.

### Actual result

No matching word is displayed.

## Other details

This happens with all 3 options for data feed (array, backend URL and function callback). I was surprised that it didn't work with backend URL and function callback, since I am responsible for the matching for these 2 options. However, the plugin doesn't recognise that a character was typed, because in function(options, callback) I have console.log(options) and nothing is being logged when I type a greek character. It doesn't matter if the greek character is first or in the middle of the word,

* Browser: Firefox 63 x86
* OS: Windows 7 x86
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Mentions

**Comment by jacekbogdanski** [comment]
Hello,

Unfortunately, we can't create a regex which will accept almost every character thus with each allowed rule, we decrease its performance - which shouldn't take place where the most of the plugin users probably won't use greek characters with Mentions feature.

However, Mentions plugin is pretty configurable and you can create your own matching pattern that suits your needs. It's as easy as adding additional [`pattern`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions_configDefinition.html#property-pattern) property to Mentions configuration. E.g. to extend Mentions instance with greek numbers, you should be fine with `/@[_a-zA-Z0-9À-žα-ωΑ-Ω]*/` - taking into account that you are using Mentions with `@` marker and 0 minimal characters.

**Comment by Wizard13** [comment]
The pattern property was exactly what I needed. Thanks!
