### ISSUE TITLE
Excel content is not correctly recognized by pastefromword plugin

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2609]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open/create a file with MS Excel formatted content.
2. Select the whole document.
3. Paste content from the clipboard into an editor.

### Expected result

Pasted content retains formatted content.

### Actual result

Pasted content is a plain text.

## Other details

It looks like Excel content is not recognized by Safari, IE8 by `pastefromword` regex:
https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/pastefromword/plugin.js#L77

* Browser: Safari, IE8
* CKEditor version: 4.11.2
* Installed CKEditor plugins: pastefromword

**Comment by mlewand** [comment]
Reading the above I'm not sure about this. Both cases are clearly upstream browser issues.

* Safari doesn't handle `text/html` data transfer properly - it doesn't include full HTML structure, where `meta` tag indicating Word Processor is included.
* IE8 doesn't support data transfer at all, and doesn't include any reasonable way for us to detect that it's a Office originated content.

Now as for proposed workaround for Safari, it is perfectly valid for just any app to put HTML and an image to clipboard at the same time.

I'm more keen to report the upstream to Safari and consider it a known limitation for IE8 as it is not supported anymore.

**Comment by Comandeer** [comment]
Ok, I reported issue to WebKit bug tracker: https://bugs.webkit.org/show_bug.cgi?id=191836

In case of IE8, nothing can be done and it will haunt us forever… and ever…
