### ISSUE TITLE
Extend Advanced plugin with download attribute

### ISSUE THREAD

**Issue by HRPortalteam** [ckeditor/ckeditor-dev#2616]
## Type of report

Feature request

## Provide description of the new feature
HTML 5 attribute [download](https://www.w3schools.com/tags/att_a_download.asp) offeres a great benefit for authors and readers alike. w3schools.com lists today a good supported by major browser. Adding it as an option on "Advanced" tab would provide a clear benefit  for us. 

*What is the expected behavior of the proposed feature?*
An additional field in "Advanced" for Link plugin. An optional checkbox for download. If ticket the attribute is added to the link.

**Comment by engineering-this** [comment]
Hi there,

Feature you are requesting is already existing in CKEditor.  Go to Link Dialo, choose Advanced Tab and find checkbox labeled as `Force Download`.

![screenshot 2018-12-04 at 11 41 33](https://user-images.githubusercontent.com/23366849/49436577-c3282a80-f7b9-11e8-91f6-5cbef206c518.png)

**Comment by HRPortalteam** [comment]
Thanks a lot for your assistance!!!
