### ISSUE TITLE
why IE8/9 can't parse response JSON

### ISSUE THREAD

**Issue by wangyang2010344** [ckeditor/ckeditor-dev#2619]
![image](https://user-images.githubusercontent.com/5354225/48964877-37114880-efec-11e8-8717-b0a17ce955ae.png)

but it can work on IE10+，and other browser

**Comment by mlewand** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
