### ISSUE TITLE
Failing tests in tests/plugins/tabletools/allowedcontent in built version

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#2621]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

1. Run http://tests.ckeditor.test:1030/tests/plugins/tabletools/allowedcontent

### Expected result

All tests passes

### Actual result

All tests fail with "Unexpected error: menu.items[0].getItems is not a function" error, due to the fact that now "Paste" is the first item in the menu.

## Other details

* CKEditor version: 4.11.2
* Installed CKEditor plugins: tabletools, clipboard

**Comment by mlewand** [comment]
Merged with #2623.
