### ISSUE TITLE
Issue with config option contextmenu_contentsCss

### ISSUE THREAD

**Issue by kapilgupta77** [ckeditor/ckeditor-dev#2627]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
The newly introduced config option to provide path of custom css class for styling context menu breaks the rendering of menu items if the path to default css(editor.css) is not provided along with it.

`config.contextmenu_contentsCss  = [CKEDITOR.basePath + 'skins/moono/editor.css', CKEDITOR.basePath+'context-menu.css'];`

### Expected result

The expectation is that the config should take path to extra css class and not the default editor.css file

### Actual result

The rendering of context menu fails if editor.css file is not provided

## Other details

* Browser: All
* OS: Window
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Default

**Comment by Comandeer** [comment]
This property works the same way as [`config.contentsCss`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss) one. The requirement to pass also the default stylesheet allows developer to completely overwrite styles of the context menu, not only to add new styles.
