### ISSUE TITLE
Paste Not Working for First Time in Edge Browser

### ISSUE THREAD

**Issue by shortPause** [ckeditor/ckeditor-dev#2635]
## Type of report

Bug
I'm trying to paste a text on CkEditor but it's not working. Neither CTRL+V Nor Right Click & paste works. This is happening on the very first time when application loads and once it loads and if I try again copying and pasting it then works i.e. on second attempt of copy & paste it's working fine!

Also, the right click and paste is enabled for the first time and once paste is selected then nothing happens and paste also becomes disabled also the copied text somehow disappears from clipboard and it's not there anymore so can't paste anywhere else also!

Ironically the same thing is working fine on Chrome but it's not on Edge Browser(Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134)

Tried browsing online but out of luck yet as similar issues were raised with CkEditor but fixed past 4.2 version and I'm using Version 4.9

Opened the same issue on [Stack](https://stackoverflow.com/questions/53317628/paste-not-working-first-time-on-ckeditor-on-edge-browser) also.

## Provide detailed reproduction steps (if any)

1. Copy something
2. Open CkEditor in Edge
3. Try to Paste which was copied in Step 1

### Expected result

*What is the expected result of the above steps?*
The content should get pasted in the editor

### Actual result

*What is the actual result of the above steps?*
Content not getting pasted in editor and even clipboard is getting cleared after this!

## Other details

* Browser: Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134
* OS: Windows 10 Enterprise
* CKEditor version: 4.9.1
* Installed CKEditor plugins: …

**Comment by shortPause** [comment]
@jswiderski thanks for acknowledging this as a bug but for upgrading the version >4.9.1 I need to check the feasibility of how much effort will it take. I'll get back to you on this once I'm done upgrading the version and see if that works or not. Also, could you possibly advise/know a workaround if any to fix this in current version!

**Comment by jswiderski** [comment]
> Also, could you possibly advise/know a workaround if any to fix this in current version!
@shortPause current version is always the latest version (4.11.1 at the time of writing) which has this problem fixed. If you were asking about 4.9.1 then there is no fix or workaround for that version and the solution is to upgrade the editor.

**Comment by jacekbogdanski** [comment]
We are not providing backward bug patches for the editor. The issue can be resolved by upgrading CKEditor4 to the latest version.
