### ISSUE TITLE
Invalid internal links in documentation 

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2636]
## Type of report

Task - documentation improvements

## Provide description of the task

With new link validator in Umberto, there was exposed issues with link used in documentation. There is incorrect hash fragment which doesn't point user to proper place:
* https://github.com/ckeditor/ckeditor-dev/blob/7c937e875c35b9bd333fcc5de9c0910a2584ad34/plugins/easyimage/plugin.js#L589
* https://github.com/ckeditor/ckeditor-dev/blob/7c937e875c35b9bd333fcc5de9c0910a2584ad34/plugins/codesnippet/plugin.js#L245

Links should be replaced with `{@glink ...}` macro, which points to guides for given project

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Merged with #2654.
