### ISSUE TITLE
Show current color in the Color Dialog

### ISSUE THREAD

**Issue by usmanlogin** [ckeditor/ckeditor-dev#2639]
## Type of report

Feature request.

## Provide description of the new feature

1. Apply color to text from Color Dialog 
2. Re open the Color Dialog and already applied color is not set in hex code input box.

### Expected result

Color Dialog should show the already applied color value in the hex code input box

### Actual result

You can only apply the color to text but cannot retrieve the color value.

## Other details
![2018-11-30_17h49_36](https://user-images.githubusercontent.com/14976613/49292148-4998ef80-f4ce-11e8-8aa3-b0602d8c9201.png)

* Browser: CHROME
* OS: WINDOWS
* CKEditor version: latest
* Installed CKEditor plugins: colorbutton

Edit:

Consider https://github.com/ckeditor/ckeditor-dev/issues/2639#issuecomment-445239796

**Comment by usmanlogin** [comment]
Sir any solution on this ?

**Comment by engineering-this** [comment]
Hello,

I've changed issue to Feature Request.

**Comment by engineering-this** [comment]
When implementing this feature it would be nice to add a line of recently used custom colors in color button.
