### ISSUE TITLE
Fix links and mentions to SDK with Examples

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2640]
## Type of report

Task - fix docs

## Provide description of the task

After merging sdk-port to ckeditor-docs, some links to sdk should be also replaced/correct in ckeditor-dev.

related to:
https://github.com/ckeditor/ckeditor-docs/pull/184

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Merged into 4.11.3.
