### ISSUE TITLE
Nested editable can't be focused under certain circumstances

### ISSUE THREAD

**Issue by mflorea** [ckeditor/ckeditor-dev#2655]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/w08o1reL/11/ in **Chrome**.
2. Click over "foo". The nested editable is focused as a result.
3. Click just above the widget (above the black border of the widget). The nested editable looses the focus as a result.
4. Click again over "foo".

### Expected result

The nested editable is focused.

### Actual result

The nested editable gets the focus for a fraction of a second but then it looses it.

## Other details

* Browser: Chrome
* OS: Any
* CKEditor version: 4.11.1
* Installed CKEditor plugins: wysiwygarea, widget, **copyformatting**

Note that:
* the issue doesn't reproduce if I remove the **copyformatting** plugin. This makes me think that this issue is related to #2470
* the issue doesn't reproduce if I replace the **padding** on the body element with **margin**. The default CKEditor content CSS [is using margin](https://github.com/ckeditor/ckeditor-dev/blob/4.11.1/contents.css#L19) so you may not be affected by this issue if you don't use **fullPage** or if you use **fullPage** and you don't have padding on the body tag.
* the issue doesn't reproduce on Firefox

**Comment by mflorea** [comment]
You can also check this video https://drive.google.com/file/d/1Voj7yMyy6oEtbFyQNlB_9Sj94vF_joBI/view .

**Comment by Comandeer** [comment]
Thanks for the report, I can confirm the issue in Chrome 71.

**Comment by Comandeer** [comment]
The issue was fixed by #2792. The fix will be released in 4.11.3.
