### ISSUE TITLE
Snippet code changed into text 

### ISSUE THREAD

**Issue by yusf786** [ckeditor/ckeditor-dev#2660]
## When ever i add code snippet and submit it to my database it will added but changed into plain text

how to get rid of this i want to add snippet into same column where my blog is placed

## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser:chrome
* OS:windows
* CKEditor version:4.11.1
* Installed CKEditor plugins:code snippet

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
