### ISSUE TITLE
Python Support Ckfinder ?

### ISSUE THREAD

**Issue by ufo911** [ckeditor/ckeditor-dev#2661]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

Please add support for Python for Ckfinder and CKeditor

**Comment by mlewand** [comment]
CKEditor already supports python in a sense that it is a JS library, so it can be served using any language as long as it gets served to the browser.

As for CKFinder this is not a repository for tracking CKFinder feature requests. I have reposted your request to a proper repostiry ckfinder/ckfinder#378 - subscribe the issue and keep an eye on it there.
