### ISSUE TITLE
Image caption cannot be editable issue with Bootstrap Modal

### ISSUE THREAD

**Issue by NingerJohn** [ckeditor/ckeditor-dev#2662]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
1.  I use ajax to async request html structrue from server, generally like this
```html
...
<div class="col-sm-10">
    <textarea class="form-control" placeholder="" name="question_description" id="question_description"></textarea>
</div>
...
<script type="text/javascript">
    CKEDITOR.replace('question_description');
</script>
```
2. Use JQuery ```html()``` insert above html elements into the current page, the ckeditor is shown and with no error in ```Chrome Console```
3. Image caption dialog is shown after image tool was clicked.
**However every input element in the image caption dialog is not editable  even after I uploaded an image**

## Expected result
Image caption dialog can be editable ( **Q: Was I using it wrongly? Or this is a bug issue?** )

## Actual result
Every input element in the image caption window is not editable

## Other details
```
CKEditor : 4.11.1
Chrome : 69.0.3497.100 (64 bit)
```

**Comment by jacekbogdanski** [comment]
Hello,

I see you resolved the problem, but to be sure I already prepared example showing that the issue doesn't exist: https://codepen.io/jacekbogdanski/pen/madgbL

**Comment by NingerJohn** [comment]
Attached the solution, for those who may came here and need.
```
$.fn.modal.Constructor.prototype.enforceFocus = function () {
    var $modalElement = this.$element;
    $(document).on('focusin.modal', function (e) {
        var $parent = $(e.target.parentNode);
        if ($modalElement[0] !== e.target && !$modalElement.has(e.target).length
            // add whatever conditions you need here:
            &&
            !$parent.hasClass('cke_dialog_ui_input_select') && !$parent.hasClass('cke_dialog_ui_input_text')) {
            $modalElement.focus()
        }
    })
};
```

> [Solution from Mr.Pavel Kovalev on stackoverflow](https://stackoverflow.com/questions/22637455/how-to-use-ckeditor-in-a-bootstrap-modal/23667151#23667151)
