### ISSUE TITLE
Inline mode dose not use stylesheet from textarea element while other elements are okay

### ISSUE THREAD

**Issue by NingerJohn** [ckeditor/ckeditor-dev#2665]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. I use textarea element as following, and I tried to give textarea style from css file or style attribute
```html
<textarea id="test" style="width:500px;border:1px solid black;height:200px;">
</textarea>
```
2. ckeditor initializing code as following:
```javascript
<script type="text/javascript">
    CKEDITOR.inline('test');
</script>
```
3. And then a large textarea box being initialized then turning into an input like element, which has very different style from original textarea box

### Expected result

Using stylesheet of textarea as ckeditor box

### Actual result

Only works on h1, div element, etc

## Other details

* Browser: Chrome
* OS: Win10
* CKEditor version: 4.11.1 - standard package ( Downloaded from official site **https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.11.1/ckeditor_4.11.1_standard.zip** )

**Comment by jacekbogdanski** [comment]
Hello,

CKEditor is initialized outside of the initial element. Just wrap your code with additional wrapper:
```html
<div style="width:500px;border:1px solid black;height:200px;">
  <textarea id="test"></textarea>
</div>
```

**Comment by NingerJohn** [comment]
@jacekbogdanski Thank you for your reply. Hope the above solution could be pointed out in the Official Documentation. At the beginning, I thought I was doing wrongly.
