### ISSUE TITLE
image2: dialog allows resizing beyond minimum allowed size

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2673]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open test http://localhost:1030/tests/plugins/image2/manual/resizer
1. Scroll to last editor.
1. Double click on image to open dialog.
1. Enter values:
`width: 1`
`height: 1`
1. Press `OK`.

### Expected result

Alert appears saying that minimum allowed width/height is 15px.

### Actual result

Dialog validation passes and image is very small.

## Other details

https://github.com/ckeditor/ckeditor-dev/blob/7c937e875c35b9bd333fcc5de9c0910a2584ad34/plugins/image2/plugin.js#L1317-L1322

Image resizer can resize to minimum 15px width/height, however image dialog doesn't implement this in any way.

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
I will fix this with #2048 as same logic should be applied on max size.

**Comment by mlewand** [comment]
Why would you want it to restrict you from setting such size? By default the plugin does not care about that.

**Comment by engineering-this** [comment]
Resize handler restricts width/height to not less than 15px, see:

https://github.com/ckeditor/ckeditor-dev/blob/7c937e875c35b9bd333fcc5de9c0910a2584ad34/plugins/image2/plugin.js#L1317-L1322

So at first I realised it should have same limitations when using dialog.

**Comment by mlewand** [comment]
Well these two things aren't really related. So unless there's no dedicated config feature, the dialog should allow for whatever dummy value the user sets.
