### ISSUE TITLE
Isn't able to enable Media Embed

### ISSUE THREAD

**Issue by newpen** [ckeditor/ckeditor-dev#2674]
## Media Embed and Auto Embed not working

https://ckeditor.com/docs/ckeditor4/latest/examples/mediaembed.html

Documentation stated that 

> "When either Media Embed or Semantic Media Embed plugin is enabled and the content provider is configured, the   button is automatically added to the toolbar. "

. I downloaded with the plugins "mediaembed" and autoembed" included.  And added the line `config.embed_provider = '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}';` in config.js

However, the embed button does not appear. Also, when pasting youtube url on the editor, `ckeditor.js:21 [CKEDITOR] Error code: autoembed-no-widget-def.` is shown on the Chrome's console.

**Comment by mlewand** [comment]
It looks like you don't have the `embed` loaded. Make sure that you add it using `config.plugins` or `config.extraPlugins`. See https://ckeditor.com/docs/ckeditor4/latest/guide/dev_plugins.html for more details.
