### ISSUE TITLE
Add an option to `numberedlist` command

### ISSUE THREAD

**Issue by marinatells** [ckeditor/ckeditor-dev#2679]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

Add possibility to pass `start` attribute for editor command `numberedlist`, provided in list plugin.

example of possible use case:
```html
// user selection
<p>item 1</p>
<p>item 2</p>
```
```js
editor.execCommand('numberedlist', {start: 5});
```
```html
<ul start="5">
    <li>item 1</li>
    <li>item 2</li>
</ul>
```

**Comment by Comandeer** [comment]
`list` plugin is intended only to create lists, all style-related features are located in [`liststyle`](https://ckeditor.com/cke4/addon/liststyle) plugin. Adding options to the commands would duplicate its functionality.
