### ISSUE TITLE
Correct docs for bender.tools.createTestsForEditors

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2684]
## Type of report

Task

## Provide description of the task

```
/**
 * Multiplies inputTests for every editor.
 *
 * @param {Object} editorsNames editors definitions.
 * @param {Object} inputTests Tests to apply on every editor.
 * @param {Boolean} isolateTests If set to `true` each test is run on new editor instance.
 * @returns {Object} Created tests for every editor.
 */
```

At first it annoyed me, that when I omit `isolateTest` IDE is highlighting it because `Invalid number of arguments, expected 3`, but in fact it's optional, so it should be marked as optional in docs.

After looking at docs above I thought we can add more fixes.
1. `editorNames` type can be changed to Array.
2. `inputTests` type can be specified as `{Object.<String, Function>}`.
3. `isolateTests` can be marked as optional with default value: `[isolateTests=false]`

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Merged into 4.11.2.
