### ISSUE TITLE
Content lost while pasting numbered list from MS Word with decimal character in content

### ISSUE THREAD

**Issue by kapilgupta77** [ckeditor/ckeditor-dev#2690]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
If a numbered list contains a decimal number and the number before decimal is same as list index then the character before decimal is stripped after pasting in CKEditor
1. Create a numbered list in MS word as shown below with two items

	 
         1. This is 1.0 here
         2. This is 2.0 here

2. Copy the list content and paste it any CKEditor sample

### Expected result

The list content should be pasted without any stripping of content

### Actual result

The number before decimal is stripped 

         1. This is 0 here
         2. This is 0 here

## Other details

* Browser: Chrome
* OS:Windows
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Default

**Comment by engineering-this** [comment]
I can confirm this issue.

**Comment by mlewand** [comment]
I'm not entirely sure if we'll be able to fix it in 4.11.2 but we'll do our best to do so.

**Comment by Comandeer** [comment]
The fix was merged to the `master` and will be released in 4.11.2.
