### ISSUE TITLE
Switching Source on/off breaks "script" element for plug-in usage

### ISSUE THREAD

**Issue by JanisE** [ckeditor/ckeditor-dev#2708]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. adding `script` element (along with others) by a custom plugin
2. switch the source view on and off

### Expected result

The plugin should still access all the content of the plugin's wrapper element in `onOk` method (by `this.element.$`).

### Actual result

In `onOk` method, `this.element.$` does not contain the `script` element normally, I cannot access it anymore to update. It appears commented out and URL-encoded. (Starts with `<!--{cke_protected}%3Cscript%20.`)

The other elements can still be accessed all right (although the whitespace content of `innerHTML` has changed, but that is not important).

## Other details

* Browser: Firefox, Chrome
* OS: Linux Mint (Ubuntu)
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Full package build, pasteFromGoogleDoc, the custom plugin I'm talking about above

**Comment by jacekbogdanski** [comment]
Hello,

we are not supporting `script` elements inside the editor. If you need to extend CKEditor4 functionality, it should be done via plugins, not script injection.

**Comment by JanisE** [comment]
@jacekbogdanski , I'm not trying to change editor's functionality by those `script` elements. They are supposed to be added as is, as part of the input content.

The plug-in I'm talking about is inserting those `script` elements (along with other allowed elements like `a`, `div` etc.). That `script` element seems to get saved and retrieved later all right.

The only problem is that plugin's `onOk` method gets that specific element encoded as a comment in `this.element.$`, all the other elements are all right. This is a problem if I want to select and modify the `script` element upon a content update.

I can still find that comment and modify as a text, but it seems more like a work-around, so I thought there is a better way.

**Comment by jacekbogdanski** [comment]
As I understand you are trying to insert raw `script` element into editors content? If so, HTML can be represented by using [code snippet](https://ckeditor.com/cke4/addon/codesnippet) functionality. In other cases it shouldn't be allowed as a part of editor thus it doesn't have visual nor functional representation except obviously JavaScript injection which is dangerous and can't be allowed.

If you need to implement some dynamic functionality inside editor, use event listeners instead.

**Comment by JanisE** [comment]
* Yes, I want to insert raw `script` element into the content.
* No, I don't want it to be actually executed in the editing mode / editor (it is to be executed when the post/content is displayed (later) in the view mode outside the editor).
* No, I don't want the code to be displayed as a code snippet (the `script` element should be invisible while editing in rich text mode, it should be visible in the Source view mode).
* I do not want to enforce any JS injection checks at editor level (it wouldn't be safe anyway).

So, the plugin is based on this `abbr` plug-in: https://github.com/ckeditor/ckeditor-docs-samples/tree/master/tutorial-abbr-2/abbr

Only instead of `abbr` element, my plug-in inserts/updates another HTML structure (wrapped within a `div` element) which contains also a `script` element (which should not execute inside the editor, but should be sent as part of the `textarea` value in the form submit request).

And again – the `script` element seems to be handled cleanly by default, no encoding, in `onOk` method, `this.element.$.querySelector('script')` returns the actual `script` element all right – except if HTML mode is switched on/off – only after that the `script` turns up encoded as a comment (and apparently decoded again in the original textarea field).
