### ISSUE TITLE
waitForImage should call callback if image is already loaded

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2714]
## Type of report

Task

## Provide description of the task

Test tool `waitForImage` calls callback on `load` event, but when image is already loaded this event will never happen, and some browsers might load images earlier than others.

https://github.com/ckeditor/ckeditor-dev/blob/master/tests/plugins/uploadfile/_helpers/waitForImage.js

I propose to add if branch:

```
else if ( image.$.complete )  {
    callback()
}
```

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
To be consistent the callback should be called _asynchronously_ - other than that I think it's an ok enhancement.
