### ISSUE TITLE
Numbered list items get reversed when using backspace key

### ISSUE THREAD

**Issue by lkues** [ckeditor/ckeditor-dev#2721]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/demo/
2. Create an indented numbered list as follows:

![image](https://user-images.githubusercontent.com/34172584/50649229-52f0fe00-0f4b-11e9-9143-a67c552317a6.png)

 
3. Place the cursor at the end of testb.  Press backspace until testa and testb items are deleted.

### Expected result

    1. Test
        1. apples
        2. oranges
        3. pears
        4. lemons 

### Actual result

    1. Test
        1. lemons
        2. pears 
        3. oranges
        4. apples

## Other details

* Browser: Chrome
* OS: Windows 7
* CKEditor version: 4.x

**Comment by engineering-this** [comment]
Reproduced on both `master` and `major` branch.
![jan-04-2019 16-31-38](https://user-images.githubusercontent.com/23366849/50695897-48fbf780-103e-11e9-957f-5e07e88cc17e.gif)

**Comment by engineering-this** [comment]
The culprit:

https://github.com/ckeditor/ckeditor-dev/blob/51f2933d32ff606c85db0aaf7045706c3ebf077a/plugins/list/plugin.js#L527-L537

Depending on `forward` param items are placed after or before `refNode`. If `forward` is falsy items will be traversed from last, and each one is inserted after `refNode`.

So we have two cases
1. `forward==true`
- Take first item, place after `refNode`.
- Take second item, place after `refNode` which is before first item, order is reversed.

2. `forward==true`
- Take last item, place before `refNode`.
- Take n-1 item, place before `refNode` which is after last item, order is reversed.

Solution is to update refNode to match last inserted child.

**Comment by Comandeer** [comment]
Merged into 4.11.3.
