### ISSUE TITLE
Failing test tests/plugins/list/blockconversion

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#2722]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

<img width="578" alt="screenshot 2019-01-04 at 13 00 52" src="https://user-images.githubusercontent.com/1078728/50687239-cdd81880-1020-11e9-93c5-02f2df3d5ede.png">

## Other details

* CKEditor version: 4.11.2 built

**Comment by mlewand** [comment]
Closed with #2728.
