### ISSUE TITLE
Link button in ckeditor not working properly.

### ISSUE THREAD

**Issue by rahimnagori** [ckeditor/ckeditor-dev#2726]
I am using the link button and it seems to not work as it is expected, every time a create a new link it creates the same link again and again : 
![image](https://user-images.githubusercontent.com/42448371/50724707-c2b3e400-1117-11e9-9ccf-ea9f13548ae7.png)

<p><a href="http://google.com" target="_blank">google.</a></p>

this link is created all the time.

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
