### ISSUE TITLE
Cannot open cell properties in standard editor

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2732]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample of build `standard` version of CKE4 (4.11.2) (b7960bbabb73c42c09718a49287618b05281eb99)
2. Add table to editor's content
3. Open `cell properties` from context menu

### Expected result

Cell properties dialog is opened

### Actual result

There is error in console:
`Uncaught TypeError: Cannot read property 'type' of null`

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.11.2
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
The code that caused this regression was reverted in #2735. Related issue #1986 has been reopened.
