### ISSUE TITLE
Deleting more than 1 row not working

### ISSUE THREAD

**Issue by hjsolleza** [ckeditor/ckeditor-dev#2734]
## Type of report

 Bug - Deleting more than 1 row not working

## Provide detailed reproduction steps (if any)

1. Highlight 2 or more cells to delete a row
2. It does not delete the rows highlighted instead creating a new rows above

### Expected result

It should delete the rows highlighted

### Actual result

*What is the actual result of the above steps?*

It creates new rows above

## Other details

* Browser: Firefox 52
* OS: Windows 10
* CKEditor version: 4.6.2
* Installed CKEditor plugins: N/A

**Comment by jacekbogdanski** [comment]
Hello,

removing table works as expected for me - selected rows are removed on backspace/delete keys. Are you able to reproduce the issue using the latest CKEditor4? You can use http://ckeditor.com/latest/samples

**Comment by hjsolleza** [comment]
Hello,

The deletion of rows (more than 1) is working for the latest CKeditor4. 
We will try to deploy a newer version for CKEditor. 

Thank you!

**Comment by jacekbogdanski** [comment]
Great, thanks for checking!
