### ISSUE TITLE
Please remove all arguments.callee

### ISSUE THREAD

**Issue by SuperPat45** [ckeditor/ckeditor-dev#2741]
## Type of report

Task

## Provide description of the task

Like the bug #331, please remove all arguments.callee calls, There are five reaming in:
> adapters/jquery.js
> core/tools.js
> plugins/adobeair/plugin.js
> plugins/dialog/plugin.js
> plugins/find/dialogs/find.js

This prevents CKEditor to work in the strict mode.

**Comment by jacekbogdanski** [comment]
Not sure if it will be possible in all places, but it's worth to do some research and try to replace [deprecated code](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee#Why_was_arguments.callee_removed_from_ES5_strict_mode).
