### ISSUE TITLE
[Docs] Broken rendering in drag and drop example

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-dev#2744]
1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/draganddrop.html
2. Drag and drop an item into the title.
3. The dropped placeholder is ugly:

![image](https://user-images.githubusercontent.com/156149/50969651-741f9480-14df-11e9-9abd-9897c3214a0f.png)

**Comment by mlewand** [comment]
Thanks, it probably got broken during Umberto migration.

Moved the issue to the docs repository ckeditor/ckeditor-docs#209.
