### ISSUE TITLE
More Colors Dialog could start with currently selected color

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2745]
## Type of report

Feature request

## Provide description of the new feature
When you open Color or Background Color Panel and the selected color is on the palette, it gets highlighted. It would be nice if Show More Colors Dialog would have the same feature of starting with currently selected color being shown. 

NOTE: Since More Colors Dialog has more colors than the Color Panel and provided that Panel doesn't keep color value which is not available on the palette, the color would need to be checked based on selection in the editor and not passed from the Panel.

**Comment by f1ames** [comment]
DUP of #2639.
