### ISSUE TITLE
Autolink: TypeError: editor.getSelection(...) is null when typing in source view

### ISSUE THREAD

**Issue by SuperPat45** [ckeditor/ckeditor-dev#2756]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Enable AutoLink and Source Editing Area plugins
2. Goto source view
3. Start typing

### Expected result

Autolink must be disabled in source mode

### Actual result

These exceptions are thrown:
> TypeError: editor.getSelection(...) is null

on firefox
> TypeError: Cannot read property 'getRanges' of null

on chrome

In the line:
`var matched = CKEDITOR.plugins.textMatch.match( editor.getSelection().getRanges()[ 0 ], matchCallback );`

## Other details

* Browser: all
* CKEditor version: latest
* Installed CKEditor plugins: AutoLink and Source Editing Area

**Comment by jacekbogdanski** [comment]
I can confirm the issue, thanks for the report!

**Comment by mlewand** [comment]
Closed in #2814.
