### ISSUE TITLE
[FF/Linux] Copy/paste rows from LibreOffice spreadsheet to table will paste them as image at first row

### ISSUE THREAD

**Issue by antics7** [ckeditor/ckeditor-dev#2758]
## Are you reporting a feature request or a bug?

 Bug

## Provide detailed reproduction steps (if any)

1. Open a spreadsheet in LibreOffice copy/pase some not empty rows.
2. In CKEditor insert a table paste data from step 1 in first table row.

### Expected result

Each row copied will be inserted as a table row in CKEditor. See Chrome behavior below:

![chrome_paste_cke](https://user-images.githubusercontent.com/46753171/51262091-40c58580-1977-11e9-8e73-11ea19e04b00.png)

### Actual result

Copied data is inserted in first row as image. See FF behavior below:

![image](https://user-images.githubusercontent.com/46753171/51262143-5c309080-1977-11e9-9fff-e0350399922f.png)

I have reproduced this in CKEditor 4 demo at https://ckeditor.com/ckeditor-4/demo/#article

## Other details

* Browser: Firefox 64
* OS: Linux (Ubuntu 16.04)
* CKEditor version: 4.7.2.2
* Installed CKEditor plugins: The ones included in CKEditor 4 demo

**Comment by jacekbogdanski** [comment]
Hello,

Pasting from LibreOffice is not officially supported. The issue about the integration is already open, so you can subscribe it to get updates: https://github.com/ckeditor/ckeditor-dev/issues/2374

Also, if you would like to see LO support in CKEditor, I encourage you to give linked ticket thumb up :+1:
