### ISSUE TITLE
Is the Accessibility Checker plugin compatible with CK Editor v4.11

### ISSUE THREAD

**Issue by shahdivyam** [ckeditor/ckeditor-dev#2763]
## Are you reporting a feature request or a bug?
Other 

Accessibility Checker plugin is an official plugin provided and supported by CKEditor developers, in the documentation it is mentioned that it has know compatibility with v4.9. but for higher version 4.10 and 4.11 the plugins compatibility is unknown. (https://ckeditor.com/cke4/addon/a11ychecker). 
As versions 4.10 and 4.11 are higher versions than 4.9, the plugin should be compatible with them as well. 

Can it be confirmed that if the plugin is compatible with versions 4.10 and 4.11 and if there are any issues if the plugin is integrated with v4.10 and v4.11   

## Other details

* CKEditor version: 4.11
* Installed CKEditor plugins: Accessibility Checker

**Comment by mlewand** [comment]
Thanks @shahdivyam for pointing this out. The answer is: it's totally fine with versions above 4.9!

You can actually play with it and latest CKEditor 4.11.2 on our demo page: https://ckeditor.com/docs/ckeditor4/latest/examples/accessibilitychecker.html

I'll make sure we update the supported versions in plugin page.

**Comment by shahdivyam** [comment]
Thanks @mlewand!
