### ISSUE TITLE
CKEDITOR SUGGESTIONS LIST SHOWING LOADING...

### ISSUE THREAD

**Issue by shubhanshujaiswal123** [ckeditor/ckeditor-dev#2764]
If I try to see the suggestion of any word then its only giving me loading ..
can you please tell me whats the issue and how it can be fixed ?

![image](https://user-images.githubusercontent.com/16736939/51374508-e2a8b780-1ac8-11e9-816e-905f5378d8bf.png)

**Comment by msamsel** [comment]
This is a third party plugin not maintained by the CKEditor team.
Please contact with plugin's author to report the problem.
You can report issue in this repository: https://github.com/WebSpellChecker/ckeditor-plugin-wsc/issues
