### ISSUE TITLE
Ignore github folder in dev/builder

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2767]
## Type of report

Task

## Provide description of the task

`.github` folder is copied to release folder by dev/builder.
Folder should be ignored in configuration:
https://github.com/ckeditor/ckeditor-dev/blob/major/dev/builder/build-config.js#L10

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Fixed with #2771.
