### ISSUE TITLE
ckeditor4 filebrowser upload url: url params are not added

### ISSUE THREAD

**Issue by klemens-u** [ckeditor/ckeditor-dev#2768]
I upgraded to CKeditor4 from version 3. Sadly my file and image upload integration does not work anymore.

CKeditor should add some url params as described here: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html

> CKEditor automatically sends some additional arguments to the file manager: 

`CKEditor=editor1&CKEditorFuncNum=1&langCode=en`

That doesn't happen with version 4.

Here is a fiddle with instructions to reproduce: https://jsfiddle.net/5wzh9a08/1/

```
<html lang="de">
<head>

<meta charset="utf-8" />

<script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>

</head>

<body>

<h1>
CKeditor 4 upload problem
</h1>

<p>
Problem: CKeditor 4 does not append "CKEditor=editor1&CKEditorFuncNum=1&langCode=en" to the upload URL.
</p>
<p>
How to reproduce:
</p>
<ul>
<li>Open web developer console in browser</li>
<li>Click (and enable) network tab</li>
<li>In CKeditor: click on image icon</li>
<li>Click "upload", select a file and click "Send to server"</li>
<li>Watch the request in web developer console: the necessary url params are not added.</li>
</ul>
<p>
Reference: <a href="https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html">https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html</a>
</p>

<textarea name="editor1" id="editor1" rows="8" cols="80">
  test 123
</textarea>

<script type="text/javascript">
  CKEDITOR.replace( 'editor1', {
    filebrowserImageUploadUrl: '/upload.html',
  });
</script>

</body>
</html>

```

**Comment by mlewand** [comment]
It is file browser plugin that has this feature. This plugin is responsible for adding the browse button:

![image](https://user-images.githubusercontent.com/5353898/51482577-1caedd80-1d97-11e9-9f87-776df8adb3ae.png)

And it does add the parameters properly, just like it is documented, see https://ckeditor.com/docs/ckeditor4/latest/examples/image.html example:

![image](https://user-images.githubusercontent.com/5353898/51482633-3ea86000-1d97-11e9-8ae1-87be9390a8fb.png)

It What you're doing - you're using a file upload feature which is a different implementation and does not have this implementation.

**Comment by klemens-u** [comment]
Thank you @mlewand, but my problem does not concern the browsing feature.
The problem is with file and image upload using the config variables "filebrowserUploadUrl" and "filebrowserImageUploadUrl". That's the "Upload" tab in your first screenshot.

The functionality is explained here https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html

Please comment on my jsFiddle demonstration using the latest CKEditor4.
Thank you!

**Comment by klemens-u** [comment]
Problem solved. CKEditor4 needs the option
`config.filebrowserUploadMethod = 'form';`

Please update the documentation at 
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html

**Comment by projectmallwall** [comment]
> Problem solved. CKEditor4 needs the option
> `config.filebrowserUploadMethod = 'form';`
> 
> Please update the documentation at
> https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html

Solved my issue, thanks a lot.
