### ISSUE TITLE
API Docs: remove duplicated link to dialogDefinition in CKEDITOR.dialog.add

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2769]
## Type of report

Task

## Provide description of the task

Go to: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog.html#static-method-add and scroll to the end of methods API docs.

![screenshot 2019-01-21 at 13 11 36](https://user-images.githubusercontent.com/23366849/51474050-60491d80-1d7e-11e9-9f8b-ed45060609d0.png)

Link to `dialogDefinition` is duplicated:

https://github.com/ckeditor/ckeditor-dev/blob/aafb4b1d0b1f6f501a95995ac08cae1bfdae9b0e/plugins/dialog/plugin.js#L1564-L1565

**Comment by mlewand** [comment]
Actually it's an upstream cksource/umberto#688. Umberto should support `@see` tag.
