### ISSUE TITLE
divarea editor, when setReadOnly is triggered by mouseclick event paste buttons has wrong state

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2775]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample: https://codepen.io/anon/pen/RvwJLL
2. Check 'Make editor read only'.

### Expected result

Paste buttons are disabled.

### Actual result

Paste buttons are not disabled

This happens because `mouseup` listener on editor.document doesn't take in count editor being read only:

https://github.com/ckeditor/ckeditor-dev/blob/d931efee7bb8875e489c172fa3e20de8e8209aef/plugins/clipboard/plugin.js#L742

https://github.com/ckeditor/ckeditor-dev/blob/d931efee7bb8875e489c172fa3e20de8e8209aef/plugins/clipboard/plugin.js#L1212-L1222

## Other details

This might affect inline editor, however focusing editor makes editor update buttons state, hence it is not visible when toolbar is hidden.

* Installed CKEditor plugins: 'divarea'

**Comment by engineering-this** [comment]
This affects angular integration sample: https://github.com/cksource/ckeditor4-angular/pull/1#issuecomment-456431795

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/460d751f8620ab780e60756c589adfb58673a9f3.
