### ISSUE TITLE
<=CKEditor 4.11.1 'paste from excel table' gets its cell alignment center/right removed

### ISSUE THREAD

**Issue by soethan** [ckeditor/ckeditor-dev#2779]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
 'paste from excel table' gets its cell alignment center/right removed (IE Edge only)

1. Copy the table from Excel sheet (make one table cell alignment to be center/right aligned)
2. Paste in CKEditor
3. center/right aligned cell becomes left aligned.
Note: You can try at https://ckeditor.com/ckeditor-4/demo/#document with IE Edge browser. Other browsers such as Chrome/Firefox are working.

### Expected result

cell alignment should be maintained

### Actual result

cell alignment are reset to left alignment.

## Other details

* Browser: <=IE 11 only
* OS: All
* CKEditor version: 4.11.1 and lower
* Installed CKEditor plugins: paste from excel

**Comment by Comandeer** [comment]
I wasn't able to reproduce it in Edge, but it is reproducible in IE.

**Comment by soethan** [comment]
Hi,
      I had updated Other details section "Browser: <=IE 11 only". The issue happens with IE 11 and below.

**Comment by engineering-this** [comment]
Hi,

Here is a raw HTML output of table with one cell aligned in IE11:

```html
<table width="64" style="width: 48pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0"><font
	color="#000000" face="Times New Roman" size="3">
</font>
	<colgroup>
		<col width="64" style="width: 48pt;">
		<font color="#000000" face="Times New Roman" size="3">
		</font>
	<tbody>
	<tr height="20" style="height: 15pt;"><font color="#000000" face="Times New Roman" size="3">

	</font>
		<td width="64" height="20" style="border: 0px black; width: 48pt; height: 15pt; background-color: transparent;">
			<font color="#000000" face="Calibri" size="3">Foo</font></td>
		<font color="#000000" face="Times New Roman" size="3">

		</font></tr>
	<font color="#000000" face="Times New Roman" size="3">
	</font></tbody>
</table>
``` 

Apparently align style is missing. We can't fix it on editor side, so I'm closing it as an upstream issue.
