### ISSUE TITLE
Undo snapshot is overwritten on selectionChange

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2780]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/latest/samples
2. Change editor content.
3. Make sure that there is at least a single undo step (undo button is not disabled).
4. Start clicking around inside editor (at least 20x) changing a selection.
5. Click undo button.

### Expected result

Undo button is enabled and undoes the last change.

### Actual result

Undo button is disabled.

## Other details

* Installed CKEditor plugins: Undo

**Comment by jacekbogdanski** [comment]
It looks like the issue is caused by `copyformatting` plugin. `applyFormatting` command is executed on `mouseup` event. The command is [integrated with undo by default](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_command.html#property-canUndo), so undo plugin listen on the command execution and creates a snapshot any time it has been used. It **should** be integrated with undo plugin, however, a snapshot should be created only if content really changed.

https://github.com/ckeditor/ckeditor-dev/blob/d931efee7bb8875e489c172fa3e20de8e8209aef/plugins/copyformatting/plugin.js#L103-L107

I already checked against regression and the only regression I found is the addition of the `applyFormatting` plugin into the default config file: https://github.com/ckeditor/ckeditor-dev/commit/9f97b190fcaab80780e720dd1c7681c60d9f7dea

**Comment by engineering-this** [comment]
There is another related issue.

1. Open sample: http://cdn.ckeditor.com/4.11.2/full-all/samples/
2. Focus editor and type one letter.
3. Press `undo`.
4. Change editor selection with mouse.

## Expected
Redo button is active.

## Actual
Redo button is inactive.

**Comment by Comandeer** [comment]
Merged into 4.11.3.
