### ISSUE TITLE
 Paste from Word strips "mailto" links in IE11

### ISSUE THREAD

**Issue by Maxiweb** [ckeditor/ckeditor-dev#2789]
## Type of report
Bug
Copy of https://github.com/ckeditor/ckeditor-dev/issues/1357 basically but for IE11

## Provide detailed reproduction steps (if any)

Go to ckeditor.com demo using IE/Edge
Paste from a Word .docx file that contains an href link and a mailto: link
[testdoc.docx](https://github.com/ckeditor/ckeditor-dev/files/2827743/testdoc.docx)

### Expected result

I expect both links to paste correctly.

### Actual result

The href link pastes fine, but the mailto: link is stripped, and all that remains is <a>email link</a>.

## Other details

* Browser: IE 11 and Edge. 
*  IE/Edge
* OS: Windows 10
* CKEditor version: 4.8.0 standard
* Installed CKEditor plugins: pastefromword

**Comment by mlewand** [comment]
Dup of #1357.
