### ISSUE TITLE
Table resize colomn bug

### ISSUE THREAD

**Issue by PHP-GLOBE** [ckeditor/ckeditor-dev#2790]
## Type of report

Calculation of table width is not correct

## Provide detailed reproduction steps (if any)

1. Create table with at least 4 coloms and a width of 500px
2. resize the last to colomns.
3. check width of the cells (visual we say, the first two cells have no width and are 50% of the 250px, but the 2 resized should be 250 together but aren't. )

### Expected result

*What is the expected result of the above steps?*
A would expect the 2 last colums to have an added width of 250 (plus or min borders)

### Actual result

*What is the actual result of the above steps?*
In my case the to colums are only 238px.

## Other details

* Browser: every
* OS: every
* CKEditor version: 4.11.2
* Installed CKEditor plugins: Does not mater, is the same behaviour in the demo on https://ckeditor.com/docs/ckeditor4/latest/examples/table.html

**Comment by engineering-this** [comment]
Hi.

There is nothing wrong about how cell widths are calculated.

Please look at table default attributes: 
```<table border="1" cellspacing="1" cellpadding="1" style="width: 500px;">```

Using web inspector on default table with 4 columns you will see that first three rows have width of 119px, and last one is 120px. After subtraction of all the borders, paddings and borders you will have 477px of inner space which matches the sum of cell widths.

![screenshot 2019-02-05 at 17 35 52](https://user-images.githubusercontent.com/23366849/52288462-8967d180-296c-11e9-9a73-61940f28767d.png)
![screenshot 2019-02-05 at 17 36 04](https://user-images.githubusercontent.com/23366849/52288465-8a98fe80-296c-11e9-98fc-e10ca9c683a0.png)

You can create same table, but with border, cellspacing and cellpadding set to 0. If you repeat reproduction steps with such table you will find that last two cells has now total width of 250px.

**Comment by PHP-GLOBE** [comment]
Seems odd padding is insit the cell and should be added to the td width???

**Comment by engineering-this** [comment]
It depends on [CSS `box-sizing`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) property.
