### ISSUE TITLE
Chrome/Safari creates selection in text node when using selectAll

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2801]
## Type of report

Feature request to workaround buggy native `SelectAll`

## Provide detailed reproduction steps (if any)

1. Open editor sample.
2. Press <kbd>Command</kbd>/<kbd>Ctrl</kbd>+<kbd>A</kbd>.
3. Check selection ranges.

### Expected result

```[<h1>Hello world!</h1>
<p>I&#39;m an instance of <a href="https://ckeditor.com">CKEditor</a>.</p>]
```

### Actual result

```<h1>{Hello world!</h1>
<p>I&#39;m an instance of <a href="https://ckeditor.com">CKEditor}</a>.</p>
```

## Proposed workaround

As a workaround I propose:
1. Add keystroke to `CKEDITOR.config.blockedKeystrokes`.
2. Move `selectAll` command outside of `selectall` plugin, which should only register a button.
3. Rework command so it creates proper selection.
Probably it will be sufficient to remove `if` branch, and just perform current `else` code for any case:
https://github.com/ckeditor/ckeditor-dev/blob/148b8778816eea03a8f8f356a464751e44da9c92/plugins/selectall/plugin.js#L36-L46
 ## Other details

* Browser: Chrome/Safari

## Edit

Reported to Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=931285

**Comment by mlewand** [comment]
Why would this selection be a problem?

**Comment by engineering-this** [comment]
@mlewand It produces an edge case:
https://github.com/ckeditor/ckeditor-dev/pull/2776#pullrequestreview-201554828

**Comment by Comandeer** [comment]
@engineering-this, as it's reported both to WebKit and Chromium, can we close it as an upstream issue?

**Comment by engineering-this** [comment]
Let's close it for now. If there is any demand for a workaround we can reopen this in the future.
