### ISSUE TITLE
Inserting nbsp (ctrl+space) breaks inline tags

### ISSUE THREAD

**Issue by jurajkapsz** [ckeditor/ckeditor-dev#2805]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Have an inline tag in content, e.g. bold, italic text, link etc; best seen on links, let's go with links.

![image](https://user-images.githubusercontent.com/2209893/52666219-f3085280-2f0d-11e9-9a52-643e786b203b.png)

```<a href="/">This is my link</a>```

2. Insert a nbsp into the inline tag's text by pressing ctrl+space.
3. A nbsp is inserted, but the inline tag is split in two.

![image](https://user-images.githubusercontent.com/2209893/52666307-3bc00b80-2f0e-11e9-9f85-f3e06393e649.png)

```<a href="/">This is</a>&#160;<a href="/">my link</a>```

### Expected result

The inline tag should not be splitted in two.

### Actual result

The inline tag is split in two.

## Other details

* Browser: `Chromium 71, Firefox 65`
* OS: `Ubuntu 18.04`
* CKEditor version: `4.11.2 (happens also in prev. versions like 4.10, maybe earlier too)`
* Installed CKEditor plugins: `'about', 'basicstyles', 'bidi', 'blockquote', 'clipboard', 'contextmenu', 'copyformatting', 'div', 'elementspath', 'enterkey', 'entities', 'floatingspace', 'format', 'horizontalrule', 'htmlwriter', 'iframe', 'image', 'indentblock', 'indentlist', 'justify', 'link', 'list', 'liststyle', 'magicline', 'maximize', 'nbsp', 'pagebreak', 'pastefromword', 'pastetext', 'preview', 'print', 'removeformat', 'resize', 'save', 'selectall', 'showblocks', 'showborders', 'sourcearea', 'specialchar', 'stylescombo', 'tab', 'table', 'tabletools', 'templates', 'toolbar', 'undo', 'wysiwygarea'`

**Comment by jurajkapsz** [comment]
Attaching my CKE build config.

[build-config.js.zip](https://github.com/ckeditor/ckeditor-dev/files/2857681/build-config.js.zip)

**Comment by msamsel** [comment]
Hi,
I have problem with reproducing this case. I test it under MacOS and Win7 and I couldn't recreate this situation.
Could you check if issue appears on editor under this page:
https://cdn.ckeditor.com/4.11.2/full-all/samples/
Could you also provide details about your system setup: what keyboard language setup are you use, what system language settings do you have?

Can you also compare behaviour with native contenteditable? Please check on this example: https://codepen.io/msamsel/pen/vbaXNV if issue is possible to reproduce (click somewhere in the link to edit it)?

**Comment by jurajkapsz** [comment]
Hi,

> I have problem with reproducing this case. I test it under MacOS and Win7 and I couldn't recreate this situation.

I have tested it now also in Win7+IE11 and got the same issue. But could not reproduce it on given link, as mentioned in my comment bellow.

> Could you check if issue appears on editor under this page:
https://cdn.ckeditor.com/4.11.2/full-all/samples/

Thanks, did not think about this before to try out, but within the given CKE demo samples, the ctrl+space did not worked at all. I guess the demo does not have the `nbsp` plugin included? Actually, I was wondering if this bug is about the [nbsp plugin](https://github.com/AlfonsoML/nbsp) rather then CKE. But haven't found it in the `plugins` directory, so I thought it is somehow adopted into CKE.

> Could you also provide details about your system setup: what keyboard language setup are you use, what system language settings do you have?

My system language / keyboard is set to English / English (US).

> Can you also compare behaviour with native contenteditable? Please check on this example: https://codepen.io/msamsel/pen/vbaXNV if issue is possible to reproduce (click somewhere in the link to edit it)?

Not sure if I understand what to do, have to dig more into this one.

I also have some custom CKE configuration in place, but after removing all of my custom preferences (think so), it behaved the same as reported.

**Comment by msamsel** [comment]
> Thanks, did not think about this before to try out, but within the given CKE demo samples, the ctrl+space did not worked at all. I guess the demo does not have the `nbsp` plugin included? Actually, I was wondering if this bug is about the [nbsp plugin](https://github.com/AlfonsoML/nbsp) rather then CKE. But haven't found it in the `plugins` directory, so I thought it is somehow adopted into CKE.

As you properly mention `nbsp` plugin is 3rd party software (https://ckeditor.com/cke4/addon/nbsp) . You can also build customised version of CKEditor, which will try to embed other (3rd party plugins). Our online builder try to integrate all selected plugins by the user on page, this why you might have integrated `nbsp` plugin inside your package, but it doesn't mean that we can support this plugin.
Please contact with software author as we cannot help you more with this case.

**Comment by jurajkapsz** [comment]
Ok thanks for confirmation and help!
