### ISSUE TITLE
Release tests fails on major branch: tests/plugins/pastefromword/generated/tickets2

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2806]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

Test in `tests/plugins/pastefromword/generated/tickets2` fails in current major branch

### Actual result

![screenshot 2019-02-13 at 12 08 43](https://user-images.githubusercontent.com/23366849/52707616-5a62e880-2f88-11e9-8662-f52d800ba76b.png)

☝️most likely this was introduced with Page Break support in PFW.

**Comment by mlewand** [comment]
@jacekbogdanski please take a look at it, whether #2598 breaks unit tests in the built version.

**Comment by jacekbogdanski** [comment]
I can confirm that #2598 breaks unit test. `pagebreak` plugin is loaded implicitly when building an editor and changes the unit test output.
