### ISSUE TITLE
Paste From Word Plugin looses columns

### ISSUE THREAD

**Issue by smatteoda** [ckeditor/ckeditor-dev#2808]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Import attached word document.
2. See content bellow "The following section is in two columns"

### Expected result

Text should be in two columns, may be the trick here would be to have an html table created with invisible borders.

### Actual result

Text is not in columns, just one text bellow another.

## Other details

* Browser: Chrome, latest release
* OS: Windows 10 
* CKEditor version: 4.11.1
* Installed CKEditor plugins: pastefromword,uploadimage,autogrow
[Simple Microsoft Word Document without big images (1).docx](https://github.com/ckeditor/ckeditor-dev/files/2860562/Simple.Microsoft.Word.Document.without.big.images.1.docx)

**Comment by jacekbogdanski** [comment]
Hello,

after checking out HTML from browser clipboard after copying the attached document, it looks like MS Word doesn't provide any metadata to distinguish columns. Also, CKEditor doesn't support columns and changing them into a table with invisible borders isn't an option in modern web development.
