### ISSUE TITLE
`editor.insertHtml` pollutes editable with empty spans

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2813]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://codepen.io/anon/pen/QYZZOG
2. Create selection in editor as following: `Foo {Bar}`.
3. Press button `insert` below editor.

### Expected result

Selected part is removed. And there is no empty element left.

### Actual result

Empty span is left behind editor which is visible by red border.

## Other details

These empty elements can't be focused (checked Chrome, Safari, Firefox), and they are removed on `getData`. They should be removed right away on `insertHtml`, because when styled they might be visible in editor.

https://github.com/ckeditor/ckeditor-dev/blob/002ec74de01c50d48e1ba2101785126a56407eeb/core/editable.js#L1719-L1723
☝️ This is where they ale splitted upon insertions, and when splitting leaves empty elements it's best place to clean them up.

**Comment by jswiderski** [comment]
This issue was originally reported by Oracle and can be observed when pseudo elements are used: https://codepen.io/j_swiderski/pen/mvzvMZ.
