### ISSUE TITLE
Font size and font issue

### ISSUE THREAD

**Issue by dreamwares-Lalit** [ckeditor/ckeditor-dev#2815]
## BUG

Bug

## Provide detailed reproduction steps (if any)

1. We are setting the default font size and font from config file of CK editor
2. While we are loading the CK editor in the page it shows expected font size and font
3.but it is not applying the to every time we have to select the text and then select font size and font
   size.

### Expected result

*What is the expected result of the above steps?*

### Actual result
Expectation is that when we are adding any text it should take font-size and font from config
it only selected in ck editor but not applied to the text
## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
[`config.font_defaultLabel`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-font_defaultLabel) and [`config.fontSize_defaultLabel`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-fontSize_defaultLabel) are meant to only display provided options in "Font" and "Font Size" combos if none option is selected, it's not intended to change the default font in the editor.

The easiest way to change the default font in the editor is to apply additional CSS using [`config.contentsCss`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss).
