### ISSUE TITLE
Resize handler is visible in read-only mode

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#2816]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html
2. Open browser console.
3. Paste and execute following code in console:
	```javascript
	CKEDITOR.instances.editor1.setReadOnly( true );
	```
4. Try to resize image in the first editor.

### Expected result

* Image can't be resized.
* Resize handler is not visible.

### Actual result

* Image can be resized.
* Resize handler is visible.

## Other details

* Installed CKEditor plugins: image2

There was #719, but it fixed issue only for editors loaded in read-only mode. As we're introducing hiding of drag handler in #865, it'd be nice to provide the same change also for resize handler.

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/4b08ca6a4e49679d980b1dcdf4e03e7a533e4b37.
