### ISSUE TITLE
Codesnippet's background not scrolling past <div> length

### ISSUE THREAD

**Issue by ThomasBraam** [ckeditor/ckeditor-dev#2817]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create div for CKEditor to place text it.
2. Add code using CodeSnippet that is too wide to fit in the div (or resize screen so div will be made smaller).

### Expected result

Field becomes scrollable and background retains color over full length of the row.

### Actual result

The field does become scrollable and fits the text of the code. However, the background does not scroll and disappears if I scroll past the div length.

https://i.imgur.com/X5FXyGU.png

## Other details

I posted the issue on [Stackoverflow](https://stackoverflow.com/questions/54719777/ckeditor-codesnippets-background-not-scrolling-past-div-length) but to avail.

* Browser: Chrome
* OS: Ubuntu 18.04
* CKEditor version: 4.9.2
* Installed CKEditor plugins: CodeSnippet

**Comment by jacekbogdanski** [comment]
Hello,

you opened the issue on CKEditor4 issue tracker, however, you are referencing the issue with CKEditor5 which currently don't have `codesnippet` plugin. Could you precise which version of CKEditor are you using?

I have no luck with reproducing the issue with CKEditor4. Please, provide more details about reproduction steps like a minimal example code.

**Comment by ThomasBraam** [comment]
Hi Jacek,

Thank you for looking into my issue, I fixed the issue myself now.
Sorry, I was a little confused. I am using ckeditor-django version 5.6.1 which, according to my documentation, comes with CKEditor 4.9.2.

I found that the background works fine if I use the standard highlight style. However, when I switch to monokai_sublime.css, the issue starts. I checked one other custom style (atelier-dune.dark.css) which exerts the same issue.

My current (Django) testing template looks like this:

```
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/monokai_sublime.css' %}" />
    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script> 
{% endblock %}

{% block content %}
{{ post.contentUL|safe }}


<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}
```

with base.html as:
```
{% load static %}
<html>
    <head>
        <title>Thomas W. Braam</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.1/dist/css/foundation.min.css" integrity="sha256-1mcRjtAxlSjp6XJBgrBeeCORfBp/ppyX4tsvpQVCcpA= sha384-b5S5X654rX3Wo6z5/hnQ4GBmKuIJKMPwrJXn52ypjztlnDK2w9+9hSMBz/asy9Gw sha512-M1VveR2JGzpgWHb0elGqPTltHK3xbvu3Brgjfg4cg5ZNtyyApxw/45yHYsZ/rCVbfoO5MSZxB241wWq642jLtA==" crossorigin="anonymous">
        
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
        <link rel="shortcut icon" href="{% static 'favicon/favicon-32x32.png' %}"/>
        <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400" rel="stylesheet">

        {% block css %}{% endblock %}

    </head>
    <body>
        <div class="page-header">
            <div class="header-left-logo">
                <a href="/">
                    <img src="{% static 'images/icon.png'%}"></a>
                <div class="header-left-name">
                    <a href="/">
                        <h1>...</h1></a>
                </div>
            </div>

            <span class="menu-right"><div class="menu-right">
                <ul class="dropdown menu" data-dropdown-menu>
                  <li class="menu-right"><a href="/">HOME</a></li>
                  <li class="menu-right">
                    <a href="#Item-2">TOOLS</a>
                    <ul class="menu hide-on-load">
                      <li class="menu-right"><a href="#Tool-1">Coming soon</a></li>
                    </ul>
                  </li>
                  <li class="menu-right"><a href="/contact">CONTACT</a></li>
                </ul>
                </ul></div>
            </span>
        </div>
    {% block content %}
    {% endblock %}

    <div class="page-footer" style="position: fixed; bottom: 0; width: 100%;height:48px;">
        <p style="font-weight: 500; font-size:9pt; color:#0a0a0a7a; text-align: center">&copy; Copyright 2019, created by <a href="..." style="color:#0a0a0a7a;">Thomas Braam</a></p>
    </div>

      <script>
    var config = {
      extraPlugins: 'codesnippet',
      codeSnippet_theme: 'monokai_sublime',
      height: 356
    };
  </script>
    <script src="{% static 'blog/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'blog/js/vendor/foundation.min.js' %}"></script>
    <script src="{% static 'blog/js/vendor/foundation.dropdownMenu.js' %}"></script>
    <script>$(document).foundation();</script>
    <script>$('ul.hide-on-load').removeClass('hide-on-load');</script>
    </body>
</html>
```

I have very limited experience with building a website, so I might be overlooking something obvious! My apologies in advance.

However, as I found the problem arising after applying the custom theme I decided to look into that and I found that changing 
```
.hljs {
  display: block;
  ...
}
```
to 
```
.hljs {
  display: inline-block;
  ...
}
```
fixed the issue.

So for me this issue is case closed.
Thanks again.

**Comment by jacekbogdanski** [comment]
Yes, it looks like highlight.js theme issue. Unfortunately, we cannot fix the code which doesn't belong to us, although you can try to report the issue on highlight.js issue tracker.
