### ISSUE TITLE
[Edge] Failing test: `tests/plugins/emoji/dropdown` 

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2826]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

`tests/plugins/emoji/dropdown`

**Comment by jacekbogdanski** [comment]
Both issues are probably related: https://github.com/ckeditor/ckeditor-dev/issues/2827

**Comment by Comandeer** [comment]
Fixed in #2828.
