### ISSUE TITLE
Multi-image paste is not working in IE

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#2834]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Paste a text mixed with multiple images,
2. Text gets pasted but images are gone.
3. I have debugged and it seems like evt.data.dataValue contains <img> tag in IE with no src. evt.data.dataTransfer never worked in IE.

Note: Single image without text gets pasted properly. 

### Expected result

Images get pasted correctly.

### Actual result

Images don't get paste correctly.

## Other details

* Browser: IE
* OS: Windows
* CKEditor version: 4.11
* Installed CKEditor plugins: not relevant

**Comment by msamsel** [comment]
Pasting images from Word on IE is quite tricky and usually it's done by our plugin, but for the browser itself. (A little more details you can find in this comment: https://github.com/ckeditor/ckeditor-dev/issues/2222#issuecomment-424667812).

Please provide more details, which exact version of IE do you use?
Please attach document which you try to copy-paste to editor?
I'll try to look closer to this case, however browser limitation might prevent proper copy-pasting image to editor.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
