### ISSUE TITLE
editor.on( 'doubleclick') doesnt work well

### ISSUE THREAD

**Issue by applibs** [ckeditor/ckeditor-dev#2856]
Bug

1. I used simplebutton plugin
2. I changed all 'simple-button-plugin' into 'my-button-plugin' and changed all necessary staffs to make this plugin as new. 
3. I make content into editor with my new plugin.
4. After doubleclick on my element new dialog open simplebutton dialog except my new plugin dialog.
5. When I set breakpoint into

### Expected result

*doubleclick event must open my plugin dialog*

### Actual result

*doubleclick event will open different plugin dialog*

## Other details

* Browser: Chrome 72
* OS: Win10
* CKEditor version: 4.11.1
* Installed CKEditor plugins: many

1.
On this code:
```
if ( element.hasClass('my-button-plugin') ) {
	evt.data.dialog = 'mybuttonDialog';
}
```
2.
my element has 'my-button-plugin' in classlist, condition works well and command 'evt.data.dialog = 'mybuttonDialog';' is fired. 

3.
but editor open simplebuttonDialog dialog except 'mybuttonDialog' !

4.
my breakpoint is also on lines:
```
if ( element.hasClass('simple-button-plugin') ) {
	evt.data.dialog = 'simplebuttonDialog';
}
```
and code in this condition is never fired.

**Comment by Comandeer** [comment]
Can you provide some live demo that shows the issue?

**Comment by applibs** [comment]
my mistake.
