### ISSUE TITLE
copy/paste text + image (from word) on IE11 not working

### ISSUE THREAD

**Issue by basbousf** [ckeditor/ckeditor-dev#2869]
Hi
we are using CKEditor 4, 
when we copy/paste a text + image from word in CKEditor, if we are using IE11 only the texte is pasted, if we use Chrome tet +images are pasted.
Is it a known IE11 issue?

**Comment by jacekbogdanski** [comment]
Hello,
we are unable to fetch an image from clipboard when pasting into IE11, so, unfortunately, it makes this issue upstream and we are unable to fix it on our side. You can check if the clipboard contains image by using https://ckeditor4-preview.ckeditor.com/master/dev/pastefromword/getclipboard.html (just paste content into the editor and check raw HTML/RTF data).
