### ISSUE TITLE
Resize handler is not created for images in read-only mode

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor-dev#2874]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create read-only instance of editor containing image
2. Open webpage
3. Paste and execute following code in console:
  ```js
  CKEDITOR.instances.editor1.setReadOnly( false );
  ```
4. Try to resize image in the first editor.

### Expected result

* Resize handler is visible
* Image can be resized

### Actual result

* Resize handler is not visible
* Image can not be resized

## Other details

* Installed CKEditor plugins: image2

#719 made resize handler disabled if editor is created in read-only mode. However it is not initialised at all, so after manually leaving read-only mode resize handler still does not show up.
Note that this is an issue only for images loaded with editor. If you add a new image afterwards (i.e. after leaving read-only mode), the problem does not exist.

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/4b08ca6a4e49679d980b1dcdf4e03e7a533e4b37.
