### ISSUE TITLE
Getting #undefined fields in dropdown of mentions plugin

### ISSUE THREAD

**Issue by apbln** [ckeditor/ckeditor-dev#2877]
**my dataFeed()-function:**

let dataFeed = function(opts, callback) {
  let matchProperty = 'username';
  let data = users
    .filter(item => item[matchProperty].indexOf(opts.query.toLowerCase()) == 0)
    .sort((a, b) => {
      return a[matchProperty].localeCompare(b[matchProperty], undefined, {
        sensitivity: 'accent'
      });
    });
  callback(data);
};

**my users:**

const users = [
  {
    id: 1,
    avatar: '1',
    fullname: 'Dang Van Thanh',
    username: 'dangvanthanh'
  },
  { id: 2, avatar: '2', fullname: 'Truong Phuong', username: 'truongphuong' }
]

**result:**
![grafik](https://user-images.githubusercontent.com/38110721/53635572-d4989b80-3c1d-11e9-8d67-230d7b57457c.png)

What am I missing???

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
