### ISSUE TITLE
Deprecate grunt docs in favor of grunt build task

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2884]
Moved from [ckeditor/ckeditor-docs#231](https://github.com/ckeditor/ckeditor-docs/issues/231).

> I've been doing countless mistakes of typing `grunt build` instead of `grunt docs`. This results with error message delayed by second or few secs.
> 
> `build` task name seems much more intuitive for me, and has always been. Though I'm curious to get opinions from other people familiar with doc generation process.
> 
> The way I propose it is to:
> 
> 1. Rename `docs` task to `build`
> 2. Add `docs` alias which will add a message that `grunt docs` is deprecated and will be removed in couple of months - use `grunt build` instead.
> 
> After a longer time we'd drop the old command.

**Comment by Comandeer** [comment]
Closed in ckeditor/ckeditor-docs#206.
