### ISSUE TITLE
Add task to build necessary thing for multidocs

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2891]
Moved from [ckeditor/ckeditor-docs#204](https://github.com/ckeditor/ckeditor-docs/issues/204).

> We should prepare grunt task, which will combine all necessary task **before running** umberto:
> https://github.com/ckeditor/ckeditor-docs/blob/master/gruntfile.js#L70
> We need to synchronise task list with [bigbang-docs](https://github.com/cksource/bigbang-docs.ckeditor.com/pull/159) what might result with errors.
> 
> We should simplify linked task to have sth like:
> 
> * `grunt.registerTask( 'before-build', [ 'api', 'fix-scayt-docs', 'prepare-examples', 'build-react' ] );`
> 
> and then have
> 
> * `grunt.registerTask( 'docs', [ 'before-build', 'umberto' ] );`
> * `grunt.registerTask( 'docs-serve', [ 'docs', 'connect' ] );`

**Comment by Comandeer** [comment]
Closed in ckeditor/ckeditor-docs#206.
