### ISSUE TITLE
Add "Docs" issue type

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2901]
Since we are moving reporting docs issues from `ckeditor-docs` to `ckeditor-dev` repo, we could add another template for reporting docs issue here:

![image](https://user-images.githubusercontent.com/1061942/53744708-d2dd0b00-3e9d-11e9-8c7e-db311299ff0d.png)

The template could be very similar to other templates, but it will be a good indicator that you are in a correct place to report docs issues.

**Comment by engineering-this** [comment]
I don't have access to repo settings.

Here is my proposal:

Issue title:
`📚 Docs issue`
Issue subtitle:
`If you want to report an issue related to documentation.`

Template:
```
## Type of report

Docs

## Provide description of requested docs changes

*What is the purpose and what should be changed?*
```

**Comment by engineering-this** [comment]
Closed by https://github.com/ckeditor/ckeditor-dev/commit/48d7c9c281a2df14ac5f71a6817c798d479c8c7c
