### ISSUE TITLE
Revise Spell Check and SCAYT howto

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2907]
Moved from https://github.com/ckeditor/ckeditor-docs/issues/132.

> As @khawkins98 reports in [ckeditor/ckeditor-dev#1678](https://github.com/ckeditor/ckeditor-dev/issues/1678):
> 
> > In the docs ([link](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_howtos_scayt.html#how-do-i-change-the-default-language-for-spell-check-as-you-type-scayt)), it would seem that this is enough to set the SCAYT spell checker language:
> > ```js
> > // Sets SCAYT to French.
> > config.scayt_sLang = 'fr_FR';
> > ```
> > 
> > 
> > However, this doesn't do anything.
> > You must also disable the user's ability to specify a default language in the UI:
> > ```js
> > config.scayt_disableOptionsStorage = 'lang';
> > config.scayt_sLang = 'fr_FR';
> > ```
> > 
> > 
> > And, success.
> 
> In addition to that there are some minor issues that should get fixed:
> 
> There's a hurting redundancy where docs enumerate put information on allowed langs:
> 
> * > to one of the 16 possible language codes
> * > The following language codes are currently supported by SCAYT: en_US, en_GB, pt_BR, da_DK, nl_NL, en_CA, fi_FI, fr_FR, fr_CA, de_DE, el_GR, it_IT, nb_NO, pt_PT, es_ES, and sv_SE
> 
> The above information should only be available in the API docs, so instead enumerating it article should link to say that list of available values can be found in api docs (linking it). Lets keep it DRY
> 
> I know this is technically a SCAYT feature, but it would be good to have fuller guidance in the CKEditor docs.

**Comment by markusd1984** [comment]
would be great to include this info in the docs, just come across the same issue and found somebody asking about this in drupal a long time ago https://www.drupal.org/project/ckeditor/issues/2832931#comment-13000856
