### ISSUE TITLE
Config options for default font family and size

### ISSUE THREAD

**Issue by blindspeed90** [ckeditor/ckeditor-dev#2922]
## Type of report

Feature request

## Provide description of the new feature

Allow the default list item for font family and size to display with the actual values like the other entries. Following the existing options for config, something like:

config.font_default = "Default (Verdana)/Verdana";
config.fontSize_default = "Default (12)/12px";

I think if font_defaultLabel or fontSize_defaultLabel weren't given that their values could be pulled from these new options (if provided) for the textbox display.

Internally you could set your own flag on the list item instead of using "cke-default" for the value since the value would be used to display the actual font family or size.  Or, today in 4.6 I accomplish this by appending " !important" to the default family and size value, and then look for that in an overridden editor.applyStyle.  This allowed me to have say "Default (Verdana)/Verdana !important;Verdana/Verdana" and distinguish between them.

			oCKEditor.applyStyle = function(oStyle) {
				var oStyleDefinition = oStyle.getDefinition();
				if (oStyleDefinition.styles) {
					var oFontFamily = oStyleDefinition.styles["font-family"];
					if (oFontFamily && oFontFamily.indexOf("!important") >= 0)
						return;
					var oFontSize = oStyleDefinition.styles["font-size"];
					if (oFontSize && oFontSize.indexOf("!important") >= 0)
						return;
				}
				CKEDITOR.editor.prototype.applyStyle.call(this, oStyle);
			};

**Comment by blindspeed90** [comment]
[plugin.zip](https://github.com/ckeditor/ckeditor-dev/files/2931502/plugin.zip)

**Comment by blindspeed90** [comment]
I attached a modified version of the font plugin, and tagged /*MOD*/ anywhere I touched.  Just so you could see a difference, I added a /*MOD-test only*/ with "Comic Sans MS" and "18px" so you could see a difference right away.

**Comment by blindspeed90** [comment]
One more note, I ended up using "!important" because I also tried:

- In style.js compareCssText() treats 'inherit' as a wildcard
- In tools.js parseCssText() normalizes and 'initial' was getting removed

**Comment by jacekbogdanski** [comment]
Hello,

to sum up, if I understand correctly, you would like to introduce two additional config options to change the default behavior of `default` item which currently updates font size or font familiy depending on browser defaults, into your custom values?

As you already wrote some code, maybe you would like to propose your own PR wich these changes?

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
