### ISSUE TITLE
How to publish a custom build as npm package

### ISSUE THREAD

**Issue by prakashsvmx** [ckeditor/ckeditor-dev#2930]
## Type of report

I am using build from sources for custom build of ckeditor4. form stable branch.
(https://ckeditor.com/docs/ckeditor4/latest/guide/dev_build.html)
 - does the build run from the stable branch if i change to the respective branch?

how can i publish the custom build  as a npm package  ? and include in my react project as a dependency.?

e.g : ckeditor4-personal as package name in the npm

## Provide description of the task
Documentation update or guidance.

## Other details

* Browser: any browser
* OS: mac os
* CKEditor version:4
* Installed CKEditor plugins: custom set of plugins in build.

--------
I checked out the stable branch and ran the build.

the build output does not say which branch it built .

Sample build output:
CKBuilder - Builds a release version of ckeditor-dev.

Checking/Updating CKBuilder...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

Starting CKBuilder...
Copying files (relax, this may take a while)
    Time taken.....: 32.809seconds
Merging language files
    Time taken.....: 5.668seconds
Generating plugins sprite image
Building ckeditor.js
Minifying ckeditor.js
Created ckeditor.js (649KB)
    Time taken.....: 7.785seconds
Building skins
    Time taken.....: 6.851seconds
Cleaning up target folder
    Time taken.....: 1.703seconds

Creating compressed files...

    Created ckeditor_4.11.3.zip...: 2515847 bytes (41% of original)
    Created ckeditor_4.11.3.tar.gz: 1780212 bytes (29% of original)
    Time taken.....: 4.071seconds

==========================
Release process completed:

    Number of files: 1419
    Total size.....: 6185809 bytes
    Time taken.....: 58.887seconds

**Comment by f1ames** [comment]
Publishing packages to npm is not related to CKEditor 4 and is out of the scope. You can refer to some online resources as there are plenty of them - for example https://docs.npmjs.com/creating-node-js-modules.

For building CKEditor form source, please refer to [official docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_build.html), you may also use [`ckeditor-presets`](https://github.com/ckeditor/ckeditor-presets).

---

> the build output does not say which branch it built

When building locally, the local branch is always used (the one on which you are at the moment of building).
