### ISSUE TITLE
Incorrect screenshot on CKEditor npm package page

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2933]
The [CKEditor npm package page](https://www.npmjs.com/package/ckeditor) contains the screenshot of a `full` preset:

![image](https://user-images.githubusercontent.com/1061942/53963843-5c831780-40ee-11e9-943e-e66eb8f4b7ba.png)
 while in fact the package contains `standard all` preset, which with default config looks like:

![image](https://user-images.githubusercontent.com/1061942/53964007-b5eb4680-40ee-11e9-81d8-69fbfbc69b71.png)

so it should be updated.

**Comment by f1ames** [comment]
After talking with @AnnaTomanek F2F (about what screenshots we have on [Angular](https://ckeditor.com/blog/CKEditor-4-integrate-WYSIWYG-editor-with-Angular/) and [React](https://ckeditor.com/blog/CKEditor-4-integrate-WYSIWYG-editor-with-React) blog post pages), the general idea is to present full featured editor. It doesn't have to be the default one (unless ofc the presented config/UI could be achieved with the given package/build).

This also applies for `ckeditor` NPM package, which means the current screenshot is fine.

**Comment by AnnaTomanek** [comment]
Btw, if you feel that the custom config from the React/Angular blog posts looks better, we may also use this one. Full preset is pretty ugly :) while the custom one (also used on the CKEditor 4 product page) looks a bit better.
