### ISSUE TITLE
ENTER at end of heading inserts <div> instead of <p>

### ISSUE THREAD

**Issue by Geo-T** [ckeditor/ckeditor-dev#2940]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. build-config.js file used 
`var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	preset: 'basic',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'.npm',
		'.travis.yml',
		'bender-err.log',
		'bender-out.log',
		'bender.ci.js',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package.json',
		'tests'
	],
	plugins : {
		'basicstyles' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'horizontalrule' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'list' : 1,
		'magicline' : 1,
		'removeformat' : 1,
		'sharedspace' : 1,
		'sourcedialog' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'tableselection' : 1,
		'tabletools' : 1,
		'toolbar' : 1,
		'undo' : 1
	},
	languages : {
		'en' : 1,
		'es' : 1,
		'fr' : 1,
		'pl' : 1,
		'ro' : 1
	}
};`
2. Open the sample page (`ckeditor/samples/index.html`)
3. Add a title (h1) 
![image](https://user-images.githubusercontent.com/10050616/54018357-bafcd400-4188-11e9-9eb0-1733294cf429.png)
4. Type ENTER key
![image](https://user-images.githubusercontent.com/10050616/54018382-cd770d80-4188-11e9-86da-46dc0abcbeec.png)

### Expected result

Current format style set to `Normal` (i.e: `p` tag), the first defined in the format dropdown.

### Actual result

Current format is `Division` (i.e: `div` tag).

## Note
Event if I override the tags list as follow: `config.format_tags = "p;h1;h2;h3;h4;h5;h6` a `div` is still created, and the format dropdown displays _Format_ instead of one of its values.

## Other details

* Browser: Chrome 72
* OS: Windows 10
* CKEditor version: 4.11

**Comment by Comandeer** [comment]
It seems that after applying styles, editor switches to inserting `div`s instead of `p`s, even when `config.enterMode` is set to `CKEDITOR.ENTER_P`.

**Comment by f1ames** [comment]
The minimal setup to reproduce this issue are just few plugins  - `format, wysiwygarea, toolbar` and it seems this behaviour is fixed by adding `enterkey` plugin. As `enterkey` adds custom enter handling (not relying on browser behaviour) and utilizes `ENTER_*` config I'm not sure if it should be treated as a bug or rather misconfiguration, WDYT @Comandeer ?

**Comment by Comandeer** [comment]
@f1ames, actually you're right. Without `enterkey` plugin, editor uses browser's default behaviour for <kbd>Enter</kbd>.

**Comment by Geo-T** [comment]
Indeed, with `enterkey` plugin it works correctly. Thank you all.
