### ISSUE TITLE
Slow performance large sites

### ISSUE THREAD

**Issue by meffj00** [ckeditor/ckeditor-dev#2942]
## Type of report
We recently moved from DNN Evoq to DNN Platform 9.2.2. The performance of the CKEditor is a tragedy on large sites with many folders and files. To select one photo (already upload) and place it on the site with Google Chrome takes about 1:26 min. With the previous editor no complaints! 
Can anything really be done about this?

## Provide detailed reproduction steps (if any)
1. Click on the picture icon in de CKEditor
2. Click on the button browse on server (first time wait a minute)
3. Select a folder to select an image 
    PS If you need to upload it an image it takes more time!
4. Wait while the systeem read the files in that folder (about 6 seconds)
    PS If there a lot of images in that folder the systeem uses paging (1,2,...) 
        (wait 6 seconds each time you go to another page)
5. Select an image and wait (about 6 seconds)
6. Click on the button OK
7. Click on the button OK again.

### Expected result
The expected result is what we asked, but not the time it takes!

*What is the expected result of the above steps?*
The expected result is what we asked,

### Actual result
The expected result is what we asked,

*What is the actual result of the above steps?*
The expected result is what we asked,

## Other details

* Browser: Google Chrome 72.0.3626.121 (Offical build) (64 bits)
* OS: Windows 7 Professional
* CKEditor version: 4.5.3 (revision 6c70c82)
* Installed CKEditor plugins: standard DNN

**Comment by f1ames** [comment]
Hi @meffj00,
it seems the issue here is not CKEditor itself but the file manager integration (frontend or backend side) which takes such a long time to process large amount of files. As you mentioned:

> Click on the button browse on server (first time wait a minute)

which means the delay is caused by the server request (to get files list) or displaying the large structure in a browser. What upload/file manager plugin do yo use?

**Comment by meffj00** [comment]
Thanks f1ames for you quick response. We think that DNN have to load all folders and files wich it takes time. Or it's the time to display the structure in the browser? The second time it goes much faster, proberly because DNN has cached it. The upload/file manager plugin is from DNN Platform release 9.2.2. (proberly custom made for DNN). Our users are complaining if they need to upload or look up multiple photos, this is definitely a time-consuming task!

**Comment by f1ames** [comment]
> We think that DNN have to load all folders and files wich it takes time. Or it's the time to display the structure in the browser? The second time it goes much faster, proberly because DNN has cached it.

Seems like a valid assumption, probably the structure is cached after the first time and next times it loads/shows much faster (so rather a server-side issue).

> The upload/file manager plugin is from DNN Platform release 9.2.2. (proberly custom made for DNN).

This means it's not an issue with CKEditor itself but the custom file manager, I suggest reporting this issue to DNN Platform team.
