### ISSUE TITLE
Form element being wiped

### ISSUE THREAD

**Issue by lsces** [ckeditor/ckeditor-dev#2944]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
HTML document with a form wrapper
Have started from scratch only using the tool bar functions to create a new small form, which saves OK, but on reopening to edit the 'form' '/form' wrapper is missing.

### Expected result
It remains present when opening in CKEditor

### Actual result
Is removed from the page

## Other details
Have been using CKEditor and it's predecessor for many years but only update sporadically. Previous version 4.4.7 had been working fine and switched back to that ...

* Browser: Firefox and Chrome both show the problem
* OS: Linux
* CKEditor version: 4.11.3
* Installed CKEditor plugins: 	plugins : {
		'divarea' : 1,
THIS is the problem ... put 'wysiwygarea' back and the form works fine!
	},

**Comment by lsces** [comment]
OK toggling between the 4.10 build and the newer 4.11.3 shows the problem ... the later build has the html5validation added which is new and I'd switched from iframe to div display as the lack of matching font has always been a niggle.

**Comment by lsces** [comment]
https://ckeditor.com/cke4/builder/475f7ac5ae9c31b6803906ff91246e6f has nothing in 4.11.3 that is not in my working 4.10 build. 
Add Form ... Add Text Field -> Add Submit Button -> Save -> Shows form,text field and Submit Button 
Open to edit and the form is missing ... 
Cancel, switch to using 4.10 build and re-open ... form is present ...

**Comment by lsces** [comment]
OK That was unexpected! Remove the forms plug-in and the whole form gets wiped when opening ... 
Back to 4.10 for now!

**Comment by lsces** [comment]
Confirmed!
Using divarea results in the form element being stripped ... swap back to wysiwygarea and it works fine ... This problem is also present in 4.10! I've got a copy of the github source running locally now and been able to roll back and confirm the problem ...

**Comment by Comandeer** [comment]
@lsces, could you prepare some minimal reproduction, e.g. on [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/)?

**Comment by lsces** [comment]
I've confirmed that the problem is with divarea and currently I've a development setup on which I can switch between divarea and wysiwygarea, so the div based or iframe based display. On the development setup I have pages stored with forms on them. If I enable divarea and view the form there is no red box for the form area ... view via source and the form wrapper is missing. Cancel out, switch back to wysiwygarea and reload the page and it displays fine. Not sure how I can emulate that via JSFiddle? You can save a new form in divarea, it's the reload which causes the problem. 
As I indicated ... I was looking to switch to divarea to give the same fonts having lived without that for many years, and rolling the source code back to 4.10 is giving the same result. I'm happy to try anything and I have now also down separate clean downloads from the website with the only difference between the two being the divarea or wysiwygarea plugin ... with the same result ...
What can I try next?

**Comment by lsces** [comment]
Bugger ... thinks are easy when you know the answer ... bottom line, you can't use 'forms' with 'dirarea' when the `<textarea>` is already being handled IN a form! Having been using the third party code that puts all this together it is often not easy to work out just where a problem comes from and having been using this code for close on 20 years now and it just worked ... May be worth adding a note on 'dirarea' that some plugins may not be usable when inserted directly in the page html. iframe protects from that problem, but even iframe may have problems when adding textarea IN the page being edited when  previewing. Now to work out how to update the iframe .css on a site by site basis instead of using divarea.
