### ISSUE TITLE
Icons property does not exist on class pluginDefinition

### ISSUE THREAD

**Issue by ankita240796** [ckeditor/ckeditor-dev#2947]
## Type of report

Bug

Creating a custom plugin as described in the [tutorial](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_sample_1.html#plugin-source-code), shows that an icons property can be defined but no such property is mentioned in the [pluginDefintion class](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_pluginDefinition.html). So, when adding a icon property in the custom plugin, typescript flags the following error: 

```
error TS2345: Argument of type '{ icons: string; init: (editor: editor) => void; }' is not assignable to parameter of type 'pluginDefinition'.
  Object literal may only specify known properties, and 'icons' does not exist in type 'pluginDefinition'.
```

## Provide detailed reproduction steps (if any)

1. Create a custom plugin with icons specified (same as tutorial [here](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_sample_1.html#plugin-source-code))
2. Compile the typescript file having the plugin definition

### Expected result

No error should be raised complaining about missing icons property.

### Actual result

Error is flagged that icons does not exist in type pluginDefintion.

## Other details

* Browser: Chrome v72.0.3626.109
* OS: Ubuntu
* CKEditor version: 4.9.2
* Installed CKEditor plugins: sharedspace

**Comment by f1ames** [comment]
@ankita240796 will https://github.com/ckeditor/ckeditor-dev/pull/2997 fix your issue?

**Comment by ankita240796** [comment]
Yes @f1ames, it will!

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor-dev/pull/2997 (https://github.com/ckeditor/ckeditor-dev/commit/dfed162989e5196ae9fab6af63bb9f8ecdab1e2b).
