### ISSUE TITLE
CKeditor filter remove some valid CSS inline style

### ISSUE THREAD

**Issue by SuperPat45** [ckeditor/ckeditor-dev#2961]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I want to use the CSS column-count property inline in a div like
```
<div style="column-count: 3">
A long article
</div>
```
But CKEditor remove the style attribute.

### Expected result

I think CKEditor, by default, must keep all valid CSS properties defined in style attribute

### Actual result

Style attribute is removed

## Other details

How can I configure CKEditor to keep some CSS properties?

* Browser: Firefox, Chrome
* OS: Windows
* CKEditor version: latest

**Comment by f1ames** [comment]
Hello @SuperPat45,
CKEditor has its own mechanism for filtering content called [ACF (Advanced Content Filter)](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html). It can be adjusted to accept more attributes (e.g. `style` you mentioned). See [`extraAllowedContent` config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraAllowedContent).
