### ISSUE TITLE
MathJax formula misplaced when merging paragraphs by pressing Delete

### ISSUE THREAD

**Issue by milossramek** [ckeditor/ckeditor-dev#2968]
## Type of report

Bug

## Provide detailed reproduction steps (if any) 
A MathJax formula at the end of a paragraph is misplaced when merging paragraphs by pressing Delete after the formula.

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html
2. Add a new formula at the end of the last paragraph, then place cursor after this formula, press Enter and add some text
3. Place the cursor to the end of the paragraph after the new formula and press Delete. The paragraphs merge and the formula is erroneously moved behind the previous formula (or any other tag which would be before the formula).

### Expected result
It is expected, that the formula remains in the correct place.

### Actual result

The formula is moved to incorrect place

## Other details
This is a regression, the problem is not present in CKeditor 4.7.3 (from cdn.ckeditor.com) and MathJax 2.7.0 from cdnjs.cloudflare.com.
The problem is related to Firefox, it is not present in Chrome.
The paragraph is redrawn in Firefox (both formulas appear only after some time), while in Chrome the paragraphs merge instantaneously without redrawing the formulas. 

* Browser: Firefox
* OS: Ubuntu & Win 10
* CKEditor version: 
* Installed CKEditor plugins:

**Comment by engineering-this** [comment]
It is not a regression, but an upstream issue. It can be reproduced with simple html:
https://codepen.io/anon/pen/EMJQOQ

You can track the upstream issue here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1539097
