### ISSUE TITLE
Failing test on Firefox 66 plugins/uploadfile/uploadfile

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2971]
## Type of report

Failing test

## Provide description of the task

![Screenshot 2019-03-22 at 11 43 35](https://user-images.githubusercontent.com/23366849/54817658-c1667200-4c97-11e9-8aea-2d828207ccc0.png)

`/tests/plugins/uploadfile/uploadfile#tests%2Fplugins%2Fuploadfile%2Fuploadfile test with uploadfile plugin`

## Other details

* Browser: Firefox 66.0
* OS: macOs
* CKEditor version: development: 4.11.4 `master`, branch and 4.12.0 `major`
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/a6e75d042aa6c7e137a87075132badd29d02fb5f.
