### ISSUE TITLE
Embed plugin not loading

### ISSUE THREAD

**Issue by halburgiss** [ckeditor/ckeditor-dev#2985]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Install embed plugin, and dependency embedbase on 4.5.9 ckeditor
2. Update config.js per instructions for config.extraPlugins = 'embed';
3. Paste the example snippet of twitter feed code from the documentation page, 
[https://ckeditor.com/docs/ckeditor4/latest/guide/dev_media_embed.html#media-embed-vs-semantic-media-embed](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_media_embed.html#media-embed-vs-semantic-media-embed)

### Expected result

*What is the expected result of the above steps?*
Embedded code should display, presumably a twitter timeline.

### Actual result

*What is the actual result of the above steps?*

All markup except the blockquote from the original code snippet is removed.
When using devtools to see what js is being loaded, the plugin.js for this plugin does not appear, as I think it probably should.

## Other details

* Browser: Chrome 72
* OS:Linux
* CKEditor version: … 4.5.9
* Installed CKEditor plugins:
a11yhelp
about
clipboard
dialog
embed
embedbase
filetools
icons.png
icons_hidpi.png
image
image2
justify
lineutils
link
magicline
notification
notificationaggregator
pastefromword
scayt
specialchar
table
tabletools
uploadimage
uploadwidget
widget
widgetselection
wsc

Note I am modifying somebody else's app and may not be able to remove plugins (not sure).

**Comment by halburgiss** [comment]
More details ... the parent web app is Laravel. There are no console or server errors.

**Comment by jacekbogdanski** [comment]
Hello,

I have no issue with embed feature, tested on 4.11.4. Please, make sure to provide [embed provider URL](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-embed_provider). If that doesn't work and you already configured provider URL, you should consider an upgrade to the latest CKEditor release.
