### ISSUE TITLE
CKEditor crashes when user conected through SSL - Uncaught TypeError: c.addRules is not a function

### ISSUE THREAD

**Issue by liu923014086** [ckeditor/ckeditor-dev#3001]
We have a intranet site where CKEditor is working as expected. The issue we saw yesterday that when a user a remote user tries to use the site through SSL (Remote user portal), CKEditor crashes with error message "Uncaught TypeError: c.addRules is not a function". please tell me how to resolve it,thanks!

![image](https://user-images.githubusercontent.com/14088192/55204629-ba48e200-520a-11e9-9aa7-0af6341a16a3.png)
![image](https://user-images.githubusercontent.com/14088192/55204647-c6cd3a80-520a-11e9-9b77-e67bf0c6a9ea.png)

**Comment by f1ames** [comment]
Could you share more info on the browser, OS and CKEditor version causing the issue? Also are there any problems with loading any of CKEditor files (see `Network` tab in the browser dev console)?

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
