### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Utsav170** [ckeditor/ckeditor-dev#3006]
## Type of report

I am using react ssr. after building, ReferenceError: window is not defined error is thrown. what to do??

### Expected result

The page loads and ckeditor is shown

### Actual result

Error is thrown and page is not loading

## Other details

* CKEditor version: v4
* Installed CKEditor plugins: ckeditor4-react npm package

**Comment by Comandeer** [comment]
React SSR is not supported currently, the progress of works can be observed at ckeditor/ckeditor4-react#15.

Please also note that this issue tracker is dedicated to issues in CKEditor 4, [`ckeditor4-react` package has its own issue tracker](https://github.com/ckeditor/ckeditor4-react/issues).
