### ISSUE TITLE
Unable to use Link toolbar option on CKEditor 4.10.1

### ISSUE THREAD

**Issue by alhabibhasan** [ckeditor/ckeditor-dev#3015]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add the Link plugin to CKEditor using the steps provided on the plugin website, along with all dependencies.
2. Set `editorOptions.extraPlugins = 'link,fakeobjects,dialogui,dialog';` to enable plugins for Links
3. Open the page with the CKEditor toolbar and click on the link option.

### Expected result

Should see the dialog box used to add a link to the page.

### Actual result

An exception is thrown in the console saying:

`Uncaught TypeError: Cannot read property 'build' of undefined`
    `at Object.build (ckeditor.js?v=8.x-1.0.0:608)`
    `at Object.build (ckeditor.js?v=8.x-1.0.0:608)`
    `at CKEDITOR.dialog.addPage (ckeditor.js?v=8.x-1.0.0:581)`
   ` at new CKEDITOR.dialog (ckeditor.js?v=8.x-1.0.0:570)`
   ` at f.openDialog (ckeditor.js?v=8.x-1.0.0:613)`
    `at f.<anonymous> (ckeditor.js?v=8.x-1.0.0:613)`
    `at a (ckeditor.js?v=8.x-1.0.0:244)`
    `at Array.n (ckeditor.js?v=8.x-1.0.0:244)`
    `at w (ckeditor.js?v=8.x-1.0.0:244)`
    `at ckeditor.js?v=8.x-1.0.0:245`

## Other details

* Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
* OS: MacOS Mojave
* CKEditor version: CKEditor 4.10.1
* Installed CKEditor plugins: Link, Dialog, Dialogui, fakeobjects

**Comment by jacekbogdanski** [comment]
Link plugins work as expected. Please, visit our guide docs for configuration details, it looks like some CKEditor is incorrectly set up.

![link](https://user-images.githubusercontent.com/10279586/55707722-8f1d7a00-59e4-11e9-89b4-714a8d1da8e5.gif)

**Comment by umrysh** [comment]
I know this issue is closed so please feel free to delete this comment if you wish. 

I ended up here looking for a solution for the same error and the solution for me to simply use this version of the links plugin: https://github.com/wp-plugins/gravity-forms-wysiwyg-ckeditor/tree/master/ckeditor/plugins/link

Just wanted to mention this in case it helps anyone else in the future
