### ISSUE TITLE
[Edge] Failing test on built version /tests/plugins/clipboard/readonly

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3016]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

`/tests/plugins/clipboard/readonly`
![Screenshot 2019-04-03 at 12 53 43](https://user-images.githubusercontent.com/23366849/55473876-08495580-5610-11e9-961e-c244f34c2b33.png)

## Other details

* Browser: Edge
* OS: Windows
* CKEditor version: 4.11.4
* Installed CKEditor plugins: full-all

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor-dev/commit/43467730b3c31081c94af1c88c538c0ae3fc52a9.
