### ISSUE TITLE
[Android] Failing tests on built version

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3018]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

`#tests/is:unit,name:getclientrectsabsolute,name:magicline,name:tickets1`
![Screenshot_20190403-144822](https://user-images.githubusercontent.com/23366849/55480169-f1aafa80-561f-11e9-9200-9688b7a1a3e0.jpg)
![Screenshot_20190403-144826](https://user-images.githubusercontent.com/23366849/55480170-f2439100-561f-11e9-9d3d-71ed9dbb6c50.jpg)

Two above can be fixed by rounding actual value.

PFW test can be ignored, as we don't support pasting from word on mobiles.

## Other details

* Browser: Chrome
* OS: Android
* CKEditor version: 4.11.4
* Installed CKEditor plugins: full-all

**Comment by f1ames** [comment]
> PFW test can be ignored, as we don't support pasting from word on mobiles.

There is task for it already - #2833.

**Comment by engineering-this** [comment]
![Screenshot_20190403-151129](https://user-images.githubusercontent.com/23366849/55482400-c24abc80-5624-11e9-9798-208ad36ed439.jpg)

It looks like `CKEDITOR.tools.convertToPx` is returning different value for some mobiles. It is used to normalize margins.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor-dev/commit/08a87a28d7e18b6dae0fe96a6927c330696efa8b.
