### ISSUE TITLE
Magicline changes selection

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3020]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample.
2. Clear editor content and create list with one item.
3. Press `ul`/`ol` from elements path to select whole list.
4. Move mouse below list.

### Expected result

Selection stays the same.

### Actual result

Selection is changed

## Other details

* Browser: Chrome, Opera
![Apr-03-2019 17-07-39](https://user-images.githubusercontent.com/23366849/55489888-0e046280-5633-11e9-92ee-d2ccea490ed5.gif)

* OS: found in macOS
* CKEditor version: found in 4.11.4
* Installed CKEditor plugins: lists, magicline, elementspath

**Comment by f1ames** [comment]
DUP of https://github.com/ckeditor/ckeditor-dev/issues/2964.
