### ISSUE TITLE
Improve sample page for mobile devices

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3033]
## Type of report

Task

## Provide description of the task

Our sample page could look much better on mobiles. 
Adding just `<meta name="viewport" content="initial-scale=1">` improves it a lot.

![Screenshot_20190404-174844](https://user-images.githubusercontent.com/23366849/55570588-01037400-5704-11e9-854c-417373ab53f3.jpg)

![Screenshot_20190404-174834](https://user-images.githubusercontent.com/23366849/55570583-ff39b080-5703-11e9-86a2-7d85ed4fa257.jpg)

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor-dev/commit/7676d8e840c0c3cafc7c3a5d273f59ed1d7370f0.
