### ISSUE TITLE
When I edit a table, the width of the table automatically scales.

### ISSUE THREAD

**Issue by Jamesxiehailong** [ckeditor/ckeditor-dev#3040]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.  insert a table in the toolbar
2.Enter text arbitrarily in a table

### Expected result
Table width remains unchanged
![image](https://user-images.githubusercontent.com/23492904/55778959-eac83000-5ad6-11e9-8bef-d3e7d996fb48.png)

### Actual result
Table width is changed
![image](https://user-images.githubusercontent.com/23492904/55778811-83aa7b80-5ad6-11e9-93be-89a6a1789e39.png)

## Other details

* Browser:chrome 73
* OS:macos 10.14
* CKEditor version:4.11.3
* Installed CKEditor plugins:tableresize,quicktable

**Comment by jacekbogdanski** [comment]
It's a normal behavior of the HTML table. Create your own CSS styles to change table CSS using [`config.contentsCss`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss) configuration option. 

I created a sample where you can see standard table vs fixed column width: https://codepen.io/jacekbogdanski/pen/yrVrxP
