### ISSUE TITLE
Pasted div tag is converted to p tag in Chrome only

### ISSUE THREAD

**Issue by drpudding** [ckeditor/ckeditor-dev#3043]
## Type of report
Bug

Copy/paste any of this **rendered** markup from a Chrome web page into the editor and no divs remain. (note: it works fine to copy markup directly into source)
```
<div class="foo">I'm a lonely div</div>
<div class="foo"><div class="bar">I'm a div in a div</div></div>
<div class="foo"><ul><li>I'm a list in a div</ul></div>
<div class="foo"><p>I'm a paragraph in a div</p></div>
<div class="foo"><a href="http:///www.github.com">I'm a link in a div</a></div>
<div>I'm a div<span class="foo"> and I'm a nested span</span></div>
```
### Expected result
Here's what I get in FireFox:
```
<div class="foo">I&#39;m a lonely div</div>

<div class="foo">
<div class="bar">I&#39;m a div in a div</div>
</div>

<div class="foo">
<ul>
	<li>I&#39;m a list in a div</li>
</ul>
</div>

<div class="foo">
<p>I&#39;m a paragraph in a div</p>
</div>

<div class="foo"><a href="http:///www.google.com">I&#39;m a link in a div</a></div>

<div>I&#39;m a div<span> and I&#39;m a nested span</span></div>
```
### Actual result
Here's what I get in Chrome:
```
<p>I&#39;m a span</p>

<p>I&#39;m a lonely div</p>

<p>I&#39;m a div in a div</p>

<ul>
	<li>I&#39;m a list in a div</li>
</ul>

<p>I&#39;m a paragraph in a div</p>

<p><a href="http://www.google.com/">I&#39;m a link in a div</a></p>

<p>I&#39;m a div&nbsp;and I&#39;m a nested span</p>
```

## Other details
* Browser: Chrome 73.0
* OS: OS X 10.11.6
* CKEditor version: 4.11
* Installed CKEditor plugins: I have tried this with no extra plugins, and with ```config.allowedContent = true``` I have also tried every manner of allowing ```div(*)[*]{*}```. I am using the Standard install but also tried it with the Full install. No difference.

Nothing will preserve divs in Chrome. Thanks for any assist!

**Comment by f1ames** [comment]
This behavior is caused by the default [`pasteFilter`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter) used for Chrome:

> 'semantic-content' – Known tags (except div, span) with all attributes (except style and class) will be kept.

because of messy content produced by the browser:

> This setting defaults to 'semantic-content' in Chrome, Opera and Safari (all Blink and Webkit based browsers) due to messy HTML which these browsers keep in the clipboard. In other browsers it defaults to null.

To disable it you may use `config.pasteFilter = null`, however it may result in additional content (like some redundant styling, etc) being pasted inside editor while in Chrome/Safari.
