### ISSUE TITLE
How React And Angular plugin should be linked in the docs (for building purposes)

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#3044]
## Type of report

Docs

## Provide a description of requested docs changes

We have a React example (and are very close to have Angular one too - https://github.com/ckeditor/ckeditor-docs/pull/223) in the docs, which uses our integrations. Integrations are linked as dev dependencies in `package.json`.

It works fine, however it means that to build docs with new integration version, one have to publish npm package or change dev deps. Changing dev deps works fine when developing things, however when building production version of docs during release it might be not the best idea. The issue is that the release flow expects to have CKEditor released first and then integrations (because integrations links to CKEditor on CDN and also have it as a peer dep so it needs to be released first).

Of course, we may have everything releases and then build production docs, but until now it was done in parallel to make things faster. I wonder if there is a better way to make these packages more decoupled so docs could be build before publishing integrations🤔

**Comment by msamsel** [comment]
1. You could link the github repository instead of pointing to package version.
2. Alternatively, you could remove integration from package.json and download it with some bash/node script during the building process. Similar to bigbang-docs bash install script.
```
if [[ -d projects/ckeditor-docs && ! -L projects/ckeditor-docs ]]; then
  cd projects/ckeditor-docs
    git submodule update --init --recursive -f
    npm i
  cd ../..
fi
```

**Comment by jacekbogdanski** [comment]
> Integrations are linked as dev dependencies in package.json.
As I can see they are rather linked as production dependencies, although it's a good thing as they are a part of doc samples.

Other than that if it's only the thing with publishing npm package, linking repo instead of npm should fix the issue? We can always keep some special branch for docs to have better control when they are updated:

```
    "ckeditor4-angular": "git+https://github.com/ckeditor/ckeditor4-angular.git#docs"
```

**Comment by engineering-this** [comment]
Actually integrations can use any version of CKEditor, so if only change to integration is updating CDN CKEditor fallback url to use latest version, than we don't really need to have this change reflected in docs, because it will use version served by docs anyway.

**Comment by f1ames** [comment]
> Actually integrations can use any version of CKEditor, so if only change to integration is updating CDN CKEditor fallback url to use latest version, than we don't really need to have this change reflected in docs, because it will use version served by docs anyway.

That's true. So the only scenario is that both CKEditor and integration package contains changes which are not compatible with previous version (so using new integration code with older CKEditor will break it or using new CKEditor version with older integration code will also fail).
In such scenario the release order needs to be as follows:

* CKEditor
* Integrations (linking to new CKEditor on CDN)
* Docs (so will have both new CKEditor and integrations versions from NPM)

Since such cases doesn't seem to happen very often I think we may stay with the flow we have now. And adjust the release order if needed. I'm closing this issue for now but feel free to drop any comment or opinions.
