### ISSUE TITLE
Request to show cell value in cell property dialog

### ISSUE THREAD

**Issue by Achilles107** [ckeditor/ckeditor-dev#3046]
Feature request

## Provide detailed reproduction steps (if any)

1. Add a table to CKEditor
2. Provide some values
3.Right click on a cell
4. Click on Cell properties

### Expected result

It shows cell properties.

### Actual result

Need the value of the cell shown, along with other properties

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version:4.7.1
* Installed CKEditor plugins:table, tabletools

**Comment by Comandeer** [comment]
Such dialog field would fulfil very narrow set of requirements for very specific projects:

* In most cases the selection would contain more than one cell. In such case the field would have to contain values of every selected cell, ultimately becoming a datagrid, or it would allow to change contents of only the first cell – neither solution is ideal.
* Table cells can contain rich formatting, widgets or even nested tables. Handling such cells would require to de facto include whole CKEditor instance inside dialog. Dialog fields are limited only to text.

Therefore there isn't field for setting cell's content as it would be limiting the ability to edit cell's content.

However if you want such limited editing of cell's content, you can add appropriate field using [`dialogDefinition` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#event-dialogDefinition) – [example](https://jsfiddle.net/Comandeer/a0wdLybm/).
