### ISSUE TITLE
Ignore (Don't force wrap with <p>) [m]something here[/m]

### ISSUE THREAD

**Issue by jkd77** [ckeditor/ckeditor-dev#3047]
## Reproduction steps

1. enter or paste "m tag" content within the editor inside Mura
2. Publish the page in Mura, check live page
3. public view of newly published page will either be wrapped in `<p>`, or preceded and followed by an empty `<p></p>`

### Expected result

Ideally, I want to see the result of the [m] tag unmolested by auto applied elements. For example if I use the custom [m] tag: **[m]$.dspFooter()[/m]** I might expect to see:

```
<footer>
    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="nav">
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                </nav>
            </div>
        </div>
    </div>
</footer>
```

### Actual result

```
<p></p>
<footer>
    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="nav">
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                </nav>
            </div>
        </div>
    </div>
</footer>
<p></p>
```

If I pre-wrap the example like:
`<div>[m]$.dspFooter()[/m]</div>`

I would see:

```
<div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="nav">
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                </nav>
            </div>
        </div>
    </div>
</footer>
</div>
```

## Other details

* Browser: Chrome 73.0.3683.86
* OS: macOS Mojave, 10.14.3
* CKEditor version: 4

**Comment by jacekbogdanski** [comment]
Sorry, I don't know what's Mura stands for. Could you provide simplified reproduction steps without 3rd party software?

**Comment by jkd77** [comment]
Thanks for the response. Unfortunately this scenario only exists within the [Mura CMS](https://www.getmura.com/). But I think this scenario is relevant to similar situations within other content management systems like Wordpress that also use short code type syntax for including dynamic content within the editor.

As for simplified reproduction steps, is there a way to tell CKEditor to ignore a specific character pattern? Perhaps similar to a regular expression? In this case, [m]and everything in here[/m]

**Comment by jacekbogdanski** [comment]
Not really, you rather need to explicitly insert an empty paragraph, it shouldn't be added magically by API. It seems like mentioned CMS upstream. Also, note that if you insert such HTML into editor without wrapping `p` tags, you will lose the ability to place a selection around a wrapper.

Nevertheless, you could use [`CKEDITOR.dtd.$removeEmpty`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html#property-S-removeEmpty) to enable auto-removing empth paragraphs:
`CKEDITOR.dtd.$removeEmpty = 1` or [custom filter](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser_filter.html) - but I rather recommend to contact with Mura CMS dev team by e.g. issue tracker to discuss the problem.

**Comment by jkd77** [comment]
Paragraph elements are automatically added by CKEditor to wrap entered text content. This is not as far as I know a result of Mura.

I have also been in communication with Mura forums on the issue, along with StackOverflow and a few others. I will look into using the removeEmpty function and see if that fits the bill. Thanks for that information.
