### ISSUE TITLE
Opening Emoji Panel on Android causes infinite jumping loop between panel and virtual keyboard

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#3049]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open Emoji sample https://ckeditor.com/docs/ckeditor4/latest/examples/mentions.html. 
2. Open Emoji Panel.

### Expected result

Emoji Panel opens and it is possible to select Emoji.

### Actual result

Emoji Panel opens, next Virtual Keyboard opens, Emoji Panel shifts up, Virtual Keyboard hides, Emoji Panel shifts down, Virtual Keyboard pops up, Emoji Panel shifts up and so on... 

Please see attached screen cast:
[chorome emoji panel.zip](https://github.com/ckeditor/ckeditor-dev/files/3064493/chorome.emoji.panel.zip)

## Other details

* Browser: Chrome (Firefox works fine)
* OS: Android
* CKEditor version: 4.11.4
* Installed CKEditor plugins: Emoji, Mentions

**Comment by engineering-this** [comment]
Looks like dup of #2594

**Comment by engineering-this** [comment]
Can you check if the issue is reproducible on branch `t/2594` from https://github.com/ckeditor/ckeditor-dev/pull/2642

**Comment by jswiderski** [comment]
Damn you. This is a duplicate of #2594 and in deed it is working fine on `t/2594` 👍
