### ISSUE TITLE
paste formula from word

### ISSUE THREAD

**Issue by gland2015** [ckeditor/ckeditor-dev#3058]
## Type of report
Feature request
## Provide description of the new feature
I want the latex code for the formula, What should I do? thanks

*What is the expected behavior of the proposed feature?*
It's best to have a function to extract code from data，thanks

**Comment by Comandeer** [comment]
Can you provide more info about requested feature? Word document with mentioned formula would be very helpful.

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
