### ISSUE TITLE
Font tag overrides inner style definition

### ISSUE THREAD

**Issue by Deeem2031** [ckeditor/ckeditor-dev#3060]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Insert following html into the editor via the sourcearea-plugin
```
<font color="#080000" size="7" face="Microsoft Sans Serif">
  <div style='font-size: 10px'>
    text
  </div>
</font>
```
2. Switch back to the wysiwyg-mode

### Expected result

A tiny "text" (Size of 10px)

### Actual result

A big "text" (Size of "7")

3. When switching back to the source you'll see
```
<div style="font-size:10px">
  <span style="color:#080000; font-family:Microsoft Sans Serif; font-size:48px">
    Text
  </span>
</div>
```

So it seems while converting the font-Tag to a span-Tag the nesting is getting messed up.
I would expect this:
```
<span style="color:#080000; font-family:Microsoft Sans Serif; font-size:48px">
  <div style="font-size:10px">
    Text
  </div>
</span>
```
Which strangely enough also get's messed up when inserting into the ckeditor.

## Other details

* Browser: Chrome/Chromium
* OS: Windows 10
* CKEditor version: 4.11.4
* Installed CKEditor plugins: "Full Package"

**Comment by Comandeer** [comment]
`span` can't contain `div` element, as `span` is inline, text-level element and `div` is a block one. The same is true also for `font`, which is defined as inline element in HTML 4.01 Transitional. Therefore CKEditor just fixes the incorrect markup.

To get correct result, you can replace `div` with `span`:

```html
<font color="#080000" size="7" face="Microsoft Sans Serif">
	<span style='font-size: 10px'>
		text
	</span>
</font>
```

**Comment by Deeem2031** [comment]
While this might be true and the markup is incorrect. The fix introduces significant visual changes.
It would be optimal if ckeditor fixes the markup and keeps the visual experience by dropping overriden styles imho.
So the expected output would be: (span without font-size)

```
<div style="font-size:10px">
  <span style="color:#080000; font-family:Microsoft Sans Serif">
    Text
  </span>
</div>
```
