### ISSUE TITLE
Adding Iframe in editor content area

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor-dev#3064]
I am making a custom plugin for ckeditor4. It should insert an iframe of an html file into the editor text area .
i tried using this but it didn't worked
```
editor.addCommand( 'insertTimestamp', {
            exec: function( editor ) {
                 editor.insertHtml( '<iframe src="./mathquill.html"  />');
          }
 });
```

**Comment by engineering-this** [comment]
Such plugin already exists: [`iframe` plugin](https://ckeditor.com/cke4/addon/iframe).
