### ISSUE TITLE
windows xp下新建一个管理员账号（不设密码），并用新建管理员账号登录时，ie8浏览器中的cekditor，无法粘贴来自word2010的内容

### ISSUE THREAD

**Issue by liu2628829** [ckeditor/ckeditor-dev#3067]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. windows xp下新建一个管理员账号（不设密码）
2.用新建管理员账号登录
3. 打开ie8浏览器中的cekditor
4.复制word2010的内容
5.粘贴到cekditor中时，无效果（光标会闪一下），ctrl+v快捷键、右键菜单“粘贴”、工具来的“粘贴自MSword的内容”按钮也无效果
6.但将word2010的内容粘贴到记事本正常，将记事本内容粘贴到cekditor也正常
7.已设置ie浏览器的安全设置，启用 对剪切板进行编程访问，启用 拖动或复制粘贴文件

* Browser: ie8
* OS:windows xp sp3
* CKEditor version: CKEditor 4
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Please, open a new issue in English, otherwise, we can't understand you.
