### ISSUE TITLE
Here is a patch that adds functionality to the ckeditor find plugin for removal of empty p tags and or find replace within a p tag, removes if newstring empty and optional removal of br tags.

### ISSUE THREAD

**Issue by joejoseph00** [ckeditor/ckeditor-dev#3072]
Feature request (a working patch is provided)

*Expect find plugin to be able to find and replace empty p tags when search is empty, OR to remove a p tag if the find string matches and there's no replace string. Expect find plugin to optionally remove br tags*

Original issue from Drupal.org: https://www.drupal.org/project/ckeditor_find/issues/3050091

See working patch below:

**Comment by joejoseph00** [comment]
here's the patch:

https://www.drupal.org/files/issues/2019-04-23/find_plugin_ckeditor_d-o-issue-3050009_github-feature_request_ckeditor_ckeditor-dev_issues_3072.patch

**Comment by joejoseph00** [comment]
patch works well, here is the patch followed by a screenshot: https://www.drupal.org/files/issues/2019-04-23/find_plugin_ckeditor_d-o-issue-3050009_github-feature_request_ckeditor_ckeditor-dev_issues_3072.patch

![ckeditor_find_plugin_patched_br_and_p](https://user-images.githubusercontent.com/1028526/56605902-1cf78880-65d3-11e9-96de-31a86556400e.png)

**Comment by jacekbogdanski** [comment]
Hello,

It's possible to remove empty spaces by providing space character to the replace tool. More complicated cases should be rather handled by regex support, although, such a feature is more useful for developers, not sure if it's something you are looking for. If so, please, create a new feature request using our template.

Your proposition operates on DOM which should be hidden from the user, nevertheless, if you would like to contribute to the CKEditor4, please create Pull Request which your proposition. Also, CKEditor4 is very expandable, don't hesitate to create your own plugin which could also be shared with our [Add-ons Library](https://ckeditor.com/cke4/addons/plugins/all).

**Comment by joejoseph00** [comment]
Content editors should not need to know the intricacies of character sets to be able to replace these garbage nbsp p elements. Even myself as a senior developer had to discover this.  The functionality I am handing over to you here is highly relevant.  It would be nice if you could add this in in some form or other.

**Comment by joejoseph00** [comment]
It is far easier to have a checkbox and prompt as the patch provides.  If you have a better idea make a patch.

**Comment by joejoseph00** [comment]
Yes its possible to remove these as you mentioned but obscure and try to explain this to content editors publishing bakery recipes pasted from word.  I figures that out painfully but these options are explicit and more people undestand it even developers.

**Comment by joejoseph00** [comment]
Do a google search for remove empty p tags and see how there are a lot of developers and web people struggling with this.

**Comment by joejoseph00** [comment]
I am responding to a huge outcry by the web for a solution to remove empty p tags
