### ISSUE TITLE
Problem with special character on cke_combo_text

### ISSUE THREAD

**Issue by samixchoumi** [ckeditor/ckeditor-dev#3074]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Add a cke_combo_text with special character in it.

### Actual result

Actually i got this : 
![something_wrong](https://user-images.githubusercontent.com/22171928/56642994-fe4bcd00-6678-11e9-8619-9b0cf7344564.png)

### Expected result

But i don't want that specials characters are encoded while hovering or selecting a value (it should be as it's shown in the list)

## Other details

* Browser: Google Chrome
* OS: Linux
* CKEditor version: 4.6.1

**Comment by jacekbogdanski** [comment]
Could you give more information about how are you customizing `format` combo labels? AFAIK we don't have any public API for that except custom lang files which would make it a feature request and I'm not sure what do you mean writing
> Add a cke_combo_text with special character in it.

**Comment by samixchoumi** [comment]
In the defaultCongif.json
I've these information : 
```
    ...
    },
    {
      "name": "styles",
      "items": [
        "Format",
        "-",
        "Blockquote"
      ]
    }
  ],
  "format_cite": {"element": "cite"},
  "format_q": {"element": "q"},
  "format_tags": "p;h2;h3;h4;h5;h6;address;cite;q",
```
Same for styleParagraph.json

in custom/lang 
my file have encoded value : 
```
CKEDITOR.plugins.languagemerge.mergeExtra('fr', {
    'format': {
        'tag_h2': 'Titre 1 (&lt;h2&gt;)',
        'tag_h3': 'Titre 2 (&lt;h3&gt;)',
        'tag_h4': 'Titre 3 (&lt;h4&gt;)',
        'tag_h5': 'Titre 4 (&lt;h5&gt;)',
        'tag_h6': 'Titre 5 (&lt;h6&gt;)',
        'tag_address': 'Adresse (&lt;address&gt;)',
        'tag_cite': 'Citation de référence (&lt;cite&gt;)',
        'tag_q': 'Citation courte (&lt;q&gt;)'
    }
});
```

**Comment by jacekbogdanski** [comment]
I see that you are using 3rd party plugin to change language files, that makes sense. Nevertheless, format labels are set by `setText` so you will see the same output as inside language file.

I think we could enable adding custom label name by `format` configuration (e.g. https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-format_div), so you could write something like:

`config.format_h1 = { element: 'h1', name: 'Title 1 (<h1>)'  };`

Would it resolve your issue?

**Comment by samixchoumi** [comment]
> config.format_h1 = { element: 'h1', name: 'Title 1 (<h1>)' };

On which file should i put this to try it ?

**Comment by jacekbogdanski** [comment]
@samixchoumi it could be available as a configuration option for all `config.format_X` settings, e.g. https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-format_div

The feature is not ready yet, I will report as a separate issue it to avoid rewording the current ticket. I'm closing this one as there is no bug with `format` plugins, it's just lacking mentioned feature.
