### ISSUE TITLE
Problem with embed video

### ISSUE THREAD

**Issue by SergAndrs** [ckeditor/ckeditor-dev#3083]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. I'm embed video via link and it's not on full block
Here is link:
https://www.youtube.com/watch?v=XAySO1oGFbI
and here is sreenshot of how it's look like
https://prnt.sc/nkom0j
2. Does media embed support .mp4?

### Expected result
and how it's look on your demo
https://prnt.sc/nkonm1

* Browser: Firefox, Chrome
* OS: Ubuntu
* CKEditor version: 4
* Installed CKEditor plugins: popup,filebrowser,youtube,imagebrowser,moxiemanager,preview,liststyle,embed,embedbase,autoembed,autolink,clipboard,notification,undo,image2,ckawesome
//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}

**Comment by f1ames** [comment]
Hello @SergAndrs,

> I'm embed video via link

Do you embed the video just by pasting a link to the video or through embed dialog?

> popup,filebrowser,youtube,imagebrowser,moxiemanager,preview,liststyle,embed,embedbase,autoembed,autolink,clipboard,notification,undo,image2,ckawesome

I can see you have a few 3rd-party plugins for embedding media - **youtube** and  **moxiemanager**, which might be the reason for the different video styling. I would check how the embedded video looks without those plugin.

**Comment by SergAndrs** [comment]
Hi @f1ames
First of thanks for quick reply.
> Do you embed the video just by pasting a link to the video or through embed dialog?
 Via embed dialog.
> I can see you have a few 3rd-party plugins for embedding media - **youtube** and **moxiemanager**, which might be the reason for the different video styling. I would check how the embedded video looks without those plugin.
I'll check and let you know

Thanks.

**Comment by SergAndrs** [comment]
Thanks for help.
