### ISSUE TITLE
"Textarea" column(specifically 'txt' column type) in Inline editing positioning issue

### ISSUE THREAD

**Issue by ankitkothariak** [ckeditor/ckeditor-dev#3097]
## Type of report

Bug

### steps (if any)

1. inline editing should be enabled on the grid, there should be one column created with  'txt' column type.
2. double click on this cell which is having this 'txt' column type, to edit this

### Expected result
the textarea opens inside the cell and while resizing the browser the textarea position should remain inside the cell with all other events should work on this. 
Basically,
![position issue](https://user-images.githubusercontent.com/49710033/57610897-4d599380-758f-11e9-8fc6-6cc019445d3c.PNG)
![resizing issue](https://user-images.githubusercontent.com/49710033/57610904-521e4780-758f-11e9-9861-440d6dc3abda.PNG)

 inline editing should work similarly  as  "ed" column type for 'txt'column type

### Actual result

the textarea opens below the cell clicked while resizing the browser size position of textarea gets changed.(please see screenshots)

## Other details
The reason being textarea opened below the clicked cell is("txt" column type), it appends the textarea to the <body> tag of the grid. However, when we edit "ed" column type cell it opens this within the cell, the reason being it appends textarea inside the <td> tag of the dhtmlx's grid.

We edited some library files and tried to open 'txt' column type inside the cell by rendering it the <td> tag of the gid instead of <body> tag. but the problem was some keypress events stopped working

* Browser:Google chrome, mozila firefox, Internet explorer
* OS:windows 10

**Comment by f1ames** [comment]
Hello @ankitkothariak,
is this issue related in any way to CKEditor? I see you are using plain textarea element as you mentioned 🤔

**Comment by ankitkothariak** [comment]
@f1ames please ignore, i have raised for plain textarea not for rich textarea. i am closing this one.
