### ISSUE TITLE
Not able to paste image using ctr v in chrome using enhanced image plugin ckeditor

### ISSUE THREAD

**Issue by azhershaikh** [ckeditor/ckeditor-dev#3102]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I am trying to paste image using ctrl + v in Ckeeditor with image2 plugin (enhanced image plugin) but nothing is being pasted in Chrome.

It works in IE but not in chrome

### Expected result

Pasted image should be visible.

### Actual result

Nothing is being pasted in chrome browser 

## Other details

* Browser: … Chrome
* OS: …  Windows 10
* CKEditor version: …  4.11.4
* Installed CKEditor plugins: …   image2 (enhanced image plugin)

**Comment by azhershaikh** [comment]
Also , it works on this demo site https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html  in chrome browser.
But not in my ckeeditor which has same version 4.11.4 and image 2 plugin installed and configured.
Just problem of chrome and still nothing is being pasted.

**Comment by f1ames** [comment]
> Also , it works on this demo site https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html in chrome browser.

The fact that it works in different CKEditor instance, means that it may be caused by misconfiguration of your instance. Are there any errors in the browser dev console?

Do you have `uploadimage` plugin included in you CKEditor instance, [`uploadUrl `](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-uploadUrl) and [`filebrowserImageUploadUrl`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-filebrowserImageUploadUrl) configured correctly?

Please take a look at the [docs on image uploading](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_manager_configuration.html#adding-file-manager-scripts-for-selected-dialog-windows).

**Comment by azhershaikh** [comment]
No errors in browser dev console.

I don't have upload image plugin as enhanced image plugin dependency shows only widget and dialog plugin as dependency. Does it really required ?

Do you have uploadimage plugin included in you CKEditor instance, uploadUrl and filebrowserImageUploadUrl configured correctly?

**Comment by azhershaikh** [comment]
I have added uploadimage plugin and now image is getting saved on server but while returning from server getting below error on console.


[CKEDITOR] Error code: filetools-response-error. 

Here is what returned : 

responseText: "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction(,"http://localhost/NvBugs5/Upload/Files/image.png" , '');</script>"


Also tried, setting      config.filebrowserUploadMethod = 'form'; in config.js but keep getting error on console and file is not visible in editor

**Comment by jacekbogdanski** [comment]
> I don't have upload image plugin as enhanced image plugin dependency shows only widget and dialog plugin as dependency. Does it really required ?

If images are only handled by URL address (hosted by an external server), you don't need `uploadimage` plugin. However, if you want to handle local images, you should configure your backend server or use [CKFinder](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_ckfinder_integration.html).

The [`filetools-response-error`](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#filetools-response-error) says you incorrectly configured your backend server, where JSON response is expected. You can read more about expected `uploadimage` response here: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html#response-file-uploaded-successfully

About the issue with copying and pasting image itself - I don't have any problem using our [Image upload](https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html#uploading-dropped-and-pasted-images) sample, just make sure you correctly configured CKEditor using provided guides.

Note that you won't be able to upload an image directly from the filesystem using CTRL+C / CTRL+V keyboard shortcuts, although in that case image can be dropped into editor.
