### ISSUE TITLE
Font doesn't displayed in Editor, when comboName passed to addCombo func is "Font"

### ISSUE THREAD

**Issue by iryna-k** [ckeditor/ckeditor-dev#3104]
## Type of report

Bug
Hello, I've faced with issue due to Font plugin.

## Provide detailed reproduction steps (if any)

1. enable Font plugin
2. open Text Editor
3. observe all the buttons

### Expected result

To see buttons Font Size, Font

### Actual result

Only Size is shown

## Other details

* Browser: Chrome, Firefox etc
* Installed CKEditor plugins: Font, Colorbutton, Justify and all default

What I've found - the problem in this place:

	CKEDITOR.plugins.add( 'font', {
		requires: 'richcombo',
		// jscs:disable maximumLineLength
		lang: 'af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn', // %REMOVE_LINE_CORE%
		// jscs:enable maximumLineLength
		init: function( editor ) {
			var config = editor.config;

			addCombo( editor, 'Font', 'family', editor.lang.font, config.font_names, config.font_defaultLabel, config.font_style, 30 );
			addCombo( editor, 'FontSize', 'size', editor.lang.font.fontSize, config.fontSize_sizes, config.fontSize_defaultLabel, config.fontSize_style, 40 );
		}
	} );
} )();

When I replace the comboName in addCombo func (instead of Font make it FontSize) and comment the second call of addCombo, the Font button is displaying in Editor. It's like something wrong with "Font" or like FontSize param is acceptable only here(just my assumption).. Please, help me understand what's wrong with it?

**Comment by iryna-k** [comment]
config.js (customized)

/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here.
	// For complete reference see:
	// http://docs.ckeditor.com/#!/api/CKEDITOR.config

	// The toolbar groups arrangement, optimized for two toolbar rows.
	config.toolbarGroups = [
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'links' },
		{ name: 'insert' },
		{ name: 'forms' },
		{ name: 'tools' },
		{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'others' },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' }
	];

	// Remove some buttons provided by the standard plugins, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Underline,Subscript,Superscript';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;h4;h5;h6;address;pre';

		// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';

    
    config.extraPlugins = 'justify,font,colorbutton';

};

**Comment by f1ames** [comment]
Hi @iryna-k,
it looks like it's working correctly. See this codepen with `standard-all` build and your config - https://codepen.io/f1ames/pen/WBoPGB?editors=1011.

Do you have any errors in browser dev console? Or using any 3rd-party plugins?

**Comment by iryna-k** [comment]
Hello @f1ames 
Thanks for response. Well, we use CKEDITOR as 3-d paty system for WISYWYG Editor in SmartEdit (part of Hybris E-commerce( platform for web development)). As I can see Font plugin doesn't work properly for a long time there. May be Hybris breaks it somehow, even though it shouldn't. Anyway it's not CKEDITOR fault.

**Comment by f1ames** [comment]
Thanks @iryna-k, I would suggest to try reaching to Hybris platform support/development team, maybe they will have some clues on this one.
