### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by TheHunterDog** [ckeditor/ckeditor-dev#3107]
you have an error in your documentation you are saying that the 					element.attribute('class', 'myclass'); should be after  openTagClose
but in fact, this is false it should be the other way around right?

please correct me if I am wrong

**Comment by Comandeer** [comment]
Can you provide some more info about the error, like the page on which is present?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
