### ISSUE TITLE
Removing a placeholder adds Zero-width spaces

### ISSUE THREAD

**Issue by loers** [ckeditor/ckeditor-dev#3110]
## Type of report

Bug

When a placeholder is removed there seem to occur some additional zero-width spaces. In combination with the autocomplete plugin this leads to invalid offset calculation if right after the removal of a placeholder.

## Provide detailed reproduction steps (if any)

1. Add some text, then a placeholder | e.g. "1 + [[Placeholder]]"
2. Remove the placeholder (e.g. by usign backspace)
3. The text contains zero-width spaces that weren't there before | e.g. "1 + <several zero-width spaces>
(4.) In our specific case if we try to enter a placeholder again using the autocomplete plugin it does not calculate the text to search with correctly because the zero-width spaces mess up the overall text length. After typing a single backspace the zero-width spaces seem to be removed.

### Expected result
The content of the editor before adding a placeholder and after deleting the placeholder are the same. No zero-width spaces should be added to the editor.

### Actual result

Removing a placeholder adds multiple zero-width spaces.

## Other details

* Browser: `JxBrowser`
* OS: `Windows`
* CKEditor version: `4.11.4`
* Installed CKEditor plugins: `autocomplete`, `button`, `clipboard`, `dialog`, `dialogui`, `placeholder (customized)`, `enterkey`, `lineutils`, `notification`, `tab`, `textmatch`, `textwatcher`, `toolbar`, `widget`, `widgetselection`

**Comment by f1ames** [comment]
Hi @loers,
Can you confirm if the same happens on a Chrome browser? `JxBrowser` is not officially supported by CKEditor 4, however I see it is Chromium based so the issue may be visible on Chrome/Safari browsers.

**Comment by loers** [comment]
I tried but I dont know yet if I can open the editor somewhere else. At least wihout some effort.

**Comment by jacekbogdanski** [comment]
JxBrowser seems to be chromium based browser, however, I'm not able to reproduce the issue with Chrome itself.

We cannot guarantee that CKEditor will work correctly in niche web browsers but if you are able to reproduce the issue with Chrome or any other browser from our [Browser Compatibility](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html) list, please, give us know so we can reopen this ticket.

Also, we have already reported issue related to Autocomplete and chromium filling chare sequence - https://github.com/ckeditor/ckeditor-dev/issues/2240. I can recommend subscribing this issue for updates as it may fix the reported bug for JxBrowser also.
