### ISSUE TITLE
Selecting a paragraph 3 times and applying heading 1 on that paragraph applies heading on next paragraph as well.

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#3118]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.  Paste this text in ckeditor.com demo page
The purpose of lorem ipsum is to create a natural looking block of text (sentence, paragraph, page, etc.) that doesn't distract from the layout. A practice not without controversy, laying out pages with meaningless filler text can be very useful when the focus is meant to be on design, not content.

The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum.

2. Select first paragraph by clicking on it 3 times.
3. Select Heading 1 from drop down.
4. The next paragraph also becomes heading.

### Expected result

Only first paragraph should change to Heading1

### Actual result

Next paragraph also changes to Heading1

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.11.4
* Installed CKEditor plugins: not relevant

**Comment by zoarif** [comment]
Note: This issue repros with indent and other block level formats as well.

**Comment by f1ames** [comment]
Confirmed (both when first text part is paragraph or list item):

![cke4 issue1](https://user-images.githubusercontent.com/1061942/58088554-3afcdc80-7bc3-11e9-80ad-a1c9266c29c8.gif)

**Comment by f1ames** [comment]
This issue is in fact caused by the upstream browser issue, please see this comment https://github.com/ckeditor/ckeditor-dev/issues/484#issuecomment-374887986. In this case I would consider it as a feature request to alter default browser behaviour.
