### ISSUE TITLE
Suggest to add more numberedlist

### ISSUE THREAD

**Issue by cabbageehero** [ckeditor/ckeditor-dev#3122]
## Type of report

Feature request

## Provide description of the new feature

*add  frequently-use numberedlist, like:
一、    (1) .    (一)   etc……

**Comment by f1ames** [comment]
There is a [List Style](https://ckeditor.com/cke4/addon/liststyle) plugin which provides a way to use some common numbering/bullets.

@cabbageehero Could you list which numbering/bullets format you would like to use?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
