### ISSUE TITLE
Should restore cursor position of div.contenteditable after CKEditor.inline action

### ISSUE THREAD

**Issue by medinsky** [ckeditor/ckeditor-dev#3126]
## Type of report

Bug with caret position after initialization of CKEDITOR on onclick (perhaps, any) event

## Provide detailed reproduction steps (if any)

1. Create div contenteditable with id="editor" (or set contenteditable before CKEDITOR.inline)
2. Add some text inside of it. Better paragraphs with some text
```
<div id="editor">
  <p>Hello my name is ...</p>
  <p>I am from ...</p>
  <p>London is the capital of Great Britain</p>
</div>
```
3. Create onclick event handler on #editor that will run CKEDITOR.inline action inside of it.
```
 editor.onclick = function(e) {    
    if (!isActivated) {
      isActivated = true;
      editor.setAttribute('contenteditable', true);
      const cke = CKEDITOR.inline('editor');
    }
  }
```

### Expected result

I expect that the caret position will be saved for me after editor initialization.
If I click by my mouse between `r` and `o` in the word `from` in the second paragraph, then I expect that caret will be as in `fr`**|**`om` 

### Actual result

Now caret moves to the start at 0 position of the whole editor. And I got  
**|**`Hello my name is ...` even when I click in div contenteditable at the word `from` as I described in expected result

## Other details

* Browser: Chrome/IE10
* OS: Windows10
* CKEditor version: 4.11.4
* Installed CKEditor plugins: default https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js without any plugins from outside.

## Playground

https://codepen.io/medinsky/pen/zQpBJQ?editors=1010

I asked this like a question, but it seems that it is a bug too.
https://stackoverflow.com/questions/56255146/how-to-restore-caret-position-after-ckeditor-inline-in-onclick-event-handler

**Comment by jacekbogdanski** [comment]
Hello,

the issue is anyhow related to the CKEditor4 itself, but the native behavior of the browser. You can reproduce the same issue using https://codepen.io/jacekbogdanski/pen/VOJXZb where I'm using native contenteditable element. Your click is propagated into uneditable element at first, so the caret won't appear despite changing element into contenteditable.

The simplest way to fix the issue would be probably by using `mosuedown` event instead of `click`.

**Comment by wwalc** [comment]
Greetings from Poland! It's nice to see we have so active community in Belarus, the number of upvotes is impressive :) Thanks for choosing CKEditor!

**Comment by medinsky** [comment]
> Hello,
> 
> the issue is anyhow related to the CKEditor4 itself, but the native behavior of the browser. You can reproduce the same issue using https://codepen.io/jacekbogdanski/pen/VOJXZb where I'm using native contenteditable element. Your click is propagated into uneditable element at first, so the caret won't appear despite changing element into contenteditable.
> 
> The simplest way to fix the issue would be probably by using `mosuedown` event instead of `click`. However, it won't fix the issue with misplaced selection, as the whole content is upcasted into more complicated HTML. You will need to restore selection after the editor has been initialized.

Thanks for the answer, it works, but it helps only with native contenteditable, CKEditor4 drops cursor at the start of its container as I shown. I think that because of full rewrite HTML it brakes ranges/selection. Is there any possiblities that ckeditor4 will learn how to restore cursor after initialization?



> Greetings from Poland! It's nice to see we have so active community in Belarus, the number of upvotes is impressive :) Thanks for choosing CKEditor!

Greetings! Yeap, we love CKEditor! :) And CKEditor loves us at some moments :)

**Comment by engineering-this** [comment]
Hi,

A bit hacky, but should be quite simple to implement.

1. Create bookmark from selection before creating editor.
1. Change bookmark element attributes so editor won't recognize it as bookmark - laso you might want to add it to ACF.
1. Create editor.
1. Revert changes from step 2.
1. Move ranges to bookmark.

https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-createBookmark
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-moveToBookmark

**Comment by medinsky** [comment]
@engineering-this , thanks for advice, will try to do that

**Comment by wwalc** [comment]
@medinsky if you manage to complete it, could you please add your code here and on Stackoverflow so that others could have a ready-to-use quick code snippet?

**Comment by medinsky** [comment]
> ready-to-use quick code snippet

```
export const insertTextAtRangeStart = (text: string) => {
    const sel = window.getSelection();

    if (sel.getRangeAt && sel.rangeCount) {
        const range = sel.getRangeAt(0);
        range.insertNode(document.createTextNode(text));
    }
};

export const insertTextAtRangeEnd = (text: string) => {
    const sel = window.getSelection();

    if (sel.getRangeAt && sel.rangeCount) {
        const range = sel.getRangeAt(0);
        range.collapse(false);
        range.insertNode(document.createTextNode(text));
    }
};
```

I created such functions to insert markers at range start and end.
Markers are:

```
export const zeroWidthNonJoiner = 8204;
export const zeroWidthJoiner = 8205;
export const bookmark = {
    end: String.fromCharCode(zeroWidthJoiner, zeroWidthNonJoiner),
    start: String.fromCharCode(zeroWidthNonJoiner, zeroWidthJoiner),
};
```

And after CKEditor init I restore ranges (selection) by finding these markers (node and offset in node).
