### ISSUE TITLE
Office2013 Skin missing from source

### ISSUE THREAD

**Issue by nm4568** [ckeditor/ckeditor-dev#3129]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. git clone https://github.com/ckeditor/ckeditor-dev.git
2. Open /skins directory

### Expected result

*What is the expected result of the above steps?*

Office2013 folder should exist

### Actual result

*What is the actual result of the above steps?*

Office2013 folder is missing

**Comment by Comandeer** [comment]
Skins can be downloaded from https://ckeditor.com/cke4/addons/skins/all

Additionally please note that Office2013 is not an official, supported by CKSource skin for CKEditor 4.
