### ISSUE TITLE
config.height is not working

### ISSUE THREAD

**Issue by voletiswaroop** [ckeditor/ckeditor-dev#3135]
## Type of report

Bug

config.height custom setting for CKEditor not working in Drupal 8

## Provide detailed reproduction steps (if any)

1. Installed CKEditor Custom Configuration plugin
2. configuared "config.height = "500px" in 'CKEditor Custom Configuration' area

### Expected result

CKEditor height should change from default 200px to 500px as per custom config

### Actual result

There is no difference in CKEditor height 

## Other details

* Browser: Chrome, Firefox
* OS: MAC
* CKEditor version: 4.10.1
* Installed CKEditor plugins: CKEditor Custom Configuration plugin

**Comment by f1ames** [comment]
Hello @voletiswaroop,
I assume this issue is related to Drupal integration. It seems to work fine with CKEditor 4 itself - see https://codepen.io/f1ames/pen/zQaPmE.

If it's Drupal related, please report it on Drupal issue tracker.

**Comment by voletiswaroop** [comment]
Thank for the update @f1ames
