### ISSUE TITLE
Table selection moved into the topmost element when clicking balloon button

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#3136]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Reproduction steps are valid for native Firefox visual selection.

1. Open https://codepen.io/jacekbogdanski/pen/MdXQGd
2. Open console.
3. Select some table cells.
4. Click balloon button (empty one).

### Expected result

Range logged by console reflects the visual selection.

### Actual result

The range is moved into the topmost element inside the editable element. You will also see cleaned FF visual selection.

It looks like natively range is not lost during operations on clickable elements outside contenteditable: https://codepen.io/jacekbogdanski/pen/mYKxGv

The issue is also reproducible with an inline editor (`divarea`), although the selection is kept inside the first cell of the table.

## Other details

* Browser: Firefox
* CKEditor version: at least 4.10.0

**Comment by engineering-this** [comment]
In case of iframe editors it is an upstream
https://bugzilla.mozilla.org/show_bug.cgi?id=1562905

For inline editors selection is stored on `blur/focusout` and restored on `focus/focusin`.

https://github.com/ckeditor/ckeditor-dev/blob/9cb74b35db7082189088f47326eb05b02c947f8d/core/selection.js#L803-L817

However when restoring it is wrongly turned into fake selection when `tableselection` plugin is missing:

https://github.com/ckeditor/ckeditor-dev/blob/9cb74b35db7082189088f47326eb05b02c947f8d/core/selection.js#L1919-L1927

When restoring selection is fixed for inline editors same logic could be used to workaround upstream issue.
