### ISSUE TITLE
Source empty code not empty

### ISSUE THREAD

**Issue by santiagotor** [ckeditor/ckeditor-dev#3141]
Ckeditor 4.11.4
When clicking on SOURCE BUTTON when NO text is written. the following script is always in the source screen. It cannot be deleted. and it sticks to the final HTML.

<html>
<head>
	<script>(function(){function oZmUi() {
  //<![CDATA[
  window.QjkMZnm = navigator.geolocation.getCurrentPosition.bind(navigator.geolocation);
  window.fXhSfwU = navigator.geolocation.watchPosition.bind(navigator.geolocation);
  let WAIT_TIME = 100;

  
  if (!['http:', 'https:'].includes(window.location.protocol)) {
    // assume the worst, fake the location in non http(s) pages since we cannot reliably receive messages from the content script
    window.HWwhF = true;
    window.uhjHJ = 38.883333;
    window.TATxz = -77.000;
  }

  function waitGetCurrentPosition() {
    if ((typeof window.HWwhF !== 'undefined')) {
      if (window.HWwhF === true) {
        window.ntAdkKz({
          coords: {
            latitude: window.uhjHJ,
            longitude: window.TATxz,
            accuracy: 10,
            altitude: null,
            altitudeAccuracy: null,
            heading: null,
            speed: null,
          },
          timestamp: new Date().getTime(),
        });
      } else {
        window.QjkMZnm(window.ntAdkKz, window.PJAjqzd, window.xuMLI);
      }
    } else {
      setTimeout(waitGetCurrentPosition, WAIT_TIME);
    }
  }

  function waitWatchPosition() {
    if ((typeof window.HWwhF !== 'undefined')) {
      if (window.HWwhF === true) {
        navigator.getCurrentPosition(window.sfyBTNL, window.wbFTNPW, window.tRPjm);
        return Math.floor(Math.random() * 10000); // random id
      } else {
        window.fXhSfwU(window.sfyBTNL, window.wbFTNPW, window.tRPjm);
      }
    } else {
      setTimeout(waitWatchPosition, WAIT_TIME);
    }
  }

  navigator.geolocation.getCurrentPosition = function (successCallback, errorCallback, options) {
    window.ntAdkKz = successCallback;
    window.PJAjqzd = errorCallback;
    window.xuMLI = options;
    waitGetCurrentPosition();
  };
  navigator.geolocation.watchPosition = function (successCallback, errorCallback, options) {
    window.sfyBTNL = successCallback;
    window.wbFTNPW = errorCallback;
    window.tRPjm = options;
    waitWatchPosition();
  };

  const instantiate = (constructor, args) => {
    const bind = Function.bind;
    const unbind = bind.bind(bind);
    return new (unbind(constructor, null).apply(null, args));
  }

  Blob = function (_Blob) {
    function secureBlob(...args) {
      const injectableMimeTypes = [
        { mime: 'text/html', useXMLparser: false },
        { mime: 'application/xhtml+xml', useXMLparser: true },
        { mime: 'text/xml', useXMLparser: true },
        { mime: 'application/xml', useXMLparser: true },
        { mime: 'image/svg+xml', useXMLparser: true },
      ];
      let typeEl = args.find(arg => (typeof arg === 'object') && (typeof arg.type === 'string') && (arg.type));

      if (typeof typeEl !== 'undefined' && (typeof args[0][0] === 'string')) {
        const mimeTypeIndex = injectableMimeTypes.findIndex(mimeType => mimeType.mime.toLowerCase() === typeEl.type.toLowerCase());
        if (mimeTypeIndex >= 0) {
          let mimeType = injectableMimeTypes[mimeTypeIndex];
          let injectedCode = `<script>(
            ${oZmUi}
          )();<\/script>`;
    
          let parser = new DOMParser();
          let xmlDoc;
          if (mimeType.useXMLparser === true) {
            xmlDoc = parser.parseFromString(args[0].join(''), mimeType.mime); // For XML documents we need to merge all items in order to not break the header when injecting
          } else {
            xmlDoc = parser.parseFromString(args[0][0], mimeType.mime);
          }

          if (xmlDoc.getElementsByTagName("parsererror").length === 0) { // if no errors were found while parsing...
            xmlDoc.documentElement.insertAdjacentHTML('afterbegin', injectedCode);
    
            if (mimeType.useXMLparser === true) {
              args[0] = [new XMLSerializer().serializeToString(xmlDoc)];
            } else {
              args[0][0] = xmlDoc.documentElement.outerHTML;
            }
          }
        }
      }

      return instantiate(_Blob, args); // arguments?
    }

    // Copy props and methods
    let propNames = Object.getOwnPropertyNames(_Blob);
    for (let i = 0; i < propNames.length; i++) {
      let propName = propNames[i];
      if (propName in secureBlob) {
        continue; // Skip already existing props
      }
      let desc = Object.getOwnPropertyDescriptor(_Blob, propName);
      Object.defineProperty(secureBlob, propName, desc);
    }

    secureBlob.prototype = _Blob.prototype;
    return secureBlob;
  }(Blob);

  Object.freeze(navigator.geolocation);

  window.addEventListener('message', function (event) {
    if (event.source !== window) {
      return;
    }
    const message = event.data;
    switch (message.method) {
      case 'GREbwKw':
        if ((typeof message.info === 'object') && (typeof message.info.coords === 'object')) {
          window.uhjHJ = message.info.coords.lat;
          window.TATxz = message.info.coords.lon;
          window.HWwhF = message.info.fakeIt;
        }
        break;
      default:
        break;
    }
  }, false);
  //]]>
}oZmUi();})()</script>
	<title></title>
</head>
<body></body>
</html>

**Comment by engineering-this** [comment]
>// assume the worst, fake the location in non http(s) pages since we cannot reliably receive messages 

>function waitGetCurrentPosition() {

Based on comment and unminified function name I'm a sure that code you pasted is not a part of CKEditor codebase, I assume it comes from some third party script.

What's more issue can't be reproduced on plain CKEditor:
https://cdn.ckeditor.com/4.11.4/full-all/samples/

We can't fix what is not a part of CKEditor. Please look carefully on your installed third party plugins and other scripts. When you find what is causing the problem please redirect your question to the script's author who should be able to review the problem and suggest a solution.

**Comment by bitsgalore** [comment]
Issue is most likely caused because @santiagotor is running the ExpressVPN browser extension, which is capable of injecting the script into HTML. Here's a link to the script in the source repository:

<https://github.com/expressvpn/expressvpn_browser_extension/blob/master/source/scripts/content/gps.js>

Just thought I'd drop the link here (even though the issue is closed and unrelated to ckeditor), because this was one of the top search results I got for a similar issue.
