### ISSUE TITLE
Clicking on editor three time does not retain the selection

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#3146]
## Type of report

Feature request

## Provide description of the new feature
When you click three times in the editor, nothing seems to work as expected in the editor since selection is lost. I am following up on this bug as an example:

Subject: Re: [ckeditor/ckeditor-dev] When deleting the last line in a bullet-ed list, formatting on the next line is lost and merged into the bullet-ed list (#3119)

It's the standard behavior of the browser. When you are doing triple-click selection, the selection is ending at the following element, not selected text node. Although, I see it rather as a feature, not an upstream bug. You will have the same behavior for any element, not only list item. During triple-click, the whole line gets selected, not only clicked text.
You can reproduce this behavior also with native contenteditable: https://codepen.io/jacekbogdanski/pen/zQRBYW

*What is the expected behavior of the proposed feature?*
Clicking in editor three times should select everything and all formats should be applied properly.

**Comment by jacekbogdanski** [comment]
Selection with triple-click is the native one and works as expected. It shouldn't select the whole editor's content, only clicked text line.

![tripleclick](https://user-images.githubusercontent.com/10279586/58693525-443f3380-8391-11e9-88ba-d918ea6b8df6.gif)

Please, add more information about the issue if there are some edge cases where selection gets broken, so we could reopen this ticket.
