### ISSUE TITLE
cke_emoji-navigation_item svg images don't appear any more. 

### ISSUE THREAD

**Issue by ro6er1** [ckeditor/ckeditor-dev#3149]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Click the emoji dropdown in : CKE4 with the emoji plugin
2. Dropdown appears as expected, however the top navigation doesn't display the images.

### Expected result

*What is the expected result of the above steps?*
Top navigation images should appear
### Actual result

*What is the actual result of the above steps?*
Top navigation images don't appear.
## Other details
I can browse directly to the image: https://cdn.ckeditor.com/4.11.4/standard-all/plugins/emoji/assets/iconsall.svg?t=J39A#cke4-icon-emoji-2
However in Chrome and Firefox I can't see anything within the svg.

* Browser: Chrome & Firefox
* OS: OSX 10.13.6
* CKEditor version: 4
* Installed CKEditor plugins: emoji

**Comment by ro6er1** [comment]
Actually this is the same issue as this: https://github.com/ckeditor/ckeditor-dev/issues/2607
Although I need to see if that fixes it...

**Comment by jacekbogdanski** [comment]
In that case, I'm closing the ticket to avoid duplication. Please, follow #2607 for updates. If you want to speed things up, please don't forget to give the mentioned ticket :+1:
