### ISSUE TITLE
Unable to resize cell column of table with merged cell(s).

### ISSUE THREAD

**Issue by rkarina** [ckeditor/ckeditor-dev#3152]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a 3x3 table.
2. Merge the middle top cell with cell on the right.
3. Attempt to resize any column.

### Expected result

Successfully able to resize selected column left or right.

### Actual result

Unable to resize selected column left or right. It only works on rare occasions if you carefully place the cursor on a specific position of the column.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: v4.11.3
* Installed CKEditor plugins: {
		'a11yhelp' : 1,
		'autolink' : 1,
		'backgrounds' : 1,
		'base64image' : 1,
		'basicstyles' : 1,
		'bgimage' : 1,
		'blockquote' : 1,
		'chart' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'contextmenu' : 1,
		'docprops' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'image' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imagerotate' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'lineheight' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'maxheight' : 1,
		'pagebreak' : 1,
		'panelbutton' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'print' : 1,
		'quicktable' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'scayt' : 1,
		'showblocks' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'textsignature' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'zoom' : 1
	}

**Comment by f1ames** [comment]
Hello @rkarina,
could you take a look if this issue is reproducible on https://codepen.io/f1ames/pen/xNNjWM?editors=1010? I have added your configuration (without 3rd-party plugins) and was not able to reproduce it on Chrome (74):

![issue 3152](https://user-images.githubusercontent.com/1061942/59021836-e4db9a80-884c-11e9-9624-f2c48f9057be.gif)

Maybe it's caused by some 3rd-party plugins? 🤔

**Comment by rkarina** [comment]
It looks to be an issue with smaller tables (zoomed out?). If you zoom in
closer and enlarge the table, the chances of column resizing are higher
compared to when the tables are zoomed out (smaller font, thinner border,
etc). How do we increase the range of when the drag resizing event starts
for the cursor?

**Comment by f1ames** [comment]
The resizing range is based on table borders so you may try to increase table's `border-spacing` or `border-width`:

![border resize](https://user-images.githubusercontent.com/1061942/59086180-3d6c6f80-8901-11e9-9652-4c2e4bd9011f.gif)

**Comment by rkarina** [comment]
Hi @f1ames , 

The table borders are meant to be thin as these are based on Form guidelines by our customers/clients. In the code, is there a setting to programmatically increase the resizing range, independant of border-spacing and border-width?

**Comment by f1ames** [comment]
> In the code, is there a setting to programmatically increase the resizing range, independent of `border-spacing` and `border-width`?

There is no such configuration option. The only way would be custom adjustments in `tableresize` plugin code: https://github.com/ckeditor/ckeditor-dev/blob/81eaa3d976507d3e87c86cec21c8859977355a0d/plugins/tableresize/plugin.js#L91-L103

**Comment by rkarina** [comment]
Hi there,

What should I be changing in this block of code? The "pillarWidth" value?
Also, are we able to debug this tableresize plugin on debug mode? I can't
seem to find the script locally and put in a breakpoint.

**Comment by f1ames** [comment]
Yes, `pillarWidth` should be adjusted (you could also update `pillarLeft` to make sure the resizing pillar is centered on the table border).

To debug, you need CKEditor 4 development version (you can use this repo or download source via [online builder](https://ckeditor.com/cke4/builder)) since the default build has minified and concatenated code which is hard to debug.

**Comment by rkarina** [comment]
So the default build doesn't use the plugin.js source for TableResize?

**Comment by rkarina** [comment]
When I comment out the entire plugin.js source for tableresize, the
resizing still functions. My impression is that I need to change the pillar
size from another script/file?

**Comment by rkarina** [comment]
Hello @f1ames , 
Can I please get an update on this, as this is an ongoing issue with our clients.

**Comment by f1ames** [comment]
Hello @rkarina,

> So the default build doesn't use the plugin.js source for TableResize?

In the build version all `plugin.js` files are concatenated into `ckeditor.js` file. While this file is minified, it's quite difficult to modify (see https://github.com/ckeditor/ckeditor-releases/blob/full/4.11.4/ckeditor.js).

> When I comment out the entire plugin.js source for tableresize, the
resizing still functions. My impression is that I need to change the pillar
size from another script/file?

Not sure why it happens, if you have source (not minified) version of the editor and remove/comment out the `tableresize` plugin, resizing would not be possible. Maybe some cache issue. Or it is a native Firefox table resizing mechanism:

![image](https://user-images.githubusercontent.com/1061942/59591258-027eee80-90ee-11e9-97c2-3b48e12156a0.png)

**Comment by rkarina** [comment]
I'm using the production build, should I find the method in the minified
file and change it in the ckeditor.js file?

**Comment by CrazyLiar** [comment]
hi, Have you solved the problem yet?

**Comment by CrazyLiar** [comment]
I met the same problem .
Can you share the solution?

My English is terrible, so... if there are any mistakes, please forgive me.

**Comment by CrazyLiar** [comment]
> Hello @rkarina,
> could you take a look if this issue is reproducible on https://codepen.io/f1ames/pen/xNNjWM?editors=1010? I have added your configuration (without 3rd-party plugins) and was not able to reproduce it on Chrome (74):
> 
> ![issue 3152](https://user-images.githubusercontent.com/1061942/59021836-e4db9a80-884c-11e9-9624-f2c48f9057be.gif)
> 
> Maybe it's caused by some 3rd-party plugins? 🤔

@f1ames   hi, I met the same problem, you can try to merge the top cell or the bottom cell(set rowspan)

**Comment by f1ames** [comment]
@CrazyLiar, were you able to reproduce it on https://codepen.io/f1ames/pen/xNNjWM?editors=1010. Can you post a `.gif` showing exact steps how to do it? I still had no luck trying to reproduce it.

**Comment by CrazyLiar** [comment]
@f1ames  The code was cloned from the github ( https://github.com/ckeditor/ckeditor-dev).
the file path is ckeditor-dev/plugins/tableresize/ 

![tableresize4](https://user-images.githubusercontent.com/10043607/61791693-4384c400-ae4d-11e9-860b-6693ff2ee067.gif)

**Comment by CrazyLiar** [comment]
@f1ames  you can also reproduce it on https://codepen.io/f1ames/pen/xNNjWM?editors=1010.
choose merge down

**Comment by f1ames** [comment]
Thanks for the update @CrazyLiar, however your issue is different from one initially reported. The initial issue is about unaccessible resizer (very thin or not appearing) and with no `tableselection` plugin involved. The issue you described is related to `tableselection` plugin and the fact that table column doesn't resize correctly and table selection is shown instead of a resizer, extracted to a separate issue - #3298.

**Comment by CrazyLiar** [comment]
thank you for your reply.
sorry My English ability is limited.
so，Is this an issue to be repaired？
