### ISSUE TITLE
Loading CSS and JS only once for multiple ckeditors

### ISSUE THREAD

**Issue by bala-drg** [ckeditor/ckeditor-dev#3160]
is there a way we can load CSS and JS only once for multiple ckeditors on the same page instead of same css/js files loading multiple times

**Comment by jacekbogdanski** [comment]
Please, refer to articles about HTTP caching e.g. https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
Caching should be done on the server level, not by the client application.
