### ISSUE TITLE
Double click on one word span produces buggy selection

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3161]
## Type of report

Feature

## Provide detailed reproduction steps (if any)

1. Once `t/2813` (#2987) is merged open manual test `tests/core/editable/manual/insert`
2. Place collapsed selection in the middle of one spans `Foo ^bar`.
3. Press `insert element`.
4. Double click on created `bar` span.
5. Press `insert element`

### Expected result

Span containing word `bar` is completely removed.

### Actual result

Span is preserved only it's text is removed.

## Other details

This is an upstream browser issue, so it is labeled as a feature to provide a workaround. To fix this we should introduce logic to optimize selection, which would also fix #3118.

* Browser: Firefox
* OS: macOS
* CKEditor version: development of 4.12.0
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
As mentioned in https://github.com/ckeditor/ckeditor-dev/pull/2987#pullrequestreview-248878061 it also happens in IE11 (other IEs should be also checked when working on the bug fix).

**Comment by f1ames** [comment]
Extracted from #2987 - there is a wider issue, similar also to #3118. It is caused as @engineering-this mentioned by specific selection which begins on the current node but ends on the beginning of the next one (which is not visible). On IE11 it occurs also with mouse selection:

![ie11 issue](https://user-images.githubusercontent.com/1061942/59616432-b307e500-9124-11e9-88ff-559002ff3f00.gif)

And also in any other browser similarly:

![all issue](https://user-images.githubusercontent.com/1061942/59616442-b8652f80-9124-11e9-821c-8f9e35b6b5bc.gif)

I think we need proper Umbrella ticket for this issue, I will create it later.
