### ISSUE TITLE
Default Browser Keystroke ALT+S required to be added

### ISSUE THREAD

**Issue by sathyaprakash94** [ckeditor/ckeditor-dev#3179]
## Type of report

Default browser keystroke feature needs to be added

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

CK Editor's keystrokes are working fine, but when saving the ckeditor data that sends to server we need to save using **ALT+S** keys. It is missing in the CKEDITOR, only supports in built editor keystrokes. 

Much appreciable if you provide this ALT+S keystroke to save the data.

**Comment by jacekbogdanski** [comment]
If you need functionality which posts form to a server, please, take a look at [save](https://ckeditor.com/cke4/addon/save) plugin.

Additionally, you will need to set correct keystroke using [`setKeystroke`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-setKeystroke) method.

```javascript
editor.setKeystroke( CKEDITOR.CTRL + 83, 'save' ); // Attach CTRL + s keystroke to the save command
```
