### ISSUE TITLE
Failing test in tests/plugins/balloontoolbar/positioning

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#3185]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/plugins/balloontoolbar/positioning

### Expected result

All tests pass.

### Actual result

`test panel reposition (<editor-name>)` tests throw "Permission denied" or "Unspecified error" errors and fail. However they pass when called directly.

## Other details

* Browser: IE10, IE11
* Installed CKEditor plugins: balloontoolbar

**Comment by jacekbogdanski** [comment]
Also Edge, so probably all MS browsers.

**Comment by jacekbogdanski** [comment]
The tests are not failing on 4.11.4.

**Comment by f1ames** [comment]
Might be related to https://github.com/ckeditor/ckeditor-dev/pull/2667 changes.

**Comment by jacekbogdanski** [comment]
Actually, it's not a regression, just test suite issue.
