### ISSUE TITLE
ckeditor 4.11.4 modo edição

### ISSUE THREAD

**Issue by Denisfug2019** [ckeditor/ckeditor-dev#3192]
## Type of report
Bug
ckeditor 4.11.4 edit mode changes html markup without permission

## Provide detailed reproduction steps (if any)

1. Example with must stay **`<p class="m-b-md p-opacity f-w-700">{{TEXTO}}</p>`**
2. After editing **`<p>{{TEXTO}}</p>`**
This error goes through several other tags that were removed from the code

### Expected result

Edit mode does not interfere with html tags if there is no need.

### Actual result

This is changing html style tags excluding class content and thus damaging the page layout.

## Other details

* Browser: …chrome
* OS: …windows
* CKEditor version: …4.11.4
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Please take a look on documentation on [how to configure Advanced Content Filter (ACF)](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html#configuring-acf) to suit your needs.
