### ISSUE TITLE
Additional undo step created when editor is blurred while widget focused

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#3198]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://codepen.io/f1ames/pen/dBOOrY.
2. Embed some video (links provided).
3. ~~Double click embedded video and update its URL via dialog.~~
4. Focus embedded widget.
5. Blur editor by clicking somewhere outside.

### Expected result

There is single undo step for video embedding.

### Actual result

There are two undo steps for the video.

See https://github.com/ckeditor/ckeditor-dev/issues/3198#issuecomment-503627098 below for detailed explanation.

## Other details

* Browser: Tested on Chrome
* OS: macOS
* CKEditor version: `4.11.4` / `4.10.0`
* Installed CKEditor plugins: `standard all` preset

**Comment by f1ames** [comment]
This issue is a little more fancy. In the steps above I blurred the editor to copy 2nd link and that was the moment when additional undo step was created.

It happens only when widget is focused and editor is blurred. The visible drag handler (has some additional styles) is included in a snapshot created on blur and as this snapshot is different than the previous one it creates additional undo step. Can be tested on https://codepen.io/f1ames/pen/JQbNZq. See (errors in the console are irrelevant for this issue):

![embed issue cause](https://user-images.githubusercontent.com/1061942/59782021-5d1a7500-92bd-11e9-920d-d208b3f35f91.gif)

**Comment by wimleers** [comment]
FYI: this was originally reported for a Drupal CKEditor plugin that comes with a Widget: https://www.drupal.org/project/entity_embed/issues/3060245.

**Comment by wimleers** [comment]
Why is this not a problem for `image2`, which also uses a CKEditor Widget? At least on https://ckeditor.com/ckeditor-4/demo/ I cannot reproduce it. Both trigger a dialog. So what's the difference?

**Comment by f1ames** [comment]
@wimleers it's connected with blurring editor and not dialog itself. It can be reproduced also on demo with `image2` plugin (blurring editor adds undo step):

![issue undo focus](https://user-images.githubusercontent.com/1061942/59907572-b1cc0600-940b-11e9-9a9b-6af943d1cdc1.gif)

My assumption is that if dialog somehow blurs the editor (but I think the default dialog logic doesn't do that) the additional undo step will be added.

**Comment by f1ames** [comment]
Another update to my previous https://github.com/ckeditor/ckeditor-dev/issues/3198#issuecomment-503627098 - the additional snapshot is created when editor is focused after blurring.

What happens is that when editor is focused (e.g. text clicked somewhere), for a very short time, widget regains fake selection (which triggers drag handler to show/blink) and then fake selection is removed due to selection change. This short widget focus (not 100% sure if it's the focus itself) triggers undo snapshot creation which contains visible drag handler. I confirmed it by locking/unlocking undo manager on widget focus/blur events - the snapshot is not created then.

**Comment by engineering-this** [comment]
![Screenshot 2019-07-05 at 13 17 40](https://user-images.githubusercontent.com/23366849/60719241-53347b00-9f27-11e9-8cb8-c3abe37f8af1.png)

Here is a diff of two snapshots that produces same data.

UndoManager doesn't support any filtering of snapshots. We could fix the issue by introducing new `UndoManager.filter` class that would allow registering rules to be applied on saved snapshot.
