### ISSUE TITLE
Failing test tests/plugins/notification/manual/classic

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3200]
## Type of report

Failing test

## Details

`tests/plugins/notification/manual/classic`
`tests/plugins/notification/manual/inline`
Notifications won't appear if console is not open. Reason for this is that test calls `console.log` and in IE if you don't open console then `console` is undefined resulting in typeerror breaking further logic.

https://github.com/ckeditor/ckeditor-dev/blob/56dc3c6dc1b323efc4b759f1328b8645579b4254/tests/plugins/notification/manual/_helpers/manualplayground.js#L6-L17

* Browser: Found in IE8, IE9, might be valid for other IEs too
* OS: Windows
* CKEditor version: Found in 4.12.0

**Comment by f1ames** [comment]
Also happens in previous `4.11.4` version. I wonder when it happened and why it went unnoticed 🤔
