### ISSUE TITLE
FileBrowser plugin: File Browser API changes does seems reflecting on the inserted image

### ISSUE THREAD

**Issue by dphadtare** [ckeditor/ckeditor-dev#3201]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. While using the CKEditor File Browser plugin with custom file manager, it's been observed that whatever changes we make to the `dialog.originalElement`  doesn't reflect on the inserted image.
2. We are trying to set the onError attribute to fall back to the default image.
3. 

### Expected result

*What is the expected result of the above steps?*
There should be a way to set the custom image attributes, which can be set programmatically and user don't have to put those. As may be the user who is uploading the image is not aware of the default image link or any other attributes. 

### Actual result

*What is the actual result of the above steps?*

It seems that the object is updated with these changes but we are not using those at the time of inserting the image tag.

## Other details
We are trying to set custom attributes through window.parent.CKEDITOR.tools.callFunction() like below.

```
window.parent.CKEDITOR.tools.callFunction(
intResponseParam, strFileUploadedUrl,
function() {
    // Get the reference to a dialog window.
    var dialog = this.getDialog();
    console.log(dialog);
    // Check if this is the Image Properties dialog window.
    if( "image" == dialog.getName() ) {
         // Get the reference to a text field that stores the "alt" attribute.
	var element = dialog.getContentElement( "info", "txtAlt" );
		
	// Assign the new value.
	if( element ) {
		element.setValue( "alt text" );
	}
						
	dialog.originalElement.setAttributes( {
		onError: "alert(\"here i am\")"
	} );
}
} );
```

* Browser: Chrome
* OS: Windowns
* CKEditor version: 4.5
* Installed CKEditor plugins:font,image,colorbutton,justify,clipboard

**Comment by jacekbogdanski** [comment]
Looking on the `image` dialog implementation I see that inserted image is rather held by  [`dialog.imageElement`](https://github.com/ckeditor/ckeditor-dev/blob/441bccdaca62437ad906df788f8251396a4dbbbc/plugins/image/dialogs/image.js#L383) property, not `dialog.originalElement`. It's also nicely encapsulated, so you probably won't be able to use it. Also, it's not recommended to use private API. 

Nevertheless, I don't see really a reason for digging into image dialog implementation, if you can use custom transformation on the image element. Please, take a look at [`addTransformations`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter.html#method-addTransformations) method to add custom attributes to the image element.
