### ISSUE TITLE
Pagebreak integration with PFW doesn't work when dynamically loading plugin

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#3220]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/gb497f1s/
2. Paste linked Word document content into the editor.
3. Check if there is a page break inside the editor.

### Expected result

Page break is present.

### Actual result

There is no page break inside the editor.

## Other details

* CKEditor version: 4.12.0
* Installed CKEditor plugins: pastefromword, pagebreak

Seems like something's messed up during loading `pagebreak` plugin via `extraPlugins` option.

**Comment by f1ames** [comment]
The quick workaround is to add `extraAllowedContent` when initializing editor like:

```js
CKEDITOR.replace( 'editor', {
  extraPlugins: 'pagebreak',
  extraAllowedContent: 'div'
} );
```

**Comment by Comandeer** [comment]
After some investigation it seems that the issue is with PFW filter itself. It detects `br` with page break styles and change it to `div`. However the same filter then picks up this `div` and modify it even further, resulting finally in deleting the `div`.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor-dev/commit/64749bb245d1e91f6a4ac4e97c9648ec47acda91.
