### ISSUE TITLE
Edge - Image Dialog: Narrator is announcing "javascript void 0" at  "Ok", "Cancel", "Reset Size" buttons

### ISSUE THREAD

**Issue by qysnolan** [ckeditor/ckeditor-dev#3226]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use Edge to open picture dialog on [demo](https://ckeditor.com/ckeditor-4/demo/)
2. Open Narrator
3. Focus on "OK", "Cancel" and "Reset" button

### Expected result

*What is the expected result of the above steps?*
Narrator should announce the button title

### Actual result

*What is the actual result of the above steps?*
It's not a big issue and doesn't block anything but it's confusing end users.
Narrator announce "javascirpt void 0" after button title
![Snipaste_2019-06-28_10-48-52](https://user-images.githubusercontent.com/4621228/60361481-26b2b900-9993-11e9-9c5f-e2c0ddea747c.png)

## Other details

* Browser: Edge
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins: N/A

**Comment by jacekbogdanski** [comment]
I cannot reproduce the issue using JAWS 2019 with Firefox browser. We are using the latest version of JAWS and Firefox as our reference environment for accessibility testing. Unfortunately, some screen readers do not follow the same pattern for screen reading, however, we are not able to provide full support for every screen reader on the market.

The issue also seems more like an upstream of Edge Narrator, than CKEditor, as it rather shouldn't read javascript inside anchor `href` attribute. I would recommend reaching out Edge / Narrator issue tracker for help with this bug.
