### ISSUE TITLE
It not work when i inset a video tag

### ISSUE THREAD

**Issue by Dolov** [ckeditor/ckeditor-dev#3232]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by SilentFlute** [comment]
i think u should add some reproduce steps on it that's convenient for some one who want help u.
in my project, i use html5video plugin to upload video in ckeditor 4, it works well

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by SilentFlute** [comment]
@jacekbogdanski oh, hi, need a little help here, thx
#3215

**Comment by Dolov** [comment]
> 我想你应该在它上面添加一些重现步骤，这对于想要帮助的人来说很方便。
> 在我的项目中，我使用html5video插件在ckeditor 4中上传视频，效果很好

Next time I mention issue, I'll take your advice.  and  html5video  works,thanks
