### ISSUE TITLE
查询的文本点击修改时给文本加个样式，比如给文本加个字体。保存只有页面会显示样式的代码加文本

### ISSUE THREAD

**Issue by Dz-Ambition** [ckeditor/ckeditor-dev#3242]
<span style="font-size:14px;">R4</span> 页面展示的

**Comment by Dz-Ambition** [comment]
<span style="font-size:14px;">R4</span>这是页面展示的

**Comment by jacekbogdanski** [comment]
Please, use English, otherwise, we won't able to help you. Also, make sure you follow our issue template.
