### ISSUE TITLE
table tr height increase

### ISSUE THREAD

**Issue by qiqingfu** [ckeditor/ckeditor-dev#3250]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. I have prepared a HTML document data, where the TR height is 5 pixels
2. Initialize editor, add some configuration items  
```javascript
this.editor = CKEDITOR.replace('emailEditor', {
                        fillEmptyBlocks: false,
                        height: $('#emailEditor').parent()
                            .height() - 75
                    });
```
3. It is found that the height of the initialized table of contents > tr becomes 22px, which is 17 pixels higher than the previous tr height.

### Expected result

*What is the expected result of the above steps?*
The height of TR should be 5 pixels

### Actual result

*What is the actual result of the above steps?*
The actual result TR is 22 pixels high

## Other details

I suspect the impact of high performance, but I haven't found the relevant attributes in the configuration.

* Browser:Chrome
* OS: mac
* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Could you provide more information about the issue? As I understand, you are initializing editor inside a table? Please, attach an HTML file structure and used plugins, so we can verify the issue correctly.

**Comment by qiqingfu** [comment]
@jacekbogdanski It's settled. Thank you for your attention and reply
