### ISSUE TITLE
Triple-click and deleting text in last table cell pulls in content below the table 

### ISSUE THREAD

**Issue by evanrigby** [ckeditor/ckeditor-dev#3256]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [ckeditor demo](https://ckeditor.com/ckeditor-4/demo/)
2. Insert a new 3x2 table above some existing content
3. Enter some text in the last cell of the table (bottom-right)
4. Triple-click the text in the table to select it
5. Press the backspace or delete key

### Expected result

The text should be removed

### Actual result

The text is removed but the paragraph of content below the table is pulled into the last cell of the table
![Capture1](https://user-images.githubusercontent.com/43147413/60888825-9d6a7480-a225-11e9-899b-2bdbc83a897a.PNG)

![Capture2](https://user-images.githubusercontent.com/43147413/60888844-a65b4600-a225-11e9-8061-4e75db61cdf4.PNG)

## Other details

* Browser: Chrome - (Firefox does not have the issue)
* CKEditor version: 4.11
* Installed CKEditor plugins: Standard Set (with table plugin)

**Comment by f1ames** [comment]
This is related to #3175 and will be fixed with #3213 PR.

**Comment by f1ames** [comment]
Since the solution required workarounds for upstream browser issues, we marked it as a new feature.
