### ISSUE TITLE
Editor with moono skin invisible due to corrupted editor.css file while downloaded via online builder

### ISSUE THREAD

**Issue by toshniba** [ckeditor/ckeditor-dev#3273]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Use latest ckeditor (v4.12.1) on your site and open it in IE 11 or Chrome 75.0.3770.142 on Windows 7.
Maybe it occurs on other IE versions and/or OS too.
It **does not occur in** earlier ckeditor version **v4.11.4** (v4.12.0 not tested as not used)

### Expected result

Editor window is shown.

### Actual result

Editor window has css attribute `visibility: hidden;` and therefore is not visible.

## Other details

* Browser: IE 11; Chrome 75
* OS: Windows 7, 64bit
* CKEditor version: 4.12.1
* Installed CKEditor plugins: 		'a11yhelp' : 1,
		'autolink' : 1,
		'basicstyles' : 1,
		'bbcode' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'dialogadvtab' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'pastetext' : 1,
		'placeholder' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'save' : 1,
		'selectall' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'tab' : 1,
		'table' : 1,
		'tabletools' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'widget' : 1,
		'wysiwygarea' : 1

**Comment by f1ames** [comment]
Hi @toshniba,
I have checked both custom codepen (https://codepen.io/f1ames/pen/bXbqZY) and our official demos (https://ckeditor.com/ckeditor-4/demo/) on Windows 7 on both IE11 and Chrome (`75.0.3770.100`) and it's working fine.

Maybe there is an issue with your setup? Do you see any errors in a browser dev console?

**Comment by toshniba** [comment]
unfortunately there are no errors in dev console.

**Comment by toshniba** [comment]
figured out that the editor is shown in Chrome when I use following files from the older release (v4.11.4):

- skins/moono/editor.css
- skins/moono/editor_gecko.css

Unfortunately they are minified which it makes very hard to me to compare them and figure out which css rule screws it up

**Comment by toshniba** [comment]
the error obviously happens at generation time of `editor.css` file of **moono** ui.
The file is much less in size than earlier versions while none of the base-files (`https://github.com/ckeditor/ckeditor-dev/tree/major/skins/moono`) have changed...
So will this be fixed or do I have to switch to another ui?

**Comment by f1ames** [comment]
@toshniba thanks for checking this issue in such details. I assume you downloaded your CKEditor instance via online builder (customized)?

I can see that it only happens when editor is downloaded via builder, it works fine for CDN and other resources. The easiest way for you to solve this issue is to download valid `editor.css` for `moono` skin from our CDN, which is https://cdn.ckeditor.com/4.12.1/full-all/skins/moono/editor.css?t=J5S7.

In the meantime we will check what's going on in the online builder. Thanks again for spotting this.

**Comment by toshniba** [comment]
@f1ames you're absolutely right, I just followed the straight download link given in my build-config.js file. But it also happens when building from scratch.
Thanks for the work around information, and the quick support in general.

Unfortunately I had to also download these files to made my editor work again in IE and Chrome. (I'll extend the list when I figure out there need some more files to be replaced)

- editor_gecko.css
- editor_ie.css
- icons.png

So either they get customizied too when downloading via builder or maybe there is somewhat else broken.
Good luck! ;-)

**Comment by f1ames** [comment]
Hello @toshniba,
it seems that CSS files for `moono` skin which online builder utilizes get corrupted during minification process. We have regenerated those files and now it looks like they are correctly minified.

Could you check if it works for you now (you will have to redownload the editor build)?

cc @qcybb

**Comment by toshniba** [comment]
Hey @f1ames 
I did a fresh straight download and tested in most recent Firefox and Chrome, also in IE 11.
Looks very good. Thanks alot!
