### ISSUE TITLE
Editor window does not show in IE or Edge

### ISSUE THREAD

**Issue by qcybb** [ckeditor/ckeditor-dev#3282]
I've upgraded to v4.12.1 and the editor window no longer shows in IE or Edge. It does work in Firefox - but not tested in Chrome.

Reverting back to v 4.11.1 solves the issue.

Details:
Internet Explorer & Microsoft Edge
Windows 10 Home
CKEditor v4.12.1
[build-config.zip](https://github.com/ckeditor/ckeditor-dev/files/3404606/build-config.zip)

**Comment by f1ames** [comment]
Hello @qcybb,
thanks for reporting. We are investigating this issue. It was already reported in #3273, you may check https://github.com/ckeditor/ckeditor-dev/issues/3273#issuecomment-512346212 for quick workaround.

Closing this as a duplicate. Please follow #3273 for updates.
