### ISSUE TITLE
ReferenceError: Can't find variable: ES6Promise

### ISSUE THREAD

**Issue by mflorea** [ckeditor/ckeditor-dev#3287]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm running integration tests using **PhantomJS** (which doesn't implement ``Promise``) and I'm using **RequireJS** (AMD) to load other modules besides CKEditor.

### Expected result

The tests were passing before upgrading to from CKEditor 4.11.4 to CKEditor 4.12.1.

### Actual result

The tests are failing now with:

    ReferenceError: Can't find variable: ES6Promise

## Other details

* Browser: PhantomJS
* OS: Ubuntu 19.4
* CKEditor version: 4.12.1
* Installed CKEditor plugins: standard set

Upon checking the code I believe the culprit is this https://github.com/ckeditor/ckeditor-dev/commit/438a019cf196255a97cb5bde76bd857e768d391a#r34380433 .

The workaround for me was to run this before my tests:

    window.Promise = window.Promise || function() {};

It works because CKEditor doesn't use the ``Promise`` that much at the moment (and so it doesn't affect my tests), but this may change in the future.

**Comment by jacekbogdanski** [comment]
I agree the test could be improved by stubbing Promise object instead of using globals.

**Comment by mflorea** [comment]
Actually this issue affects **IE11** and not just PhantomJS, for the same reasons, but this time at runtime and not during tests, which raises the severity of the issue IMO.

**Comment by f1ames** [comment]
> The workaround for me was to run this before my tests:
>
> ```
> window.Promise = window.Promise || function() {};
> ```

It will work only if tests are not using promises, so it's a quick workaround, but not a proper solution.

> Actually this issue affects **IE11** and not just PhantomJS, for the same reasons, but this time at runtime and not during tests, which raises the severity of the issue IMO.

So basically, it is an issue for ever browser where polyfill is used and CKEditor loaded via **RequireJS** (or any other AMD loader)😭

@mflorea thanks for investigating this issue. I wonder if there is any reasonable way to detect that CKEditor was loaded via AMD and adjust the polyfill setup in https://github.com/ckeditor/ckeditor-dev/commit/438a019cf196255a97cb5bde76bd857e768d391a#r34380433 🤔
