### ISSUE TITLE
When copying and pasting a sentence (more than 2 lines) in a table of MS word, the tag of the last sentence is different.

### ISSUE THREAD

**Issue by 2ju2** [ckeditor/ckeditor-dev#3294]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Define ckeditor's config.js to preserve formatting when copying and pasting. (cf. See below)
2. Create a table in MS Word. (Example, 3x3)
3. Create a four-line sentence with the same format in one cell of the table (wrap it with Enter and make sure there is no Enter after the last line)
4. Copy and paste 4 lines into ckeditor. (copy not table just text)

### Expected result

The sentences of all lines are output to the same tag.
(Because, in MS word, all sentences are the same format)

### Actual result

However, the last line (example, line 5) is treated as an empty space,
If you copy and paste the 1st to 4th lines, the tags of all the lines are the same.

[Sentence in last line - Tag]
h1 > span > span> span 

[Sentences in different lines - Tag]
p > span > span > span > span > span 
--> In other versions and environments, it is also output as p tag instead of h1 tag.
But the tags are still different from the sentences in other lines

## Other details

* Browser: IE11, Chrome 56+
* OS: Window10
* CKEditor version: 4.x.x (I used it in several versions) 
* Installed CKEditor plugins: pastfromword, ...
* config.js : 
  config.height = 300;
  config.forcePasteAsPlainText = false;			
  config.pasteFromWordRemoveFontStyles = false;		
  config.pasteFromWordRemoveStyles = false;		
  config.allowedContent = true;					
  config.extraAllowedContent = 'p(mso*,Normal)';	
  config.pasteFilter = null;						
  config.enterMode = CKEDITOR.ENTER_P;

**Comment by f1ames** [comment]
Can you provide your sample Word file and a screenshot how it looks for you when pasted? And information which version of MS Word you used?

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
