### ISSUE TITLE
Improve mathematical equations for Paste from Word

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#3296]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample e.g. https://ckeditor.com/latest/samples
2. Create MSWord file with a mathematical equation.
3. Copy and paste the content into the editor.

### Expected result

Image with mathematical equation pasted into the editor.

### Actual result

A mathematical equation is doubled with its image and text versions.

![formulas](https://user-images.githubusercontent.com/10279586/61788562-a86ef880-ae12-11e9-9e88-dc789c72796b.gif)

## Other details

* CKEditor version: at least 4.10.0
* Installed CKEditor plugins: pastefromword

**Comment by f1ames** [comment]
DUP of #1720.

**Comment by sony-gogo** [comment]
I am also facing same issues did you get any solution for that?
