### ISSUE TITLE
Add Proofreader documentation and sample

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-dev#3301]
WebSpellChecker introduced a new spell checking option for CKEditor: Proofreader (aka WProofreader): https://webspellchecker.com/wsc-proofreader/

We should expand our spellchecking documentation to cover it:
* Demo: https://ckeditor.com/docs/ckeditor4/latest/examples/spellchecker.html - their demo is here: https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor4
* Documentation: https://ckeditor.com/docs/ckeditor4/latest/features/spellcheck.html

**Comment by f1ames** [comment]
Some WProofreader docs:
* https://docs.webspellchecker.net/pages/viewpage.action?pageId=442663877
* http://dev.webspellchecker.net/api/wscbundle/AutoSearchCreation.html
* https://github.com/WebSpellChecker/wproofreader

**Comment by f1ames** [comment]
Added initial PR - https://github.com/ckeditor/ckeditor-docs/pull/256.

**Comment by Comandeer** [comment]
Docs merged into `stable`.
