### ISSUE TITLE
The Subscript & Superscript can be used together?

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor-dev#3303]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
It can be tests at https://ckeditor.com/docs/ckeditor4/latest/examples/basicstyles.html.
1. Select parts of text content.
2. Click Subscript and then click Superscript.

### Expected result

It effects with only one of them.

### Actual result

The Subscript and Superscript effects together.

## Other details

* Browser: Chrome, IE....
* OS: Windows
* CKEditor version: 4.11.4

**Comment by engineering-this** [comment]
Hello

Thank you for your submission. According to HTML Specification, allowed content of `<sub>` and `<sup>` is [`Phrasing content`](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2). I didn't find any other restrictions, so it means that one of them can be nested in another.
I'm closing the issue, as this is valid behaviour.
