### ISSUE TITLE
Align Buttons Incorrectly Processes MathML

### ISSUE THREAD

**Issue by aWaylonLao** [ckeditor/ckeditor-dev#3313]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Select MathML object
2. Click on align center button

### Expected result

![expected](https://user-images.githubusercontent.com/53048121/62483977-19090400-b787-11e9-9417-5a647d9043c4.png)

(manually edited under DevTools to move it to the center. Added style="text-align:center" to the p tag)

### Actual result

![actual](https://user-images.githubusercontent.com/53048121/62483991-27572000-b787-11e9-8dc8-206ffeca6c3d.png)

## Other details

* Browser: Google Chrome
* OS: macOS
* CKEditor version: 4.13.0
* Installed CKEditor plugins: MathJax, WYSIWYG

**Comment by jacekbogdanski** [comment]
Hello, I didn't spot any issue with aligning MathJax formulas:

![mathalign](https://user-images.githubusercontent.com/10279586/62516566-b87cd400-b825-11e9-8136-007be4809c44.gif)

I see that your MathJax widget instance looks different than in our default feature implementation. Could you tell more about this customization and also provide information about [`config.mathJaxLib`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxLib) path?

**Comment by aWaylonLao** [comment]
Looks like we had the config.mathJaxLib path set to: 
config.mathJaxLib = '//cdn.mathjax.org/mathjax/2.6-latest/MathJax.js?config=TeX-AMS_HTML'
But now it's:
var mathJaxLib = CKEDITOR.config.mathJaxLib = bender.config.mathJaxLibPath;

Not sure how to check and see if we're using the Mathematical Formulas plugin

**Comment by jacekbogdanski** [comment]
As you can see on my gif our default MathJax plugin looks much different than the one on yours. It looks like it's not the same plugin or it's highly customized. Nevertheless, there should be no issue with aligning buttons as the computation is a part of a widget, so we would have the same issue with other widgets also.

> Not sure how to check and see if we're using the Mathematical Formulas plugin

Please, take a look at your editor configuration file (`config.js`) and initialization code. You should be looking for config properties like `plugins` or `extraPlugins`. Copy both with the next comment so we can make sure that we are talking about the same plugin.

**Comment by aWaylonLao** [comment]
Looking into this further, we've found that the issue is with the justify plugin. On the justifyCommand.prototype we found that the iterator.getNextParagraph seems to be trying to justify blank <p> elements surrounding the math. It appears to have an issue with the math <span> elements

Currently aligning turns:
`<div class="choiceinteraction-choice-editable choiceinteraction-choice-editable-0 cke_widget_editable cke_widget_editable_focused" contenteditable="true" data-cke-widget-editable="choice0" data-cke-enter-mode="1" data-cke-display-name="simpleChoice"><p style="text-align:center">
    <br></p>
    <p>
      <span data-cke-bookmark="1" style="display: none;">&nbsp;</span>
      <span tabindex="-1" contenteditable="false" data-cke-widget-wrapper="1" data-cke-filter="off" class="cke_widget_wrapper cke_widget_inline cke_widget_focused cke_widget_selected" data-cke-display-name="math" data-cke-widget-id="1" role="region" aria-label="math widget"><span class="mathmleditor pm-cke-widget cke_widget_element" data-cke-widget-data="%7B%22mathML%22%3A%22%3Cmath%3E%20%3Cmn%3E4%3C%2Fmn%3E%20%3Cmi%3Ex%3C%2Fmi%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%3D%3C%2Fmo%3E%20%3Cmn%3E360%3C%2Fmn%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%2B%3C%2Fmo%3E%20%3Cmn%3E80%3C%2Fmn%3E%20%3C%2Fmath%3E%22%2C%22classes%22%3A%7B%22pm-cke-widget%22%3A1%2C%22mathmleditor%22%3A1%7D%7D" data-cke-widget-upcasted="1" data-cke-widget-keep-attr="0" data-widget="mathmleditor"><span class="pm-cke-widget-label pm-cke-widget-fixed-text"></span>
      <span class="mathmleditor-content" id="C59729171">
        <span class="MathJax_Preview" style="color: inherit; display: none;"></span>
        <span class="MathJax" id="MathJax-Element-1-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mn>4</mn><mi>x</mi><mo>&amp;#xA0;</mo><mo>=</mo><mn>360</mn><mo>&amp;#xA0;</mo><mo>+</mo><mn>80</mn></math>" role="presentation" style="position: relative;">
          <nobr aria-hidden="true"><span class="math" id="MathJax-Span-1" style="width: 7.886em; display: inline-block;">
            <span style="display: inline-block; position: relative; width: 6.488em; height: 0px; font-size: 121%;">
              <span style="position: absolute; clip: rect(1.656em, 1006.49em, 2.8em, -999.997em); top: -2.54em; left: 0em;">
                <span class="mrow" id="MathJax-Span-2"><span class="mn" id="MathJax-Span-3" style="font-family: STIXGeneral-Regular;">4</span>
                <span class="mi" id="MathJax-Span-4" style="font-family: STIXGeneral-Italic;">x
                  <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.003em;"></span>
                </span>
                <span class="mo" id="MathJax-Span-5" style="font-family: STIXGeneral-Regular;">&nbsp;</span>
                <span class="mo" id="MathJax-Span-6" style="font-family: STIXGeneral-Regular; padding-left: 0.321em;">=</span>
                <span class="mn" id="MathJax-Span-7" style="font-family: STIXGeneral-Regular; padding-left: 0.321em;">360</span>
                <span class="mo" id="MathJax-Span-8" style="font-family: STIXGeneral-Regular;">&nbsp;</span>
                <span class="mo" id="MathJax-Span-9" style="font-family: STIXGeneral-Regular; padding-left: 0.257em;">+</span>
                <span class="mn" id="MathJax-Span-10" style="font-family: STIXGeneral-Regular; padding-left: 0.257em;">80</span></span>
                <span style="display: inline-block; width: 0px; height: 2.546em;"></span>
              </span></span>
              <span style="display: inline-block; overflow: hidden; vertical-align: -0.15em; border-left: 0px solid; width: 0px; height: 1.004em;"></span>
            </span>
          </nobr><span class="MJX_Assistive_MathML" role="presentation">
            <math xmlns="http://www.w3.org/1998/Math/MathML"><mn>4</mn><mi>x</mi><mo>&nbsp;</mo><mo>=</mo><mn>360</mn><mo>&nbsp;</mo><mo>+</mo><mn>80</mn></math></span></span>
            <script type="math/mml" id="MathJax-Element-1"><math> <mn>4</mn> <mi>x</mi> <mo>&nbsp;</mo> <mo>=</mo> <mn>360</mn> <mo>&nbsp;</mo> <mo>+</mo> <mn>80</mn> </math></script>
          </span></span>
          <span class="cke_reset cke_widget_drag_handler_container" style="background: url(&quot;http://localhost:8080/unify/qti-jq/js/ckeditor/plugins/widget/images/handle.png&quot;) rgba(220, 220, 220, 0.5); top: -13px; left: 2px; display: block;"><img class="cke_reset cke_widget_drag_handler" data-cke-widget-drag-handler="1" src="data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==" width="15" title="Click and drag to move" height="15" role="presentation" draggable="true"></span>
        </span><span data-cke-bookmark="1" style="display: none;">&nbsp;</span></p>
        <p style="text-align:center"><br></p>
      </div>`

into:
`<div class="choiceinteraction-choice-editable choiceinteraction-choice-editable-0 cke_widget_editable cke_widget_editable_focused" contenteditable="true" data-cke-widget-editable="choice0" data-cke-enter-mode="1" data-cke-display-name="simpleChoice">
    <p style="text-align:center"><br></p>
    <p style="text-align: center;">
      <span tabindex="-1" contenteditable="false" data-cke-widget-wrapper="1" data-cke-filter="off" class="cke_widget_wrapper cke_widget_inline cke_widget_focused cke_widget_selected" data-cke-display-name="math" data-cke-widget-id="1" role="region" aria-label="math widget"><span class="mathmleditor pm-cke-widget cke_widget_element" data-cke-widget-data="%7B%22mathML%22%3A%22%3Cmath%3E%20%3Cmn%3E4%3C%2Fmn%3E%20%3Cmi%3Ex%3C%2Fmi%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%3D%3C%2Fmo%3E%20%3Cmn%3E360%3C%2Fmn%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%2B%3C%2Fmo%3E%20%3Cmn%3E80%3C%2Fmn%3E%20%3C%2Fmath%3E%22%2C%22classes%22%3A%7B%22pm-cke-widget%22%3A1%2C%22mathmleditor%22%3A1%7D%7D" data-cke-widget-upcasted="1" data-cke-widget-keep-attr="0" data-widget="mathmleditor"></span></span></p>
      <p style="text-align: center;"><span class="MathJax_Preview" style="color: inherit; display: none;"></span>
        <span class="MathJax" id="MathJax-Element-1-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mn>4</mn><mi>x</mi><mo>&amp;#xA0;</mo><mo>=</mo><mn>360</mn><mo>&amp;#xA0;</mo><mo>+</mo><mn>80</mn></math>" role="presentation" style="position: relative;">
          <nobr aria-hidden="true">
            <span class="math" id="MathJax-Span-1" style="width: 7.886em; display: inline-block;">
              <span style="display: inline-block; position: relative; width: 6.488em; height: 0px; font-size: 121%;">
                <span style="position: absolute; clip: rect(1.656em, 1006.49em, 2.8em, -999.997em); top: -2.54em; left: 0em;">
                  <span class="mrow" id="MathJax-Span-2">
                    <span class="mn" id="MathJax-Span-3" style="font-family: STIXGeneral-Regular;">4</span>
                    <span class="mi" id="MathJax-Span-4" style="font-family: STIXGeneral-Italic;">x<span style="display: inline-block; overflow: hidden; height: 1px; width: 0.003em;"></span></span>
                    <span class="mo" id="MathJax-Span-5" style="font-family: STIXGeneral-Regular;">&nbsp;</span>
                    <span class="mo" id="MathJax-Span-6" style="font-family: STIXGeneral-Regular; padding-left: 0.321em;">=</span>
                    <span class="mn" id="MathJax-Span-7" style="font-family: STIXGeneral-Regular; padding-left: 0.321em;">360</span>
                    <span class="mo" id="MathJax-Span-8" style="font-family: STIXGeneral-Regular;">&nbsp;</span>
                    <span class="mo" id="MathJax-Span-9" style="font-family: STIXGeneral-Regular; padding-left: 0.257em;">+</span>
                    <span class="mn" id="MathJax-Span-10" style="font-family: STIXGeneral-Regular; padding-left: 0.257em;">80</span>
                  </span><span style="display: inline-block; width: 0px; height: 2.546em;"></span></span></span>
                  <span style="display: inline-block; overflow: hidden; vertical-align: -0.15em; border-left: 0px solid; width: 0px; height: 1.004em;"></span></span></nobr>
                  <span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>4</mn><mi>x</mi><mo>&nbsp;</mo><mo>=</mo><mn>360</mn><mo>&nbsp;</mo><mo>+</mo><mn>80</mn></math></span></span>
                  <script type="math/mml" id="MathJax-Element-1"><math> <mn>4</mn> <mi>x</mi> <mo>&nbsp;</mo> <mo>=</mo> <mn>360</mn> <mo>&nbsp;</mo> <mo>+</mo> <mn>80</mn> </math></script></p><p style="text-align: center;">
                    <span tabindex="-1" contenteditable="false" data-cke-widget-wrapper="1" data-cke-filter="off" class="cke_widget_wrapper cke_widget_inline cke_widget_focused cke_widget_selected" data-cke-display-name="math" data-cke-widget-id="1" role="region" aria-label="math widget">
                      <span class="mathmleditor pm-cke-widget cke_widget_element" data-cke-widget-data="%7B%22mathML%22%3A%22%3Cmath%3E%20%3Cmn%3E4%3C%2Fmn%3E%20%3Cmi%3Ex%3C%2Fmi%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%3D%3C%2Fmo%3E%20%3Cmn%3E360%3C%2Fmn%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%2B%3C%2Fmo%3E%20%3Cmn%3E80%3C%2Fmn%3E%20%3C%2Fmath%3E%22%2C%22classes%22%3A%7B%22pm-cke-widget%22%3A1%2C%22mathmleditor%22%3A1%7D%7D" data-cke-widget-upcasted="1" data-cke-widget-keep-attr="0" data-widget="mathmleditor"></span></span></p><p style="text-align: center;">
                        <span tabindex="-1" contenteditable="false" data-cke-widget-wrapper="1" data-cke-filter="off" class="cke_widget_wrapper cke_widget_inline cke_widget_selected" data-cke-display-name="math" data-cke-widget-id="1" role="region" aria-label="math widget">
                          <span class="mathmleditor pm-cke-widget cke_widget_element" data-cke-widget-data="%7B%22mathML%22%3A%22%3Cmath%3E%20%3Cmn%3E4%3C%2Fmn%3E%20%3Cmi%3Ex%3C%2Fmi%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%3D%3C%2Fmo%3E%20%3Cmn%3E360%3C%2Fmn%3E%20%3Cmo%3E%26nbsp%3B%3C%2Fmo%3E%20%3Cmo%3E%2B%3C%2Fmo%3E%20%3Cmn%3E80%3C%2Fmn%3E%20%3C%2Fmath%3E%22%2C%22classes%22%3A%7B%22pm-cke-widget%22%3A1%2C%22mathmleditor%22%3A1%7D%7D" data-cke-widget-upcasted="1" data-cke-widget-keep-attr="0" data-widget="mathmleditor">
                            <span class="pm-cke-widget-label pm-cke-widget-fixed-text" style="text-align: center;"></span>
                            <span class="mathmleditor-content" id="C59729171" style="text-align: center;"></span></span>
                            <span class="cke_reset cke_widget_drag_handler_container" style="background: url(&quot;http://localhost:8080/unify/qti-jq/js/ckeditor/plugins/widget/images/handle.png&quot;) rgba(220, 220, 220, 0.5); top: -13px; left: 2px; display: block;">
                              <img class="cke_reset cke_widget_drag_handler" data-cke-widget-drag-handler="1" src="data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==" width="15" title="Click and drag to move" height="15" role="presentation" draggable="true"></span></span></p>
                              <p style="text-align:center"><br></p>
                            </div>`


Are there any settings we could change to get the CKEditor working?


Our entire config object is:
`autoUpdateElement: false
autoUpdateElementJquery: true
contentsLangDirection: "ltr"
disallowedContent: "table[cellpadding,cellspacing]"
examples: {items: Array(15), select: ƒ}
extraAllowedContent: "stylesheet[data-href,data-type,data-media,data-title];outcomedeclaration[data-basetype,data-cardinality,data-identifier,data-normalminimum,data-normalmaximum];defaultvalue;value;hottext[data-id,data-class,data-lang,data-label,data-identifier,data-fixed];prompt[data-id,data-class,data-lang,data-label];simplechoice[data-id,data-class,data-lang,data-label,data-identifier,data-fixed];inlinechoice[data-id,data-class,data-lang,data-label,data-identifier,data-fixed];simplematchset;simpleassociablechoice[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-matchmax,data-matchmin];hotspotchoice[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-shape,data-coords,data-hotspotlabel];associablehotspot[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-shape,data-coords,data-matchmax,data-matchmin];gaptext[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-matchmax,data-matchmin];gapimg[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-matchmax,data-matchmin];gap[data-id,data-class,data-lang,data-label,data-identifier,data-fixed,data-required,data-gapprops,data-gaptext,data-correctresponse,data-mapentries];object[data-id,data-class,data-lang,data-label,data-data,data-type,data-width,data-height];portablecustominteraction[data-custominteractionidentifiertype];a[data-id,data-class,data-lang,data-label,href,data-type];instance;mfrac[bevelled];mfenced[open,close];mstyle[mathsize];mi[mathvariant,mathcolor];mo[largeop];mn;mroot;msqrt;mtable;mtr;mtd;mspace[linebreak];msubsup;menclose[notation];mover;mrow;munder;munderover;msub;msup;mmultiscripts;none;mprescripts;mtext[mathbackground,mathcolor,mathsize,mathvariant];responseprocessing[data-template];responsecondition;responseif;responseelse;responseelseif;and;sum;or;not;equal;fieldvalue[data-fieldidentifier];variable[data-identifier];baasevalue[data-basetype];setoutcomevalue[data-identifier];lookupoutcomevalue;exitresponse;match;correct[data-identifier];*(*)"
extraPlugins: "qti_common,associateinteraction,choiceinteraction,drawinginteraction,extendedtextinteraction,gapmatchinteraction,gap,graphicgapmatchinteraction,graphinginteraction,hotspotinteraction,hottextinteraction,hottext,inlinechoiceinteraction,matchinteraction,custominteraction,orderinteraction,textentryinteraction,uploadinteraction,examples,mathmleditor,oembed,passage,placeholder,qti_preview,rubricreference,rubricgroupreference,rubricblock,simpleuploads,stylesheet,wsc"
filebrowserBrowseUrl: "X"
filebrowserImageUploadUrl: "/unify/modules/resources/QtiUpload"
filebrowserUploadUrl: "/unify/modules/resources/QtiUpload"
fontSize_sizes: "2X Small/xx-small;Extra Small/x-small;Smaller/smaller;Small/small;Medium/medium;Larger/larger;Large/large;Extra Large/x-large;2X Large/xx-large"
image_previewText: " "
magicline_tabuList: ["data-no-magicline"]
plugins: "about,a11yhelp,basicstyles,bidi,blockquote,clipboard,colorbutton,colordialog,contextmenu,dialogadvtab,div,elementspath,enterkey,entities,filebrowser,find,flash,floatingspace,font,format,forms,horizontalrule,htmlwriter,image,iframe,indentlist,indentblock,justify,language,link,list,liststyle,magicline,maximize,newpage,pagebreak,pastefromword,pastetext,preview,print,removeformat,resize,save,selectall,showblocks,showborders,smiley,sourcearea,specialchar,stylescombo,tab,table,tabletools,templates,toolbar,undo,wysiwygarea"
qti_preview: {select: ƒ}
removeDialogTabs: "image:Link;image:Upload;image:advanced"
resize_dir: "both"
resize_maxHeight: 3000
resize_maxWidth: 3000
resize_minHeight: 250
resize_minWidth: 400
rubricDataSource: {search: ƒ, get: ƒ}
rubricGroupDataSource: {search: ƒ, get: ƒ}
simpleuploads_acceptedExtensions: "jpeg|jpg|png|gif"
simpleuploads_imageRegexp: /.(?:jpe?g|gif|png)$/i
smiley_path: "http://localhost:8080/unify/qti-jq/js/ckeditor/plugins/smiley/images/"
toolbar: (14) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, "/", {…}, {…}, {…}, {…}, {…}]
undoStackSize: 50
wsc_customDictionaryIds: ""
wsc_customLoaderScript: undefined
wsc_customerId: "1:HaZsd1-PVwlN3-gNDjn1-UTcUw1-4jzp23-nDBOz-6KEi63-hHTDQ2-BlEad-j2tD72-jb9qM1-CZ8"
wsc_userDictionaryName: ""`

Currently working on setting up a code reproduction!

**Comment by jacekbogdanski** [comment]
I see that you are using some 3rd party plugin for mathematical equations. We are not able to debug and fix code which doesn't belong to us. Please, contact plugin author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
