### ISSUE TITLE
Add textNode.isEmpty member

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#3326]
## Type of report

Feature request

## Provide description of the new feature

The function should check whether the text node is empty or its value is set to `CKEDITOR.dom.selection.FOLLOWING_CHAR_SEQUENCE` which should be treated as an internal string, not real text node value.

**Comment by Comandeer** [comment]
I propose adding optional parameter `ignoreWhiteSpace` to cover one more use-case: https://github.com/ckeditor/ckeditor-dev/blob/64749bb245d1e91f6a4ac4e97c9648ec47acda91/core/dom/element.js#L1021

**Comment by jacekbogdanski** [comment]
I would avoid passing [flag boolean parameters](https://martinfowler.com/bliki/FlagArgument.html) to methods which makes them less obvious to work with. Maybe let's go with additional member `isBlank`? Seems like a super simple method but much more verbose.

**Comment by Comandeer** [comment]
IMO `isEmpty` and `isBlank` sounds too similar and I can imagine having trouble with differencing between these two, always checking docs to choose the right one.
