### ISSUE TITLE
Maximize and minimize ckeditor

### ISSUE THREAD

**Issue by AmmarAlhabib** [ckeditor/ckeditor-dev#3339]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. I have multi-tabs and I have a Ckeditor inside on of tabs 
2. When I maximize and minimize the Ckeditor for a few time, the alignment for the content layout will be ruined.  
3. After I did a deep tracing I figure out that when I maximized the Ckeditor, it will remove the class property from all parents divs and then add style (style="position: static; overflow: visible; z-index: 9995;") to those divs. when I minimize the Ckeditor it will restore the classes names and remove the style ((style="position: static; overflow: visible; z-index: 9995;")) and restore the previous style. but sometimes it doesn't restore the previous classes and style for those divs. 

### Expected result

 Restore the previous classes and style for those divs. 

### Actual result

it doesn't restore the previous classes and style for those divs. So, the alignment for the content layout will be ruined.  

## Other details
This way is a bad way to manage the maximization of CKEditor.
* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by AmmarAlhabib** [comment]
CKEditor version 4

**Comment by jacekbogdanski** [comment]
Could you provide minimal demo with the issue using some online editor like https://codepen.io, https://jsfiddle.net or just raw code in a comment?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
