### ISSUE TITLE
colordialog bug

### ISSUE THREAD

**Issue by danik34rus** [ckeditor/ckeditor-dev#3340]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. downloaded plugin colordialog from site
2. opened config.js and add config.extraPlugins = 'youtube,enchancedcolorbutton';
3. pressed ctrl + f5 on my site

### Expected result

the icon for changing the color did not appear, but the Youtube icon remained

### Actual result

the icon for changing the color did not appear, but the Youtube icon remained

## Other details

* Browser: Google Chrome (last version)
* OS: Windows 7 Professional
* CKEditor version: 4.3.1
* Installed CKEditor plugins: youtube video, colordialog

**Comment by danik34rus** [comment]
i added { name: 'colors', groups: [ 'TextColor', 'BGColor' ] }, to config.toolbarGroups = [
and nothing

**Comment by jacekbogdanski** [comment]
[Color dialog](https://ckeditor.com/cke4/addon/colordialog) plugin is used as a part of more advanced plugins and it doesn't register any button itself. Use both [Color dialog](https://ckeditor.com/cke4/addon/colordialog) and [Color button](https://ckeditor.com/cke4/addon/colorbutton) plugins to enable the color palette feature.

`enchancedcolorbutton` is not maintained by CKEditor4 so we cannot help with that plugin. Please, contact plugin maintainer if this plugin is supposed to work with `colordialog`.
