### ISSUE TITLE
In article mode, 'Outdent','Indent' button only works on the list

### ISSUE THREAD

**Issue by yaphot** [ckeditor/ckeditor-dev#3341]
https://ckeditor.com/ckeditor-4/demo/#article
article editor In article mode, 'Outdent','Indent' button only works on the list;
but other mode,'Outdent','Indent' button always works

**Comment by Dumluregn** [comment]
Thank you for bringing our attention to this. As a matter of fact it's not a bug - just the plugin [Indent Block](https://ckeditor.com/cke4/addon/indentblock) is currently not included in Article Mode. However as it appears in other modes, we decided that it makes sense to unify this behaviour on our webpage, which makes your issue rather a task than bug.

**Comment by f1ames** [comment]
Moved this issue to websites repository, closing this one.

**Comment by yaphot** [comment]
How can I modify it, it can be same In article mode, because now this problem is treated as a bug.
