### ISSUE TITLE
Copy and pasting the HTML text in Ck editor is giving different DOM structure in chrome & IE

### ISSUE THREAD

**Issue by Tejaravulapalli** [ckeditor/ckeditor-dev#3344]
## Type of report

When we copy the HTML text from Chrome and paste in IE 11 & chrome browser resulting different DOM structure in CK editor

## Provide detailed reproduction steps (if any)

1. Copy the below text from Chrome browser
<!DOCTYPE html>
<html>​
<body>​
​
<h1>This is heading 1</h1>​
<h2>This is heading 2</h2>​
<h3>This is heading 3</h3>​
<h4>This is heading 4</h4>​
<h5>This is heading 5</h5>​
<h6>This is heading 6</h6>​
​
</body>​
</html>

2. Paste the above text in Ck editor in Chrome browser & IE 11 ( We are validating Ck editor control in email body in CRM)

### Expected result

When we paste the HTML text in IE 11 it should have the same styles in DOM as like in chrome browser

### Actual result

IE 11 browser is adding some extra in-line styles in DOM for pasted content in CK editor

## Other details

* Browser:  IE11
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins
[RE_ Bug 1466574_ Email template created in IE11 with Html content is rendered as normal text in draft mail.zip](https://github.com/ckeditor/ckeditor-dev/files/3519390/RE_.Bug.1466574_.Email.template.created.in.IE11.with.Html.content.is.rendered.as.normal.text.in.draft.mail.zip)
: …

Observations :
Issue is repro if you copy the HTML text in Chrome browser and paste in Ck editor in IE 11. If we copy and paste from IE to IE issue is not repro.

Please find the attached mail thread for more information

**Comment by Tejaravulapalli** [comment]
The sample HTML text is 
<h1>This is heading 1</h1>​
<h2>This is heading 2</h2>​
<h3>This is heading 3</h3>​
<h4>This is heading 4</h4>​
<h5>This is heading 5</h5>​
<h6>This is heading 6</h6>​

**Comment by Comandeer** [comment]
This is a native behaviour of Chrome: it adds its own styling to copied HTML. To work around this issue, you can use [paste filter](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter).
