### ISSUE TITLE
Find Toolbar issue

### ISSUE THREAD

**Issue by mathan05** [ckeditor/ckeditor-dev#3351]
I have check the ckeditor sample and find the word using Find toolbar, but match cyclic option only working. Remaining match case and match whole world is not working. It shows "specified text not found". I checked the all possibilities for both options.

Below options are not working in ckeditor sample 
1.Match case
2.Match whole word

### Expected result

If find text "option", it highlighted in ckeditor when clicking Match case and Match whole word separately.

### Actual result

Specified text not found

## Other details

* Browser: Chrome
* OS: Windows 7
* CKEditor version: 4.11.4

**Comment by engineering-this** [comment]
Hi.

I can't reproduce your issue. All find options seem to work for me. Can you reproduce this issue with the latest CKEditor 4.12.1? You can test here: https://cdn.ckeditor.com/4.12.1/full-all/samples/

**Comment by mathan05** [comment]
Hi.

I checked the link (https://cdn.ckeditor.com/4.12.1/full-all/samples/) that you provided, Match cyclic working fine. Match whole word and match case getting same issue.

Can you please help me, how to remove find options check boxes for below in config.js
1.Match case
2.Match whole word

Because we need only **Match cyclic**

Thanks in advance

**Comment by engineering-this** [comment]
I still can't reproduce your issue. All the matching options are working to me as expected. Can you write detailed steps how do you reproduce issue?

>Can you please help me, how to remove find options check boxes for below in config.js

Unfortunately dialog definition for `find` plugin is hardcoded, there is no config option that allows to choose which checkboxes are available in dialog.

**Comment by mathan05** [comment]
Hi,

Please find the attached document, which gives detailed explanation for step by step and getting issues while click on Match case and Match Whole word separately.
[doc.docx](https://github.com/ckeditor/ckeditor-dev/files/3540969/doc.docx)

**Comment by engineering-this** [comment]
Hi.

When you have `match cyclic` option unchecked, then search will start from current selection. If your selection is at the end of editor content, then nothing will be found. When `match cyclic` is checked then when end the content is reached search will be continued from the beginning.

Please look at attached gif:

![Aug-26-2019 15-30-51](https://user-images.githubusercontent.com/23366849/63694382-9c61c680-c816-11e9-955f-010adb022119.gif)

**Comment by mathan05** [comment]
Thank you. I understood the functionality.
