### ISSUE TITLE
Collapse Toolbar button not visible 

### ISSUE THREAD

**Issue by rsedano** [ckeditor/ckeditor-dev#3362]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Based on the documentation I have set to true the toolbarCanCollapse configuration
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbarCanCollapse

### Expected result

Collapse toolbar button is displayed

### Actual result

Collapse toolbar button is not displayed

## Other details
I did an example using CKEditor 4.12.1 (ink below). You can see that the button is not displayed. https://codepen.io/rsedano/pen/jONmjbO

* Browser: Chrome
* OS: …
* CKEditor version: 4.11.4 and  4.12.1
* Installed CKEditor plugins: All

**Comment by jacekbogdanski** [comment]
[`config.editorConfig`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-editorConfig) is supposed to work with custom file configuration which can be additionally set by [`config.customConfig`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-customConfig) option.

Your code inside `editorConfig` is never executed. For the codepen purpose, you can pass configuration directly into initialization method e.g. `CKEDITOR.replace( 'editor', config )`.

**Comment by rsedano** [comment]
We have a project where we use the config.js file to set the configuration and it looks like below. I can confirm that our code is executed in our website since the rest of the configuration works fine but the collapse toolbar is not displayed. We add several CKEditors to the page dynamically, can it be that the problem?. 

 ***** config.js ****
CKEDITOR.editorConfig = function( config ) {

    config.toolbar =
    [
        { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo'] },
        { name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll'] },
        { name: 'colors', items: ['TextColor'] },
        { name: 'insert', items: ['Table','Image'] },
        { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'] },
        { name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
        { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
        { name: 'plugin', items: ['SpellChecker', 'Scayt', 'Sourcedialog'] },
        { name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize'] }
    ];

    config.removePlugins = 'resize, elementspath, magicline, dragdrop';
    config.toolbarCanCollapse = true;
    
    config.enterMode = CKEDITOR.ENTER_DIV;
    config.format_tags = "div;p;h1;h2;h3;h4;h5;h6;pre;address";

    // Load plugin to enable autogrow
    config.extraPlugins = 'find,onchange,colordialog,colorbutton,selectall,justify,liststyle,font,scayt,dragAndDropOff,sharedspace,autogrow,sourcedialog';
    config.autoGrow_minHeight = 50;
    config.autoGrow_bottomSpace = 10;
    config.autoGrow_onStartup = true;
    config.autoGrow_maxHeight = userSettings.EditorHeight ? userSettings.EditorHeight.replace(/\D/g, '') : 0;

};
