### ISSUE TITLE
Missing closing tag causes extra tags to be added to html

### ISSUE THREAD

**Issue by doveye** [ckeditor/ckeditor-dev#3377]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. In Drupal source mode, I added  `<code></code>` tags around some text
2. But missed the "/" in one `</code>` tag
3. Saved the doc
4. Drupal added `<code><code> </code></code>` around nearly every element (and even blank lines) after the missing "/", for the whole of the rest of the doc. eg

```
<p><code><code><b><a href="#top">Go back to top</a></b></code></code></p>
<code><code> </code></code>
```

### Expected result

The html should remain as is. A warning that an end tag is missing would be good.

### Actual result

Too many `<code>` tags! I believe I've also seen this with `<b>` tags. Apparently this is due to the Advanced Content Filter (ACF) adapting the html.

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4 (embedded in Drupal 8)
* Installed CKEditor plugins: None I believe

**Comment by jacekbogdanski** [comment]
It's the normal browser behavior that incorrectly closed tag (without `/`) will be applied to the following content. You can test it here: https://codepen.io/jacekbogdanski/pen/dybZBLW

Tags are duplicated because CKEditor4 converts HTML into semantic elements and if they are nested it needs to apply them on a lower level.

However, it's desired behavior so the only recommendation I can give is to use correct HTML syntax.

**Comment by doveye** [comment]
@jacekbogdanski  Thanks, but shouldn't CKEditor give a warning message instead of modifying the whole of the rest of the doc? So for example, if it comes across a <code> tag after another <code> tag, it warns that there's a missing end tag? And possibly also inserts an end tag itself before the second <code> tag? Then it can leave the rest of the doc unchanged and it would be much simpler for the author to fix.

**Comment by jacekbogdanski** [comment]
CKEditor4 is a text editor, not HTML so such feature rather goes beyond its purpose. Of course, you are able to modify with `sourcearea` plugin but that's it. The linting feature is much more complicated than just checking tag closing. Bear in mind that don't get any warning from the browser about incorrectly closed tag element also.
