### ISSUE TITLE
Polyfill for Object.keys() doesn't accept non-objects on IE8

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#3381]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Execute `CKEDITOR.tools.object.keys( undefined )` or `CKEDITOR.tools.object.keys( null )` on IE8 browser

### Expected result

An empty array as it works for other browsers.

### Actual result

Throw an error: "Object expected"

## Other details

* Browser: IE8
* OS: Win7
* CKEditor version: 4.12.1
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
It seems that this discrepancy is caused by the difference between `Object.keys` behaviour in ES5 and ES2015+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Notes
