### ISSUE TITLE
ckeditor spell checker is not working in mobile app

### ISSUE THREAD

**Issue by electem** [ckeditor/ckeditor-dev#3386]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1 : added the ckeditor
2 : Write any wrong spelling

### Expected result
When ever I use mobile app in web form the spell checker is working fine. It is proving options for different corrections. By using the same code after generating APK, in mobile spell checker should work in ck editor.
![editor](https://user-images.githubusercontent.com/54798178/64344754-b5cff300-d00c-11e9-8dbb-d531d3c86628.png)

### Actual result
Spell checker is not working in mobile APP.
![Screenshot_2019-09-05-18-44-09-612_com uralian MyTechReportsV2](https://user-images.githubusercontent.com/54798178/64345398-e95f4d00-d00d-11e9-98dc-3665410f6186.png)

## Other details

* Browser: chrome 
* OS: …
* Installed CKEditor plugins: …4.12.1

Could you please suggest me that how the spell checker will work for mobile App.

**Comment by jacekbogdanski** [comment]
Both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization. Please the report ticket directly in or [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
