### ISSUE TITLE
Enter key breaks table structure when pressed in a table selection

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#415]
## What type of issue would you like to report?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Nope.

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.dev:1030/tests/plugins/tableselection/manual/tableselection
2. Select some cells.
3. Press <kbd>Enter</kbd>.

### Expected result

* New line is inserted into first selected cell.
* Other cells are emptied.
* Fake selection is removed.

### Actual result

* Other cells are not emptied.
* Fake selection is preserved.

## Other details

* Browser: Firefox
* CKEditor version: 4.7.0

**Comment by yguarata** [comment]
Hi,

I can still reproduce this bug in current CKEditor release. Tested in Linux/Chrome Version 65.0.3325.146 (Official Build) (64-bit)

Steps to reproduce:

1. Enter https://ckeditor.com/ckeditor-4/
2. Add a table with the default dialog configuration
3. Select some cells e press enter.

The images bellow show what happens:

Table selection: ![image](https://user-images.githubusercontent.com/802909/37565143-4e0c2bb6-2a82-11e8-917d-df7e79efe4e5.png)

After press enter: ![image](https://user-images.githubusercontent.com/802909/37565145-56256812-2a82-11e8-84da-ecf28eecefdd.png)

**Comment by mlewand** [comment]
@yguarata thanks for the heads-up I can reproduce your issue, you can follow it at #1816.

**Comment by yguarata** [comment]
thanks @mlewand.
