### ISSUE TITLE
MenuButton with label puts "(Selected)" at the end of the label when clicked

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#421]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/14237

## Provide detailed reproduction steps (if any)

1. Add a Menu Button to the toolbar, using the menubutton plugin.
2. Change the skin css to show the label for the button.
3. Open the editor and click on the menu button

### Expected result

The menu button label should not change.

### Actual result

The menu button label changes from 'Label' to 'Label (Selected)'.

**Comment by jacekbogdanski** [comment]
I wonder how this change will affect accessibility? Additional `(Selected)` postfix is added for `TRISTATE_ON` state for buttons with arrow indicator i.e `colorbutton` and `menubutton`. Do we need indicate by aria label that the button is *opened* like `Language (Selected)`, `Background Color (Selected)`?

**Comment by mlewand** [comment]
@jacekbogdanski `aria-expanded` attribute should be used to denote opened menu. See https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html#rps_label.
