### ISSUE TITLE
Paste From Word Filter is not integrated with BR mode

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#423]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/16979

## Provide detailed reproduction steps (if any)

1. Open http://nightly.ckeditor.com/17-04-19-06-08/full/samples/old/enterkey/enterkey.html
2. Sent enter mode to BR
3. Paste contents from attached document
4. Switch to Source Mode

### Expected result

```<b><i>Paste from word</i></b><br />```

### Actual result

```<p><b><i>Paste from word</i></b></p>```

**Comment by msamsel** [comment]
I'm curious why there can't be just disallowed `p` element in editor configuration? I assume that, if `p` tag is allowed, then is nothing wrong when it appears after pasting from word. Or is there any other reason why we need to filter it within "paste from word plugin?
In my opinion this might result with some further consequences, where:
- user would like to have paragraph tags in editor after pasting from word, but it won't be possible
- or paragraphs will be filtered from editor by pasting from word plugin, but not by other plugins, so there appear some inconsistency.

I've made some demo (https://codepen.io/msamsel/pen/zzejwJ) showing up that general `disallowContent` rules work quite nice and from my perspective seems to be solution for described problem.

@jswiderski do you know some background o this case? Maybe you'll be able to say something more here.

**Comment by msamsel** [comment]
@mlewand can you check my comment in a spare time?

**Comment by jswiderski** [comment]
@msamsel while the diallowedContent removes the unwanted paragraphs, please note there are plugins like Div Container which uses `Div P`. With that `disallowedContent` rule you can insert the container but its inner `P` will be removed when e.g. switching to source and back. This was not the case in 4.5.11.

I have also noticed difference in selection (this is probably related to other issue or it is a change in behavior).  In version 4.5.11, you were getting `<b><i>Paste from word</i></b><br />^` (the ^ char represents selection) and now you are getting `<b><i>Paste from word^</i></b>` what causes styles being continued after pressing enter. This is definitely a difference when comparing to version 4.5.11 but which of these two is now considered correct behavior? Should we continue styles or not?

**Comment by mlewand** [comment]
Agreed with @jswiderski. In addition to that we're also missing enter mode div integration which should be added after BR mode (#816).

**Comment by mlewand** [comment]
@Comandeer I'll ask you to review this one.
