### ISSUE TITLE
Editor chrashes current Chrome

### ISSUE THREAD

**Issue by roben** [ckeditor/ckeditor-dev#427]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to ​http://nightly.ckeditor.com/17-05-29-06-08/full/samples/ using latest Google Chrome
2. Activate Souce Code view
3. Paste following HTML Code:
`<input class="ui:include" type="button" value="/cms/components/mvp_1blf_201516" disabled="true"/>`
4. Switch back to WYSIWYG-mode
5. Click around in editor content

### Expected result

Editor is usable.

### Actual result

Editor crashes Chrome tab with 100% CPU load. Tab needs to be killed with chrome task manager.

## Other details

* Browser: Latest stable Google Chrome
* OS: Reported to us by customers running Windows (7 or 10), reproduced on macOS 10.12.5
* CKEditor version: 4.6.1, 4.7.0, nightly
* Installed CKEditor plugins: see nightly example

**Comment by jswiderski** [comment]
We have this issue reported on track - https://dev.ckeditor.com/ticket/17003

**Comment by wojtekw92** [comment]
This issue is no longer reproducible with chrome version 59.0.3071.104 (Official Build) (64-bit).
