### ISSUE TITLE
pasteFromWordRemoveFontStyles and pasteFromWordRemoveStyles is not working as expected in IE 11

### ISSUE THREAD

**Issue by nish-mdn** [ckeditor/ckeditor-dev#428]
## Are you reporting a feature or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. My ckeditor configuration is below

```js
CKEDITOR.replaceClass = 'rich_editor';
CKEDITOR.editorConfig = function( config )
{
  config.extraPlugins = 'base64image';
  config.allowedContent = true;
  config.disableNativeSpellChecker = false;
  config.pasteFromWordPromptCleanup = false;
  config.pasteFromWordRemoveFontStyles = true;
  config.pasteFromWordRemoveStyles = true;

  // Toolbar groups configuration.
  config.toolbar = [
    { name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ ] },
    { name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
    { name: 'insert', items: [ 'base64image', 'Table', ] },
    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat' ] }
  ];
};

```
2. Just copy and paste the content of attached file into ckeditor. Look at the extra indent on "Reporting:" and "Variances/Observations:". Unnecessary space indent on these lines. But if you look at  the word doc there is no additional/extra spaces. This issue only on IE11 browser (we didn't checked older versions of IE). But other browsers like chrome and Firefox are working as expected.
3. [Reports Comments CYNCPS-619.docx](https://github.com/ckeditor/ckeditor-dev/files/1040873/Reports.Comments.CYNCPS-619.docx)

### Expected result
There should not be any additional spaces on IE 11.
*What is the expected result of the above steps?*
There should not be any additional spaces on IE 11.
### Actual result

*What is the actual result of the above steps?*
![screenshot-1](https://cloud.githubusercontent.com/assets/1856945/26625493/e38c4bd6-4611-11e7-8897-15119c9b170f.png)

See extra indentation on "Reporting:" and "Variances/Observations:" compare "Over-Advance:" line.

## Other details

* Browser: IE 11
* OS: Windows  
* CKEditor version: 4.2.3
* Installed CKEditor plugins: 4 2.3

**Comment by mlewand** [comment]
This is actually what we get from Internet Explorer 11.

If you take a look on a demo using [plain content editable](https://codepen.io/mlewand/pen/VPPEwJ) and paste the content there, you'll see the same thing. We can only base our pasting on what we get from the browser.

You could report an issue on IE bug tracking system but it wont be considered as IE team supports only security fixes, so I'm afraid you're out of luck here.
