### ISSUE TITLE
it was not possible to complete the request due to file system permission restrictions.

### ISSUE THREAD

**Issue by Atul1413** [ckeditor/ckeditor-dev#429]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Atul1413** [comment]
it was not possible to complete the request due to file system permission restrictions.

i am getting error while trying to upload images & pdf from machine,the code is working properly on local host but facing an issue on hosted server

![error_fileuploading](https://cloud.githubusercontent.com/assets/11453397/26630541/c4b239ba-4624-11e7-9f53-9a322437726e.PNG)

**Comment by mlewand** [comment]
This is a CKFinder issue, please report it in it's issue tracker at https://github.com/ckfinder/ckfinder/issues
