### ISSUE TITLE
Unit tests fails in Chrome on Travis CI in CKEditor dev version

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#431]
# Are you reporting a feature or a bug?

Other: Integration issue -  it is an issue connected with Travis CI, not sure if the cause is in the code base.

## Provide detailed reproduction steps (if any)

See https://travis-ci.org/ckeditor/ckeditor-dev/jobs/236308123. Seems like Chrome loses focus when running unit tests (tests connected with focus are failing). Strangely it happens only with dev version, built tests run passes.

## Other details

* Browser: Chrome 58 run on Xvfb
* OS: Linux
* CKEditor version: latest `master` dev version (https://github.com/ckeditor/ckeditor-dev/commit/c5676c7b80f25254710636308694c879e6f05f18)
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
![image](https://cloud.githubusercontent.com/assets/1061942/26631167/1ebe4770-460a-11e7-9026-929a94382056.png)

I run unit tests on Chrome 58 on Xfvb with Ubuntu 16 (similar how it works on Travis CI) and the same (and few more) tests fails. Next things to check:
- If unit tests fails on linux with GUI (not via Xfvb).
- Go back in history / bisect to check if there is any commit which makes tests fails.

**Comment by f1ames** [comment]
Bisecting shows the failing commit is https://github.com/ckeditor/ckeditor-dev/commit/5ef7f741d9468735125f852ac6691b17f5d64072 which is quite strange... :) I will run the tests for it and nearby commits once again to check if the results are stable and then check how it behaves with GUI.

**Comment by f1ames** [comment]
Looking at the prepared Travis CI builds, the bisect results seems to be confirmed:
- failing commit - https://travis-ci.org/cksource/ckeditor-dev/builds/237935603
- commit before failing one - https://travis-ci.org/cksource/ckeditor-dev/builds/237933667

**Comment by f1ames** [comment]
The cause of this issue is one of the XSS test which triggers the dialog on Linux:
![image](https://cloud.githubusercontent.com/assets/1061942/26670669/d719c85a-46b2-11e7-96e8-c9c369419fee.png)

The dialog gets focused and rests of the tests run without a focus inside tab (dialog is focused). The breaking commit fixed the condition so the test is run on all browsers except some IE (instead of running only in IEs) which means this is the breaking test.

**Comment by mlewand** [comment]
Skipping the changelog entry as it's not important from end user perspective.
