### ISSUE TITLE
Balloonpanel unit tests fails when run in a set

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#441]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/17042

## Provide detailed reproduction steps (if any)

Unit tests `tests/plugins/balloonpanel/positioning.inline` fails when run in a set with other tests. When run as a single tc all 3 tests passes.

## Other details

* Browser: Safari
* OS:iOS 10.3.2

**Comment by msamsel** [comment]
For now it seems to be problem in safari to not properly handle scrollTo inside an iframe.
https://bugs.webkit.org/show_bug.cgi?id=172854
