### ISSUE TITLE
Link dialog has invalid width when editor is maximized and browser window resized

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#453]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/fullpreset.html.
1. Press maximize button (switches to maximized mode).
1. Change one of the link types to email (double click on link an edit in dialog).
1. Resize the window so its height is less than default dialog height (see screenshot).
1. Click on the edited link to open link dialog again.

### Expected result

Link dialog has proper size, and its content fits well inside it.

### Actual result

Link dialog is very narrow and some of its content is placed outside.
![image](https://cloud.githubusercontent.com/assets/1061942/26714573/53f552ee-4772-11e7-8478-6adec47f9fbf.png)

## Other details

* Browser: Chrome 58
* OS: OS X
* CKEditor version: 4.7.0
* Installed CKEditor plugins: Full preset

**Comment by ukambham** [comment]
I am also facing the issue. For all dialog width is not proper size.
![Capture](https://user-images.githubusercontent.com/55147719/64622920-187f1100-d3b6-11e9-8670-5915a8fded78.PNG)


How to fix this issue?
