### ISSUE TITLE
CKEDITOR_BASEPATH not work

### ISSUE THREAD

**Issue by brucewar** [ckeditor/ckeditor-dev#454]
If my `location.href` is a HTML5 hash URL, it will work unexpectedly. And then I looked into source code, found that the regular expression may result in it. 

* Browser: Chrome
* OS: Win10
* CKEditor version: >=4.0

**Comment by mlewand** [comment]
Hi @brucewar could you provide a simplified step by step repro case as requested in our template?

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by mooflu** [comment]
We ran into this. Relative path code does not seem to handle fragment:

https://github.com/ckeditor/ckeditor-dev/blob/51f2933d32ff606c85db0aaf7045706c3ebf077a/core/ckeditor_base.js#L144

'http://mamabear.local/#692345326/leader'.match( /^[^\?]*\/(?:)/ )[ 0 ]
"http://mamabear.local/#692345326/"

'http://mamabear.local/discodash/#692345326/summaryreports'.match( /^[^\?]*\/(?:)/ )[ 0 ]
"http://mamabear.local/discodash/#692345326/"

Maybe just needs a hash in regex. I.e.:
'http://mamabear.local/discodash/#692345326/summaryreports'.match( /^[^\?#]*\/(?:)/ )[ 0 ]
"http://mamabear.local/discodash/"
