### ISSUE TITLE
Editor gone after pasting into an editor within a table

### ISSUE THREAD

**Issue by hponka** [ckeditor/ckeditor-dev#460]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

It happens every times with CKEditor 4.7.0 full preset (dynamically loaded inline editor) when you:

1. open https://codepen.io/anon/pen/wewbmj
1. select whole editor content
1. press backspace
1. then paste some content (e.g. pure text)

But it doesn't happens if you remove tableselection plugin.

### Expected result

Content is pasted properly.

### Actual result

Editor disappears and only pasted content is showing.

## Other details

* Browser: Chrome 58.0.3029.110
* OS: Windows 7 Pro
* CKEditor version: 4.7.0
* Installed CKEditor plugins: full preset

**Comment by mlewand** [comment]
@hponka I can't repro it, could you try to check https://codepen.io/mlewand/pen/WOeBvM ?

There's an empty inline editor (just below the first paragraph)

1. Click empty inline editor (just below the first paragraph).
1. Press backspace.
1. Paste text.

The content is visible.

**Comment by hponka** [comment]
@mlewand It happens when editor is in table cell: https://codepen.io/anon/pen/wewbmj

**Comment by mlewand** [comment]
Thank you @hponka now I can reproduce the issue.

**Comment by Comandeer** [comment]
It seems that changes connected with handling pasting in `tableselection` plugin that were made in 4.7.2 fixed this issue: https://codepen.io/anon/pen/VzXxzK

**Comment by mlewand** [comment]
@Comandeer that's right I also can no longer reproduce this issue from version 4.7.2. @Mgsy can I ask you to do manual test in order to (tripple) confirm that the issue has been fixed?

If it is we need to move this ticket to 4.7.2 milestone, and correct changelog entry.

**Comment by Mgsy** [comment]
> @Mgsy can I ask you to do manual test in order to (tripple) confirm that the issue has been fixed?

I can confirm that this issue doesn't occur anymore.

**Comment by mlewand** [comment]
Thanks for confirming! It was most likely fixed with this major PR: #694.

Added changelog entry in a3483c379.
