### ISSUE TITLE
Can't select cells in tfoot

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#465]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/17067

## Provide detailed reproduction steps (if any)

1. Open ​https://jsfiddle.net/0cr59Loa/
1. Start selecting from a row above the one with headings.
1. Stop selecting at the end of the table.

### Expected result

All selected rows remain selected.

### Actual result

All rows below the one with headings are unselected just after releasing mouse button.

## Other details

It seems to be connected with the order of elements in table. If tfoot is after tbody, then everything seems to be working correctly.

**Comment by Comandeer** [comment]
Both HMTL Living Standard and HTML 5.x don't allow `tfoot` before `tbody` anymore:

> As a child of a `table` element, after any `caption`, `colgroup`, `thead`, `tbody`, and `tr` elements, but only if there are no other `tfoot` elements that are children of the `table` element.

Therefore this issue is no longer valid.
