### ISSUE TITLE
Safari freezes on nested tables

### ISSUE THREAD

**Issue by kaero598** [ckeditor/ckeditor-dev#471]
## Are you reporting a feature or a bug?

Bug.

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

The issue had been reported throught ticket [#16970](http://dev.ckeditor.com/ticket/16970). Although my case does not involve comments in HTML source.

## Provide detailed reproduction steps (if any)

1. Open "Source" mode.
2. Paste following HTML (or the one [from the ticket](http://dev.ckeditor.com/attachment/ticket/16970/bug.txt)):
```html
<table>
    <tr>
        <td>
            <table>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
```
3. Leave "Source" mode.
4. Set cursor somewhere in the content.
5. Safari stops working.

### Expected result

I expect no hang within Safari browser.

### Actual result

Safari tab hangs and consumes 100% CPU.

## Other details

* Browser: Safari 10.0.3 (12602.4.8).
* OS: macOS 10.12.3.
* CKEditor version: 4.4.0, 4.5.3, 4.7.0.
* Installed CKEditor plugins: only sourcearea, table, toolbar and wysiwygarea.

**Comment by beatadelura** [comment]
I also noticed that the browser is freezing when 3 tables were added by using `Table` on the toolbar.

### Steps to reproduce:

1. Click `Table` on the toolbar.
2. Click `OK`.
3. Click `Table` on toolbar again.
4. Click `OK`
5. Click `Table` on toolbar again.
6. Click `OK`

**Comment by beatadelura** [comment]
This bug is related to the core. It's reproducible even if `table`is disabled. It concerns only classic editor because it's not reproducible with `div-based` editor.

**Comment by andrewboni** [comment]
Any updates on this? Also running into this in production on Safari 11.0.2 and CKEditor 4.7.x

**Comment by klingat** [comment]
Any updates? Issue is still open and am experiencing this in production as well on Safari version 11.0.3.

**Comment by mlewand** [comment]
> Any updates on this? Also running into this in production on Safari 11.0.2 and CKEditor 4.7.x

Not yet, however we see some interest here. We'll try to give it a spin somewhere next week to understand how it could be fixed / how it affects CKE.



> and also happens if the HTML has a comment at the top of the file, and another comment at the bottom of the file.

That sounds like a separate case. I'd ask you to make a separate bug report with complete repro steps, so that we won't miss it.

**Comment by msamsel** [comment]
It seems to be an upstream issue. I've report it to Safari: https://bugs.webkit.org/show_bug.cgi?id=183741
You can check how browser behave without CKEditor here: https://codepen.io/msamsel/pen/qoqMpd

**Comment by mlewand** [comment]
Thanks for the research @msamsel.

As pointed out, it turns to be an upstream issue in Safari core. But not all hope is gone yet! We have reported an upstream issue, best what you can do now is to add yourself to "CC list" in Bugzilla, so that you show Safari team your support for that issue.

**Comment by klingat** [comment]
@msamsel @mlewand Added myself to the list. Thank you!
