### ISSUE TITLE
Paste problem with CKEditor 4.7.0

### ISSUE THREAD

**Issue by smiska** [ckeditor/ckeditor-dev#472]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Copy text to clipboard
2. Paste from the clipboard to the *beginning/end/highlighted* part of textarea

The screenshots provide pictures about the debugging process. Trying to insert the word "Thank" from the clipboard, in ckeditor.js the `this.$.innerHTML` contains the full document body, which gets overwritten. In the second and third picture the steps after the insert are visible.

### Expected result

The content from the clipboard gets inserted to the location of the cursor

### Actual result

The whole document gets wiped out

## Other details

* Browser:  58.0.3029.110
* OS: Ubuntu 16.04 (64bit)
* CKEditor version: 4.7.0 full

![screenshot from 2017-06-06 13-07-11](https://cloud.githubusercontent.com/assets/16736043/26827775/fdfc81c8-4abe-11e7-9862-edaa671e13df.png)
![screenshot from 2017-06-06 13-07-36](https://cloud.githubusercontent.com/assets/16736043/26827774/fdfafa6a-4abe-11e7-9336-5b98a4769b6c.png)
![screenshot from 2017-06-06 13-07-27](https://cloud.githubusercontent.com/assets/16736043/26827773/fdfabb0e-4abe-11e7-8cf8-1c1110eda494.png)

**Comment by mlewand** [comment]
Thanks @smiska for the report, can I ask you to provide more detailed step-by-step report? It's my understanding that you're trying to paste a simple "Thank" text into the end of header, and as a result content gets wiped, but I can't reproduce it.

Can you reproduce it on any of [our demos](http://ckeditor.com/)?

**Comment by smiska** [comment]
I'll try to reproduce it in the examples section, in the meantime I provide a screenshot about how the  4.4.0 version of the CKEditor software works in our system. The root issue in [#479](https://github.com/ckeditor/ckeditor-dev/issues/479) seems to be similar. The `this` keyword somehow doesn't refer to only a dom element, but the entire document in string format. After the paste the elements are in place but are not shown.
![screenshot from 2017-06-07 17-03-23](https://user-images.githubusercontent.com/16736043/26886273-38a3397a-4ba5-11e7-88c9-016647b89add.png)

**Comment by mlewand** [comment]
Ok we're waiting for the steps then, because screens won't give us too much of a value now. Try to provide repro steps on one of [our CKEditor demos](http://ckeditor.com/).

**Comment by hponka** [comment]
Is the editor inside a table? If yes, this is the same bug as here: https://github.com/ckeditor/ckeditor-dev/issues/460

**Comment by smiska** [comment]
The text boxes are inside nested `div`s in which CKEditor is used to edit the text, but those `div`s are in placed in `table` elements indeed, and the full editor software (where the problem occurs) has wrapper `table`s as well. I hope it helps. This problem doesn't happen with CKE 4.6.2 .

**Comment by mlewand** [comment]
Thanks for help @hponka indeed it does look like the same case. @smiska please follow #460 issue to keep an eye on it.
