### ISSUE TITLE
Cannot edit empty anchor tags

### ISSUE THREAD

**Issue by benphelps** [ckeditor/ckeditor-dev#476]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Click on the anchor button with no text selected
2. Set the name of the anchor tag, the empty anchor tag is created
3. Attempt to edit the added anchor tag, either via right click or by clicking the anchor button with the anchor tag selected

You can observe this here as well: http://sdk.ckeditor.com/samples/classic.html

### Expected result

You should be able to edit the anchor tag.

### Actual result

You cannot edit the anchor tag.

## Other details

* Browser: Chrome 59
* OS: OS X 10.12.5
* CKEditor version: 4.7 / 4.7.1
* Installed CKEditor plugins: The default "Full" package, nothing else.

**Comment by mlewand** [comment]
Thanks for the report. This is a regression introduced in **4.7.0**, most likely it was introduced when adapting link plugin to multi range support.

**In addition to what was reported by OP** I can see that it's no longer possible to open edit dialog with a double click, which sounds like is related to this issue.

**Comment by Comandeer** [comment]
The issue with double click is connected with fix for http://dev.ckeditor.com/ticket/11956 which also landed in 4.7.0, but it's completely unrelated to the one that cause this issue.
