### ISSUE TITLE
ckeditor is not loading for the first time, need to refresh the page in Primefaces

### ISSUE THREAD

**Issue by VenkataGireesh** [ckeditor/ckeditor-dev#499]
Hi Everyone,

I am using ckeditor in my primefaces project. It is not loading for the first time, have to refresh or reload  the page. In chrome developer tool am seeing below error.

CKEditor throwed a error while destroying the old instance: TypeError: Cannot read property 'clearCustomData' of null primefaces-extensions.source.js:701

In .xhtml page below code i have used for ckeditor.

<pe:ckEditor  id="guaracommentGuarantorDetailID" width="96%" height="100"
 toolbar="#{serverDetail.toolbar}">
</pe:ckEditor>

In serverdetail file: 
toolbar = [['Print','Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo','Find', 'Replace', '-', 'SelectAll', '-', 'Scayt','/','Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat','NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl','Table','Styles', 'Format', 'Font', 'FontSize','TextColor', 'BGColor','Maximize']]

Below list of jars am using:
primefaces-6.0
primefaces-extensions-6.0.0
resources-ckeditor-6.0.0

I have tried many things but nothing worked. Can someone help me here please...!

**Comment by jswiderski** [comment]
Hi,

The Extension CKEditor PrimeFaces is not our creation and the error is not being thrown in `ckeditor.js` but in `primefaces-extensions.source.js` file. You should report this issue to PrimeFaces.

**Comment by VenkataGireesh** [comment]
Thanks
