### ISSUE TITLE
Cannot read property 'ltr' of undefined

### ISSUE THREAD

**Issue by bpzhang** [ckeditor/ckeditor-dev#502]
I use the version 4.7.0 where I download from the homepage.
when I change the language to the 'zh-cn',then throw a error 'Cannot read property 'ltr' of undefined' in the browser
![image](https://user-images.githubusercontent.com/1734396/27032562-ff48b75c-4fa7-11e7-9182-50922fad4009.png)

how do fix this?

thanks

**Comment by jswiderski** [comment]
Please attach `build-config.js` file for your editor. I have just downloaded CKEditor full package, changed the language to `zh-cn` but no error was thrown.
```
var editor = CKEDITOR.replace( 'editor1', {
	language: 'zh-cn'
});
```
What have I missed?

**Comment by bpzhang** [comment]
build-config.js was in my editor folder, and I don't know where is my wrong.
If I   replace  the ckeditor.js of 4.7.0 with the ckeditor.js of ckeditor-dev
the then  change language to zh-cn . there is no error  and  it works.

**Comment by jswiderski** [comment]
Please try downloading the CKEditor package one more time from our [download page](http://ckeditor.com/download). Please also clear browser's cache according to http://www.wikihow.com/Clear-Your-Browser%27s-Cache and then re-check the problem.
