### ISSUE TITLE
Allowed content rule allowing all elements using "object format" does not produce the same result as allowedContent = true

### ISSUE THREAD

**Issue by gfox1984** [ckeditor/ckeditor-dev#503]
The[ CKEditor documentation ](http://docs.ckeditor.com/#!/guide/dev_disallowed_content) states that `allowedContent = true` can be replaced with an equivalent object format rule:

> How to Allow Everything Except...
> A popular requirement is to allow all HTML features except a few specific ones. In this case setting CKEDITOR.config.allowedContent to true is not a solution, because this completely disables the Advanced Content Filter, so CKEDITOR.config.disallowedContent will not work either.
Therefore the only solution is to write an allowed content rule allowing all elements. Fortunately, this can be done easily by using the object format of allowed content rules and the CKEDITOR.dtd object.

However, replacing `config.allowedContent = true` with:

```
config.allowedContent = {
    $1: {
        // Use the ability to specify elements as an object.
        elements: CKEDITOR.dtd,
        attributes: true,
        styles: true,
        classes: true
    }
};
```

does not produce the same results. With the second solution, the CKEditor still replaces some content with others (eg `<font color="..."` become `<span style="color:...">`.

Therefore it seems that if you want to "allow everything except...", you have no way of preserving the source of the content...

* Browser: Edge 15
* OS: Windows 10 Creator Update
* CKEditor version: 4.7

**Comment by jswiderski** [comment]
All elements are allowed but part of ACF are also transformations which in this case are still active and it so happens that font plugin has transformations `font => span` defined thus you are getting that result. Please see: https://github.com/ckeditor/ckeditor-dev/blob/2354a28a70d545616579e4d2926ac0a19e32bf90/plugins/font/plugin.js#L41-L82

Allowing all elements in the editor will not produce the same results as with disabled ACF.

**Comment by gfox1984** [comment]
Is there any way to disable or override these transformations?
