### ISSUE TITLE
Bug with WordPress Version 4.8

### ISSUE THREAD

**Issue by neilogden** [ckeditor/ckeditor-dev#507]
## Are you reporting a feature or a bug?

After upgrading to WordPress version 8, when going to the widgets page, I get an error 

Fatal error: Call to undefined method _WP_Editors::enqueue_default_editor() in /home/serswimming/public_html/wp-includes/general-template.php on line 3090

I did a search for this error and found others having the same issue for the same reason but after doing a search it doesn't appear to have been reported already.

**Comment by mlewand** [comment]
Hi @neilogden - thanks for the report, however this is the issue of a Wordpress integration itself. So you could drop the issue to the relevant place https://github.com/ckeditor-for-wordpress/ckeditor-for-wordpress/issues. At the same time note that we're no longer actively maintaining the project, so unless there's some community contribution, it won't be addressed any time soon.

**Comment by neilogden** [comment]
Hi


It took me half an hour to find anywhere to report this issue on your not very user friendly website.  I have reposted it to where you said to.

If you have no intention of sorting it soon, may I ask why you are still advertising this product and selling the premium version which is now effectively a product that does not work?

Many thanks

Neil Ogden

**Comment by mlewand** [comment]
> may I ask why you are still advertising this product and selling the premium version which is now effectively a product that does not work?

Sure, however to answer this question I'll have to ask where you find the information about us supporting CKEditor for WordPress as a part of premium version?

**Comment by neilogden** [comment]
Hi

I am neither advertising the product or selling the premium version.  I use the free CKEditor plugin on my 20 or so Wordpress websites and have now found that it doesn’t work with the newest WordPress release (or rather the widgets don’t work when it is activated).  I clicked on “plugin homepage” within the plugin information and that got me to your website which I assumed was the webpage of the developer.

**Comment by mlewand** [comment]
So as you can see this plugin is no longer actively maintained by CKSource (see https://wordpress.org/plugins/ckeditor-for-wordpress/).
