### ISSUE TITLE
Image Resize  while uploading by ckeditor

### ISSUE THREAD

**Issue by bhavanai13** [ckeditor/ckeditor-dev#510]
i wanted to re-size image when it is uploaded by ckeditor .
we tried to do change on this file /ckfinder/config.php by changing cofig settings
$config['Images'] = Array(
'maxWidth' => 660,
'maxHeight' => 660,
'quality' => 90);
But in our case we need to fix only width of image and height should vary as per aspect ratio.
but when i comment 'maxHeight' or i set 'maxHeight' => 0 it is not working.
can you please give me solution on above change ?
![ckeditor_change](https://user-images.githubusercontent.com/29423320/27124988-739f6182-5110-11e7-99a6-9c76e5fdbaa9.png)

**Comment by f1ames** [comment]
Hello @bhavanai13,
this is a CKFinder issue, you may report it in a proper repository - https://github.com/ckfinder/ckfinder/issues.
