### ISSUE TITLE
Missing items in a11yhelp dialog

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#512]
## Are you reporting a feature or a bug?

BUG

## Provide detailed reproduction steps (if any)

Problem exist on **master** branch. It's not present on 4.7.0
1. focus editor
1. press `ALT+0` to open a11yhelp
1. in `General` section there are only 2 entries: `Editor DialogEditor Dialog` and `Editor List Box` instead of entire help list.

### Expected result

Full list visible.

### Actual result

Not-full list present in dialog.

## Other details

* CKEditor version: master branch

Blocked by #523

**Comment by mlewand** [comment]
It was probably introduced with #413 as it's not reproducible on 4.7.0 but it is on the latest master branch.

**Comment by mlewand** [comment]
I believe this ticket was fixed recently @msamsel could you confirm it?

**Comment by msamsel** [comment]
Problem is not exist any longer. It was introduced in commit 33dddedc3febfd1b613412600c1a02cbcd595f08. After fixing method `getCommandKeystroke` everything is working ok.
