### ISSUE TITLE
"removePlugins": "toolbar" seemingly has stopped working in v4.7

### ISSUE THREAD

**Issue by jonnott** [ckeditor/ckeditor-dev#516]
Prior to v4.7, this config would show a 'read-only' CKEditor, without a toolbar.

		{
			"readOnly": true,
			"allowedContent": true,
			"removePlugins": "toolbar,elementspath"
		}

..but since v4.7, it now shows the toolbar :(

**Comment by jonnott** [comment]
Related? https://github.com/ckeditor/ckeditor-dev/issues/491

**Comment by mlewand** [comment]
This is a duplicate of #491.
