### ISSUE TITLE
Can't copy/paste from Outlook into CKEditor form in IE11 in some cases

### ISSUE THREAD

**Issue by nctomba** [ckeditor/ckeditor-dev#517]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Copy text from an email in Outlook.
2. Paste into CKEditor on our website in IE11.

### Expected result

The text should be copied over into CKEditor.

### Actual result

No text is copied.

## Other details

* Browser: Internet Explorer 11
* OS: Windows 7
* CKEditor version: 4.7
* Installed CKEditor plugins: Full Package Plugins

The copy/paste from emails in Outlook works if using Chrome, but does not work using IE11 in some cases. It works when using the CKEditor text box on CKEditor's website, and it works when running index.html from the "samples" directory. It does not work when implementing it locally or on our server. We tried implementing CKEditor by replacing the "textarea" part of our html code like it says on the website to install, but when that didn't work, we also tried implementing it like you do in index.html by calling "sample.js".

To reiterate, we can copy and paste things normally into CKEditor from browsers, or notepads, but when copying from Outlook, the paste functionality does not work when implementing CKEditor locally or on our server. It works fine with other browsers, but IE11 does not allow us to paste into the box in some cases.

**Comment by mlewand** [comment]
Currently we do not support Outlook oficially. However we know that it does work nicely in modern browsers like Chrome and Firefox, as these browsers have a nice support for [clipbaordData](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData), and we're able to access to raw HTML produced by Word/Outlook which has many similarities.

In IE11 this API is not implemented, and often times serves us a different markup for Word and Outlook, thus we don't support it, and there are no plans for implementing it in near future.

One thing to note is that IE11 is no longer gets any support from Microsoft other that security fixes, so this enhancement will not be added in the future. However, there's a good chance to have it for Microsoft Edge, as it recently implemented [clipbaordData](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData) API, it can be tracked in #468.
