### ISSUE TITLE
Getting native selection from new table selection returns null

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#519]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open any editor sample with table plugin and insert table
2. Select few cells 
3. In console execute `CKEDITOR.instances.editorName.getSelection().getNative()`

### Expected result

Native Selection Object for first ragne is returned

### Actual result

Null is returned

## Other details

* Browser: any
* OS: any
* CKEditor version: 4.7

**Comment by wojtekw92** [comment]
Actually table selection uses fake selection (the same way as widgets do), so the actual selection does not make much sense for it. This should be mentioned in documentation, so I will update this.
The proper solution is to make `getSelection` with `forceRealSelection` setted to `true` and use `getRanges` method.
To check if selection is fake see: http://docs.ckeditor.com/#!/api/CKEDITOR.dom.selection-property-isFake.
