### ISSUE TITLE
Widget selection is not removed when widget is inside of a table cell

### ISSUE THREAD

**Issue by plblum** [ckeditor/ckeditor-dev#522]
## Are you reporting a feature or a bug?
Bug

Widgets have a selection mode. When they are clicked on, they get selected. When the insertion point or selected range is changed, they become unselected. This worked in 4.6.x. 
When a widget is inside of a table cell (td), the selection mode fails to unselect when the creates an insertion point selection (range = collapsed). It fails to select when the cell ONLY contains the widget.

To reproduce:
1. Go to http://sdk.ckeditor.com/samples/captionedimage.html
2. Insert a 2 column, 1 row table as shown in the supplied image. Include text in each cell.
3. Select the image widget and use the copy command.
4. Move the insertion point into the first cell.
5. Paste.
The widget is established correctly.
6. Select the widget. It becomes selected.
7. Click the insertion point into the text of the second cell.

![widget inside table cell 1](https://user-images.githubusercontent.com/1823645/27263251-88a16d3e-5433-11e7-83cf-c0516ff82e58.png)

Expected:
Widget becomes unselected.

Actual:
Widget stays selected, while the insertion point is active where you clicked.

8. Type.
Expected:
Typing to appear at the insertion point.
Actual:
Typing is ignored.

## Other details
If you make a selected range in the other cell, unselection happens correctly.
If you omit text in the first cell, after pasting, you can click on the widget but it refuses to establish the selection.

I looked into the source code and can point out the issue.
selection.js/checkSelectionChange. This function now checks for fake selection support on tables through a call to isRealTableSelection. It does not test for fake selection used on widgets.
This is a proposed change:
`if ( !realSel || ( !realSel.isHidden() && ((this.widgets.selected.length > 0) || !isRealTableSelection( realSel, sel )) ) ) {`

However, I don't think its the right implementation because the fake selection engine should support user supplied selections. (I have created one for my installation.) Instead, I believe each consumer of fake selections should register a hook that is executed when realSel.isHidden() returns false. This will benefit users who are not using the tableselection plugin too.

* Browser: Chrome Version 58.0.3029.110 (64-bit)
* OS: Windows 7 Professional SP 1
* CKEditor version: 4.7.0
* Installed CKEditor plugins: While I have the tableselection plugin, the config has it in removePlugins.

**Comment by msamsel** [comment]
Hi,

you're I tried to reproduce mentioned problem, but without proper effect. :(
Since reporting the issue there is already Chrome 59, and we just release CKEditor 4.7.1.
I made such steps, can you confirm is this proper way of reproduction this error?
1. Open page http://sdk.ckeditor.com/samples/captionedimage.html
1. Create table 1 row 2 columns
1. write something in both cells
1. Copy image widget (<kbd>Cmd</kbd>+<kbd>C</kbd>)
1. Paste it to table cell (<kbd>Cmd</kbd>+<kbd>V</kbd>)
1. Click into second cell
1. Start to typing on keyboard

Now selection should remain on the widget in 1st cell and text should not appear in 2nd cell? Am I understand you correct?
Because different things happen for me: cell text is disappearing and image widget in cell cannot be selected at all.

Could you confirm that my approach to reproduction this problem is correct? Maybe I missed something?

Browser: Chrome 59
OS: MacOS
CKEditor version: 4.7.1
plugins: full-all

**Comment by plblum** [comment]
I am now using Chrome 59 and see the same problem using my original test steps.
In step 2, I typed "abc" into the first cell and "def" into the second cell.
I moved the insertion point after "abc" and used Ctrl+V to paste the image.
The image becomes selected with the blue frame that is used by widgets.
I click in "def" and the insertion point appears there but the blue frame remains around the image.
Type "g" and you expect "g" to appear as part of "def". However, nothing happens.

Another variation.
In step 2, only type "def" into the second cell and leave the first cell empty.
Click in the first cell and type Ctrl+V to paste the image.
Now try to select the image by clicking on it. It never gets the blue frame. I cannot select it and I cannot put an insertion point next to it to type in more text in the first cell.

I plan on installing 4.7.1 into my app today. Hopefully the page with the demo is already running that version.

**Comment by msamsel** [comment]
Hi,

thank you for better description. I was able to reproduce this situation here: https://codepen.io/msamsel/pen/BZrXxj?editors=1010.
Info to reproduce it in my example:
1. Select image in table to have blue border around it
1. Click into 2nd cell, to put carer in it
1. Start typing

Result:
Selection is kept on previously selected image even though caret is visible in another place. You cannot type in it.

**Comment by msamsel** [comment]
This issue: #520 might be related to this one.
