### ISSUE TITLE
Typo in language file

### ISSUE THREAD

**Issue by bell87** [ckeditor/ckeditor-dev#526]
Bug

Typo in en-gb.js lang file `confirmCancel` string.
`dialogue` should be `dialog`

 https://github.com/ckeditor/ckeditor-dev/blob/master/lang/en-gb.js#L67

**Comment by beatadelura** [comment]
@bell87 In my knowledge, the word `dialog` is typically used in American English. While `dialogue` is the preferred spelling in American and British English :)

I found more about it here:

https://en.oxforddictionaries.com/definition/dialog_box
http://writingexplained.org/dialog-vs-dialogue-difference

@AnnaTomanek Could you express your opinion?

**Comment by AnnaTomanek** [comment]
Hi Andrew,

thanks for looking into this. In general, all localization matters are handled directly through [CKEditor UI Translation Center](https://www.transifex.com/projects/p/ckeditor/) at Transifex. The localizations are provided by the community (we only maintain a few that we have native speakers for), so whatever is there, comes from particular language teams (and is sometimes a matter of some heated debates :D).

In any case, we would very much appreciate if you joined the British English team there, and had a look at the `en-gb` translations. Feel free to correct anything you find off, your help will be much appreciated!

Thanks again!
