### ISSUE TITLE
Android support with version 4.7

### ISSUE THREAD

**Issue by pgscannell** [ckeditor/ckeditor-dev#529]
## Are you reporting a feature or a bug?

Bug:  I thought that version 4.7 was supposed to support the use of Android smart phones?  My code fails on this: var eDivText    = CKEDITOR.instances.eDiv0.getData();
NOTE:  What I really want is this: 
   for ( x=0; x <= numWinners; x++ )
      {
      sEDIV       = "eDiv" +         x;
      eDivText    = CKEDITOR.instances[ sEDIV ].getData();
      .
      .
      .
      }

## Provide detailed reproduction steps (if any)

1. … This code works fine on a regular PC running Chrome, Firefox, and IE 11.0
2. … I need this ability because many people want to use this website to upload photos from their phones.

### Expected result

*What is the expected result of the above steps?*
The var eDivText should contain the raw contnnts of the CKEditor div.

### Actual result

*What is the actual result of the above steps?*
The code doesn't seem to execute.  I have an alert(); immediately following the call to getData() and it doesn't occur.

## Other details

* Browser: … Chrome.
* OS: … Android
* CKEditor version: … 4.7

* Installed CKEditor plugins: … whatever domes in from the standard install

**Comment by wojtekw92** [comment]
I can not reproduce this bug. On Chrome Mobile 58 everything is working fine. Here you have some example of working getData https://codepen.io/anon/pen/yXpYZP.
