### ISSUE TITLE
Link color goes wrong after changed its color and added words after it

### ISSUE THREAD

**Issue by betseyliu** [ckeditor/ckeditor-dev#531]
## Are you reporting a feature or a bug?
A bug 🐛

## Reference:
https://ppt.baomitu.com/editor#/

## Provide detailed reproduction steps (if any)

1. Open https://codepen.io/mlewand/pen/brmoLr
1. Place the caret at the end of red CKEditor link: `(...) of CKEditor^.`.
1. Type anything.

### Expected result

Typed text gets appended to the existing link.

### Actual result

Font color gets removed from original link. Typed text is not inserted to the link.

## Other details

* Browser: Google Chrome v58.0.3029.110
* OS: macOS Sierra v10.12.4
* CKEditor version: v4.7.0

**Comment by mlewand** [comment]
Interesting, I have a feeling that it's an upstream WebKit issue. And in fact it is, [test it in plain contenteditable](https://codepen.io/mlewand/pen/brmoLr).

All that remains here is to find upstream issue/report it to Chrome and (if it still reproduces in Safar) WebKit teams, leaving the link here.

@msamsel can I ask you to do that?

btw I have added clear repro steps to the original report.

**Comment by msamsel** [comment]
I reported the situation to Chrome and Safari:
- https://bugs.webkit.org/show_bug.cgi?id=176049
- https://bugs.chromium.org/p/chromium/issues/detail?id=759994
