### ISSUE TITLE
Link in About Dialog points to CKEditor 3.x user's guide.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#532]
## Are you reporting a feature or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Open about dialog and click on the "Check CKEditor User's Guide for help."

### Expected result

~User's guide link should point to http://docs.ckeditor.com/#!/guide/dev_features. Also the text should probably be changed.~

Edit by mlewand: There's no need to keep this link any longer. Let's just remove it.

### Actual result

The link in about dialog- "Check CKEditor User's Guide for help." is pointing to http://docs.cksource.com/CKEditor_3.x/Users_Guide

## Other details
* Browser: any
* OS: any
* CKEditor version: 4.0+
* Installed CKEditor plugins: N/A

**Comment by wojtekidd** [comment]
We're getting rid of this line (approved by @wwalc ) however all users who have an older version of CKEditor should be actually redirected somewhere and I wthink the link suggested by @jswiderski makes sense.

**Comment by wwalc** [comment]
Just remove that line. Regarding users with older releases, keep it as is, no redirects or anything like that.

Reasoning: the old link still shows a better users guide for the **end users** than features overview, which has a different target audience.

**Comment by wojtekidd** [comment]
The old link shows me this:
![screen shot 2017-11-15 at 09 25 04](https://user-images.githubusercontent.com/6146254/32825931-e813c41e-c9e6-11e7-9dc8-c08aa715727a.png)

**Comment by msamsel** [comment]
@wojtekidd it was corrected within #1041, so it will work correct with 4.8.0 release.
Take a look at nightly build :) http://nightly.ckeditor.com/17-11-15-07-05/full/samples/

**Comment by wwalc** [comment]
@wojtekidd about which link you were talking about?

![screen shot 2017-11-15 at 12 45 38](https://user-images.githubusercontent.com/545175/32834453-f6cdb818-ca02-11e7-9568-06b9169a65e6.png)

**Comment by wwalc** [comment]
C'mon https://docs.ckeditor.com/ckeditor4/docs/ is not **user's** guide.

**Comment by wwalc** [comment]
@msamsel I just talked with @wojtekidd and hereby confirm that this paragraph with a link to User's Guide should be still removed.

**Comment by msamsel** [comment]
In #1041 I just correct most of the links to use https and do not additionally redirect user. Also change this link to point to CKEditor4 documentation not CKEditor3 as it seems to be wrong.

About `About` plugin I talk with @AnnaTomanek, when I clean up all those URLs, and as far as I remember corrects to this plugin (links, logos, etc stuff) remain to be done with this issue.

**Comment by mlewand** [comment]
So we decided we're not going to keep this link in the dialog and we'll just remove it.
