### ISSUE TITLE
First alteration of a text after pasting (ctrl+v) does not trigger 'change' event

### ISSUE THREAD

**Issue by dryzhkov** [ckeditor/ckeditor-dev#554]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/13763

**EDIT:** We have quite a few issue related to change event handling. 
a. I believe 3 below are all duplicates or are very close to each other and one fix could handle all 3 of them
https://dev.ckeditor.com/ticket/13763
https://dev.ckeditor.com/ticket/14675
https://dev.ckeditor.com/ticket/13005
b. When implementing the solution, it would probably be best to create in a way that it allows fixing below issues in the future:
https://dev.ckeditor.com/ticket/13235
https://dev.ckeditor.com/ticket/14329
https://dev.ckeditor.com/ticket/14386
c. There is also a pull request which is panned to be reviewed for CKEditor 4.7.2 - https://github.com/ckeditor/ckeditor-dev/pull/308

## Provide detailed reproduction steps (if any)

1. Paste text into the editor (ctrl +v).
2. Select text.
3. Press delete / backspace.

### Expected result

Change event should be fired as the content of the editor is changed.

### Actual result

Change event is not fired.

## Other details

* Browser: All
* OS: Windows / MacOS
* CKEditor version: 4.5.0 - Repro on (http://ckeditor.com/features)

**Comment by msamsel** [comment]
Hi

I tested it on `4.6.0`, `4.6.1`, `4.6.2`, `4.7.0`, `4.7.1`. It worked fine on every version. I was able to attach my function on `change` event which was fired on <kbd>Delete</kbd> and <kbd>Backspace</kbd> pressing.
You can check my example under this link.
https://codepen.io/msamsel/pen/owpVBy?editors=1011

Browser: Chrome 59
OS: MacOs
Plugins: Full-all
CKEditor version: 4.6.0 - 4.7.1

Can you check if the problem occurs in your case?

**Comment by dryzhkov** [comment]
Can you try pasting text into the editor using ctrl-v in step #1? It appears if the text is typed in it works as expected but not when its pasted. Thanks

**Comment by f1ames** [comment]
This is a known issue http://dev.ckeditor.com/ticket/13763 (_First alteration to text after it is pasted in (ctrl+v) does not trigger 'change' event_), but it happens only after paste, could you confirm that it is your case @dryzhkov?

**Comment by msamsel** [comment]
I can confirm that. When text is pasting `change` event is missing.

**Comment by dryzhkov** [comment]
Yep. Thats exactly what I am seeing. Looks like original bug was filed about 2 years ago.

**Comment by f1ames** [comment]
Thanks for confirming @dryzhkov. I altered issue title and description a little so it better describes the issue.

**Comment by mlewand** [comment]
@wojtekw92 please check what can be done about it.
