### ISSUE TITLE
Firefox: XSS on double-clicking Flash object

### ISSUE THREAD

**Issue by Daxx909** [ckeditor/ckeditor-dev#556]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None found

## Provide detailed reproduction steps (if any)

1. Use Firefox with Flash plugin installed
2. Open nightly full editor: http://nightly.ckeditor.com/17-06-23-06-08/full/samples/
3. Put in source: `<embed src="javascript:alert(document.domain)" type="application/x-shockwave-flash"></embed>`
4. Double-click Flash object

### Expected result

Should not execute the javascript code

### Actual result

Executes the javascript code, enabling XSS attack

## Other details

* Browser: Firefox 54.0 with Flash plugin
* OS: Windows 10
* CKEditor version: 4.7.0
* Installed CKEditor plugins: flash

**Comment by mlewand** [comment]
Thank you for the report. We'll investigate your report.

Meanwhile I'll close this issue, as we're asking for sending security reports through [our contact form](http://cksource.com/contact). Actually information about this was missing in our template, so sorry for that.

**Comment by mlewand** [comment]
Removed original description.
