### ISSUE TITLE
Greek, Armenian and other numbered list styles not displayed

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#559]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

While browsing numbered list style plugin I have found a [bunch of unused list styles](https://github.com/ckeditor/ckeditor-dev/blob/6a9b227/plugins/liststyle/dialogs/liststyle.js#L94-L101). The thing is that `Array.concat` doesn't add them to the context array, but returns instead.

After changing it in a way it should be so:

```
if ( !CKEDITOR.env.ie || CKEDITOR.env.version > 7 ) {
	listStyleOptions = listStyleOptions.concat( [
		[ lang.armenian, 'armenian' ],
		[ lang.decimalLeadingZero, 'decimal-leading-zero' ],
		[ lang.georgian, 'georgian' ],
		[ lang.lowerGreek, 'lower-greek' ]
	] );
}
```

The translations and everything is there in place, it's just that this feature has not been shown for years.

![Custom ordered list types](https://i.imgur.com/iURyEBQ.png)

The thing to ask here is whether we want to include it, or do we want to completely remove it.

I checked our old [Trac](http://dev.ckeditor.com) and it did not include any tickets requesting for this feature, so I say it's useless and can be safely removed not to bloat the editor.

**Comment by jacekbogdanski** [comment]
There is still no tickets requesting this feature, so I think we can safely remove this hidden feature from CKEditor.
