### ISSUE TITLE
Hyperlinks automatically adding our intranet domain in front of intended destination.

### ISSUE THREAD

**Issue by nctomba** [ckeditor/ckeditor-dev#560]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Use the hyperlink button to attach a link to text.
2. Submit the form to our database for viewing in our intranet.

### Expected result

When viewing the form, we should see a clickable link that takes us to the domain we specified with the link tool.

### Actual result

The link automatically adds our intranet domain before the intended destination. For example, let's say I want to link to http://www.google.com/ and I want to attach it to the word "here." I use the link tool and set the destination to http://www.google.com/ and submit the form. I checked the HTML source code and the link appears to be correct. It looks like this: \<a target="_blank" href="http://www.google.com/">here</a\>. I'm expecting the word "here" to be a link to google.com, however, when hosting the form on our server, the link looks like this: [OUR INTRANET SERVER]/http://www.google.com/. When clicking this link, it redirects us to an error page as this page does not exist.

I have found a weird workaround for this. I notice that if I view the HTML source code and change the double quotes inside the anchor tags to single quotes and then submit the form, the links work as expected. However, if I change the double quotes to single quotes and switch it back to text mode, when switching it back to source mode again, I find that all the single quotes within the anchor tags have been automatically replaced by double quotes, which will make the links not work again. So the only workaround right now is to finish editing our form, switch to source mode and change all the double quotes within the anchor tags to single quotes and then submit the form. If we need to go back and update the form, as soon as we edit the form, all of our single quotes have returned to double quotes and we must repeat the process to get the links to work as intended again.

## Other details

* Browser: Internet Explorer 11, Google Chrome
* OS: Windows 7
* CKEditor version: 4.7
* Installed CKEditor plugins: Full Package Plugins

**Comment by msamsel** [comment]
Hi,

could you provide some step by step guide how to reproduce this error?
I tried myself to get such situation but I wasn't able to find it. You can check my test environment here: https://codepen.io/msamsel/pen/owEyLx?editors=1010

Maybe you have some special configuration of the editor or you have some special environment which outside of CKEditor change links? I'll appreciate some code snippet or link to test environment, where problem will be possible to reproduce.

**Comment by beatadelura** [comment]
@nctomba It's been a while and we didn't get any information from you so I'm closing this issue.

**Comment by maggie192** [comment]
Hi 
I got the same issue as nctomba. May I know how could I fix this issue?
Thanks!!
