### ISSUE TITLE
CKEditor Changes Table Style and Border

### ISSUE THREAD

**Issue by tomsuchy** [ckeditor/ckeditor-dev#566]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Not Found

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/standardpreset.html
2. Edit &lt;table&gt; tag in "Source" view - edit to resemble the below:

    &lt;table align="right" border="0" cellpadding="5" cellspacing="0" style="border: 0px solid #000000;"&gt;

3. Switch to WYSIWYG view; it has a border.
4. Switch back to code view: It is now:

    &lt;table align="right" border="1" cellpadding="5" cellspacing="0"&gt;

### Expected result

It shouldn't put any border, since no border is requested.

### Actual result

It thinks a border was requested and sets border="1"

## Other details

* Browser: Chrome 59 @ Linux, Mac, Windows; Edge
* OS: Linux, Mac, Windows
* Installed CKEditor plugins: standard presets

## Comments

First time bug-poster, long-time user!

Behavior is the same in the nightly build standard editor.

This can be worked-around by breaking the border: tag apart into border-color, border-style, and border-width, which then doesn't change the border attribute.

**Comment by mlewand** [comment]
AFAICS any value of `border` property (even 0px) results with setting a border to 1. Definitely an issue.

**Comment by mlewand** [comment]
Also confirmed with edge so it's a cross browser, will add this information in original details. The for all of this is a [simplified transformation](https://github.com/ckeditor/ckeditor-dev/blob/6a9b227/plugins/table/plugin.js#L29-L41) in the table plugin.

**Comment by larsinsd** [comment]
Has this been fixed with 4.7.1?

**Comment by f1ames** [comment]
@larsinsd We are targeting CKEditor 4.7.3, the fix was just merged to `master` branch so you can be sure it will be included in the next release.
