### ISSUE TITLE
Undo event slow in CKeditor

### ISSUE THREAD

**Issue by sakthisudhan82** [ckeditor/ckeditor-dev#567]
I have faced in CKEditor slow response when we triggered undo event, if more than 1000 paragraphs in mozilla firefox browser

**Comment by f1ames** [comment]
Hello @sakthisudhan82,
could you provide more detailed reproduction steps and information about your environment as asked in the issue template?

**Comment by beatadelura** [comment]
It's been a long time since @sakthisudhan82 created this issue. Because there is no answer, I'm closing it.
