### ISSUE TITLE
Fontawesome icons removed after save

### ISSUE THREAD

**Issue by gmanolache** [ckeditor/ckeditor-dev#570]
## Are you reporting a feature or a bug?
BUG

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

No duplicate

## Provide detailed reproduction steps (if any)

1. Add the fontawsome library to the page
2. Go to the SDK demo page and click on source
3. Add the fontawesome icon tag: `<i class="fa fa-rocket" aria-hidden="true"></i>`
4. Preview the page and notice the image appears
5. Go back to source and modify
6. Notice that the icon tag is replaced

### Expected result

*What is the expected result of the above steps?*
The fontawesome style should be saved and persisted

### Actual result

*What is the actual result of the above steps?*
The fontawsome style is not persisted

## Other details

* Browser: All
* OS: Linux/Windows/Mac
* CKEditor version: 4.4.8, 4.7

**Comment by msamsel** [comment]
Hi,

I think it's not an issue but more question: how to configure CKEditor to have possibility of inserting fontawesome.
You're description is reminiscent to behaviour of ACF. Please read how our content filtering works: http://docs.ckeditor.com/#!/guide/dev_acf. It should help in this case. :)
