### ISSUE TITLE
CKEditor not loading using RSA token authentication

### ISSUE THREAD

**Issue by divintrish** [ckeditor/ckeditor-dev#574]
## Are you reporting a feature or a bug?

Bug
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*
No reference related to this
## Provide detailed reproduction steps (if any)

1. User is connected through RSA Token
2. The URL and even the contents of the HTML file gets changed like DANA
3. …

### Expected result

*What is the expected result of the above steps?*
Load the CKEditor
### Actual result

*What is the actual result of the above steps?*
Not loading the CKEditor at all
## Other details

* Browser: IE8,9,10,11 and Chrome
* OS: Windows 7
* CKEditor version: CKEditor 4.6
* Installed CKEditor plugins:pastefromexcel

**Comment by wojtekw92** [comment]
Hi,
Can you say more about your configuration? From what server are you adding editor, what server software are you using? Did you try to check this issue on the last version of CKEditor?

**Comment by beatadelura** [comment]
@divintrish It's been a while and we didn't get any information from you so I'm closing this issue.
