### ISSUE TITLE
Removing table columns throw an error

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#577]
## Are you reporting a feature or a bug?

Bug

### Case 1
1. Open http://sdk.ckeditor.com/samples/table.html
2. Select whole 2013 section inside the table (see screenshot below)
3. Right click inside the selection and choose "Column"→"Delete Columns"

<img width="835" alt="Example of selected columns" src="https://user-images.githubusercontent.com/1078728/27682696-da816eea-5cc3-11e7-89db-5ab28e508af4.png">

#### Expected result

Columns are deleted.

#### Actual result

Columns are not deleted and the error is thrown:

> ckeditor.js:66 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

### Case 2
1. Open http://sdk.ckeditor.com/samples/table.html
2. Select 2013 section without the header inside the table (see screenshot below)
3. Right click inside the selection and choose "Column"→"Delete Columns"

<img width="839" alt="Example of selected columns" src="https://user-images.githubusercontent.com/1078728/27682867-70e8f9ca-5cc4-11e7-9766-24f4b62cbb77.png">

#### Expected result

Columns are deleted.

#### Actual result

Columns are deleted, but the error is thrown:

> ckeditor.js:66 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

Additionally selection is put inside incorrect cell (see screenshot below).

<img width="842" alt="Incorrect position of cursor" src="https://user-images.githubusercontent.com/1078728/27682904-90d6db26-5cc4-11e7-8ee4-89464696d9be.png">

## Other details

* CKEditor version: 4.7.0

**Comment by msamsel** [comment]
During testing this issue I found additional case: #648
