### ISSUE TITLE
Img tag is stripped when advanced content filter is enabled

### ISSUE THREAD

**Issue by radpet** [ckeditor/ckeditor-dev#578]
Question

Hi,
I am using ckeditor version 4.7 and I have recently enabled the advanced content filter option and set it to allow all content by using the provided in the documentation code snippet 
` $0: {
            // Use the ability to specify elements as an object.
            elements: CKEDITOR.dtd,
            attributes: true,
            styles: true,
            classes: true
          }`

However when I use the editor#setData all content is inserted except img tags. I have enabled image plugin and when I run the check for enabled img tag it returns true. The images are shown if I disable the acf by using `allowedContent :true`. I don't have any custom filters rules and I have not included any 
3rd party plugins that might add some.

Would please give me clues why this happens ? Thanks in advance !

**Comment by wojtekw92** [comment]
Hi,
Github issues are used by us only for bugs and features. More about this you can find [here](http://docs.ckeditor.com/#!/guide/dev_howtos_bugs_and_features). All questions about editor and configuration should go to stackoverflow. So feel free to ask [there](https://stackoverflow.com/questions/tagged/ckeditor).
