### ISSUE TITLE
Unwanted "cke_table-faked-selection-table" class in table properties dialog box

### ISSUE THREAD

**Issue by smartcorestudio** [ckeditor/ckeditor-dev#579]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Select some cells in the table. For example you can use table from this page: http://sdk.ckeditor.com/samples/fullpreset.html
2. Go to the 2nd tab in the "Table properties" dialog box

### Expected result

In the "CSS classes" input field you should see only actual classes, not the virtual ones. In this particular case the field should be empty

### Actual result

In the "CSS classes" input field you'll see "cke_table-faked-selection-table". It can confuse some users

## Other details

* Browser: Firefox
* OS: Windows
* CKEditor version: 4.7.0 at least
* Installed CKEditor plugins: advanced tab, table selection

![2017-06-29 14_05_28-ckeditor sdk samples full preset](https://user-images.githubusercontent.com/2891792/27685127-8025248e-5cd5-11e7-9abc-b217b9a8a184.png)

**Comment by mlewand** [comment]
A trivial fix is just to use `data-` attribute, and apply styling using this attribute. 🙂
