### ISSUE TITLE
Fonts setting should not be toggling options

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#584]
## Are you reporting a feature or a bug?

Feature request

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/16865

## Provide detailed reproduction steps (if any)

1. Change the font size for the first time it works correctly.
2. But if select the same font size again, it will revert back to the original font size. The same for font style.
3. This behavior doesn't conform to other main editors, and could bring problems. 

### Expected result

Please prevent revert font back to original font if select same font again.

### Actual result

Resetting the font to original font if select font again.

## Additional Information

To provide a possibility to remove the font all the way. It was specified in [the comment below](https://github.com/ckeditor/ckeditor-dev/issues/584#issuecomment-313076114).

**Comment by mlewand** [comment]
While fixing this we need to preserve the old functionality, I mean being able to remove the font setting. It can be done by adding an extra option like `<unset>` at the beginning.

I'm not sure though how it will feel for the most users, so we should discuss this part.

**Comment by mlewand** [comment]
OK as for removing the font, let's simply add a "Default" entry at the beginning of the dropdown. 

## Default Option Visibility

This entry should not be displayed if there's no font selected.

![Default is hidden when no size is used](https://i.imgur.com/JmK6CPh.png)

But it should be visible when the font size is selected.

![Default is visible a font size is used](https://i.imgur.com/CBW5fVy.png)

## [Discussion] Default Option Visuals

I think it would be a nice addition to make it somehow visually distuingishable, just because how it looks in case of font dropdown:

![Default option in font dropdown](https://i.imgur.com/tQB96Ax.png)

I feel like marking it with italics or sth like that would improve it, and indicate a special function of this option.

**Comment by fredck** [comment]
+1, with remarks

> Default Option Visibility
> This entry should not be displayed if there's no font selected.

This is a UX and accessibility issue. Ideally, the default option should be always there and, in the above case, we may consider marking it as the selected one.

> Paragraph format shouldn't get a "Default" option as there already is Paragraph (or Normal (DIV) in case of enter mode div) which serves this role.

+1

**Comment by Reinmar** [comment]
Agree with @fredck. I don't think that the option should disappear.



> I feel like marking it with italics or sth like that would improve it, and indicate a special function of this option.

I'm afraid that this might be slightly confusing in the case of font name dropdown. Is the text italic by default?

I agree that it might be good to mark this option. But, if that's possible, I'd try to avoid styling which may be conflicting with the sense of the dropdown.

**Comment by fredck** [comment]
If anything, a separator could be used, not a different style, in fact. But I don't see this as essential.

**Comment by mlewand** [comment]
> I'm afraid that this might be slightly confusing in the case of font name dropdown. Is the text italic by default?
> 
> I agree that it might be good to mark this option. But, if that's possible, I'd try to avoid styling which may be conflicting with the sense of the dropdown.

Actually per @msamsel suggestion, parenthesis does the magic here neatly. It gives a proper cue, without bloating the dropdown, see:

![Default label](https://i.imgur.com/i8sCqYF.png)

**Comment by mlewand** [comment]
To sum it up:

OK as for removing the font, let's simply add a "Default" entry at the beginning of the dropdown. 

## Default Option Visuals

The "default" option should be visually distinguishable. It should simply be wrapped with parenthesis symbols.

![Default label](https://i.imgur.com/i8sCqYF.png)

## Affected Dropdowns

Dropdown affected by this change should be "Font Name", "Font Size" and "Paragraph Format" but no styles combo.

### Paragraph Format

Paragraph format **shouldn't** get a "Default" option as there already is Paragraph (or Normal (DIV) in case of enter mode div) which serves this role.

### Styles Combo

This dropdown is a typical multiple choice combo so it should not be affected by this change.

**Comment by msamsel** [comment]
@mlewand should be there some config option which preserve _old_ behave of those drop down lists? And if yes then which behave should be default one _old_ or _new_?

**Comment by mlewand** [comment]
@msamsel I was mentioning config option some time ago, however I think that we will go without an option, and wait for users feedback. If our community will want to be able to disable it, we'll quickly add it in the upcoming minor release.

**Comment by f1ames** [comment]
Fixed with #615 (https://github.com/ckeditor/ckeditor-dev/commit/ef464eca090adad6e325be0741dbfbec710db5ce).
