### ISSUE TITLE
Boolean Attributes (like required) not correctly recognized by form dialogs

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#586]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/14291

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/fullpreset.html.
1. Open Source mode and replace content with `<input checked required type="checkbox" />`.
1. Switch back to WYSIWYG mode.
1. Double click on checkbox to open dialog.

### Expected result

Dialog should show that the input is required (**required** option checked).

### Actual result

The **required** option is not checked.

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.7.1
* Installed CKEditor plugins: Full preset

The cause of the issue is described here http://dev.ckeditor.com/ticket/14291#comment:2.

**Comment by Comandeer** [comment]
Merged into 4.10.2 branch.

**Comment by mlewand** [comment]
Note that you can already have a peek at the working solution in our [nightly preview](https://ckeditor4-preview.ckeditor.com/next/samples/index.html) 😉
