### ISSUE TITLE
Check for potential memory leaks 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#589]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)
* https://dev.ckeditor.com/ticket/16869
* https://dev.ckeditor.com/ticket/12307
* http://dev.ckeditor.com/ticket/11010
* http://dev.ckeditor.com/ticket/13123

## Provide detailed reproduction steps (if any)

1. Open AJAX sample in Chrome with dev tools enabled and set to memory tab
2. Create editor and take a memory snapshot.
3. Destroy editor and take memory snapshot
4. Repeat steps 2 & 3 few times

### Expected result

Everything or almost everything is released.

**NOTE:** From what I remember getData should work after destroying the editor and should return actual editor data (I don't remember what was the exact reason behind it though).

### Actual result

There are a lot of DOM objects being left behind.

* Browser: Any
* OS: Any
* CKEditor version: at least from 3.0
* Installed CKEditor plugins: N/A

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/20caee9f792369d38f961ffbc045dbab66ae2eb1.
