### ISSUE TITLE
Insert Column before and After fails if a cell vertical split exist

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#591]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/13729 (see also https://github.com/ckeditor/ckeditor-sdk/issues/164#issue-104653533).

## Provide detailed reproduction steps (if any)

1. Created a table with 4 columns and 3 rows.
1. Make a vertical split in the cell 2,2.
1. Do a column insert before in 4th column.

### Expected result
A new column is inserted between 3rd and 4th column.

### Actual result 
A new column will be created between 2nd and 3rd column.

## Other details

* Browser: All
* OS: All
* CKEditor version: 3.5.1 (reproduced in 4.7.1)
* Installed CKEditor plugins: Full

**Comment by mlewand** [comment]
@f1ames can you check say 4.6.0, 4.4.5 to see if it's a regression or not?

**Comment by f1ames** [comment]
@mlewand It was already checked by @jswiderski in http://dev.ckeditor.com/ticket/13729. I put this information in **Other details**:
> CKEditor version: 3.5.1 (reproduced in 4.7.1)

**Comment by f1ames** [comment]
@mlewand Unless you meant it was fixed in 4.6.0 and then broken again. I will check 4.6.0 (it was reported in 4.5.3 so there is no point in checking earlier as it was already done).

**Comment by f1ames** [comment]
Also reproducible in 4.6.0 so it does not look like a regression.

**Comment by f1ames** [comment]
Closed with #592 (https://github.com/ckeditor/ckeditor-dev/commit/fc149eeb4b92ba9ea64c6becee9e0ddff906097f).
