### ISSUE TITLE
instance.element is undefined

### ISSUE THREAD

**Issue by lessonsharing** [ckeditor/ckeditor-dev#593]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. CKEDITOR.replace( ... )
2. Open JS console
3. function getEditor(bool) say: "instance.element is undefined ..."

### Expected result

N/A

### Actual result

Code crash.

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.7.1
* Installed CKEditor plugins: Full

# Path
```javascript
getEditor: function( optimized ) {
	var instances = CKEDITOR.instances,
		name, instance, editable;

	optimized = optimized || optimized === undefined;

	for ( name in instances ) {
		instance = instances[ name ];

		// Continue only if instance.element is present.
		// fix: #593
		if (undefined !== instance.element) {
			if ( instance.element.equals( this ) && instance.elementMode != CKEDITOR.ELEMENT_MODE_APPENDTO )
				return instance;

			if ( !optimized ) {
				editable = instance.editable();

				if ( editable && ( editable.equals( this ) || editable.contains( this ) ) ) {
					return instance;
				}
			}
		}
	}

	return null;
}
```

**Comment by mlewand** [comment]
Can't reproduce the case, see https://codepen.io/mlewand/pen/RgJBex?editors=1010#0

More precise steps, or a working demo would be greatly appreciated.

**Comment by lessonsharing** [comment]
Hello,

If you try:

```javascript
Object.prototype.MyFunc = function() {
	return 1;
};

var element = CKEDITOR.document.findOne( 'textarea' );

CKEDITOR.replace( element );

console.log( element.getEditor( false ) );
console.log( element.getEditor() );
```

You will see an error in your console.

**Comment by mlewand** [comment]
We do not support environment with modified prototypes of core types.

Consider changing your other logic, so that it does not rely on that fact as this is an anti pattern.

**Comment by lessonsharing** [comment]
Ok, thank you.
