### ISSUE TITLE
Whitespace in CKEditor is changing the cursor focus

### ISSUE THREAD

**Issue by binodpaikaray** [ckeditor/ckeditor-dev#596]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)
**In Track Change mode:**

- Space is added but cursor is not moved.
- On adding another space or typing the text at the end of the line, cursor is added to the beginning of the line.

**In non track change mode:**

- Space is added but cursor is not moved.
- On adding another space, cursor moves and adds space before and after the cursor.
- On adding another space or typing the text, cursor is added to the beginning of the word (this happens inconsistently when not in track change mode).
- When user tries to add a space after a comma, the cursor moves to the beginning of the previous word.

### Expected result

*What is the expected result of the above steps?*
It should work normally and not move cursor randomly.

### Actual result

*What is the actual result of the above steps?*
It's moving the cursor start of the line or starts the next word without any space.

## Other details

* Browser: Google Chrome (We use this only)
* OS: … Windows 7, Mac OS
* CKEditor version: … 4.6.1
* Installed CKEditor plugins: … CKEditor Tracked Changes, Comments, Autocorrect, pastefromexcel, tableresize, autogrow, etc.

**Comment by binodpaikaray** [comment]
Can someone please help on this?

**Comment by msamsel** [comment]
Hi,

response is similar to #600. Your configuration seems to have not officially supported plugins. Could you check if the problem occurs where only native plugins are used, and if yes, then what steps should I made to reproduce problematic situation? Example editor instance with all plugins: https://codepen.io/msamsel/pen/RgJxZq?editors=1010

**Comment by msamsel** [comment]
I close this issue with the same comment as in #600.

> If you check plugins listed here: http://ckeditor.com/addons/plugins/all you can find out who is author of which plugin. We can help with plugins developed by CKSource. In case of plugins which was created by someone else you need to contact with proper author.
> 
> In previous comment I gave you link to example where preset full-all was used, which contains all plugins developed by CKSource. Unfortunately, if problem cannot be reproduced with our plugins, then this issue should be direct to different author.
