### ISSUE TITLE
word-wrap and word-break property is getting removed in IE if we switch from Preview view to Source code view

### ISSUE THREAD

**Issue by vinaydhakre** [ckeditor/ckeditor-dev#598]
## Are you reporting a feature or a bug?
bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. … In IE11 browser, go to Source Code view and paste the following code:
`<div style="left:0; text-align: center; word-wrap: break-word; word-break: break-word">abc</div>`
2. … Switch to preview view and then switch to source code view.
3. …word-wrap and word-break property is getting removed in IE browsers.

### Expected result
`<div style="left:0; text-align: center; word-wrap: break-word; word-break: break-word">abc</div>`

### Actual result
`<div style="left: 0px; text-align: center; -ms-word-wrap: break-word;">abc</div>`

* Browser: … IE 11
* OS: …Windows10,8,7
* CKEditor version: …4.7.1 (Standard)"
* Installed CKEditor plugins: … NA

Please find below the link of demo present in this ticket for your reference:
https://stackoverflow.com/questions/44888062/ie-word-wrap-and-word-break-issue-in-ckeditor

**Comment by vinaydhakre** [comment]
Can someone help me on this?

**Comment by wojtekw92** [comment]
Hi,
It's browser issue. We are not able to do anything with this.
