### ISSUE TITLE
The editing (specially Undo) of tracked changes content leaves back the tool tip data in the content itself

### ISSUE THREAD

**Issue by binodpaikaray** [ckeditor/ckeditor-dev#600]
## Are you reporting a feature or a bug?
**Bug**

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

- In the CK editor, enable tracked changes and start typing some text and delete a word. Press Ctrl+Z (undo action).
- A tool tip text gets stayed back in the content as residue

### Expected result

*What is the expected result of the above steps?*
It should not leave any tooltip content as permanent content and should be visible only on mouse hover on the tracked change content.

### Actual result

*What is the actual result of the above steps?*
The above action leaves the tooltip content back permanently in the content.

## Other details

* Browser: Google Chrome (we support only this one)
* OS: Windows 7, Mac OS
* CKEditor version: 4.6.1
* Installed CKEditor plugins: CKEditor Tracked Changes, Comments, Autocorrect, pastefromexcel, tableresize, autogrow, etc.

**Comment by binodpaikaray** [comment]
Can someone please help on this?

**Comment by msamsel** [comment]
Hi,

your description is not clear for me. It seems that described problem is related to some community plugin, not available directly in full package of editor.
Can you confirm that problem exist also here: https://codepen.io/msamsel/pen/RgJxZq?editors=1010. And if yes, then what kind of steps should I made to reproduce the issue? This package contains all plugins available with CKEditor and supported by us.

**Comment by binodpaikaray** [comment]
Hello,

Don't you support LITE plugin for tracked changes? I couldn't see any tool for that in the given URL to test it.

**Comment by msamsel** [comment]
If you check plugins listed here: http://ckeditor.com/addons/plugins/all you can find out who is author of which plugin. We can help with plugins developed by CKSource. In case of plugins which was created by someone else you need to contact with proper author.

In previous comment I gave you link to example where preset `full-all` was used, which contains all plugins developed by CKSource. Unfortunately, if problem cannot be reproduced with our plugins, then this issue should be direct to different author.
