### ISSUE TITLE
[iOS Safari] Selection issues while typing

### ISSUE THREAD

**Issue by minaseem** [ckeditor/ckeditor-dev#606]
I am developing an iOS app which integrates ckeditor 4.6.2. I just started testing on iOS 10, seems like ckeditor does not work at all. Whenever i have more than 500 words in a document,the following issues occur:

- Focus keeps on switching between caret current position and top of page. Sometimes caret is also moved to the top of page while i am typing.
- Touch event does not work when document is long, so i cannot start typing.
- Cannot scroll my content -- happens randomly.
- While scrolling content from top to bottom caret moves with the scrollbar, but caret moves back to its actual position on scroll end.

I have tested on nightly build 4.7.1 also. Issues can be reproduced in that build also. Any ideas on the fix? 

This bug has already been reported https://dev.ckeditor.com/ticket/12457 and there is no update since long. Can you guys update on this?

**Comment by msamsel** [comment]
Hi,
it seems to be this same problem as reported here: #498.
