### ISSUE TITLE
Remove 'tc' tag from manual tests

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#608]
## Are you reporting a feature or a bug?

Task

## Provide detailed reproduction steps (if any)

We are switching from `tc` tag to `bug`/`feature` tags in manual tests. All `tc` tags should be removed.

We could replace existing `tc` tags with `bug`/`feature` tag, but I am not sure how to distinguish which one should be used when replacing. WDYT @mlewand @Comandeer ?

**Comment by mlewand** [comment]
It's easy to tell the type of test when you start the work on a ticket. However for existing manual tests it doesn't make sense to go though all tests and manually verify whether it should be marked as `bug` or a `feature`.

It doesn't make sense to keep `tc` tag hanging either, as such I'd say that for all the old tickets we should just put `bug` for simplicity sake.
