### ISSUE TITLE
Caret disappear on touch devices in IE

### ISSUE THREAD

**Issue by drazenp** [ckeditor/ckeditor-dev#614]
Bug: This issue is happening only on touch devices while taping on ckeditor. The issue is happening in IE11, but it's working fine in Chrome. Tested on Windows 8.1. If using mouse instead of tapping everything is working fine.

On table cell focus a ckeditor is placed inside div element and added in table cell. The caret is placed at the end of text. If tapped on empty part of the cell, the caret will show up and shortly after disappear. If tapped on text inside the ckeditor the caret will not disappear.

*An example on [link](http://plnkr.co/edit/xwBzBdWWYVRTCWiqN1N6?p=preview)*

## Steps

1. Open link above and run example
2. Tap on empty places inside the cells

### Expected result

*On the first tap should be possible to add data.*

### Actual result

*The cursor is not displayed in the cell and no data is entered when using the keyboard inputs.
(NOTE: By clicking on the cell for a 2nd time you will be able to add data)
(NOTE: Enter key will work)*

## Other details

* Browser: IE11.0.9600.18205
* OS: Windows 8.1
* CKEditor version: 4.6.2 basic
* Installed CKEditor plugins: None

**Comment by beatadelura** [comment]
Hi @drazenp, thank you for creating an issue. Unfortunately, we don't support IE11 browser on touch devices. [Here](http://docs.ckeditor.com/#!/guide/dev_browsers) you can find more information about CKEditor 4 browser support.
