### ISSUE TITLE
Not possible to enter text after selecting dropdowns - Touch device

### ISSUE THREAD

**Issue by drazenp** [ckeditor/ckeditor-dev#618]
Bug

*It's reproachable on the official [website](http://ckeditor.com/)*

## Provide detailed reproduction steps (if any)

1. Open the page form the link above.
2. Set cursor inside text (tap in text).
3. Select one of the drop-downs from toolbar (styles, fonts,...)
4. Try to continue typing.

### Expected result

*Should be able to continue writing with newly applied styles.*

### Actual result

*Nothing happening.
NOTE: Enter key is working. Backspace key will not delete text, but do go page back.*

## Other details
It's working in Chrome.

* Browser: IE11
* OS: Windows 8.1
* CKEditor version: 4.7.1
* Installed CKEditor plugins:

**Comment by beatadelura** [comment]
Hi @drazenp, thank you for creating an issue. Unfortunately, we don't support IE11 browser on touch devices. [Here](http://docs.ckeditor.com/#!/guide/dev_browsers) you can find more information about CKEditor 4 browser support.
