### ISSUE TITLE
Editor view scrolls automatically when start typing on iphone

### ISSUE THREAD

**Issue by klasver** [ckeditor/ckeditor-dev#623]
When the editor has an content height of 100px on a iPhone and we have that much content so a vertical scroll will appear. The view automatically starts to scroll when you on blur the editor, focus again, scroll to the very first line in top of the editor and start typing.

## Provide detailed reproduction steps (if any)

1. 100px height CKeditor
2. Open on iPhone with Safari
3. Add content so a verical scrollbar will appear
4. onBlur, focus on the content input again
5. Scroll to the top
6. Start typing

### Expected result

Shouldn't try to auto scroll to a position on it's own.

### Actual result

Scrolls away from it's position and user isn't able to see the cursor anymore nor what he's typing.

## Other details

Browser: Safari
OS: iPhone OS
CKEditor version: 4.7

**Comment by beatadelura** [comment]
@klasver It's a duplication of #498 so I'm closing this issue.
