### ISSUE TITLE
Picture upload problem

### ISSUE THREAD

**Issue by luocong2016** [ckeditor/ckeditor-dev#626]
## Picture upload problem

Callback after uploading pictures？

**Comment by wojtekw92** [comment]
Hi,
Github issues are used by us only for bugs and features. More about this you can find [here](http://docs.ckeditor.com/#!/guide/dev_howtos_bugs_and_features). All questions about editor and configuration should go to stackoverflow. So feel free to ask [there](https://stackoverflow.com/questions/tagged/ckeditor).
