### ISSUE TITLE
Memo acting Differently when pasting or scrolling 

### ISSUE THREAD

**Issue by kalesb** [ckeditor/ckeditor-dev#635]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Closing as there is no information provided in the issue.
