### ISSUE TITLE
Plugin TableTools in combination with inline editor breaks out of editable element

### ISSUE THREAD

**Issue by b2m** [ckeditor/ckeditor-dev#640]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

* https://dev.ckeditor.com/ticket/16796

## Provide detailed reproduction steps (if any)

1. Use inline editor with plugin tabletools **in** a table.
1. Use the editor tools to insert a table with `TH` (both in rows and columns).
1. Use the context menue on the leftmost column to add another column on the left.

Sample HTML structure after step 2:

```html
<table>
  <tbody>
    <tr>
      <td>
        <div id="editor1" contenteditable="true">
          <table border="1" cellspacing="1" cellpadding="1" style="width: 500px;">
            <thead>
              <tr>
                <th scope="row"><br></th>
                <th scope="col"><br></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row"><br></th>
                <td><br></td>
              </tr>
            </tbody>
          </table>
        </div>
      </td>
    </tr>
  </tbody>
</table>
```

### Expected result

There should be another column before the `TH` column (**in** the editable area).

### Actual result

There is another column **outside** the editable area.

## Other details

This problem is independent of browser type and os.

This problem applies to other settings also. For example the alignment of a `TH` cell is instead set on the first `TD` cell **outside** the editor.

The cause of the problem is that the **tabletools** plugin does not stop at the "root" node of the editor when searching for `var nearestCell` and `var parent`.

**Comment by msamsel** [comment]
It seems that problem doesn't exists since 4.7.0.
Can you confirm that?
https://codepen.io/msamsel/pen/PjVmMx
