### ISSUE TITLE
extractContents returns incorrect result when multiple nodes are selected

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#644]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/14256

## Provide detailed reproduction steps (if any)

Please try this codepen: https://codepen.io/anon/pen/MoZOPE

1. Clear editor contents and type "This is some sample text"
2. "This is some [sample text]" - apply marker yellow to given selection
3. "This is [some sample text]" - apply bold to given selection
4. "[This is some sample text]" - apply below code in browser console to given selection

```
var currentRange = CKEDITOR.instances.editor1.getSelection().getRanges()[0];
console.log(currentRange.extractContents().getHtml());
```
### Expected result

`This is <strong>some <span class="marker">sample text</span></strong> `

### Actual result
`This is <strong><span class="marker">sample text</span>some </strong>`

## Other details

* Browser: Any
* OS: Any
* CKEditor version: CKEditor 4.5.0+
* Installed CKEditor plugins: N/A

**Comment by Comandeer** [comment]
It seems that this fix eliminates also [pretty nasty bug in lists](https://dev.ckeditor.com/ticket/13842).

**Comment by mlewand** [comment]
> It seems that this fix eliminates also pretty nasty bug in lists.

It has _improved this TC partially_ but it does not fix it yet. I'll post it as a separate issue on GH.
