### ISSUE TITLE
HTML uses inline CSS instead of custom element in Chrome

### ISSUE THREAD

**Issue by djdenv** [ckeditor/ckeditor-dev#645]
I've developed a simple plugin that adds a button to outline text. The element must be a tag that is not in the DTD (i.e. `<o>`). Even when added to the DTD, CKEDITOR creates unexpected HTML after the styled text is created, delete and then recreated. 

### Steps to Reproduce
I've created a JSFiddle to simulate the behavior. https://jsfiddle.net/djdenv/tquffnre/5/

1. Once you open the fiddle, use the blank button to start the outlining. 
2. Type a few characters. Using the browsers developers tool HTML inspector you'll see the proper `<o>test</o>` HTML.
3. Delete those character so you have nothing
4. Retype new characters. Note the slightly off styling.
5. Use the inspector tool again and you'll see HTML with inline CSS such as below. 

### Expected result
I expected to see `<o>new text</o>` or at least no styling at all.

### Actual result

`<font color="#ffffff"><span style="letter-spacing: 1.6px; -webkit-text-stroke: 0.1px rgb(0, 0, 1);">new text</span></font>`

## Other details

* Browser: CHROME (works as expected in Firefox)
* OS: Mac, probably others.
* CKEditor version: 4.7.1
* Installed CKEditor plugins: basic, plus custom seen in the fiddle.

**Comment by msamsel** [comment]
Hi,
unfortunately problem seems to be in Chrome not in CKEditor.
Please check this example: https://codepen.io/msamsel/pen/VWRaPj
It's regular div with `contenteditable="true"` where `<o>` tag is used. Try to reproduce your steps in it and look for behaviour without any editor.

That's why described problem seems to be Chrome issue not CKEditor.

**Comment by msamsel** [comment]
Reference link to Chrome BUG: https://bugs.chromium.org/p/chromium/issues/detail?id=742896
