### ISSUE TITLE
Delete columns work incorrectly with native selection on Chrome

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#648]
## Are you reporting a feature or a bug?
BUG

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)
Example: https://codepen.io/msamsel/pen/bRZrNV
1. Open editor **without tableselection** plugin in Chrome.
1. Fill some data in table.
1. Put caret in cell which is not in last column. Caret have to be after last character. In example it might after last `D` character.
1. Open context menu.
1. Choose `Column -> Delete Column`

### Expected result
Only one column will be delete. Column where caret is put

### Actual result
2 columns are removed.

### Note:
It seems that Chrome wrongly keep selection range, when collapsed selection is put after last character in table cell. Start node is properly set in current cell, but end node is set up to cell from next column.

## Other details

* Browser: Chrome & Safari
* OS: MacOS
* CKEditor version: 4.7.1
* Installed CKEditor plugins: full-all **without tableselection**

**Comment by Comandeer** [comment]
This issue was fixed as a part of #577.
