### ISSUE TITLE
<a> tag is automatically generated when adding an anchor

### ISSUE THREAD

**Issue by joewardman** [ckeditor/ckeditor-dev#656]
Bug

When adding a target for the anchor tag, the element adds an <a> tag within whatever text / heading we use. As a result the text becomes a hyperlink with blue text and a line underneath. Is it possible to make this feature optional, or is there a piece of code we can comment out to remove this bit of functionality?

## Provide detailed reproduction steps (if any)

1. Highlight a piece of text and click the flag (anchor) button on the WYSIWYG editor.
2. Enter any anchor name and click OK
3. A red flag appears next to the link and the text now appears as a hyperlink. We simply only need the ID attribute (without manually removing the <a> tag) so that it appears as normal.

* IE, Chrome
* CKEditor version: 4.5.11
* Installed CKEditor plugins: Anchor, Link

**Comment by msamsel** [comment]
Hi,
it's a way how anchors work anchors. It takes selection and make link from selected text. Anchor is generated as `<a>` tag. You can also put caret without selection in a place where you would like to insert only flag, this will generate empty anchor.
So I'm not quite sure what you consider as a bug? Can you provide better description what is not working?

**Comment by beatadelura** [comment]
@joewardman It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Comment by Fefaine** [comment]
Actually in XHTML, it's possible to make an anchor on any element, not just on 'a' element
Exemple here https://www.bennadel.com/blog/822-using-body-id-as-a-back-to-top-page-anchor.htm
Therefore it would be nice to have an option to add an id to an html element

**Comment by pthurmond** [comment]
I'm going to vote this up because adding an ID anchor in any type of element has been around for a VERY VERY long time. This absolutely should be how it works.
