### ISSUE TITLE
Email Protected replacing Email. 

### ISSUE THREAD

**Issue by rameezte** [ckeditor/ckeditor-dev#658]
why CKEditor is replacing my emails with [Email Protected] ??? i need to disable it immediately.

**Comment by wojtekw92** [comment]
You should check http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-emailProtection

In the future please use github issues only for bugs/features information. For all questions about CKEditor configuration and implementation please use stackoverflow.

**Comment by rameezte** [comment]
No sir. please tell me exact string which i need to write to disable email protected in text. it is not working.
