### ISSUE TITLE
Pasting images from Word

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#662]
## Are you reporting a feature or a bug?

Feature request

## Provide detailed reproduction steps (if any)

1. Open attached Word document.
2. Select all its content.
3. Paste into CKEditor.

### Expected result

Image is pasted correctly.

### Actual result

Image is not pasted and console shows error:

> Not allowed to load local resource: `file:///[redacted]/clip_image002.png`

There should be a sensible way to detect such images and try to embed them anyway, converting to Blob (see also #505). However I'm not sure how to omit limitation with ability to get access to local files… Maybe try to extract images from RTF representation of pasted Word content?

## Other details

* Browser: Chrome, Firefox
* OS: macOS
* CKEditor version: 4.7.1
* Installed CKEditor plugins: pastefromword

## Attachments

* [Document1.docx](https://github.com/ckeditor/ckeditor-dev/files/1159137/Document1.docx)

**Comment by mlewand** [comment]
Yes, image blobs are extractable from RTF clipboard.

**Comment by bahuma20** [comment]
Works in Internet Explorer

**Comment by mlewand** [comment]
That's correct AFAIR it does work only in IE11 (as it inlines all the images natively). This feature has been reverted in MS Edge though.

**Comment by mlewand** [comment]
Added information on browser compatibility.

**Comment by fikoborquez** [comment]
I have this issue pasting images with text in Chrome but not in Firefox. Can anybody give me some help?

**Comment by JURALOVE** [comment]
Thanks. This hile was my solution ;)
