### ISSUE TITLE
Problem with line heigt

### ISSUE THREAD

**Issue by LutzerFasihi** [ckeditor/ckeditor-dev#665]
## Are you reporting a feature or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

The set of line heigt definition is always lost - see the  [Screen video](https://www.fasihi.net:443/portal/load/fid498257/Problem%20Line%20Height.mp4)

## Provide detailed reproduction steps (if any)

1. create two lines
2. set the line heigt definition on the second line
3. click in the first line or switch to the source - the line heigt definitions are lost

### Expected result

*What is the expected result of the above steps?*

the line heigt definitions are lost

*What is the actual result of the above steps?*

## Other details

* IE11
* OS: WIN10
* CKEditor version: newest

**Comment by msamsel** [comment]
Hi,

your movie shows that line height work the same way as font family or font size. There inserted span with proper style values. Now, if you not write anything in it, then during switching to source mode it will be removed. Empty elements are removed.
Try to select text and then apply line height, or after using lien height type something in editor, to not left empty span in it.
