### ISSUE TITLE
Alignment buttons won't enable when useComputedState is off and justifyClasses are set

### ISSUE THREAD

**Issue by blindspeed90** [ckeditor/ckeditor-dev#669]
## Are you reporting a feature or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)
Not reported

## Provide detailed reproduction steps (if any)

1. Add config.useComputedState=false
2. Add config.justifyClasses=["AlignLeft", "AlignCenter", "AlignRight", "AlignJustify"]
3. Add any text, then click any alignment button

### Expected result
The selected button should be turned on and the associated class is applied

### Actual result
The selected button is not turned on, but the associated class is applied

## Other details
This is not documented anywhere, so I can only assume that when specifying classes that they alone should drive the selection state, and there is no need to look at useComputedState and thus "align"/"text-align".  If that is done, then it is assumed that each of the classes is mapped to text-align values which CKEditor expects, and may not be the case for all consumers.  I made one small addition to refresh() which checks for the classes:

		refresh: function( editor, path ) {
			var firstBlock = path.block || path.blockLimit;

			this.setState( firstBlock.getName() != 'body' &&
						   (editor.config.justifyClasses ? firstBlock.hasClass(this.cssClassName) : getAlignment( firstBlock, this.editor.config.useComputedState ) == this.value) ? CKEDITOR.TRISTATE_ON : CKEDITOR.TRISTATE_OFF );
		}

This alone fixes the selection issue, and will fix #655.  The one other issue I wasn't sure about that only the author will know is in onDirChanged():

				// Always switch CSS margins.
				var style = 'text-align';
				var align = node.getStyle( style );

				if ( align == 'left' )
					node.setStyle( style, 'right' );
				else if ( align == 'right' )
					node.setStyle( style, 'left' );

This code isn't in an else block after the if(classes) test, and it seems like it should be, and isn't a margin like it says.

**Comment by blindspeed90** [comment]
Turning use computedState back on wasn't selecting the default/computed button, so I added this test:

			this.setState( firstBlock.getName() != 'body' &&
			               (editor.config.justifyClasses && !this.editor.config.useComputedState ? firstBlock.hasClass(this.cssClassName) : getAlignment( firstBlock, this.editor.config.useComputedState ) == this.value) ? CKEDITOR.TRISTATE_ON : CKEDITOR.TRISTATE_OFF );

**Comment by beatadelura** [comment]
@blindspeed90 You have to apply those styles to editor content by adding [contentCss](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-contentsCss) in your config, e.g.
`config.contentsCss = 'css/styles.css';`

And in your `css/styles.css`:

```
.AlignLeft {
	text-align: left
}
.AlignRight {
	text-align: right;
}
.AlignCenter {
	text-align: center;
}
.AlignJustify {
	text-align: justify;
}
```

**Comment by blindspeed90** [comment]
The styles are added, I didn't add that as a step, that's not the problem.  The setting of the state is the problem.
