### ISSUE TITLE
Failing Firefox on CI

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#673]
## Are you reporting a feature or a bug?

Task

## Provide detailed reproduction steps (if any)

1. Open some Travis build status page, e.g. https://travis-ci.org/ckeditor/ckeditor-dev/builds/257194039

### Expected result

Build is all green.

### Actual result

Firefox is red :(

It seems that there is some issue with Firefox on Travis, especially in case of asynchronous tests involving `wait` and `resume` functions. We should investigate it more and try to find sensible solution.

**Comment by f1ames** [comment]
Maybe we should try to run those tests in the same manner they run on Travis (Linux + xvfb or Linux only)? Maybe there is some issue with this config and bender. It might not necessarily be Travis fault.

**Comment by mlewand** [comment]
@f1ames good point, could be the thing.

**Comment by Comandeer** [comment]
I've made a small research and the results are not optimistic.

I've run `bender -c bender.ci.js` command on Node 4.7.0 on both Linux Mint 18.2 and macOS 10.12.6 in Firefox 3 times at one OS. All 6 tests failed:

* on Mint there were about 3-5 random failing tests, all connected with `wait`/`resume`,
* on macOS there were about… 120+ failing tests (it seems that Firefox ran from console does not have proper focus),
* I've try to run tests using xvfb on Linux, but it didn't work at all.

I've also run some tests in Chrome, to compare, and it always passed. So it seems that the issue is not necessary with Travis, but with Firefox itself.

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/ckeditor-dev/commit/a6e75d042aa6c7e137a87075132badd29d02fb5f.
