### ISSUE TITLE
ckeditor change numbers order list orders

### ISSUE THREAD

**Issue by shemesh15** [ckeditor/ckeditor-dev#683]
## Are you reporting a feature or a bug?
Bug 

## Provide detailed reproduction steps (if any)

1.write the following text in CKEditor by using the numberedList Button:

        1. one
            1.two
                1. three
                2. four

2. remove line number 2 ("1.two") with the backspace key

### Expected result

     1.one
           1.three
           2.four

### Actual result

    1.one
            1.four
            2.three
why the inner list order was reversed?

## Other details

* Browser:Chrome version 58.0.3029.110
* OS: win 7
* CKEditor version: 4.7
* Installed CKEditor plugins: …
It Happens also in the demo ckeditor in http://ckeditor.com/

**Comment by msamsel** [comment]
Hi,

I have problem with reproducing such situation. I'm checking the issue here: https://cdn.ckeditor.com/4.7.1/full-all/samples/ and when I use backspace list is moved properly to the left. Can you describe what I need to do to repeat this bug?

**Comment by shemesh15** [comment]
hi
Indeed, the list is moved to the left. But this isn't the bug
The bug is that the inner list was reversed.
According to the example above:
instead of 
1. three
2. four

I get

1. four
2. three

**Comment by msamsel** [comment]
Oh I haven't notice that for the first time ;)

**Comment by Dumluregn** [comment]
In CKEditor 4.11.4 the issue is no longer present (tested on Chrome, Firefox, Opera and IE8).
