### ISSUE TITLE
CKWebSpeech Voice to Text Plugin not working

### ISSUE THREAD

**Issue by visvendra** [ckeditor/ckeditor-dev#685]
1) Not working by following configuration- 
Add-on installation instructions
If you want to add the plugin manually, you will need to:

Extract the downloaded plugin .zip into the plugins folder of your CKEditor installation. Example:
http://example.com/ckeditor/plugins/ckwebspeech
Enable the plugin by using the extraPlugins configuration setting. Example:
config.extraPlugins = 'ckwebspeech';

2) Not able to find proper documentation and demo pages.

**Comment by mlewand** [comment]
This is a third party plugin not maintained by CKEditor team.

Please use CKWebSpeech Voice to Text issue tracker https://github.com/infectedalex/ckwebspeech/issues to report the problem. You'll always find plugin's issue tracker link on it's [addon repository page](http://ckeditor.com/addon/ckwebspeech).

**Comment by ultranaco** [comment]
Demo and documentation is here

https://ultranaco.com/briefcase/ckwebspeech
