### ISSUE TITLE
Options in contextmenu missing

### ISSUE THREAD

**Issue by reimersmarkus** [ckeditor/ckeditor-dev#686]
bug

Options in contextmenu missing

## Provide detailed reproduction steps (if any)

1. open the editor the context-menu without options of image2-plugin
![bildschirmfoto 2017-07-27 um 16 05 05](https://user-images.githubusercontent.com/20432562/28674363-7b47110e-72e5-11e7-932d-8e832afc4418.png)

2. switch to sourcecode and back

3. the context-menu with options of image2 
![bildschirmfoto 2017-07-27 um 16 05 16](https://user-images.githubusercontent.com/20432562/28674407-97e3f052-72e5-11e7-8f74-2c15d3481d70.png)

### Expected result

contextmenu display the option of image2 directly

### Actual result

contextmenu without image2-option

## Other details

* Browser: Firefox 54.0.1 (IE11)
* OS: macOS Siera
* CKEditor version: version:"4.7.0",revision:"320013d"
* Installed CKEditor plugins: image2

**Comment by reimersmarkus** [comment]
issue in the firefox-console after show the context-menu with image2-options:
e.getAscendant is not a function

**Comment by reimersmarkus** [comment]
Part in source:
`<td style="width: 325px;"><img alt="" border="0" src="getimage.php?id=7753" style="width: 288px; height: 353px;" /></td>`

**Comment by msamsel** [comment]
@reimersmarkus 
> edit: this issue solved by updating the ckeditor to 4.7.1

I close the issue then :)

**Comment by reimersmarkus** [comment]
Thats not correct. 
The items are still displayed after you change the view.

**Comment by msamsel** [comment]
@reimersmarkus would it be possible for you to provide example showing this problem? Some kind of codepen.io, jsfiddle.net etc.?

**Comment by reimersmarkus** [comment]
No, sorry. Integration is a part of a rich application...

**Comment by mlewand** [comment]
I have cleared out some outdated comments to keep the history clean.

@reimersmarkus I have created a simplified sample with CKE 4.7.1 where you can see that all the context menu options of image2 widget (nested in a table) are in place: https://codepen.io/mlewand/pen/vJemxE

Please, play around and see if you can provide any further hints on this, otherwise we simply can't repro it on our end.

**Comment by reimersmarkus** [comment]
ok, i can only confirm #759 
thanks a lot.

**Comment by mlewand** [comment]
@reimersmarkus thanks for clarification. Also, feel free to add 👍 reaction to the main report comment in #759 so that it gets more attention!
