### ISSUE TITLE
Broken content in article editor after using shortcut CTRL+Z

### ISSUE THREAD

**Issue by beatadelura** [ckeditor/ckeditor-dev#704]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open Edge browser.
2. Go to http://ckeditor.com/ and choose `Article Editor`.
3. Put caret at the end of the text.
4. Press `Enter`.
5. Use `CTRL+Z` shortcut to undo.

### Expected result

The layout looks the same as before use `CTRL+Z` shortcut.

### Actual result

The layout is broken.

## Other details
* Support ticket number: 32334
* Browser: Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393
* OS: Windows 10

If you use the F12 developer tools to change the User Agent String to Chrome the site works as expected.

Here is additional information about the Edge UA String: https://msdn.microsoft.com/library/hh869301(v=vs.85).aspx

**Comment by mlewand** [comment]
Interestingly it does destroy the widget structure when pressing <kbd>ctrl</kbd>+<kbd>z</kbd>, and **does not happen** if you undo using toolbar button, so it's not the issue with the undo command itself.

Also I can not reproduce this issue on old widget demos like: http://cdn.ckeditor.com/4.7.1/full-all/samples/old/image2/image2.html

**Comment by f1ames** [comment]
Closed in #734.
