### ISSUE TITLE
Widget drag should only work with left mouse button

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#711]
## Are you reporting a feature request or a bug?

Bug

 ## Provide detailed reproduction steps (if any)

1. Open any demo with a widget, e.g. [Captioned Image SDK sample](http://sdk.ckeditor.com/samples/captionedimage.html).
2. Hold down right/middle mouse button on the widget's drag icon.
3. Drag the cursor anywhere else.

 ### Expected result

Non-right click does not trigger dragging.

 ### Actual result

It does trigger the drag.

 ## Other details

 This issue happens only for block widget. Inline widgets are working well.

**Comment by beatadelura** [comment]
Blocked by #810.
