### ISSUE TITLE
when i highlight a word, if not the last word in sentence, it highlights with a space after word

### ISSUE THREAD

**Issue by zachisit** [ckeditor/ckeditor-dev#720]
## Are you reporting a feature request or a bug?
bug

## Provide detailed reproduction steps (if any)
watch video:
https://www.screencast.com/t/iXhC1PKjtC

### Expected result
i should hightlight word, and it only highlights the selected word text and not extra space

### Actual result
word letters and extra space at end of word is highlighted

## Other details

* Browser: IE11
* OS: Windows
* CKEditor version:4.7
* Installed CKEditor plugins:config.extraPlugins = 'listblock,button,richcombo,font,panel,panelbutton,floatpanel,colorbutton,dsimmedia,sourcedialog,iframe,specialchar,pastefromword,pastetext,format,horizontalrule,removeformat,blockquote,find,table,copyformatting,justify,selectall';

**Comment by beatadelura** [comment]
@zachisit This issue is not related to CKEditor. This is how IE and other Microsoft packages work. Therefore, you should report this directly to Microsoft.
