### ISSUE TITLE
Editor crashes after performing drag & drop on styled text

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#724]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Put the caret at the beginning of the paragraph.
2. Press <kbd>Ctrl</kbd> + <kbd>B</kbd> and type `test`.
3. Select this word and drag it downwards.

### Actual result

Editor crashes.

```
ckeditor.js:160 Uncaught TypeError: Cannot read property 'type' of null
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.setStart (ckeditor.js:160)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.setStartAfter (ckeditor.js:161)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.setStartAt (ckeditor.js:162)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.moveToPosition (ckeditor.js:159)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.splitElement (ckeditor.js:165)
    at ckeditor.js:372
    at $.insertHtml (ckeditor.js:340)
    at $.<anonymous> (ckeditor.js:350)
    at a.h (ckeditor.js:11)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
```

## GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/28924759-10f4f568-7863-11e7-80bc-d3e3bf14211d.gif)

## Other details
Bug doesn't occur if there is the empty paragraph under dragged word.

* Browser: All browsers
* OS: Windows 10
* CKEditor version: 4.7.1

**Comment by wojtekw92** [comment]
regression in 4.5.0

**Comment by wojtekw92** [comment]
the problem occurs after this patch `f44dfd968bcd35903b1c02bca533b0d018780cd1`.
when we are trying to make drag&drop after the last line editor want to place dragged nodes after the last text node, but meanwhile we are removing this node. The problem doesn't occurs in native editable element https://codepen.io/wojtekw92/pen/MvORVy

**Comment by jswiderski** [comment]
The problem occurs when you drag styled text below the body element. Please note that when body has `height` set to `auto` it will be as high as your text what in case of one line of text will make the `body` one  line high which is much smaller than actual iframe holding it. 

The workaround in this case is setting `min-height` on `body` element (can be done in `contents.css` for classic editor) to certain value. On a desktop iframe container `height` is `200px` so setting the `body` to `160px` - `200px` will solve the problem.

**Comment by jacekbogdanski** [comment]
Setting body to `min-height` creates a visible scroll. Also, it won't resolve the issue thus a user can still drop an element at the edge of the editor.

**Comment by jacekbogdanski** [comment]
The issue is caused mostly by incorrectly bookmarks insertion for drag and drop ranges (https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/clipboard/plugin.js#L1941). It seems like the easiest way to fix the issue would be ignoring DnD when drag and drop ranges are the same. However, it creates additional issues with undo and widget plugins. I added some test fix available on `t/724` branch, although it requires additional testing and refactoring thus failing widget DnD unit tests.

**Comment by mlewand** [comment]
@msamsel please take over this ticket after @jacekbogdanski research.

**Comment by f1ames** [comment]
This issue was solved by https://github.com/ckeditor/ckeditor-dev/pull/2803 (`4.11.3` version).
