### ISSUE TITLE
Styles combo disabled when using style with multiple, not sorted classes

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#727]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/13206

## Provide detailed reproduction steps (if any)

1. Open: https://jsfiddle.net/z90dfv8n/
2. Click on the styles combo.

### Alternative steps

1. Create a minimal CKEditor instance that includes the `stylescombo` plugin and the `styleSet` configuration option set to:

```
[ { name: 'Marker', element: 'span', attributes: { 'class': 'b-test a-test' } } ]
```
2. Click on the styles combo.

### Expected result

Styles combo shows one style that's named "Marker".

### Actual result

Styles combo is empty and disables itself upon clicking on it.

## Other details

* With the class order switched (sorted lexically) the bug does not occur.
* The (bug-inducing) style is recognized but in this form the ACF filters it out from the styles list.
* Pasting this snippet: 

```
<p><span class="b-test a-test">Test</span></p>
```

into the source and switching modes back and forth produces a sorted output like this: 

```
<p><span class="a-test b-test">Test</span></p>
```

* Browser: All
* OS: All
* CKEditor version: 4.3
* Installed CKEditor plugins: `stylescombo`

**Comment by saike** [comment]
same situation. Styles from styleset not displayed.

**Comment by wimleers** [comment]
Drupal issue: https://www.drupal.org/node/2710431.

**Comment by wwalc** [comment]
Just a note that there has been already a solution proposed in https://github.com/cksource/ckeditor-dev/commits/t/13206a
which at first glance makes sense (just sort classes as soon as possible, if it works then it's done). Did not check if it works, but normalizing unordered classes seems like the way to go anyway.

**Comment by mlewand** [comment]
Could we give it a spin? @msamsel I'll assign you to this ticket so that it's on your list once you're back from holidays 🙂.

**Comment by weseze** [comment]
This is still an issue on 4.10.1: not fixed...

**Comment by Comandeer** [comment]
@weseze, this issue had very limited scope and was about style combo being disabled or empty after adding style with unsorted classes. That behaviour is no longer reproducible in newer CKEditor.

**Comment by BastianBalthasarBux** [comment]
I can still reproduce with version 4.11.1 ...

**Comment by f1ames** [comment]
I can confirm that the issue is fixed on latest `4.11.3` version (check here https://jsfiddle.net/p4m25qk0/).

If there is some related issue, it should be reported as a separate ticket. cc @BastianBalthasarBux

**Comment by BramDriesen** [comment]
I can still reproduce this on `4.11.3` using the latest Drupal version.

**Comment by f1ames** [comment]
@BramDriesen maybe it's caused by some specific config. Could you share you config related to styles combo?

**Comment by outdoorsman** [comment]
Just cross-linking this issue that I think also showed up in TYPO3... https://stackoverflow.com/questions/54213690/typo3-8-ckeditor-stylesset-multiple-classes-start-classname-with-bg-does-not-w.
