### ISSUE TITLE
CKEDITOR.timestamp does not work for CSS files

### ISSUE THREAD

**Issue by hardhub** [ckeditor/ckeditor-dev#731]
## Are you reporting a feature request or a bug?

Bug(?)

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

I think it is a bit discussed here (but about config.js):
http://ckeditor.com/forums/CKEditor/Problem-with-config.js-not-updating

## Provide detailed reproduction steps (if any)

1. Exactly after ckeditor.js is executed run this: CKEDITOR.timestamp = 'some_number';
2. So requests from ckeditor have new timestamp, for example: config.js?t=some_number
3. But not CSS requests.. It is still: contents.css?t=H5SC

### Expected result

contents.css?t=some_number

### Actual result

contents.css?t=H5SC

## Other details

* Browser: FF, latest...
* OS: Win x64
* CKEditor version: 4.7
* Installed CKEditor plugins: basic

**Comment by mlewand** [comment]
The `timestamp` feature is set during compile-time. It's used to make sure that browser does not use resources from previous version of CKE.

You should just rebuild CKEditor and it will be changed, see [Building CKEditor from Source Code](http://docs.ckeditor.com/#!/guide/dev_build).

**Comment by hardhub** [comment]
How then can I be sure that my app will reload config.js / styles.js / contents.css files of ckeditor?
I can edit config.js, styles.js, contents.css... and I do not need to rebuild ckeditor for that.
I even never built it myself.. I have downloaded custom bundle from site.

**Comment by hardhub** [comment]
This question was already discussed:
https://stackoverflow.com/questions/14940452/force-ckeditor-to-refresh-config

And this was labelled as accepted answer... From your point of view it is not... So what is the solution then?

**Comment by hardhub** [comment]
Any update on this?

**Comment by Capenus** [comment]
I have the same Issue. If you use `config.contentsCss = ['contents.css', 'your_own_styles.css'];` and make changes to `your_own_styles.css`, those changes arent reflected in the editor. Even if you set `CKEDITOR.timestamp = 'v1.0.1';` to a new value.

**Comment by phil123456** [comment]
yes the timestamp trick does not work at all

**Comment by LiamDawe** [comment]
I'm also currently seeing this issue with JS files with the latest version of CKEditor, perhaps it has been broken completely/
