### ISSUE TITLE
AutoSave and Mathjax Plugins Conflict

### ISSUE THREAD

**Issue by mzamandotnet** [ckeditor/ckeditor-dev#733]
We are using CKeditor plugins of autosave and mathjax, we are adding it using

config.extraPlugins = 'mathjax';
config.extraPlugins = 'autosave';

in config.js

It is working only last one, the second last one stopped working
Please suggest some solution, is there some ordering issue or some other config is missing.

**Comment by AnnaTomanek** [comment]
[`config.extraPlugins`](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-extraPlugins) accepts a list of all additional plugins to be loaded, so you should declare its value like this:

```
config.extraPlugins = 'mathjax,autosave';
```

In your code you are overwriting one declaration with another.

**Comment by mzamandotnet** [comment]
oops, that's true, thanks a lot @AnnaTomanek
