### ISSUE TITLE
Inline editor remains active after tabbing off editor - MS Edge

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor-dev#736]
**Steps to reproduce**
Using MS Edge, place focus in an inline editor
Tab out of the editor onto a button element
Hit the enter key

**Expected result**
The click event of the button element should be fired.

**Actual result**
The button click event is not fired but the editor steals the browser's focus.

Other details (browser, OS, CKEditor version, installed plugins)
This is reproducible in CKEditor 4.7.1

This can be seen with all versions of Edge. For some reason it doesn't seem to be a problem with input elements of type button, only button elements (though it may affect other elements as well).

I can reproduce this with the CKEditor demo page. I select the inline editor and shift-tab back to the button elements to select one of the other editor demos. Hitting the enter key on one of the button elements pulls the focus back to the editor. I've attached an animated GIF.

![edge tab button issue](https://user-images.githubusercontent.com/19921879/29041098-3aac51c8-7b77-11e7-898b-8b4a846f32d4.gif)

**Comment by beatadelura** [comment]
@jbalinski This issue does not directly affect CKEditor Inline but https://ckeditor.com/ website. I checked this behavior with this [example](https://jsfiddle.net/ubconhrv/). I'll report this straight to ckeditor.com repo.
