### ISSUE TITLE
selectionChange event integration with tableselection plugin

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#740]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/a1thu949/
2. Open browser console
3. Select some cells starting from the first cell.

### Expected result

Event is fired for every change in selection (adding or removing cell from selection).

### Actual result

Event is fired only once.

It's possible to fire event for every change if selection starts from the last cell. As editor does not recognize the direction of the issue, every change in such selection is treated as changing beginning of the selection, causing `selectionChange` to be fired.

connected with #739 

## Other details

* CKEditor version: 4.7.0+
* Installed CKEditor plugins: tableselection

**Comment by mlewand** [comment]
DUP of #739.
