### ISSUE TITLE
Drag & Drop in plain text mode doesn't work in Safari

### ISSUE THREAD

**Issue by Teppichratte** [ckeditor/ckeditor-dev#741]
## Bug

Hi, when I use your editor in plain text mode (config.forcePasteAsPlainText = true;) so that no styling is possible then everything works great if you enter or paste content which contains formatting (e. g. smaller font, font color, images). Here the formatting and the images are filtered and the result is just a plain text which is correct.

I have tested this behaviour with the main browsers. The only problem which I have noticed is: If you drag content which contains formatting or images into an editor with Safari, then the content is dropped 1:1 and the formatting isn't removed which is wrong. I've also tested it with Firefox, Chrome, MS Edge and IE11 and the result is correct. The bug is only there in Safari.

* Browser: Safari 5.1.7
* OS: Windows 10 Prof. 64 Bit
* CKEditor version: 4.5.9
* Installed CKEditor plugins: Full featured

**Comment by msamsel** [comment]
Hi,

Latest version of Safari is 10.1.2 and is not supported on Windows platform. Windows version of Safari stopped being released in 2012 (version 5.1.7). We don't support obsolete version of Safari. Unfortunately I cannot help you more with this case.
