### ISSUE TITLE
Unit tests prompts to open the file/app which breaks test run in IE11 on Windows 10

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#742]
## Are you reporting a feature request or a bug?

Other: issue with unit test.

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None.

## Provide detailed reproduction steps (if any)

While running unit tests in IE11 on Windows 10, one test in `http://tests.ckeditor.dev:1030/tests/core/htmldataprocessor` causes browser to open dialog proposing opening an app. This dialog breaks (stops unless close) the test run.

![screen shot 2017-08-08 at 12 17 29](https://user-images.githubusercontent.com/1061942/29067886-c6295cce-7c34-11e7-84f6-4d7876412419.png)

## Other details

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.7.1

**Comment by msamsel** [comment]
Notes:
* Problematic test: `frame with src=javascript 4`
