### ISSUE TITLE
Unable to merge paragraphs when the last element is a widget

### ISSUE THREAD

**Issue by drunklol** [ckeditor/ckeditor-dev#749]
## Are you reporting a feature request or a bug?

not sure if this behavior is intended.

## Provide detailed reproduction steps (if any)

1. go to http://sdk.ckeditor.com/samples/captionedimage.html
2. select an image and remove set alignment to none and untick Captioned image 
3. pull said image at the of a paragraph
4. select the beginning of the following paragraph and press backspace like this:
![image](https://user-images.githubusercontent.com/16104507/29097198-da16d108-7c98-11e7-8bd5-cd379985b1fd.png)

### Expected result

paragraphs getting merged like normal with the widget in the middle.

### Actual result

backspace is only deleting the widget of the first paragraph and not merging both paragraphs.

## Other details

* Browser: Chrome 60.0.3112.90
* OS: Win 10
* CKEditor version: 4.7.1

This may not be a big issue with images but this behavior gets extremely annoying when you want to use for example a lot of inline widgets for footnotes.

**Comment by msamsel** [comment]
I was able to reproduce this error.
Note: <kbd>Shift</kbd>+<kbd>Backspace</kbd> seems to delete new line, but remain a little messy html. There remain some empty text nodes after image.

**Comment by jacekbogdanski** [comment]
Please, follow #1572 for more information about issue status.
