### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by syedyasser** [ckeditor/ckeditor-dev#762]
This is a bug (in my eyes).

I came across a bug with Internet Explorer 11, while Firefox and Chrome are working fine.
This was already filed in 2014
https://ckeditor.com/forums/Support/scrollIntoView-throwing-undefined

In my case it is an iframed page redirecting to (calling) a javascript function closing the popup

....
        if (parent.self.opener == undefined) {
            parent.self = window.parent.parent.$.magnificPopup;
            parent.self.opener = window.parent.parent;
        }
        // add to textarea and close
        parent.self.opener.imageSelectorToBody(gallery, textarea);
        parent.self.close();
The failing code part:

scrollIntoView:function(){this.type!=CKEDITOR.SELECTION_NONE&&this.getRanges()[0].scrollIntoView()}

**Comment by beatadelura** [comment]
Duplicated #761.
