### ISSUE TITLE
Integration between undo and tableselection

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#763]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Build current master or enable `undo` in `tests/plugins/tableselection/integrations/clipboard`
2. Run http://tests.ckeditor.dev:1030/tests/plugins/tableselection/integrations/clipboard/pastemerge#tests%2Fplugins%2Ftableselection%2Fintegrations%2Fclipboard%2Fpastemerge%20test%20table%20expansion%20on%20larger%20table%20(classic)

### Expected result

Test passes without any error

### Actual result

Test fails with error:

> Uncaught TypeError: Cannot read property 'type' of null

## Other details

I can't reproduce error manually – it seems that it's an issue connected solely with unit tests

* Browser: …
* OS: …
* CKEditor version: current `master`
* Installed CKEditor plugins: `undo`, `tableselection`

**Comment by Comandeer** [comment]
It seems to be caused by the fact that paste listener empty all cells before pasting, causing `range.createBookmark2` call to fail while trying to normalize text nodes in selection (as there are no more text nodes there).

**Comment by mlewand** [comment]
Fixed with #764.
