### ISSUE TITLE
Scrolling up the dropdown list is disabled after selecting the option

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#774]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)
1. Select some text.
2. Open font size dropdown and scroll down.
3. Select i.e. size 26.
4. Open dropdown again and try to scroll up.

### Expected result
User should be able to scroll up the dropdown.

### Actual result
Scrolling up is impossible.

## GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/29214958-6c9dfb70-7ea9-11e7-9b13-f4e939edbcca.gif)

## Other details

* Browser: Chrome, Opera
* OS: Windows 10
* CKEditor version: 4.7.2

**Comment by wojtekw92** [comment]
This is browser issue.
You can reproduce it on this pen https://codepen.io/wojtekw92/pen/xLzgMJ?editors=1010

1. click hide button twice
1. Move mouse cursor over the scroll bar
1. try to use scroll wheel(up direction) and try to click above the scroll position

## excepted result
scroll bar should move up

## chromium issue
 https://bugs.chromium.org/p/chromium/issues/detail?id=758130
