### ISSUE TITLE
Paste from Pages

### ISSUE THREAD

**Issue by mark-wade** [ckeditor/ckeditor-dev#776]
## Are you reporting a feature request or a bug?

Feature request

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None found.

## Provide detailed reproduction steps (if any)

1. Open Pages document ([sample](https://github.com/ckeditor/ckeditor-dev/files/1218316/Links.pages.zip))
2. Copy contents
3. Paste into CKEditor

### Expected result

Content is pasted as formatted in document.

### Actual result

Formatting (bold text) and links are lost.

## Other details

* Browser: Safari Version 10.1.2 (12603.3.8)
* OS: macOS 10.12.6 (16G29)
* CKEditor version: 4.7.1
* Installed CKEditor plugins: Standard Package

**Comment by mlewand** [comment]
@mark-wade I don't have currently Pages at hand - could you check if the markup is preserved in this example: https://codepen.io/mlewand/pen/mMqQrO ?

If it's possible please check it also using Chrome browser to compare the results.

**Comment by mark-wade** [comment]
Works in Chrome but not Safari.

<img width="1909" alt="screen shot 2017-08-16 at 11 28 04" src="https://user-images.githubusercontent.com/1433869/29359304-00b7c528-8276-11e7-9c35-8fffc19b0278.png">

**Comment by mlewand** [comment]
That's interesting, so by the looks of it Safari transforms the source markup.

Can I ask you to paste same content into this codepen: https://codepen.io/mlewand/pen/xqwRJb

![Screenshot of the codepen](https://user-images.githubusercontent.com/5353898/29359550-6484ce8a-827f-11e7-8ebc-4f69811ee499.png)

This will give us an information what Safari provides from the data transfer. Feel free to provide a gist link in case if it's super long.

**Comment by mark-wade** [comment]
> Your clipboard did not contain any text/html :((

**Comment by mlewand** [comment]
@mark-wade that's odd, looks like Safari doesn't provide a clipboard there in which case this is an upstream issue. Some1 with a mac will have to check this.

**Comment by mlewand** [comment]
We checked this issue and it is Safari issue, it does not put text/html in the data transfer. Here are the types included by Safari:

* com.apple.iWork.TSPNativeData
* com.apple.iWork.TSPNativeMetadata
* com.apple.iWork.TSPDescription
* com.apple.iWork.pasteboardState.hasTextStoragesAttachmentsNotAllowed
* com.apple.iWork.pasteboardState.hasTextStoragesAttachmentsAllowed
* com.apple.iWork.pasteboardState.countOfObject-1
* com.apple.iWork.pasteboardState.hasNativeTypes
* com.apple.flat-rtfd
* NeXT RTFD pasteboard type
* public.rtf
* text/rtf
* public.utf16-external-plain-text
* CorePasteboardFlavorType 0x75743136
* public.utf8-plain-text
* text/plain
* dyn.ah62d4rv4gk81n65yru
* CorePasteboardFlavorType 0x7573746C
* com.apple.traditional-mac-plain-text
* CorePasteboardFlavorType 0x54455854
* dyn.ah62d4rv4gk81g7d3ru
* CorePasteboardFlavorType 0x7374796C

@mark-wade this issue should be reported in WebKit / Safari bug tracker. Feel free to cross link it to this issue.

**Comment by mark-wade** [comment]
Can't you do anything with text/rtf?

**Comment by mlewand** [comment]
Unfortunately text/rtf has no use for us - we'd have to implement a parser for RTF just to handle such cases. The bug in Safari is quite obvious here, and easy to fix so that's the proper way to solve it.
