### ISSUE TITLE
Remove Format removes also language definition

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#779]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open http://sdk.ckeditor.com/samples/fullpreset.html
2. Select some text and click "Language"→"French".
3. Click "Remove Format".

### Expected result

`span` element with language definition is not removed

### Actual result

`span` element with language definition is removed

## Other details

* Installed CKEditor plugins: removeformat, language

**Comment by mlewand** [comment]
A fix for this issue should simply [add a remove format filter](https://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-addRemoveFormatFilter) (if present, because remove plugin might not be present).
