### ISSUE TITLE
flexbox  feature

### ISSUE THREAD

**Issue by drunklol** [ckeditor/ckeditor-dev#782]
## Are you reporting a feature request or a bug?

 feature request

Not sure if this belongs here but since WYSIWYG editors are a thing I noticed that a lot of people trying to hack basic layouts with tables which they aren't invented for. There are also a lot of plugins trying to deal with this in some way or another like inserting pre defined layouts.

a Flexbox feature could users allow to easily build complex layouts. It could look like this in an inline editor:

![flexbox](https://user-images.githubusercontent.com/16104507/29254301-e707c02c-8092-11e7-815d-3f83c33c32d8.png)

where users could similar to the table plugin add columns and edit the flexbox CSS properties of rows and cells via a dialog.

[Flexbox browser support](http://caniuse.com/#search=flexbox)
[Bootstrap 4 flexbox classes](https://getbootstrap.com/docs/4.0/utilities/flex/)
****

**Comment by mlewand** [comment]
@drunklol thanks for the feature request. Flex box is a great layout technique, however it does not apply to our editor as we're focusing on content creation, and not really on creating complete webpages/layouts.

It's fine for plugins to use it as an implementation detail, but we won't provide feature explicitly for working with flex boxes. Thus it's a won't fix for us ATM.
