### ISSUE TITLE
Cannot switch to source mode after making a list starting with widget

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#783]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

No

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/mediaembed.html.
2. Switch to Source mode and replace content with

```
<p>&nbsp;</p>
<p>foo</p>
<p>bar</p>
```
3. Insert `https://open.spotify.com/track/2XsTC2dPbmWREu5RQ1mQC0` in the first line using Media Embed dialog.
4. Select whole content starting from the bottom (do not use `Select All` or `Ctrl/Cmd + a` as issue does not appear then).
5. Create a list from selection.
1. Switch to Source mode.

### Expected result

Possible to switch to Source mode.

### Actual result
The `Unable to get value of the property 'attributes': object is null or undefined` error is thrown.

## Other details

Does not happens for some embedded media (checked also twitter and youtube embedding which seems to work fine).

* Browser: IE9
* OS: Windows 7
* CKEditor version: 4.7.2
* Installed CKEditor plugins: `embed`

**Comment by wojtekw92** [comment]
This bug is reproducible on different environments. This is selection problem when we are selecting from bottom our selection start is inside iframe wrapper with `contenteditable=false`.

**Comment by mlewand** [comment]
This issue is fixed on IE11 @ Windows 10, see the version below:

![image](https://user-images.githubusercontent.com/5353898/29715267-e4e11786-89a6-11e7-84ea-7a4da0a4021d.png)

Thus it's an upstream issue. However I don't see MS fixing it as they're no longer supporting IE11.
