### ISSUE TITLE
Generic manual test for table selection

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#786]
## Are you reporting a feature request or a bug?

Task

 ## Provide detailed reproduction steps (if any)

We need to include a generic manual test for table selection. There are plenty manual tests for table selection, so maybe one could be simply reused?

Things that I believe should be included:

* A simple table (at least 6x4).
* A table with headers (first row+first column) with caption and summary.
* A second table with `colspan` and `rowspan` attributes.
* A third table with a nested table.

**Comment by Comandeer** [comment]
It seems that enhancing current `tests/plugins/tableselection/manual/tableselection` test would be the easiest way. Just drop version tag and add caption/summary to some table and we're done.
