### ISSUE TITLE
Cut doesn't work inside the nested table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#787]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create the table.
2. Put the caret at the cell.
3. Create the nested table.
4. Type something in two different cells (inside the nested table).
5. Select these cells.
6. Press <kbd>Ctrl</kbd> + <kbd>X</kbd>.

### Expected result

Text should be cut.

### Actual result

The selection disappears, text wasn't removed, but cells were copied to the clipboard. 

## GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/29268614-e007af8e-80ed-11e7-9dab-9ab71261334e.gif)

## Other details

* Browser: All browsers
* OS: Windows 10
* CKEditor version: 4.7.2

**Comment by Comandeer** [comment]
Actually this issue is not connected with `tableselection` plugin, it's more generic issue connected with `editable.extractHtmlFromRange` method and it's reproducible in Firefox (as it's the only browser with multiple-range selection) even in older versions than 4.7.0.

**Comment by mlewand** [comment]
We won't be able to include this release into upcoming release. I'm putting it to 4.8.0, but if we'll be adding a any minor release in between it's perfectly fine to move it to any sooner release.
