### ISSUE TITLE
Toolbar does not work in IE 11 on Windows Server

### ISSUE THREAD

**Issue by anupbhore** [ckeditor/ckeditor-dev#794]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Ensure your Internet Explorer 11 is up to date.
2. Launch URL https://ckeditor.com/ 
3. Select any text and click on Bold button from toolbar.
4. Try any other toolbar button.

### Expected result
The style of the selected text should be changed.
Buttons in toolbar should work.

### Actual result
The style of selected text does not change.
Buttons in toolbar not working.

## Other details
This was working fine on older versions of IE 11.
There are no JavaScript errors observed.

* Browser: Internet Explorer
* OS: Windows
* CKEditor version: 4.7.1
* Installed CKEditor plugins: Using Ckeditor demo page.

**Comment by anupbhore** [comment]
![ckeditor not working in ie11 latest version](https://user-images.githubusercontent.com/29601854/29409417-b7d4cffa-8369-11e7-875b-fdf215762016.PNG)

**Comment by mlewand** [comment]
So far I have checked IE11 version on Win10 box, and it does work correctly, but it's a much different version number than yours:

![image](https://user-images.githubusercontent.com/5353898/29409614-5d796de8-834d-11e7-978e-b15b094b4252.png)

I'll check on other Windows version and will update this issue.

**Comment by mlewand** [comment]
So far I have checked IE11 version on Win10 box, and it does work correctly, but it's a much different version number than yours:

![image](https://user-images.githubusercontent.com/5353898/29409614-5d796de8-834d-11e7-978e-b15b094b4252.png)

I'll check on other Windows version and will update this issue.

**Comment by anupbhore** [comment]
That is weird because for me it is not working on this version as well. I am using windows server 2012.
![ckeditor not working in ie11 11 0 45 version](https://user-images.githubusercontent.com/29601854/29411235-9736ea28-8371-11e7-8ab0-913f29b27949.PNG)

**Comment by mlewand** [comment]
Checked on yet another version on Win7, and it still works well.

![image](https://user-images.githubusercontent.com/5353898/29411939-17294728-8357-11e7-95e1-5f3d34045fa7.png)

Do you have by any chance some browser extensions? Or maybe quirks/compat mode globally enabled somehow?

@jswiderski any thoughts on this?

**Comment by prashu-a** [comment]
@mlewand Yes, I saw this post before raising #795 . In my case, formatting does not work irrespective of text selected or not. Also none of the toolbar buttons work. Like, Image or Table.

**Comment by mlewand** [comment]
I think it's the exact same case for @anupbhore I'm assuming that clicking a button simply doesn't trigger any action. @anupbhore is that the case?

Also can I ask any of you check CKEditor in a non-server OS IE11 version?

**Comment by anupbhore** [comment]
@mlewand  Yes, clicking a button doesn't simply trigger any action. CKEditor is working just fine in non-server OS IE11 version. In addition, the issue is observed even in version 4.5.3 and 4.6.2.
   I ensured compatibility/quirks mode is not enabled. I have not installed any specific browser extension other than what is shipped out of box in IE.

**Comment by prashu-a** [comment]
@mlewand, Yes, I see similar behavior as anubhore. Unfortunately, I have to get it working on server IE11.

**Comment by jswiderski** [comment]
Please open: https://www.qualys.com/research/security-alerts/2017-08-08/microsoft/ and expand "Microsoft Internet Explorer Security Update for August 2017" section. The patch version of 11.0.9600.18763 fixes 5, 6 and 8. 

Since older versions of editor don't work with that patch, there is most likely something wrong with this update but we would be getting much more bug reports than 1, so before we go into panic mode there are two things to check which come to my mind:
1. Please compare your IE11 11.0.9600.18763 settings with settings of IE11 11.540.15063.0 available on win 10 for example. Maybe these patches introduced some new IE settings which for example block execution of JavaScript but this can be worked around by unchecking IE setting.
2. Please make sure you have all the updates installed. Maybe this update really breaks something but there was additional update which fixes the problem and which you have missed?

**Comment by anupbhore** [comment]
@jswiderski  Please note that the issue is reproducible only on systems that have Windows Server.
I compared settings and did not see any difference.
The system also has latest update installed.

**Comment by wwalc** [comment]
@anupbhore could you try reducing security settings in IE to check when CKEditor will start working again? Make sure to note down your current settings to be able to get back to them later.

**Comment by anupbhore** [comment]
@wwalc Even with lowest security settings, it does not work.

**Comment by prashu-a** [comment]
bumping this to check if there is any update.

**Comment by jacekbogdanski** [comment]
I have no issue using CKEditor with Windows Server 2012 R2. Please, make sure that you enabled URLs with Internet Explorer Enhanced Security Configuration.

![win12](https://user-images.githubusercontent.com/10279586/60658970-8f4adb80-9e54-11e9-83b6-eb58af48c84e.gif)
