### ISSUE TITLE
duplication of image while copy-paste from outlook

### ISSUE THREAD

**Issue by SandipNagar** [ckeditor/ckeditor-dev#802]
## Are you reporting a feature request or a bug?

 issue type: Bug

## Provide detailed reproduction steps (if any)

1. I have one e-mail from which i am copying the content (content has more than 2 images) and i am copying from outlook
2. Paste to my page where CKEDITOR 4.6.2 is integrated
3. Left side image is showing twice (duplication of image).

### Expected result

Left side image should be displayed once as per original content.

### Actual result

Left side image is showing twice (duplication of image).

## Other details

* Browser: Chrome, FireFox
* OS: Windows 7
* CKEditor version: 4.6.2
* Installed CKEditor plugins: 

dialogui,dialog,about,a11yhelp,basicstyles,blockquote,clipboard,panel,floatpanel,menu,contextmenu,resize,button,toolbar,elementspath,enterkey,entities,popup,filebrowser,floatingspace,listblock,richcombo,format,horizontalrule,htmlwriter,wysiwygarea,image,indent,indentlist,fakeobjects,link,list,magicline,maximize,pastetext,pastefromword,removeformat,sourcearea,specialchar,menubutton,scayt,stylescombo,tab,table,tabletools,undo,wsc

Url for refference screenshot about the issue :- https://dev9.wesrch.com/Image_issue_outlook.png

**Comment by beatadelura** [comment]
@SandipNagar Thank you for creating this issue. Unfortunately, we do not support copy/paste functionality from outlook, so I'm closing this for now.
