### ISSUE TITLE
Firefox draws yellow outline outside image2 widget drag handles

### ISSUE THREAD

**Issue by quicksketch** [ckeditor/ckeditor-dev#804]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Two similar (won't fix) issues have been reported here:

https://dev.ckeditor.com/ticket/13269
https://dev.ckeditor.com/ticket/12449

## Provide detailed reproduction steps (if any)

1. Load ckeditor.com in Firefox.
2. Use the inspector to remove the `padding: 10px` CSS on the `figure` element in the editor.
2. View the yellow border when hovering over the sample image.

![image](https://user-images.githubusercontent.com/100206/29479953-e0af967e-8429-11e7-9613-1bea551d9056.png)

This issue requires the widgets plugin for handling captions.

### Expected result

The drag handle is outside the yellow border, rather than inside of it, as it is in other browsers.

### Actual result

Yellow border extends around the absolutely positioned drag handle.

## Other details

* Browser: Firefox 55
* OS: All
* CKEditor version: 4.7.2
* Installed CKEditor plugins: widget, image2

---

While this issue has been reported in the past and marked "won't fix" based on it being an underlying bug in Firefox (it definitely is), it's easy enough to work around this problem by using `box-shadow` instead of `outline` to achieve the same results: https://stackoverflow.com/a/15077889/845793

PR to follow.

**Comment by quicksketch** [comment]
PR filed at https://github.com/ckeditor/ckeditor-dev/pull/805.

Screenshot with PR applied:

![image](https://user-images.githubusercontent.com/100206/29480223-8708786e-842b-11e7-8bba-f631d80c0fed.png)

**Comment by beatadelura** [comment]
@quicksketch Everything works fine if default style like mentioned `padding: 10px` has not been removed. So it can't be treated as a bug. If you would like to customize CSS styles you need to take care of this issue on your own. 

Anyway, thank you for the contribution!
