### ISSUE TITLE
Post Editor - Useragent sniffing breaks it in Pale Moon

### ISSUE THREAD

**Issue by Arthmoor** [ckeditor/ckeditor-dev#806]
This issue was originally posted here: https://dev.ckeditor.com/ticket/17004

I notice it has not been brought over to this tracker, so I'm opening it again and will repost the report directly in case that link above ever dies for some reason.

> I was directed to report this here by Rhett Buck at Invision Power Services (no, I'm not happy about being passed off when you're not the guys I'm paying for support). There is an issue with the CKEditor supplied to them, and on your own homepage as well. I am using the Pale Moon web browser, originally a fork from Firefox, but diverging into its own entity more recently. When attempting to use any function of IPB where the editor is needed, all that happens is the text box stalls with "Loading..." and never comes up. I have confirmed this across at least 5 sites now using IPB 4 where I have accounts and can post. There is also confirmation in other packages such as Drupal that the editor will do the same thing there. I have also verified that your own samples on the front page at ckeditor.com cause the red throbber to spin forever and nothing loads. I have traced this down to a useragent issue.
> 
> Pale Moon defaults to this useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:3.2) Goanna/20170422 PaleMoon/27.3.0
> 
> If I change it to this: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0 PaleMoon/27.3.0 then everything works properly, including the demos on your front homepage.
> 
> Rhett then found another post on the Pale Moon forums where a user tracked it down even further to your ckeditor.js parsing the useragent incorrectly based on the rv: parameter. The link to that post is here: ​https://forum.palemoon.org/viewtopic.php?t=13035
> 
> Since Pale Moon is a legitimate desktop web browser used by millions of people, I think this is an issue that should be addressed in your detection scheme so that it benefits anyone using your package downstream, like IPB and Drupal, and users on sites with that software don't have to spoof a useragent to get access to something that clearly works just fine. This seems like a relatively simple fix that will maintain the intent of your compatibility check without locking out those of us who are by choice using something that's not Firefox, IE, or Chrome.

There is no reason to be performing an ancient Gecko check in 2017. Nobody still uses Gecko engines that old except for spambots.

**Comment by msamsel** [comment]
Hi,
CKEditor browser support is described here: https://docs.ckeditor.com/#!/guide/dev_browsers. Pale Moon is not officially support browser. So please be aware that I cannot promise that this issue will be fixed. But still some extra information will be needed for better understanding what happen.

Just to clarify a little bit entire situation.
You are a client of Invision Power Services not CKEditor? And you reported problem to them and you were asked to write to us?

Forum post seems to point to this code as source of problem: https://github.com/ckeditor/ckeditor-dev/blob/master/core/env.js#L294-L300
If it's possible you can provide more detail what kind of errors do you have and what exactly is not working. To get wider context of this situation. Can you also check if situation appear on our [demo page](https://cdn.ckeditor.com/4.7.2/full-all/samples/).

**Comment by Arthmoor** [comment]
Yes, I am a paid client of Invision Power Services. They sent me here after I opened the ticket with them back in April. As I explained before, I wasn't happy about them passing the buck like this since I'm paying them and not you guys.

Yes, that code block you highlighted is where the problem lies. It would be trivial to solve by simply adding something to account for the Goanna engine, or to make the Gecko check more reasonable since you're already allowing browsers that are 15 years old to pass the test anyway. Nobody uses stuff that old anymore.

As far as what happens when the bug hits, if you go into a post reply box or anywhere else the CKEditor is called, clicking into it to start typing results in it simply getting stuck saying "Loading..." and doing nothing. Modifying the javascript to allow Gecko 3 results in it working just fine.

It would also be greatly appreciated if someone would notify Rhett Buck about the status of this issue because they will need to pull an update from your branch code to fix this on their end too. Though honestly they should be the ones having to report this to you to get fixed, not end users.

**Comment by msamsel** [comment]
Hi,

unfortunately we're currently not going to extend variety of supported browsers, but there is some possibility which might be working for you in this case.
You can force editor to load on unsupported browsers, by overwriting `isCompatible` method.
It has to be done **after script library load** and **before editor initialising**.
I prepared some fast example: https://codepen.io/msamsel/pen/qXyByY?editors=1010 how it might look. And more detail description of this process you can find here: https://docs.ckeditor.com/#!/guide/dev_unsupported_environments.
You can create more complicated expression than simple `true`, if you have such need.
Please be aware that enabling editor in such way is done at your risk.
You can propose this solution to Invision to solve your problem to load editor in Pale Moon.

**Comment by Arthmoor** [comment]
Gotta say, this is incredibly disappointing. It's a pretty simple change in the script that won't break anything for anyone else but will provide support for a legit browser that behaves properly in every respect when spoofing the user agent. Your code obvious can't tell the difference. I don't see why it should be up to end users to fix problems caused by software packages they're paying good money for.

**Comment by jswiderski** [comment]
It's not just about enabling the browser. We have to test it before adding it to list of supported ones and then test it whenever new fix, feature is being made or new editor version is being released. I'm sorry but PaleMoon is not a main stream browser at the moment and 0,02% of market share is just not worth all that effort. We will hover be happy to add it in the future once it becomes more popular.

As @msamsel has explained. The Power Services can easily fix this issue by enabling this particular browser in editor they provide. CKEditor API gives the possibility to enable just a extra single browser with the help of [isCompatible](https://docs.ckeditor.com/#!/guide/dev_unsupported_environments-section-blacklisting-some-unsupported-environments).

**Comment by Arthmoor** [comment]
Firefox 3 isn't a mainstream browser either yet your Gecko check will allow that to work even though the editor does in fact break for it. The logic doesn't really hold here.

**Comment by mlewand** [comment]
@Arthmoor:

> Firefox 3 isn't a mainstream browser either yet your Gecko check will allow that to work even though the editor does in fact break for it.

The difference is that we simply don't care what happens on Firefox 3, as we're not checking it, same thing for unsupported IE6/7.

If we were to keep support for every single browser in the world, referenced code would get extremely dirty, rather quickly. Some way to keep the sanity would be either refactoring it into a more featureful component, or completely base CKE4 on feature detection. Personally I like the later more, however it's a very big task, and often it's not possible to detect everything.

However in case of mentioned Pale Moon browser there is upstream issue. Since it's forked from FF, it's in PM browser interest to keep compatibility FF, so it should keep API/user agents compatible with latest FF.
