### ISSUE TITLE
Dragging and dropping content in read-only mode

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#808]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/35f3gqvw/
2. Start dragging widget.
3. Try to drop it below the text, when copy cursor is shown (warning: it's not shown in every browser).

### Expected result

Nothing happens.

### Actual result

Widget disappears.

## Other details

* CKEditor version: 4.5.0+
* Installed CKEditor plugins: image2

It seems that there is no sensible mechanism to control mouse integration in widgets, see also #719 or #710.

**Comment by wojtekw92** [comment]
This is more general problem with drag&drop functionality in readOnly mode: 
![drag drop](https://user-images.githubusercontent.com/7364832/30022930-c19bec14-916d-11e7-9d06-d5b70d6081e5.gif)
