### ISSUE TITLE
Firefox drag handles in div editing area

### ISSUE THREAD

**Issue by mark-wade** [ckeditor/ckeditor-dev#812]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Was previously reported in old tracker

https://dev.ckeditor.com/ticket/17007

## Provide detailed reproduction steps (if any)

Using Firefox with the divarea plugin present

1. Insert a table, image or other element which will show Firefox's drag handles when selected
2. Select the element
3. Scroll the editor

### Expected result

The drag handles on the corners of the element scroll with the window, attached to the element

### Actual result

The drag handles remain where they are and do not scroll with the content

## Other details

Tested with Firefox 53.0 (64-bit) on macOS 10.12.4 and CKEditor 4.6.2 (latest versions at time of report)

Demo: ​https://cl.ly/100R2a2j0d0S

**Comment by beatadelura** [comment]
@mark-wade Could you please check, whether this problem occurs also in CKEditor version 4.7.2 with the newest Firefox version 55?

**Comment by mark-wade** [comment]
Behaviour is slightly different now, but still not right:

<img width="1200" alt="screen shot 2017-08-23 at 12 35 17" src="https://user-images.githubusercontent.com/1433869/29613809-91325152-87ff-11e7-88c1-a6834c675e99.png">

**Comment by beatadelura** [comment]
I can reproduce [this](https://github.com/ckeditor/ckeditor-dev/issues/812#issuecomment-324302151) issue with CKEditor 4.7.2 on Firefox 55.0.2. Check https://jsfiddle.net/12og0jkj/1/

**Comment by mlewand** [comment]
The reason for this is that [`disableNativeTableHandles`](https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-disableNativeTableHandles) and [`disableObjectResizing`](https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-disableObjectResizing) are not handled by `divarea` plugin, see lines https://github.com/ckeditor/ckeditor-dev/blob/60d63d2dafbdf0bf324d3206c3eac8fb6c76efb0/plugins/wysiwygarea/plugin.js#L551-L557.

And that was on purpose, as we can't modify the outer document.

If only [`document.queryCommandEnabled`](https://developer.mozilla.org/pl/docs/Web/API/Document/queryCommandEnabled) was working well for this case, we could play a bit with it and for instance check the state of `enableInlineTableEditing` command when focusing the editor, and then restoring it to it's initial value once the editor is blurred. But I have just checked it now and it does not work correctly for this feature, and probably never will.

Anyway, aside from ideal solution, at the moment developer can fix it easily by calling:

```js
window.document.execCommand( 'enableInlineTableEditing', false, false );
```

And disabling this feature for the whole document.
