### ISSUE TITLE
Cannot select text inside nested table after paste

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#821]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/fullpreset.html/
2. Insert following content in the `Source mode`:
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>Cell 1</td>
			<td>Cell 2</td>
			<td>Cell 3</td>
		</tr>
		<tr>
			<td>Cell 4</td>
			<td>Cell 5</td>
			<td>Cell 6</td>
		</tr>
	</tbody>
</table>

```

3. Switch to WYSIWYG mode and select _Cell 1_ and _Cell 4_.
4. Past in other cell in the way that nested table is pasted.
1. Try to select some text in the pasted table.

![aug-23-2017 12-11-09](https://user-images.githubusercontent.com/1061942/29611003-437eb34a-87fc-11e7-9e00-6bf0c028bc66.gif)

### Expected result

Text is selected.

### Actual result

Not able to select text.

## Other details

* Browser: Chrome 56
* OS: OS X
* CKEditor version: 4.7.2
* Installed CKEditor plugins: Full preset (`tableselection`)

**Comment by Dumluregn** [comment]
Closing issue as it is no longer reproducible in `4.12.1`.
