### ISSUE TITLE
repeat append script tag and link tag while init multiple ckeditors

### ISSUE THREAD

**Issue by gexiaowei** [ckeditor/ckeditor-dev#824]
repeat append script tag and link tag while init multiple ckeditors, 
![jietu20170824-164041](https://user-images.githubusercontent.com/2364344/29657709-0e5aea54-88eb-11e7-9968-dc1752e77576.jpg)
it make to much time to load them event the http status is 304
 so i want to know how to fix it

**Comment by gexiaowei** [comment]
my ckeditor verision is 4.7.1

**Comment by mlewand** [comment]
You're using **dev** version of CKEditor. In your production environment, where performance matters, you should use [release version](https://github.com/ckeditor/ckeditor-releases). It's also available as `ckeditor` on Bower.

You can also use our [online builder](https://ckeditor.com/builder).

For more details see https://docs.ckeditor.com/#!/guide/dev_best_practices-section-use-minified-versions

Also please fill tickets in our default template, it allows us to get more details needed to identify your problem.
