### ISSUE TITLE
Right click on a widget within a table

### ISSUE THREAD

**Issue by Sillorn** [ckeditor/ckeditor-dev#825]
## Are you reporting a feature request or a bug?

Bug.

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None i guess.

## Provide detailed reproduction steps (if any)

1. Create a table ;
2. Create a widget in a cell of this table ;
3. Right click on the widget.

### Expected result

Select widget only.

### Actual result

It select widget and highlight cell. Could be annoying for users.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.7.2
* Installed CKEditor plugins: tableselection / widgetselection

**Comment by wojtekw92** [comment]
duplicates #710
