### ISSUE TITLE
PFW fixture generator does not return full native clipboard

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#827]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

1. Open `dev/pastefromword/getclipboard.html`.
2. Paste any Word content.

### Expected result

Content inside "Raw Data Received" field contains all pasted HTML.

### Actual result

Content inside "Raw Data Received" field contains only HTML fragment.

## Other details

It's caused by the fact that `getData` lacks second attribute.

**Comment by mlewand** [comment]
Fixed by #828.
