### ISSUE TITLE
Add/edit Radio button, enabled status is not saved under IE 9-11

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#834]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

- https://dev.ckeditor.com/ticket/8175
- https://dev.ckeditor.com/ticket/12465

## Provide detailed reproduction steps (if any)

1. Open any sample
2. Clear content
3. Press form element -> radio button
4. Fill all fields and check "enabled"
5. Press OK 

### Expected result

Radio button is added to edit area, with Enabled status 

### Actual result

Radio button is enabled **visually**, but after viewing the source of radio button in dev-tools  `checked="checked"` is not there.  Of course after double click on radio, status Enabled is not set in dialog window as well.

## Other details

* Browser: IE9-11
* OS: Windows
* CKEditor version: 3.0+
* Installed CKEditor plugins: Forms

**We have fixed this issue recently for checkboxes.**

**Comment by msamsel** [comment]
Upstream: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13497247/

**Comment by mlewand** [comment]
Fixed with #845.
