### ISSUE TITLE
drop user-agent requirement

### ISSUE THREAD

**Issue by ilf** [ckeditor/ckeditor-dev#837]
## Are you reporting a feature request or a bug?

Bug

Reference: https://github.com/xwiki-labs/cryptpad/issues/172

## Provide detailed reproduction steps (if any)

1. run `chromium --user-agent='Mozilla/5.0' https://cryptpad.fr/pad/`

### Expected result

Page displays cryptpad with CKEditor.

### Actual result

Page sais "Loading..." - and hangs there.

## Other details

* Browser: any
* OS: any

**Comment by msamsel** [comment]
Hi @ilf,
you can manual remove checking compatibility in CKEditor. To do so you need to overwrite `CKEDITOR.env.isCompatible` to return always true or return true in wider spectrum of browser, but this change you do on your own risk. `isComaptible` should be replaced after loading library but before loading editors on page. More information you can find here: https://docs.ckeditor.com/#!/guide/dev_unsupported_environments
Example how it might be done you can find here: https://codepen.io/msamsel/pen/qXyByY?editors=1010
I hope it will help in your project and resolve this issue. :)

**Comment by ilf** [comment]
Thanks. But is there a possibility to make this default? User-Agents are very revealing information and I don't want to send out my operating system, architecture, locale or software versions.

And since every CryptPad uses this, I cannot use any CryptPad installation - unless I contact the admins and convince them of changing their CKEditor config. :(

**Comment by msamsel** [comment]
If you wish to understand better what exactly is happen, please look into this code:
https://github.com/ckeditor/ckeditor-dev/blob/aaec49329c201813fed928c25f7aed5ecf7de859/core/env.js#L294-L300

CKEditor checks for those 3 condition and in case of `false` result editor won't be load. This is what happen here. Sometimes there might be also some solutions design directly to specific browser (e.g. IE only cases, etc.)

Generally I see 2 option either convince portal admin to change config or you can manipulate your user-agent string to fulfil those condition. You should be able to use some part of IE, Gecko, or WebKit with high enough version to get CKEditor loaded. Best would be to use part of your actual UA string, to get proper fixes in CKEditor for your browser.

Unfortunately we don't plan to remove user-agent validation.
