### ISSUE TITLE
image not displayed

### ISSUE THREAD

**Issue by jyothinaga** [ckeditor/ckeditor-dev#855]
I am using ckeditor 4.7.2.If i add images in the editor, while saving & taking print, image URL is displayed.  When the document is updated, that image & the URL is not displayed.

**Comment by wojtekw92** [comment]
Hi @jyothinaga.
Can you give us step by step reproduction method? I'm not able to reproduce this issue. It would be great for us if You will use our issue template.

**Comment by jyothinaga** [comment]
When i uplaod image it is uplaoding and displaying image.While giving print it is showing the image url.
While i am trying to update,at that time that image or image url is not at all showing.

**Comment by jyothinaga** [comment]
I am using CKEditor 4.7.2 version

**Comment by wojtekw92** [comment]
@jyothinaga please provide us all infromation about editor configuration and your environment(such us editor plugins you are using, browser version, OS). The easiest way is to use our issue template.

**Comment by jyothinaga** [comment]
I have added extracted CKEditor in my project`s plugins.Using Mozilla firefox 40.0 and windows7 64 bit.

**Comment by wojtekw92** [comment]
Please update your browser to the latest stabile release. According to our docs we are supporting only the latest stable release:  https://docs.ckeditor.com/#!/guide/dev_browsers. If the issue will still occurs please inform us and add all required information(you have list in docs) https://docs.ckeditor.com/#!/guide/dev_issues_tracker.
