### ISSUE TITLE
Bug in CKEDITOR.plugins.link.getSelectedLink

### ISSUE THREAD

**Issue by MichaelHeerklotz** [ckeditor/ckeditor-dev#859]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. run ckeditor from [cdn](http://cdn.ckeditor.com/4.7.3/full-all/samples/)
1. run source mode
1. insert `<p><a class="linkClass" href="https://www.google.pl"><img src="http://lorempixel.com/10/20/" /> some button text </a></p>`
1. go back to WYSIWYG mode.
1. double-click on `some button text`

### Expected result
the link dialog should show with proper href data.

### Actual result

the link dialog shows without `href` and `class` data.

## Other details
What I found out so far:
- getSelectedLink (editor, false) works
- on right-click selection.getSelectedElement() is null, but when I double-click it points to the correct "a"
- on right-click range.getCommonAncestor() points to the "some button text", on double-click range.getCommonAncestor() points to the "p" tag <<<< this causes the problem in my opinion.

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.7.2

**Comment by MichaelHeerklotz** [comment]
This fix works for me.

**Comment by wojtekw92** [comment]
regression since 4.7.0

**Comment by mlewand** [comment]
I have created a quick unit test for that: https://gist.github.com/mlewand/4b61bbd8540de0b1ecc00e0c99e12404

**Comment by Comandeer** [comment]
I've updated issue's description.
