### ISSUE TITLE
Add docs for installing NuGet package

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#861]
## Are you reporting a feature request or a bug?

Task

 ## Provide detailed reproduction steps (if any)

After adding NuGet packages for CKEditor, we need docs in [Installing CKEditor with Package Managers](https://docs.ckeditor.com/#!/guide/dev_package_managers) guide.

I'm putting an issue in this repository so that we won't forget it.

**Comment by mlewand** [comment]
This issue can hang here, we can do it during testing phase. `ckeditor-dev` repo will not be affected by this change.

**Comment by mlewand** [comment]
This issue can hang here, we can do it during testing phase. `ckeditor-dev` repo will not be affected by this change.

**Comment by Comandeer** [comment]
Closed by ckeditor/ckeditor-docs#109.
