### ISSUE TITLE
Object styles are only visible when selecting whole element

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#862]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open editor sample and clear editor contents.
2. Create unordered list with one or two elements.
3. Put cursor into one of elements and open styles dropdown.

### Expected result

Square Bulleted List styles should be available in styles dropdown.

### Actual result

Square Bulleted List styles should is available in styles dropdown only when whole UL element is selected (can be done with element's path at the moment).

## Other details

* Browser: ANY
* OS: ANY
* CKEditor version: 4.7.2
* Installed CKEditor plugins: 

**The same thing is happening for tables so Object styles are affected in general. **

**Comment by msamsel** [comment]
Bug has appear after #646.

**Comment by msamsel** [comment]
It seems that restoring previous functionality shouldn't be so hard. There would be analysed only start of selection what should be the same what we have in previous versions.
Replace `getSelectedElement()` with `getStartElement()` here: https://github.com/ckeditor/ckeditor-dev/blob/da389f9f08a8df4562ce14ae02ad215dd510c454/plugins/stylescombo/plugin.js#L145

-----
But still entire menu seems to be a little bit buggy.
In case of selection like below, square option won't appear:
```html
<p>Li[st</p>
<ul>
    <li>One</li>
    <li>T]wo</li>
    <li>Three</li>
</ul>
<p>New paragraph.</p>
```

In case of selection like below, square option will appear but pressing it won't apply it to the element:
```html
<p>List</p>
<ul>
    <li>One</li>
    <li>T[wo</li>
    <li>Three</li>
</ul>
<p>New ]paragraph.</p>
```

Squares also won't be applied in case of such situation:
```html
<ul>
	<li>O[ne</li>
</ul>
<ul>
	<li>Tw]o</li>
</ul>
```

Fixing those cases would require much more work on it.

**Comment by wimleers** [comment]
This bug was reported _twice_ against Drupal 8.4, which was released a week ago.

See https://www.drupal.org/node/2911749.

We'd appreciate it if this could be fixed in a 4.7.x release, rather than having to wait for a 4.8.x release.

**Comment by jonnott** [comment]
Please get this fix out as soon as humanly possible - I'd say it's a critical bug, and it's causing problems for many of my users.

**Comment by mlewand** [comment]
@wimleers sorry that you guys had to wait for it till, 4.8.0 - unfortunately we were unable to get it in earlier.

@jonnott it's already merged to the major branch and waiting to be released. You can preview it in our [nightly demos](http://nightly.ckeditor.com). 4.8.0 is scheduled at Dec 5th.
