### ISSUE TITLE
Typing into selected table throws an error

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-dev#867]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://sdk.ckeditor.com/samples/table.html
2. Select whole table using elements path.
3. Type any letter.

### Expected result

Table is replaced with typed text.

### Actual result

Table is replaced with typed text, but at the same moment error is thrown:

> Uncaught TypeError: Cannot read property 'type' of null

## Other details

* CKEditor version: 4.7.0+
* Installed CKEditor plugins: tableselection

**Comment by Comandeer** [comment]
It seems that the proposed fix introduced new issue:

1. Open CKEditor sample.
2. Open browser's console.
3. Insert table with nested table.
4. Select outer table.
5. Blur the editor.
6. Refocus the editor, but doesn't change the selection.
7. Press <kbd>Delete</kbd>.

**Expected result:**

Table is removed.

**Actual result:**

Table is removed, but there are warnings in the console:

> [CKEDITOR] Error code: range-startcontainer.

> Error code: range-endcontainer.

**Comment by mlewand** [comment]
The reason for above is #873, I'll extract this case into a separate case.
