### ISSUE TITLE
CTRL + C without selected text clears the clipboard buffer

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor-dev#869]
## Are you reporting a feature request or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Select and copy text from another application.  
2. Paste the selected content into a text editor to make sure it was copied.
3. Place cursor in CKEditor without selecting any text.
4. Use CTRL+C to copy
5. Paste the "copied" text to a text editor.

### Expected result
The copy buffer should still have the copied text that existed in it before the steps above.  This is consistent with other applications where hitting CTRL + C when text isn't selected does not modify the active contents of the clipboard.   CTRL + C without selected text is handled this way because it only occurs when a user does it accidentally.

This is reproducible on the CKEditor demo page.
 
### Actual result
The copy buffer is cleared.

## Other details

* Browser:  Chrome/Firefox
* OS: Windows 10
* CKEditor version:  4.7.2
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Fixed in #890 (https://github.com/ckeditor/ckeditor-dev/commit/59c8722484ce4f45d8e3f0693981671f063cdd98).
