### ISSUE TITLE
Integrating filebrowser in CKeditor while uploading image getting error as Image Source URL is missing.

### ISSUE THREAD

**Issue by ashalathapalagiri** [ckeditor/ckeditor-dev#880]
## Reporting Bug

Integrated File browser plugin in CKEditor and enabled the plugin by adding these two lines.

config.extraPlugins = "imagebrowser";
config.extraPlugins = "filebrowser";
config.filebrowserBrowseUrl= '/browser/browse.php';
config.filebrowserImageBrowseUrl= '/browser/browse.php?type=Images';
config.filebrowserUploadUrl= '/uploader/upload.php';
config.filebrowserImageUploadUrl= '/uploader/upload.php?type=Images';
config.filebrowserWindowWidth= '640';
config.filebrowserWindowHeight= '480';

Selecting an image and upload is working fine but when clicking on Ok button it is displaying as " Image soure URL is missing ".

**Comment by msamsel** [comment]
Hi @ashalathapalagiri,
in your config you're overwrite `extraPlugins` attribute so `imagebrowser` seems to be not added.
Please take a look at our documentation: https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-extraPlugins. You should have combined those two lines into one to have properly defined extraPlugins.:
```
config.extraPlugins = "imagebrowser,filebrowser";
```

**Comment by ashalathapalagiri** [comment]
I have solved this issue by installing kcfinder

**Comment by woshiyushengzhou** [comment]
> I have solved this issue by installing kcfinder

hi ashalathapalagiri, I am trying to use KcFinder, but when I copy and paste images I am not getting the correct response
