### ISSUE TITLE
paste as plain text and allow html with styles same time

### ISSUE THREAD

**Issue by moizriaz** [ckeditor/ckeditor-dev#882]
Is there any way to do **paste as plain text** and **allow HTML with styles** same time in CKEditor text editor.
if use paste as plain text functionality than its remove my style from code, or if I try to allow HTML with styles functionality so it does not allow me to paste as plain text. 

I see that functionality working in MailChimp website but I do not understand how they did it.

**Comment by mlewand** [comment]
Sorry, I don't understand your issue. You either paste as plain text **or** you paste as HTML with styles. You can't do both at the same time, that's the point of feature, and that's how they differ.

**Comment by moizriaz** [comment]
Thank you, sir,  for quick reply I am looking to working like that
Mailchimp as I attached in word document

**Comment by mlewand** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
