### ISSUE TITLE
Content after emoji deleted, Embed twitter.

### ISSUE THREAD

**Issue by jvrdom** [ckeditor/ckeditor-dev#884]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to a tweet a get the blockquote to insert
2. Open CKEditor
3. Paste the blockquote from twitter
4. Click on button save.

### Expected result

That the full tweet embeded on the CKEditor.

### Actual result

The tweet is embeded, but all the content after a emoji is erased.

## Other details

* Browser: Chrome
* OS: Mac, Linux
* CKEditor version: 4.7
* Installed CKEditor plugins: Media Embed

**Comment by mlewand** [comment]
Can you try to repro it on https://sdk.ckeditor.com/samples/mediaembed.html page? I have tried an example [tweet with emoji in the middle](https://twitter.com/m_lewand/status/889824545569419269) and it does work well for me.

Checked on Chrome/FF on Win10 though, so clipboard integration might differ slightly.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
