### ISSUE TITLE
Codesnippet prevents Full HTML page load Drupal 7

### ISSUE THREAD

**Issue by mfuller526** [ckeditor/ckeditor-dev#885]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …The codesnippet plugin downloaded the builder version is different from the one downloaded separately. It does not have plugin.js. This caused fll HTML not to load in drupal 7
2. …
3. …

### Expected result
page loading
*What is the expected result of the above steps?*
page loading
### Actual result
blank page
*What is the actual result of the above steps?*

## Other details

I have no log error but it still does not working. Turning off my ise codesnippt request made the page load.

* Browser: …FFx
* OS: …10.6.8
* CKEditor version: …
* Installed CKEditor plugins: …many

**Comment by msamsel** [comment]
Hi,

I need more details how to reproduce the problem on my side, to fully understand the problematic case.
Please take a look into my example. https://codepen.io/msamsel/pen/JrjaBM?editors=1010 It's working fine for me.
Please give me more information how you build editor, and what do you use to build it (page builder or repository builder or sth else?).
Is there any errors in the console or other problems except blank page?

**Comment by mfuller526** [comment]
Drupal 7 installation. Full ckeditor download plus added a few plugins.
![filezillascreensnapz001](https://user-images.githubusercontent.com/1572817/30407642-5546ac64-98ae-11e7-9c23-3b44a1780f37.png)

**Comment by wwalc** [comment]
This is a CKEditor 4 issue tracker, in order to reproduce the issue please provide a set of steps that require only using HTML + JS and do not require installing a CMS. If the issue exists only in Drupal 7 or only together with the CKEditor module in Drupal 7, it should be handled in the [CKEditor module issue tracker](https://www.drupal.org/project/issues/ckeditor).

**Comment by mfuller526** [comment]
DOH! Mea culpa. Did not install downloaded full build ckeditor folder into ckeditor module correctly. Codesnippet does not cause a crash. Thank you for helping!!!

**Comment by mfuller526** [comment]
Problem solved. Error in installing  on D7 site within D7 module. Sorry for hassle. Thank you for writing/helping.
