### ISSUE TITLE
How to show CKEditor Track Changes Tab in sidebar

### ISSUE THREAD

**Issue by ShubhamKabra** [ckeditor/ckeditor-dev#886]
# 1.Already used LITE plugin but it is still not working.Please Help Out.

![capture1](https://user-images.githubusercontent.com/31796943/30239786-41503656-9581-11e7-8655-37b21760f827.PNG)
![capture2](https://user-images.githubusercontent.com/31796943/30239787-415162b0-9581-11e7-9084-3c96815b0826.PNG)

For Reference see This:- https://www.ibfd.org/sites/ibfd.org/files/content/pdf/CMS_CKEditor4%20x_User%27sGuide%20v%200.14.pdf

**Comment by mahiaayush** [comment]
you should need add given changes under `ckeditor>config.js` file.

First - resistor your plugins in extraPlugin variable . 
`CKEDITOR.editorConfig = function( config ) {
	config.plugins = 'artLogDialog,colorbutton,print,dialogui,dialog,basicstyles,,undo,wsc';
}
then you should need register your plugin  with coma secret.
and add tools in config.toolbar = ['lite-toggleshow', 'lite-acceptall', 
	             		    'lite-rejectall', 'lite-acceptone', 
	             		    'lite-rejectone','lite-previous','lite-next',
	             		    'changePreviousTrack', 'changeNextTrack', 'roleChange'];

**Comment by msamsel** [comment]
Hi @ShubhamKabra,

please follow our template for creating bug or feature request. Currently your description doesn't provide information how to reproduce problem. What exactly problem you have, and in what environment it appears. If you want to report bug please add those information, so we will be able to reproduce problem on our side.

In case that you have problem with installation or using CKEditor, then GitHub is not proper channel to get such help. Please get familiar with our [support information](https://github.com/ckeditor/ckeditor-dev/blob/master/.github/SUPPORT.md).

**Comment by ShubhamKabra** [comment]
hi @mahiaayush 
I am unable to find some plugins like artLogDialog,wsc and some tools like 'changePreviousTrack', 'changeNextTrack', 'roleChange'. I checked cdeditor site but its not over there also please help me with this. 
If u have any demo then please share it with us.

**Comment by ShubhamKabra** [comment]
Hi @msamsel 
Can you please provide the link of template so that it will be easy for us to get the solutions.

**Comment by msamsel** [comment]
It's automatically added when you create a new issue. Below you can find this same template :)
Most important information for me is:
- information what you consider as a bug
- what steps I need to make to reproduce this same error on my computer
- what is your environment setup, which version of CKEditor do you use, what plugins do you have installed in CKEditor, what browser and OS do you use.
- really helpful might be also preparing some code snippet or example, where problem occurs, on page such as: codepen.io, jsfiddle.net, etc.

----
```
## Are you reporting a feature request or a bug?

<!--
Replace this comment with your issue type: Bug / Feature request / Other, please explain.

Please **do not report security issues here**, use the contact form at http://cksource.com/contact instead.
-->

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …
```

**Comment by ShubhamKabra** [comment]
We are unable to display the track changes which shows the changed and deleted data in sidebar. As above i have mentioned. Just show me how to display in that pattern which i have asked the first time.

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.5
* Installed CKEditor extra  plugins: LITE,Lance.

**Comment by ShubhamKabra** [comment]
We are unable to display the track changes which shows the changed and deleted data in sidebar. As above i have mentioned. Just show me how to display in that pattern which i have asked the first time.

Browser: Chrome
OS: Windows
CKEditor version: 4.5
Installed CKEditor extra plugins: LITE,Lance.

**Comment by msamsel** [comment]
@ShubhamKabra is this issue still valid? You closed it and I'm not sure that you expect to still check it? Please also check the actual version of CKEditor (4.7.3), and without third part plugins. 
If issue is actual, please provide steps to reproduce bug.
If you not report a bug, but you have support questions please get familiar with our [support information](https://github.com/ckeditor/ckeditor-dev/blob/master/.github/SUPPORT.md).

**Comment by ShubhamKabra** [comment]
We installed the CKEditor (4.7.3) and we did the changes in the editor and tried to get DATA(the selected area within image)

we had fired this event and got the data  ------>  lite.findPlugin(state.editor).getChanges();
![capture](https://user-images.githubusercontent.com/31796943/30631231-233ac8ba-9e01-11e7-9e3a-a173f390cca3.PNG)

**Comment by msamsel** [comment]
@ShubhamKabra you refer to **third party plugin** not supported by CKEditor team. If mention problem is related to these plugins only, then please contact with its author.

In case that problem is in CKEditor, please follow with information from my previous comment I need information how to reproduce the problem with step by step guid **without third party plugins**. Your current description don't allow me on reproducing problem.
