### ISSUE TITLE
Unclear error message for width and height fields

### ISSUE THREAD

**Issue by b2m** [ckeditor/ckeditor-dev#889]
## Are you reporting a feature request or a bug?

This is a duplicate of the Bugreport by Anjaneyulu on https://dev.ckeditor.com/ticket/14280. It regards the error message shown for invalid values in the width and height fields that are available in the dialogs for images and possibly more.

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

 * https://dev.ckeditor.com/ticket/14280

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/standardpreset.html
2. Open Image Dialog
3. Enter a **number** into the width or height field like: 0, -200, or 3.1415926
4. Click Ok.

### Expected result

An error message should be shown describing valid values for the width and height fields.
Something like _Width must be a natural number > 0_

### Actual result

The shown error message says _Width must be a number_.

## Other details

* CKEditor version: 4.7.2

**Comment by wojtekw92** [comment]
Hi @b2m,
thank you for creating issue. Are you sure that you can reproduce this issue on 4.7.2? 
When I try to reproduce this issue on http://cdn.ckeditor.com/4.7.2/full-all/samples/
I'm getting proper error message:
![screen shot 2017-09-11 at 10 36 33](https://user-images.githubusercontent.com/7364832/30265776-7ffcb05c-96dd-11e7-985d-fec8427a3de1.png)

**Comment by b2m** [comment]
Hi @wojtekw92 

Reproduced with the **images** dialog on 4.7.2
Not with the tables dialog => modified my error description accordingly.
