### ISSUE TITLE
where-is-the-code-in-ckeditor-keypress-handling-in-case-of-a-anchor-element

### ISSUE THREAD

**Issue by mahiaayush** [ckeditor/ckeditor-dev#892]
https://stackoverflow.com/questions/46156648/where-is-the-code-in-ckeditor-keypress-handling-in-case-of-a-anchor-element
 I have a question related ckeditor please someone guide me.
 if we have ckeditor contents like blow:
`<p>hello this is a <a href="url">link</a> test</p>`
and when we put cursor at the place  of ^  in `<a href="url">link^</a> test</p>` and start to type something then we got that we are typing at `<a href="url">link</a>^ test</p>` 
where is the code which we set the cursor at the end of `a` element. please guide because in my ckeditor have costume element xref and i want same behavior/activity on that. 
looking for positive reply.

**Comment by msamsel** [comment]
Hi,

this kind of behaviour is browser specific and it's not related to CKEditor. Please check how it works natively without CKEditor. You can also find out that this behaviour differ between browsers, e.g. Firefox detect from which side you access this place (from link side or paragraph side - you can test by moving cursor with arrow keys) and according to it text might be added to link or to paragraph.
We doesn't consider this behaviour as a bug. This is a way how browser work with `contenteditable="true"` elements, what includes how browser work with CKEditor.

Example with native element: https://codepen.io/msamsel/pen/NaKooX
