### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier on Chrome when loading ckeditor.js

### ISSUE THREAD

**Issue by Olo-Burrows** [ckeditor/ckeditor-dev#893]
Hello,

We have a JavaScript error in the Chrome console when we load ckeditor.js file. This error is only on the last version of Chrome : *61.0.3163.79*.
![2017-09-12 11-39-07](https://user-images.githubusercontent.com/6861747/30319145-68c027e8-97af-11e7-8022-ad6dfb696ec0.png)
![2017-09-12 11-41-43](https://user-images.githubusercontent.com/6861747/30319146-68cd5148-97af-11e7-812f-87d6915b9255.png)

**Comment by mlewand** [comment]
It's very unlikely that the produced build has any sort of syntax error. Can you download the source code once again? Maybe it got corrupted or something?

Obviously our editor is loading with [the latest build](http://cdn.ckeditor.com/4.7.2/standard-all/samples/) so it's my assumption that this particular file is somehow corrupted.

**Comment by Olo-Burrows** [comment]
We just find the cause of the problem. A BOM caractère is present at the beginning of the _ckeditor.js_ file. This BOM is a problem for us because we aggregate files before and after your file. After that, the caracter is present at the middle of the result file and Chrome 61 can't interpret it and throw an exception.

Can you tell us if it's normal or an invalid caracter ?

Thank you.
![2017-09-12 15-53-54](https://user-images.githubusercontent.com/6861747/30329462-9fc6a758-97d2-11e7-870c-2e4822a1b334.png)

**Comment by mlewand** [comment]
It's perfectly fine for UTF files to include BOM, in that case it's up to your builder to strip BOM characters from concatenated files.

**Comment by thE-iNviNciblE** [comment]
i've the same proble 4.1.6
