### ISSUE TITLE
image2 addon does not support link ?

### ISSUE THREAD

**Issue by simogeo** [ckeditor/ckeditor-dev#894]
## Bug

Bug on adding link on image (with image2 addon)

## Provide detailed reproduction steps (if any)

1. use [image2 addon](https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/image2)
2. insert image 
3. select image
4. insert link 
5. **link is not created ....**

It works well with on instance of CKeditor only, but does not work when several

### Expected result

A clickable image (link on image) ...

### Actual result
Link is not created .... there is no <a> tag in html source.

## Other details

* Browser: FF 55.0.2 (64 bits)
* OS: ubuntu 16.04
* CKEditor version: 4.71
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
Hi,

I'm not able to reproduce this error. Take a look into my example: https://codepen.io/msamsel/pen/wrBypM. I'm able to select image and create link for it. As result I get `img` tag surrounded with an `a` tag. Could you check my test page and give a little more info how can I reproduce this issue?

**Comment by simogeo** [comment]
Hi @msamsel and thanks for your reply,

Your working example put me on the right way. Actually, it works when one instance of CKeditor only is present. But having 2 instances or more in the same page, it seems ckeditor is lost .... and it does not work anymore.

**Comment by msamsel** [comment]
Could you provide such example in codepen, jsfiddle, jsbin, etc.? So I'll be have the same testing environment.

**Comment by simogeo** [comment]
Here is the codepen and actually it works well ! https://codepen.io/anon/pen/Bwyrmw

I have some more plugins on my app and have to test all this myself ! Sorry for disturbing. I guess the issue is mine. I close the issue and will reopen it if necessary only.

Thanks for your time.
