### ISSUE TITLE
Extending link plugin

### ISSUE THREAD

**Issue by simogeo** [ckeditor/ckeditor-dev#911]
## Technical issue / advice

Hi all,

I extended link plugin to be able to link to my local CMS pages. I created a new plugin named "adv_link" not to erase link default addon.
But I have an issue because I'm now using image2 plugin which is directly connected  to link addon to handle correctly things .... Using [my advanced plugin](https://github.com/simogeo/ckeditor-adv_link) and image2, I'm getting some [troubles as identified here](https://github.com/ckeditor/ckeditor-dev/issues/894).

I thought "ok, let's overwrite default link addon " but this is not possible since the plugin itself, is now integrated into the core js file. So, I'm not able to tweak `plugin.js` function neither to add lang variables to handle multiple langage.

My question is simple. How should I do ? Thansk for your answer

### Expected result

working link plugin with image2 support

## Other details

* Browser: FF 55.0.2 (64 bits)
* OS: ubuntu 16.04
* CKEditor version: 4.73
* Installed CKEditor plugins : image2, link

**Comment by msamsel** [comment]
Hi,
it's not necessary to integrate plugins into core file to have worked one.
You can use our repository locally, use some simple http server and open this file `samples\index.html`. You will see that plugins are not integrated in this case.
It's necessary to remember about proper folder structure when you add your own plugin. More information you can find here: https://docs.ckeditor.com/#!/guide/plugin_sdk_sample_1

**Comment by simogeo** [comment]
Hi @msamsel : I did not checked yet if your propasal fit my needs but I'll have a look on this later. Anyway, Thanks for replying to me.
