### ISSUE TITLE
CK Editor Rendering as Child for DataView [ExtJS 4.2.1] getting error

### ISSUE THREAD

**Issue by biswas-supriyo** [ckeditor/ckeditor-dev#913]
## Couple of Bugs:

**_Issue 1:_**
**Steps to Replicate:**
Step 1: Open/Render CK Editor [as a child component for a DataView EXTJS 4.2.1].
Step 2: Following Error will get printed in the Console. Still no visible functionality failure as such post getting this issue.

**Error Logs:**
ckeditor.js:61 Uncaught TypeError: Cannot read property 'insertBefore' of null
    at CKEDITOR.dom.element.insertAfter (ckeditor.js:61)
    at b (ckeditor.js:336)
    at a.<anonymous> (ckeditor.js:332)
    at a.m (ckeditor.js:10)
    at a.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at a.fireOnce (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fireOnce (ckeditor.js:13)
    at Object.<anonymous> (ckeditor.js:255)
    at f (ckeditor.js:235)

_Need Solution to fix or avoid getting this error._

**_Issue 2:_**
**Steps to Replicate:**
Step 1: Open/Render CK Editor [as a child component for a DataView EXTJS 4.2.1].
Step 2: "top/about:blank" URL been hit every time ckeditor rendered. If any screen has 50 such rendering. Screen suffering Performance issue.

**Warning Logs:**
The "SimpleUploads" plugin now is disabled.

_Need Solution to fix or avoid getting this warning and URL request._

**Comment by wojtekw92** [comment]
Hi,
are you able to reproduce this issue on http://cdn.ckeditor.com/4.7.2/full-all/samples/?

**Comment by biswas-supriyo** [comment]
Hi,

As mentioned in the post, by default its working. But when the mentioned steps in the bug post are followed, issue can be replicated.

Not aware of any solution.

**Comment by wojtekw92** [comment]
Hi, as you said issue is not on our side so its problem with integration, please inform integration creators about the issue.

**Comment by biswas-supriyo** [comment]
Hi,

For Issue 1, I think if we have a null check for the "insertBefore" it will resolve the issue. Its now missing.
For Issue 2, any reason why  "top/about:blank" URL been hit every time ckeditor rendered?

**Comment by wojtekw92** [comment]
Can you move issue 2 to other issue report?
null check is not a resolution its only workaround. You should find source of the problem.

**Comment by biswas-supriyo** [comment]
issue 2 already moved to new issue 923.

for issue 1, there is a timeout event for toolbar, its difficult to track the source before that event in call trace. After the timeout event handled, parent is null.
