### ISSUE TITLE
Change of mathjax 'title' and 'button' properties in de.js

### ISSUE THREAD

**Issue by manschwa** [ckeditor/ckeditor-dev#915]
I could not find a way to change the 'title' and/or 'button' property defined in the plugin's lang.js file via the config.js file.
I would like to avoid changing it directly inside the lang.js file. So I'm asking you, if you could possibly change it to a more fitting translation in German?

I am suggesting:
**'button': "TeX-Formel einfügen"
'title': "TeX-Formel einfügen"**

I also would change the english translation to "Insert TeX equation".

Kind regards,
Manuel

**Comment by mlewand** [comment]
Thanks for the report. All the language changes happen through [CKEditor UI Translation Center](https://www.transifex.com/projects/p/ckeditor/) at Transifex. It features an easy web UI for our end users to convieniently add language entries.

We'd kindly ask you to provide your change there, thanks!
