### ISSUE TITLE
Typing in the editor inserts character in nearby element

### ISSUE THREAD

**Issue by cadilhac** [ckeditor/ckeditor-dev#918]
When caret is placed just at the beginning of a link, typing a character does not prepend this character to the link text. Instead, it puts the character before (and outside) the link. This is the behaviour I want for my own plugin.

I have created a plugin that inserts a span element (with a specific class and attributes). Again, I place the caret just before the first character of this Span element, but when I type a character, it prepends this character to the text of the Span. Why this difference? What should I check/change so that it behaves like links? Note that this happens when the Span is the first element of the line. If (by using the source view) I add a character before the span, then (coming back to the editor) typing a character just before the Span correctly adds it to the text that is before the Span.

**Comment by wojtekw92** [comment]
Hi @cadilhac,
According to our github [SUPPORT file](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md) we do not provide support on our github issue page. This page should be used only for reporting bugs. If you have any development problem or technical question please go to [stackoverflow with ckeditor tag](https://stackoverflow.com/tags/ckeditor).

**Comment by cadilhac** [comment]
Well, I see nothing in the Link code that could explain such behaviour, so I thought this was standard across all ckeditors plugin, and therefore that it could be a bug since I get another behaviour when adding my own plugin.
Btw, I posted a question on stackoverflow, with the ckeditor tag, and got no answer before posting here and referencing the SO post. So, being supported is not that easy...

**Comment by f1ames** [comment]
@cadilhac could you link your SO question here (I wasn't able to find it)?

**Comment by cadilhac** [comment]
@f1ames The SO post is about [another subject](https://stackoverflow.com/questions/46186108/loading-local-ckeditor-plugins-when-a-cdn-is-used-and-chrome-cache).
