### ISSUE TITLE
CKeditor renders in MS Edge but none of the features works

### ISSUE THREAD

**Issue by fdgsogc91** [ckeditor/ckeditor-dev#924]
## bug

**Issue Type:** Bug

**Descriptive Summary:** Using CKeditor 4.7.3.  Works in my ColdFusion site using IE 11 but not MS Edge. None of the buttons work.  Can't even select text that I've typed.

**Steps to Validate Issue:** I went to the sample HTML file provided to test and configure the ckeditor.  It works just fine in MS Edge.  No issues.  However, I noted a major difference in my implementation of ckeditor vs the sample.  I am using the recommended TEXTAREA replace implementation.  But the CKEditor sample is using a DIV implementation.  This is not a fair comparison of the issue.  I need a TEXTAREA sample to compare to if you want me to give you more details on the issue than what I have provided below.

**Steps to Reproduce:** 
1. Downloaded, unzipped and uploaded version 4.7.3 of CKeditor to my website (where I've been using CKeditor for years).
2. Named the folder ckeditor_4.7.3
3. I use the <textarea> format to render the ckeditor.  So I updated the path in the script in my <head> tag: <script src="ckeditor_4.7.3/ckeditor.js"></script>
4. This is my code for the textarea tag:
            <textarea name="dialoguecomment" id="dialoguecomment"></textarea>
            <script>
                CKEDITOR.replace( 'dialoguecomment' );
            </script>
5. I customized the ckeditor using the toolbar configurator in the sample folder.  Just hid and moved around some buttons. This is my updated config.
`/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';

	config.toolbarGroups = [
		{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ name: 'forms', groups: [ 'forms' ] },
		{ name: 'links', groups: [ 'links' ] },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		'/',
		{ name: 'tools', groups: [ 'tools' ] },
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'colors', groups: [ 'colors' ] },
		{ name: 'others', groups: [ 'others' ] },
		{ name: 'about', groups: [ 'about' ] }
	];

	config.removeButtons = 'Flash,Iframe,Language,Button,ImageButton,HiddenField,Select,Textarea,TextField,Radio,Checkbox,Form,Save,Preview';

  config.width = "95%";

};
`

* Browser: …Microsoft Edge
* OS: …Windows  10
* CKEditor version: … 4.7.3
* Installed CKEditor plugins: … all from the Full Package

**Comment by msamsel** [comment]
Hi,

do you see any error in Edge console? Can you prepare separate example on page like: codepen.io, jsfiddle.net, etc.?

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by fdgsogc91** [comment]
Hoping adding a comment will reopen this issue.
I have prepared a simple page on my site using CKEditor that demonstrates the issues I'm having in Microsoft Edge.  The reason I installed this version of CKEditor was because is was supposed to deal with MS Edge issues.  Please help me figure out what I've done incorrectly with the installation.  However, note that I am having no issues on Microsoft Internet Explorer.  Thank you.

[https://www.claimscorpinc.com/projects/ztest5.cfm](https://www.claimscorpinc.com/projects/ztest5.cfm)

**Comment by msamsel** [comment]
Hi,
your page contains bunch of syntax errors in HTML. You can check it e.g. [here](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.claimscorpinc.com%2Fprojects%2Fztest5.cfm&charset=%28detect+automatically%29&doctype=Inline&group=0)
It also better to use HTML5 syntax if it's possible for you. Most probably Edge don't know what to do with those errors and behave wrongly.
Please fix errors in your html, if possible update it to HTML5 syntax, and then load CKEditor. As you can see our [test page](https://cdn.ckeditor.com/4.7.3/full-all/samples/) (where is no html errors) works properly on Edge.

**Comment by mlewand** [comment]
@fdgsogc91 also for reference, always check CKEditor 4 official demos for a reference:

* https://ckeditor.com/ckeditor-4
* https://cdn.ckeditor.com/4.7.3/standard/samples

If something works there, and doesn't on your instance, it's a good tell that there's some integration issue going on there.

**Comment by fdgsogc91** [comment]
I really appreciate the assistance with my integration issue of getting CKEditor 4 working on my ColdFusion server in MS Edge.

However, no one has yet directly commented on the fact that the documentation (https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_installation) recommends one implementation of CKEditor 4 and your test page which works on Edge uses a different implementation method.  Below I have provided the recommended code which I have used and the code used by the test page (https://cdn.ckeditor.com/4.7.3/full-all/samples/).  I would appreciate some guidance on how to get the recommended implementation done or please point me to the documentation that describes how to implement per the test page.  I'm sorry that the code snippets are not formatting very well. Thank you in advance for your assistance.

**CODE PER DOCUMENTATION**
&#60;!DOCTYPE html&#62;
&#60;html&#62;
    &#60;head&#62;
        &#60;meta charset="utf-8"&#62;
        &#60;title&#62;A Simple Page with CKEditor&#60;/title&#62;
        &#60;!-- Make sure the path to CKEditor is correct. --&#62;
        &#60;script src="../ckeditor.js"&#62;&#60;/script&#62;
    &#60;/head&#62;
    &#60;body&#62;
        &#60;form&#62;
            &#60;textarea name="editor1" id="editor1" rows="10" cols="80"&#62;
                This is my textarea to be replaced with CKEditor.
            &#60;/textarea&#62;
            &#60;script&#62;
                // Replace the &#60;textarea id="editor1"&#62; with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            &#60;/script&#62;
        &#60;/form&#62;
    &#60;/body&#62;
&#60;/html&#62;


**CODE PER TEST PAGE**
	&#60;div class="adjoined-bottom"&#62;
		&#60;div class="grid-container"&#62;
			&#60;div class="grid-width-100"&#62;
				&#60;div id="editor"&#62;
					&#60;h1&#62;Hello world!&#60;/h1&#62;
					&#60;p&#62;I'm an instance of &#60;a href="http://ckeditor.com" &#62; CKEditor &#60;/a&#62;.&#60;/p&#62;
				&#60;/div&#62;
			&#60;/div&#62;
		&#60;/div&#62;
	&#60;/div&#62;
