### ISSUE TITLE
Balloon Toolbar

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-dev#933]
## Are you reporting a feature request or a bug?

Feature request

 ## Provide detailed reproduction steps (if any)

We need an balloon toolbar component.

This component should be displayed for a provided DOM element - say table, image, etc.

Ideally it would be great if it's compatible with existing DOM interfaces (I'm looking at [CKEDITOR.ui.button](https://docs.ckeditor.com/#!/api/CKEDITOR.ui.button)) - it's fine to use subclass though.

**Comment by mlewand** [comment]
I believe we can use a lot of logic from the [balloon panel](https://github.com/ckeditor/ckeditor-dev/blob/a0ba16d36458847bbc8af4bac73d25657b461340/plugins/balloonpanel/plugin.js) here.

**Comment by mlewand** [comment]
Note we're in the middle of renaming process from Inline Toolbar to Balloon Toolbar, so some old task might refer to it as "Inline Toolbar".

**Comment by mlewand** [comment]
# Internet Explorer 8 Compatibility

During the course of development, we used [`options.cssSelector`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.plugins.balloontoolbar.contextDefinition-property-cssSelector) property, that uses `HTMLElement.matches` property which is not implemented in IE8.

Any other aspect of Balloon Toolbar looks to be working well on IE8, that is:

* `options.widgets`
* `options.refresh`

The toolbar itself positions well and works correctly on IE8, so there's no problem with that too.

So as long as you use `options.refresh` rather than `options.cssSelector` you'll have Balloon Toolbar working well on IE8 too.

**Comment by shibinas** [comment]
2ef
