### ISSUE TITLE
Context menu is not showing when CKEditor is used in JavaFX's WebView

### ISSUE THREAD

**Issue by Jugen** [ckeditor/ckeditor-dev#942]
Bug

*Previously reported here:  https://dev.ckeditor.com/ticket/13035*

## Provide detailed reproduction steps (if any)

1. Create JavaFX application, example:
```java    
   public class CkTest extends Application
   {
       public static void main( String[] args )
       {
           launch( args );
       }
    
       @Override
       public void start( Stage primaryStage )
       {
           WebView  web = new WebView();
           System.out.println( web.getEngine().getUserAgent() ); // Webkit version
           web.getEngine().load( "https://ckeditor.com" );
           primaryStage.setScene( new Scene( web ) );
           primaryStage.show();
       }
   }
```
2. Launch application and scroll down to CKEditor instance.
3. Right click inside editor, or create a table and right click a cell.

### Expected result

*Paste or Tabletools context menu should show.*

### Actual result

*Cursor moves to location of right click, but no context menu is displayed.*

## Other details

* Browser: JavaFX (version 8.0.141) WebView
* OS: Windows 7, 8, and 10
* CKEditor version: 4.1.1 - 4.7.2
* Installed CKEditor plugins: Full Package

**Comment by msamsel** [comment]
Hi @Jugen,
unfortunately JavaFX is not officially [supported environment](https://docs.ckeditor.com/#!/guide/dev_browsers). It's possible that JavaFX is missing some features available in regular browsers, what cause this situation. There is slight chance that someone from the community on StackOverflow had similar problem and will be able to help you. Unfortunately here we can't do more.
