### ISSUE TITLE
What ist the right value for CKEDITOR_BASEPATH if building distribution Version from my SPA

### ISSUE THREAD

**Issue by Csini** [ckeditor/ckeditor-dev#943]
## Reproduction steps

1. using something like this starter-pack: https://github.com/scokmen/angularjs-gulp-boilerplate
all the js code from all the bower_components are concatenated to one libsXXX.js and it is so imported into my index.html
2. I'm using angular-ckeditor:
bower install angular-ckeditor --save
3. adding ckeditor:
 bower i ckeditor --save
4. add to the html
  <textarea ckeditor="vm.options" ng-model="vm.testck"></textarea>
5. do Production Build (concatenate libsXXX.js)
$ gulp build:prod (or "npm run production")
$ gulp server:prod

### Expected result

I'm not getting any error, CKEditor is working fine.

### Actual result

I'm getting this error:
libs-fd69678c5c.js:200000 Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.f (libs-fd69678c5c.js:200000)
    at g (libs-fd69678c5c.js:200001)
    at Array.n (libs-fd69678c5c.js:200002)
    at q (libs-fd69678c5c.js:200002)
    at libs-fd69678c5c.js:200002

## Other details

Your Documentation says, that I should set the global CKEDITOR_BASEPATH and it will solve my problem. What is the right value for this variable in my case? (I don't have any separate ckeditor.js nowhere in my dist Package. The main point is, that all the js code from all the bower_components are concatenated to one libsXXX.js and it is so imported into my index.html

* Browser: does not matter
* OS: does not matter
* CKEditor version:  "ckeditor": "#full/4.4.6",
* Installed CKEditor plugins: -

**Comment by Csini** [comment]
https://ckeditor.com/forums/CKEditor/CKEditor-problem-after-a-grunt-build

**Comment by Csini** [comment]
https://stackoverflow.com/questions/15301099/ckeditor-4-build-minify-and-uglify

**Comment by cention-mujibur-rahman** [comment]
Hello Csini, the concatanated js file only included ckedior.js but rest of the plugins are not included. Please do following to resolve it.
1. symlink the ckeditor folder from bower_components directory or wherever the ckeditor folder exists to your webserver root path.(lets say /opt/lamp/<your-root-dir>/ckeditor)
2. set basePath like `window.CKEDITOR_BASEPATH` = location.origin + '/ckeditor/";` location.origin would be like `https?http://localhost` 
after that restart web server and then the minified js will work for ckeditor plugins etc.

**Comment by msamsel** [comment]
Hi @Csini,
angular is not officially supported platform by CKEditor team. It's custom integration made by the community.
If `basePath` is the same thing as in our official docs, then you can take a look into our [docs](https://docs.ckeditor.com/#!/api/CKEDITOR-property-basePath) and adapt it to your project.

Please also notice that GitHub is platform to report bug or features requests. If you need support assistance please take a look into [this file](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md), to get more information about possible options.

**Comment by Csini** [comment]
Thank you!
