### ISSUE TITLE
Can not insert a paragraph after blockquote tag alone

### ISSUE THREAD

**Issue by ma44a** [ckeditor/ckeditor-dev#944]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

When you start editing blank ckeditor field, and click on blockquote, it is impossible to get out of quote element without going to source code.

### Expected result

Could you please enable clicking outside the blockquote through gui in order to exit the blockquote tag?

## Other details

* Browser: all
* OS: ALL
* CKEditor version: all
* Installed CKEditor plugins: 4.7

**Comment by mlewand** [comment]
This is a feature request, and actually this is exactly what the [Magic Line](https://ckeditor.com/addon/magicline) plugin does. It's by default included in standard / full preset.

![Magic Line plugin used to insert a new line after the blockquote](https://user-images.githubusercontent.com/5353898/30643554-c075c392-9e0f-11e7-8bb4-11b50e826fc7.gif)

As for keyboard users, use double enter to get out of the blockquote.
