### ISSUE TITLE
Pasting text as an image if copied text from ONENOTE

### ISSUE THREAD

**Issue by AhmadRaza786** [ckeditor/ckeditor-dev#947]
## Pasting text as an image if copied text from ONENOTE

![untitled](https://user-images.githubusercontent.com/23386374/30683484-0e16b0a4-9ec7-11e7-93e1-60bfd6e8d839.png)

**Comment by mlewand** [comment]
This issue request doesn't have almost any information.

To report issues use [our template](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md) as you skipped a lot of key information. On top of that writing the description in image is not a good idea, as it's not indexable by searching engines and is inaccessible.

**Comment by asimkhan034** [comment]
having same issue.. I've one note installed in my machine, and whenever i copy text from one note application and paste it in CKEditor, Text is pasted along an image. don't know how this image is being created of the same text. kindly review. Thanks
