### ISSUE TITLE
Issues with implementing angular2-hotkeys

### ISSUE THREAD

**Issue by prashu-a** [ckeditor/ckeditor-dev#954]
I am implementing Angular2 Hotkeys as in below article,
http://lostindetails.com/blog/post/Hotkeys-in-Angular2

In app.module.ts:
import { HotkeysService, Hotkey } from 'angular2-hotkeys';
@NgModule({
  imports: [
    BrowserModule, HttpModule, FormsModule, ReactiveFormsModule, DpDatePickerModule, ImageCropperModule, private _hotkeysService: HotkeysService
  ]

When I add reference to HotkeysService, I get below error,

Error: (SystemJS) Unexpected token <
SyntaxError: Unexpected token <
at eval (<anonymous>)
at Object.eval (http://localhost/angular2/entity/services/HotkeyService.js:14:26)
at eval (http://localhost/angular2/entity/services/HotkeyService.js:73:4)
at eval (http://localhost/angular2/entity/services/HotkeyService.js:74:3)
Evaluating http://localhost/Profile/Select/angular2-hotkeys.js
Evaluating http://localhost/angular2/entity/services/HotkeyService.js
Evaluating http://localhost/angular2/entity/app.module.js
Evaluating http://localhost/angular2/entity/boot.js
Error loading http://localhost/angular2/entity/boot.js
at eval (<anonymous>)
at Object.eval (http://localhost/angular2/entity/services/HotkeyService.js:14:26)
at eval (http://localhost/angular2/entity/services/HotkeyService.js:73:4)
at eval (http://localhost/angular2/entity/services/HotkeyService.js:74:3)
Evaluating http://localhost/Profile/Select/angular2-hotkeys.js
Evaluating http://localhost/angular2/entity/services/HotkeyService.js
Evaluating http://localhost/angular2/entity/app.module.js
Evaluating http://localhost/angular2/entity/boot.js
Error loading http://localhost/angular2/entity/boot.js

I do not see angular2-hotkeys.js in node_modules folder / subfolders.

In case the above error is because of missing angular2-hotkeys.js, anyways to create it?

**Comment by mlewand** [comment]
We do not provide / support any Angular implementation. Please reach out to the original maintainer.

**Comment by prashu-a** [comment]
Even with the reference from https://www.npmjs.com/package/angular2-hotkeys is not supported?

Cause I see the above article redirecting to github.com for issues.
