### ISSUE TITLE
File is not an image

### ISSUE THREAD

**Issue by jonlaurie** [ckeditor/ckeditor-dev#959]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

Uploading image using config.extraPlugins = 'imageuploader';

### Expected result

Image upload

### Actual result

*What is the actual result of the above steps?*
Alert: This site says... File is not an image.

Warning: getimagesize(): Filename cannot be empty in: [pathname to my file ]imguploadphp on line 44
## Other details

* Browser: Edge/Chrome/IE/Firefox/Safari
* OS: Win 10
* CKEditor version: CKEditor 4.6.2
* Installed CKEditor plugins: imageuploader

**Comment by beatadelura** [comment]
This is a third party plugin not maintained by the CKEditor team.

Please contact with plugin's author to report the problem. You'll always find plugin's contact details on it's [addon repository page](https://ckeditor.com/addons/plugins/all).

You can also try to use CKeditor plugin for uploading images https://ckeditor.com/addon/uploadimage
