### ISSUE TITLE
Workaround for Edge not supporting custom MIME types in `dataTransfer.setData`

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#962]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Extracted from #468.
Upstream issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8007622.

The Edge browser still does not support custom MIME types in `dataTransfer.setData`. This are used in `clipboard` plugin for storing `dataTransfer` id (which is used to much dataTransfer objects between events).

The proposal is to apply a workaround which will save custom MIME types in `text/html` MIME type as an HTML comment like:

```
<!--cke-data:DATA-->
```

Where `DATA` is [stringifed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and [encoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) JSON object.

This will happen dynamically as Edge throws an error/exception when custom MIME types is set. The exception will be caught and fallback used.

**Comment by f1ames** [comment]
There is one specific issue I stumbled upon when working on the fix:

1. Go to http://tests.ckeditor.dev/tests/plugins/clipboard/manual/buttons.
2. Perform copy and paste (as in scenario).

![sep-28-2017 11-55-42](https://user-images.githubusercontent.com/1061942/30971287-c74cf790-a467-11e7-8d79-73f0a26524f4.gif)

`OpenClipboard Failed` error is thrown (in this line - https://github.com/ckeditor/ckeditor-dev/blob/t/468-962/plugins/clipboard/plugin.js#L2095). Looks like some Edge issue with synchronous access to clipboard on paste. Haven't found any reports on https://developer.microsoft.com/en-us/microsoft-edge/platform/issues, but clearly looks like native issue.

---

I wasn't able to reproduce this issue with plain contenteditable, however `OpenClipboard Failed` error seems to be caused by two or more applications accessing the clipboard at the same time (not sure why it happens here still)... Simply changing the code to access `clipboardData` only once solves the issue - see https://github.com/ckeditor/ckeditor-dev/pull/968/commits/2347c18a4136ec9e9761579d5f0a626b9541d254.

**Comment by f1ames** [comment]
There is one more issue worth mentioning here. While the [code setting a `cke/id` mime type](https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/clipboard/plugin.js#L2173) is executed in all normal flows (copy/paste, drag/drop), the id is not set in `native dataTransfer` object for external transfers (browsers with `CKEDITOR.plugins.clipboard.isCustomDataTypesSupported = true`).

It happens due to a fact that for such transfers the `CKEDITOR.plugins.clipboard.dataTransfer` object is created on `paste` or `drop` event and there setting or editing native `dataTransfer` mime types has no effect (see [this demo](https://jsfiddle.net/859hfs37/10)). The `cke/id` is however stored locally in `CKEDITOR.plugins.clipboard.dataTransfer` object which is fine as it does not have to be passed to any further events.

However, the `paste` behaviour in Edge browser is quite different which causes an issue here:

* The `drop` behaves the same as in other browsers so setting/editing mime types on `drop` has no effect on `native dataTransfer`.
* The `paste` behaviour allows to set/edit mime types, **however when setting new mime type all others are cleared (making them empty)** - this causes an issue when plain text (`text/plain` mime type) is copied and on `paste`, the `cke/id` comment is set as `text/html` which clears `text/plain` mime types contents.

The solution might be resetting all available mime types (so `set( type, get( type ) )` ) as it solves the problem with resetting mime types.

**Comment by f1ames** [comment]
Reported issue with `dataTransfer store` not in readonly mode on paste here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14038089/.

**Comment by mlewand** [comment]
> The solution might be resetting all available mime types (so nativeDataTransfer.setData( type, nativeDataTransfer.getData( type ) ) ) as it solves the problem with resetting mime types.

This is just a hack relying on current browser implementation bug.

Instead the problem here is that clipboard api tries to overwrite datatransfer in `paste`/`dragend` events, [even with seeing that it's not a proper way](https://github.com/ckeditor/ckeditor-dev/blob/2170117322e6b3fc359629d8e911e9ad7e783593/plugins/clipboard/plugin.js#L2175).

The solution here would be to fix the source of it, and call (our) `dataTransfer.setData()` with `clipboardIdDataType` only in proper events. Seems like `initPasteDataTransfer` and `initDragDataTransfer` are the best candidate for that.

**Comment by f1ames** [comment]
`OpenClipboard Failed` error issues reported to upstream: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14073387/.

**Comment by f1ames** [comment]
This was closed with its parent task #468 in #1153.
