### ISSUE TITLE
Bug: configuration flag forceSimpleAmpersand does not work

### ISSUE THREAD

**Issue by alexmaris** [ckeditor/ckeditor-dev#965]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/16746#no1
Previously reported in this ticket, but the steps to replicate were not correct. The documentation states that the `forceSimpleAmpersand` flag will  _"force using `&` instead of `&amp;` in element **attributes** values."_ 

(https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-forceSimpleAmpersand)

## Provide detailed reproduction steps (if any)

1. Create a new editor with the `forceSimpleAmpersand` option set to `true` (https://codepen.io/anon/pen/gGmOmW?editors=1010)
1. Switch to Source View
1. Add an `<a>` tag with an `href` attribute that contains an ampersand ex: `<a href="http://www.blah.com?foo=1&bar=2">Test link</a>` 
1. Switch WYSIWYG View
1. Switch back to Source View

### Expected result

Anchor tag href property should remain the same:
`<a href="http://www.blah.com?foo=1&bar=2">Test link</a>`

### Actual result

Anchor tag href property has the ampersand encoded
`<a href="http://www.blah.com?foo=1&amp;bar=2">Test link</a>`

## Other details

* Browser: Chrome Version 60.0.3112.113 (Official Build) (64-bit)
* OS: MacOS
* CKEditor version: 4.7.1
* Installed CKEditor plugins: default plugins

**Comment by mlandmann** [comment]
The sad facts are some websites do not support the &amp; and expect only the & to be there.  thus as is -- CKeditor breaks the URL.  Who gives a damn about the specs -- CKEditor needs to fix this and let the users control what is needed and not force something that doesn't work (sometimes)

**Comment by mw-jko** [comment]
Looks like this problem was introduced with 4.5.0 - with 4.4.8 it works as expected.

**Comment by siemas** [comment]
@alexmaris your commit solves the problem (bug) for me. Cloud you make a pull request for this fix?

**Comment by alexmaris** [comment]
PR submitted, sorry for the delay!

**Comment by mlandmann** [comment]
> The sad facts are some websites do not support the & amp; and expect only the & to be there. thus as is -- CKeditor breaks the URL. Who gives a damn about the specs -- CKEditor needs to fix this and let the users control what is needed and not force something that doesn't work (sometimes)

I wrote this several years ago, and today 6/24/20 it is still an issue.  forceSimpleAmpersand does not work.  CKeditor people,,you are not Google.  We the users of your product wear big pants and can deal with backward compatibility.   Will you get this fixed and stop hiding behind some outdated standards.  I just spent hours on this today.  I have better things to do with my life.

**Comment by f1ames** [comment]
@mlandmann I see this issue was fixed some time ago in #2416 and #2418. However, if you still experiencing any problems with this configuration option please [open a new issue](https://github.com/ckeditor/ckeditor4/issues/new?assignees=&labels=type%3Abug&template=1-bug-report.md&title=) describing your case and reproduction steps.
