### ISSUE TITLE
Executing editor.destroy() during image upload throws error

### ISSUE THREAD

**Issue by MaksimMakarevich** [ckeditor/ckeditor-dev#966]
## Are you reporting a feature request or a bug?
Bug 

## Provide detailed reproduction steps (if any)

1. Start upload large file
2. Destroy editor

### Expected result

*What is the expected result of the above steps?*
Uploading are canceled.

### Actual result
Editor are crashed with error.

*What is the actual result of the above steps?*

## Other details

* Browser: All
* OS: Window
* CKEditor version: 4.7.1
* Installed CKEditor plugins: default plugins

**Comment by beatadelura** [comment]
I'm able to reproduce this issue on [SDK Sample](https://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images) with CKEditor version 4.7.3.

**Comment by mlewand** [comment]
Fixed with 33d301fb2e.
