### ISSUE TITLE
How to change the ckfinder file upload path in asp.net

### ISSUE THREAD

**Issue by saikotesh** [ckeditor/ckeditor-dev#970]
Hi,

I am successfully integrated ckeditor and ckfinder in my web app and its working fine.
But the uploaded images are saving into application folder images/files.
But i want to change the file upload folder name dynamically using js script.

i have read many posts but not working in my application.

help me to change the folder name..

thanks

**Comment by beatadelura** [comment]
@saikotesh It looks like this issue is related to CKFinder not to CKEditor. If you have found a bug, please report it on CKFinder [issue tracker](https://github.com/ckfinder/ckfinder). You also can ask a question on [stackoverflow](https://stackoverflow.com/questions/tagged/ckfinder).
