### ISSUE TITLE
Toolbar behaving inconsistently when it is shifted to bottom (Firefox only)

### ISSUE THREAD

**Issue by minaseem** [ckeditor/ckeditor-dev#974]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
1. Open given jsbin in Firefox (https://jsbin.com/subezocayo/1/edit?output), Click on `Run with JS` button
2. Click on the `Format` dropdown in `ckeditor` toolbar.

### Expected result

*Dropdown should open above toolbar*

### Actual result

*Dropdown opens below the toolbar, and shift that shift upward which looks weird if there is no scroll in the page*

## Other details

* Browser: Firefox
* OS: Tried on mac so far
* CKEditor version: Tried on 4.6.2, 4.7.3
* Installed CKEditor plugins: 
```js
// A snapshot from build-config.js

{
		'basicstyles' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'enterkey' : 1,
		'format' : 1,
		'indentlist' : 1,
		'link' : 1,
		'list' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'wysiwygarea' : 1
	}
```

## Screenshot 

<img width="658" alt="screen shot 2017-09-28 at 3 04 34 pm" src="https://user-images.githubusercontent.com/5484032/30959540-237090e0-a45e-11e7-85f2-8494e9206531.png">

**Comment by mlewand** [comment]
I can not reproduce it on Firefox 57.0 at Win10 @msamsel, could you double check it?

**Comment by msamsel** [comment]
I also cannot reproduce it on MacOS with Firefox 57.0.4. It seems that problem doesn't exists any longer.
