### ISSUE TITLE
BUG: CKEditor is not decoding properly the character Ŵ

### ISSUE THREAD

**Issue by raulQA** [ckeditor/ckeditor-dev#975]
+*Description*+:
CKEditor bug
Some special characters used in CKEditor are not properly integrated in html

+*Expected Result*+:
It should be encoded properly special characters to html for example: character Ŵ

+*Current Result*+:
html representation is properly done
html encoding is not encoding the special character Ŵ

+*Steps to reproduce*+:
# Use CKEditor
![image](https://user-images.githubusercontent.com/31350404/30963539-b84daa40-a445-11e7-9e45-2364418c5b6f.png)
# Add special character Ŵ using the "Insert Special Character" button
![image](https://user-images.githubusercontent.com/31350404/30963554-c8cbc21c-a445-11e7-8636-4b54ca22b7c5.png)
![image](https://user-images.githubusercontent.com/31350404/30963569-d628a8f8-a445-11e7-95eb-a86cf3d58b8d.png)
# click on source to see the html generated
![image](https://user-images.githubusercontent.com/31350404/30963598-eddaf0a0-a445-11e7-99e9-15bb96b6c613.png)
![image](https://user-images.githubusercontent.com/31350404/30963627-062ba348-a446-11e7-9ea4-ba07a6a2c351.png)

**Comment by msamsel** [comment]
Hi,
if you set flag [`entities_processNumerical: true`](https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-entities_processNumerical) character will be encoded. Please take a look at this example: https://codepen.io/msamsel/pen/wreGzb.
It solves issue from my perspective, so I close it for now. In case that you have some more information about this case, then feel free to comment, so I could reopen it.
