### ISSUE TITLE
copy paste image from word to ck editor in chrome

### ISSUE THREAD

**Issue by madhanjoe** [ckeditor/ckeditor-dev#980]
copy paste image from word to ck editor in chrome - security issue, unable to paste the image in chrome

**Comment by msamsel** [comment]
Hi @madhanjoe,
please use our [template](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md) to report an issue. Currently your description is missing few important information.
What exactly is problem? What are the symptoms and what you consider as wrong behaviour? Please also take a look into this feature request: #662. Maybe this feature will resolve your issue?

**Comment by mlewand** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
