### ISSUE TITLE
FileLoader holds old data in memory

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor-dev#982]
## Are you reporting a feature request or a bug?   Bug

The imageupload plugin uses fileLoaders to upload images.  The fileLoader has 2 properties that potentially hold a lot of data (file and data).  The uploadRepository appears to hold onto a reference to all fileLoaders even after they have finished uploading.   Because the reference to old fileLoaders are maintained the file and data properties stay in memory until the page is refreshed.

## Provide detailed reproduction steps (if any)

1. Upload images via the imageupload plugin
2. Check that uploadRepository.loaders still has reference to all the fileLoaders even well after the files have been uploaded

### Expected result
The fileLoaders should be disposed of properly after they are no longer useful.

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome, Firefox, IE11
* OS: Windows 10
* CKEditor version:  4.7.3
* Installed CKEditor plugins: basicstyles,button,clipboard,colorbutton,colordialog,contextmenu,dialogadvtab,dialogui,divarea,enterkey,entities,fakeobjects,filetools,floatpanel,font,htmlwriter,image2,indent,indentblock,indentlist,link,list,listblock,liststyle,menu,menubutton,notification,notificationaggregator,panel,panelbutton,pastetext,popup,removeformat,resize,richcombo,scayt,showborders,tab,table,tableresize,tabletools,toolbar,undo,uploadimage,widget

**Comment by msamsel** [comment]
Hi,

thank you for this report. It seems to be possible to happen, but it would be great to make a little bit wider research and left specific info in comments or issue description.
That's why, would it be possible for you to point out in our source code, where exactly references are kept? What kind of variables should be cleared out? Maybe even you could propose some solution how we can solve this issue?

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
