### ISSUE TITLE
Copy/paste column to table with footer creates infinite loop

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#996]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to `tests/plugins/tableselection/manual/integrations/clipboard/clipboard`.
2. Select (might be partially) one column in the first table:
![image](https://user-images.githubusercontent.com/1061942/31122610-cea41dc4-a83c-11e7-8cba-e4fb0dff792d.png)

3. Paste into table with footer (selection should contain column part with the footer cell):
![image](https://user-images.githubusercontent.com/1061942/31122654-f458dd5c-a83c-11e7-84e7-a02e372383e5.png)

### Expected result

The copied cells are copied correctly.

### Actual result

The script hangs and when stopped you can see that there were some unnecessary columns added to the table:
![image](https://user-images.githubusercontent.com/1061942/31122717-33ba0098-a83d-11e7-920d-31e4b5331d23.png)

## Other details

* Browser: **Edge 16+ (preview)**
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `tableselection`, `clipboard`

**Comment by mlewand** [comment]
Just great, is it a browser regression? In which case we should upsream it to the Edge team as soon as possible.

**Comment by f1ames** [comment]
Well, my mistake, haven't checked other browsers... It happens also on Chrome, Firefox, Safari and IE11 so it is general issue. And it is a regression introduced in 4.7.2.

**Comment by jacekbogdanski** [comment]
The regression has been introduced with 7094ce2dba.

**Comment by jacekbogdanski** [comment]
According to the [WHATWG specification](https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element) (thanks @Comandeer!) the `tfoot` element may be only used after `tbody`. Although in our manual tests `tfoot` is placed before `tbody`. So there is no issue with `tableselection` plugin. Hovewer manual tests may be improved and I will do it in the followup ticket.
